/**
 * AntDesign Icon Set
 * @see https://icon-sets.iconify.design/ant-design/
 *
 * Auto-generated - do not edit manually
 */

import { createIconSet } from '../createIconSet';

const ant_designIconNames = {
  'account-book-filled': true,
  'account-book-outlined': true,
  'account-book-twotone': true,
  'aim-outlined': true,
  'alert-filled': true,
  'alert-outlined': true,
  'alert-twotone': true,
  'alibaba-outlined': true,
  'align-center-outlined': true,
  'align-left-outlined': true,
  'align-right-outlined': true,
  'alipay-circle-filled': true,
  'alipay-circle-outlined': true,
  'alipay-outlined': true,
  'alipay-square-filled': true,
  'aliwangwang-filled': true,
  'aliwangwang-outlined': true,
  'aliyun-outlined': true,
  'amazon-circle-filled': true,
  'amazon-outlined': true,
  'amazon-square-filled': true,
  'android-filled': true,
  'android-outlined': true,
  'ant-cloud-outlined': true,
  'ant-design-outlined': true,
  'anthropic-filled': true,
  'apartment-outlined': true,
  'api-filled': true,
  'api-outlined': true,
  'api-twotone': true,
  'apple-filled': true,
  'apple-outlined': true,
  'appstore-add-outlined': true,
  'appstore-filled': true,
  'appstore-outlined': true,
  'appstore-twotone': true,
  'area-chart-outlined': true,
  'arrow-down-outlined': true,
  'arrow-left-outlined': true,
  'arrow-right-outlined': true,
  'arrow-up-outlined': true,
  'arrows-alt-outlined': true,
  'audio-filled': true,
  'audio-muted-outlined': true,
  'audio-outlined': true,
  'audio-twotone': true,
  'audit-outlined': true,
  'backward-filled': true,
  'backward-outlined': true,
  'baidu-outlined': true,
  'bank-filled': true,
  'bank-outlined': true,
  'bank-twotone': true,
  'bar-chart-outlined': true,
  'barcode-outlined': true,
  'bars-outlined': true,
  'behance-circle-filled': true,
  'behance-outlined': true,
  'behance-square-filled': true,
  'behance-square-outlined': true,
  'bell-filled': true,
  'bell-outlined': true,
  'bell-twotone': true,
  'bg-colors-outlined': true,
  'bilibili-filled': true,
  'bilibili-outlined': true,
  'block-outlined': true,
  'bold-outlined': true,
  'book-filled': true,
  'book-outlined': true,
  'book-twotone': true,
  'border-bottom-outlined': true,
  'border-horizontal-outlined': true,
  'border-inner-outlined': true,
  'border-left-outlined': true,
  'border-outer-outlined': true,
  'border-outlined': true,
  'border-right-outlined': true,
  'border-top-outlined': true,
  'border-verticle-outlined': true,
  'borderless-table-outlined': true,
  'box-plot-filled': true,
  'box-plot-outlined': true,
  'box-plot-twotone': true,
  'branches-outlined': true,
  'bug-filled': true,
  'bug-outlined': true,
  'bug-twotone': true,
  'build-filled': true,
  'build-outlined': true,
  'build-twotone': true,
  'bulb-filled': true,
  'bulb-outlined': true,
  'bulb-twotone': true,
  'calculator-filled': true,
  'calculator-outlined': true,
  'calculator-twotone': true,
  'calendar-filled': true,
  'calendar-outlined': true,
  'calendar-twotone': true,
  'camera-filled': true,
  'camera-outlined': true,
  'camera-twotone': true,
  'car-filled': true,
  'car-outlined': true,
  'car-twotone': true,
  'caret-down-filled': true,
  'caret-down-outlined': true,
  'caret-left-filled': true,
  'caret-left-outlined': true,
  'caret-right-filled': true,
  'caret-right-outlined': true,
  'caret-up-filled': true,
  'caret-up-outlined': true,
  'carry-out-filled': true,
  'carry-out-outlined': true,
  'carry-out-twotone': true,
  'check-circle-filled': true,
  'check-circle-outlined': true,
  'check-circle-twotone': true,
  'check-outlined': true,
  'check-square-filled': true,
  'check-square-outlined': true,
  'check-square-twotone': true,
  'chrome-filled': true,
  'chrome-outlined': true,
  'ci-circle-filled': true,
  'ci-circle-outlined': true,
  'ci-circle-twotone': true,
  'ci-outlined': true,
  'ci-twotone': true,
  'claude-filled': true,
  'clear-outlined': true,
  'clock-circle-filled': true,
  'clock-circle-outlined': true,
  'clock-circle-twotone': true,
  'close-circle-filled': true,
  'close-circle-outlined': true,
  'close-circle-twotone': true,
  'close-outlined': true,
  'close-square-filled': true,
  'close-square-outlined': true,
  'close-square-twotone': true,
  'cloud-download-outlined': true,
  'cloud-filled': true,
  'cloud-outlined': true,
  'cloud-server-outlined': true,
  'cloud-sync-outlined': true,
  'cloud-twotone': true,
  'cloud-upload-outlined': true,
  'cluster-outlined': true,
  'code-filled': true,
  'code-outlined': true,
  'code-sandbox-circle-filled': true,
  'code-sandbox-outlined': true,
  'code-sandbox-square-filled': true,
  'code-twotone': true,
  'codepen-circle-filled': true,
  'codepen-circle-outlined': true,
  'codepen-outlined': true,
  'codepen-square-filled': true,
  'coffee-outlined': true,
  'column-height-outlined': true,
  'column-width-outlined': true,
  'comment-outlined': true,
  'compass-filled': true,
  'compass-outlined': true,
  'compass-twotone': true,
  'compress-outlined': true,
  'console-sql-outlined': true,
  'contacts-filled': true,
  'contacts-outlined': true,
  'contacts-twotone': true,
  'container-filled': true,
  'container-outlined': true,
  'container-twotone': true,
  'control-filled': true,
  'control-outlined': true,
  'control-twotone': true,
  'copy-filled': true,
  'copy-outlined': true,
  'copy-twotone': true,
  'copyright-circle-filled': true,
  'copyright-circle-outlined': true,
  'copyright-circle-twotone': true,
  'copyright-outlined': true,
  'copyright-twotone': true,
  'credit-card-filled': true,
  'credit-card-outlined': true,
  'credit-card-twotone': true,
  'crown-filled': true,
  'crown-outlined': true,
  'crown-twotone': true,
  'customer-service-filled': true,
  'customer-service-outlined': true,
  'customer-service-twotone': true,
  'dash-outlined': true,
  'dashboard-filled': true,
  'dashboard-outlined': true,
  'dashboard-twotone': true,
  'database-filled': true,
  'database-outlined': true,
  'database-twotone': true,
  'deep-seek-filled': true,
  'delete-column-outlined': true,
  'delete-filled': true,
  'delete-outlined': true,
  'delete-row-outlined': true,
  'delete-twotone': true,
  'delivered-procedure-outlined': true,
  'deployment-unit-outlined': true,
  'desktop-outlined': true,
  'diff-filled': true,
  'diff-outlined': true,
  'diff-twotone': true,
  'dingding-outlined': true,
  'dingtalk-circle-filled': true,
  'dingtalk-outlined': true,
  'dingtalk-square-filled': true,
  'disconnect-outlined': true,
  'discord-filled': true,
  'discord-outlined': true,
  'dislike-filled': true,
  'dislike-outlined': true,
  'dislike-twotone': true,
  'docker-outlined': true,
  'dollar-circle-filled': true,
  'dollar-circle-outlined': true,
  'dollar-circle-twotone': true,
  'dollar-outlined': true,
  'dollar-twotone': true,
  'dot-chart-outlined': true,
  'dot-net-outlined': true,
  'double-left-outlined': true,
  'double-right-outlined': true,
  'down-circle-filled': true,
  'down-circle-outlined': true,
  'down-circle-twotone': true,
  'down-outlined': true,
  'down-square-filled': true,
  'down-square-outlined': true,
  'down-square-twotone': true,
  'download-outlined': true,
  'drag-outlined': true,
  'dribbble-circle-filled': true,
  'dribbble-outlined': true,
  'dribbble-square-filled': true,
  'dribbble-square-outlined': true,
  'dropbox-circle-filled': true,
  'dropbox-outlined': true,
  'dropbox-square-filled': true,
  'edit-filled': true,
  'edit-outlined': true,
  'edit-twotone': true,
  'eleven-labs-filled': true,
  'ellipsis-outlined': true,
  'enter-outlined': true,
  'environment-filled': true,
  'environment-outlined': true,
  'environment-twotone': true,
  'euro-circle-filled': true,
  'euro-circle-outlined': true,
  'euro-circle-twotone': true,
  'euro-outlined': true,
  'euro-twotone': true,
  'exception-outlined': true,
  'exclamation-circle-filled': true,
  'exclamation-circle-outlined': true,
  'exclamation-circle-twotone': true,
  'exclamation-outlined': true,
  'expand-alt-outlined': true,
  'expand-outlined': true,
  'experiment-filled': true,
  'experiment-outlined': true,
  'experiment-twotone': true,
  'export-outlined': true,
  'eye-filled': true,
  'eye-invisible-filled': true,
  'eye-invisible-outlined': true,
  'eye-invisible-twotone': true,
  'eye-outlined': true,
  'eye-twotone': true,
  'facebook-filled': true,
  'facebook-outlined': true,
  'fall-outlined': true,
  'fast-backward-filled': true,
  'fast-backward-outlined': true,
  'fast-forward-filled': true,
  'fast-forward-outlined': true,
  'field-binary-outlined': true,
  'field-number-outlined': true,
  'field-string-outlined': true,
  'field-time-outlined': true,
  'file-add-filled': true,
  'file-add-outlined': true,
  'file-add-twotone': true,
  'file-done-outlined': true,
  'file-excel-filled': true,
  'file-excel-outlined': true,
  'file-excel-twotone': true,
  'file-exclamation-filled': true,
  'file-exclamation-outlined': true,
  'file-exclamation-twotone': true,
  'file-filled': true,
  'file-gif-outlined': true,
  'file-image-filled': true,
  'file-image-outlined': true,
  'file-image-twotone': true,
  'file-jpg-outlined': true,
  'file-markdown-filled': true,
  'file-markdown-outlined': true,
  'file-markdown-twotone': true,
  'file-outlined': true,
  'file-pdf-filled': true,
  'file-pdf-outlined': true,
  'file-pdf-twotone': true,
  'file-ppt-filled': true,
  'file-ppt-outlined': true,
  'file-ppt-twotone': true,
  'file-protect-outlined': true,
  'file-search-outlined': true,
  'file-sync-outlined': true,
  'file-text-filled': true,
  'file-text-outlined': true,
  'file-text-twotone': true,
  'file-twotone': true,
  'file-unknown-filled': true,
  'file-unknown-outlined': true,
  'file-unknown-twotone': true,
  'file-word-filled': true,
  'file-word-outlined': true,
  'file-word-twotone': true,
  'file-zip-filled': true,
  'file-zip-outlined': true,
  'file-zip-twotone': true,
  'filter-filled': true,
  'filter-outlined': true,
  'filter-twotone': true,
  'fire-filled': true,
  'fire-outlined': true,
  'fire-twotone': true,
  'flag-filled': true,
  'flag-outlined': true,
  'flag-twotone': true,
  'folder-add-filled': true,
  'folder-add-outlined': true,
  'folder-add-twotone': true,
  'folder-filled': true,
  'folder-open-filled': true,
  'folder-open-outlined': true,
  'folder-open-twotone': true,
  'folder-outlined': true,
  'folder-twotone': true,
  'folder-view-outlined': true,
  'font-colors-outlined': true,
  'font-size-outlined': true,
  'fork-outlined': true,
  'form-outlined': true,
  'format-painter-filled': true,
  'format-painter-outlined': true,
  'forward-filled': true,
  'forward-outlined': true,
  'frown-filled': true,
  'frown-outlined': true,
  'frown-twotone': true,
  'fullscreen-exit-outlined': true,
  'fullscreen-outlined': true,
  'function-outlined': true,
  'fund-filled': true,
  'fund-outlined': true,
  'fund-projection-screen-outlined': true,
  'fund-twotone': true,
  'fund-view-outlined': true,
  'funnel-plot-filled': true,
  'funnel-plot-outlined': true,
  'funnel-plot-twotone': true,
  'gateway-outlined': true,
  'gemini-filled': true,
  'gif-outlined': true,
  'gift-filled': true,
  'gift-outlined': true,
  'gift-twotone': true,
  'github-filled': true,
  'github-outlined': true,
  'gitlab-filled': true,
  'gitlab-outlined': true,
  'global-outlined': true,
  'gold-filled': true,
  'gold-outlined': true,
  'gold-twotone': true,
  'golden-filled': true,
  'google-circle-filled': true,
  'google-outlined': true,
  'google-plus-circle-filled': true,
  'google-plus-outlined': true,
  'google-plus-square-filled': true,
  'google-square-filled': true,
  'group-outlined': true,
  'harmony-o-s-outlined': true,
  'hdd-filled': true,
  'hdd-outlined': true,
  'hdd-twotone': true,
  'heart-filled': true,
  'heart-outlined': true,
  'heart-twotone': true,
  'heat-map-outlined': true,
  'highlight-filled': true,
  'highlight-outlined': true,
  'highlight-twotone': true,
  'history-outlined': true,
  'holder-outlined': true,
  'home-filled': true,
  'home-outlined': true,
  'home-twotone': true,
  'hourglass-filled': true,
  'hourglass-outlined': true,
  'hourglass-twotone': true,
  'html5-filled': true,
  'html5-outlined': true,
  'html5-twotone': true,
  'hugging-face-filled': true,
  'idcard-filled': true,
  'idcard-outlined': true,
  'idcard-twotone': true,
  'ie-circle-filled': true,
  'ie-outlined': true,
  'ie-square-filled': true,
  'import-outlined': true,
  'inbox-outlined': true,
  'info-circle-filled': true,
  'info-circle-outlined': true,
  'info-circle-twotone': true,
  'info-outlined': true,
  'insert-row-above-outlined': true,
  'insert-row-below-outlined': true,
  'insert-row-left-outlined': true,
  'insert-row-right-outlined': true,
  'instagram-filled': true,
  'instagram-outlined': true,
  'insurance-filled': true,
  'insurance-outlined': true,
  'insurance-twotone': true,
  'interaction-filled': true,
  'interaction-outlined': true,
  'interaction-twotone': true,
  'issues-close-outlined': true,
  'italic-outlined': true,
  'java-outlined': true,
  'java-script-outlined': true,
  'key-outlined': true,
  'kubernetes-outlined': true,
  'laptop-outlined': true,
  'layout-filled': true,
  'layout-outlined': true,
  'layout-twotone': true,
  'left-circle-filled': true,
  'left-circle-outlined': true,
  'left-circle-twotone': true,
  'left-outlined': true,
  'left-square-filled': true,
  'left-square-outlined': true,
  'left-square-twotone': true,
  'like-filled': true,
  'like-outlined': true,
  'like-twotone': true,
  'line-chart-outlined': true,
  'line-height-outlined': true,
  'line-outlined': true,
  'link-outlined': true,
  'linkedin-filled': true,
  'linkedin-outlined': true,
  'linux-outlined': true,
  'loading-3-quarters-outlined': true,
  'loading-outlined': true,
  'lock-filled': true,
  'lock-outlined': true,
  'lock-twotone': true,
  'login-outlined': true,
  'logout-outlined': true,
  'mac-command-filled': true,
  'mac-command-outlined': true,
  'mail-filled': true,
  'mail-outlined': true,
  'mail-twotone': true,
  'man-outlined': true,
  'mastodon-filled': true,
  'medicine-box-filled': true,
  'medicine-box-outlined': true,
  'medicine-box-twotone': true,
  'medium-circle-filled': true,
  'medium-outlined': true,
  'medium-square-filled': true,
  'medium-workmark-outlined': true,
  'meh-filled': true,
  'meh-outlined': true,
  'meh-twotone': true,
  'menu-fold-outlined': true,
  'menu-outlined': true,
  'menu-unfold-outlined': true,
  'merge-cells-outlined': true,
  'merge-filled': true,
  'merge-outlined': true,
  'message-filled': true,
  'message-outlined': true,
  'message-twotone': true,
  'meta-filled': true,
  'minus-circle-filled': true,
  'minus-circle-outlined': true,
  'minus-circle-twotone': true,
  'minus-outlined': true,
  'minus-square-filled': true,
  'minus-square-outlined': true,
  'minus-square-twotone': true,
  'mistral-filled': true,
  'mobile-filled': true,
  'mobile-outlined': true,
  'mobile-twotone': true,
  'money-collect-filled': true,
  'money-collect-outlined': true,
  'money-collect-twotone': true,
  'monitor-outlined': true,
  'moon-filled': true,
  'moon-outlined': true,
  'more-outlined': true,
  'muted-filled': true,
  'muted-outlined': true,
  'netflix-filled': true,
  'node-collapse-outlined': true,
  'node-expand-outlined': true,
  'node-index-outlined': true,
  'notification-filled': true,
  'notification-outlined': true,
  'notification-twotone': true,
  'number-outlined': true,
  'ollama-filled': true,
  'one-to-one-outlined': true,
  'open-a-i-filled': true,
  'open-a-i-outlined': true,
  'ordered-list-outlined': true,
  'paper-clip-outlined': true,
  'partition-outlined': true,
  'pause-circle-filled': true,
  'pause-circle-outlined': true,
  'pause-circle-twotone': true,
  'pause-outlined': true,
  'pay-circle-filled': true,
  'pay-circle-outlined': true,
  'percentage-outlined': true,
  'perplexity-filled': true,
  'phone-filled': true,
  'phone-outlined': true,
  'phone-twotone': true,
  'pic-center-outlined': true,
  'pic-left-outlined': true,
  'pic-right-outlined': true,
  'picture-filled': true,
  'picture-outlined': true,
  'picture-twotone': true,
  'pie-chart-filled': true,
  'pie-chart-outlined': true,
  'pie-chart-twotone': true,
  'pinterest-filled': true,
  'pinterest-outlined': true,
  'play-circle-filled': true,
  'play-circle-outlined': true,
  'play-circle-twotone': true,
  'play-square-filled': true,
  'play-square-outlined': true,
  'play-square-twotone': true,
  'plus-circle-filled': true,
  'plus-circle-outlined': true,
  'plus-circle-twotone': true,
  'plus-outlined': true,
  'plus-square-filled': true,
  'plus-square-outlined': true,
  'plus-square-twotone': true,
  'pound-circle-filled': true,
  'pound-circle-outlined': true,
  'pound-circle-twotone': true,
  'pound-outlined': true,
  'poweroff-outlined': true,
  'printer-filled': true,
  'printer-outlined': true,
  'printer-twotone': true,
  'product-filled': true,
  'product-outlined': true,
  'profile-filled': true,
  'profile-outlined': true,
  'profile-twotone': true,
  'project-filled': true,
  'project-outlined': true,
  'project-twotone': true,
  'property-safety-filled': true,
  'property-safety-outlined': true,
  'property-safety-twotone': true,
  'pull-request-outlined': true,
  'pushpin-filled': true,
  'pushpin-outlined': true,
  'pushpin-twotone': true,
  'python-outlined': true,
  'qq-circle-filled': true,
  'qq-outlined': true,
  'qq-square-filled': true,
  'qrcode-outlined': true,
  'question-circle-filled': true,
  'question-circle-outlined': true,
  'question-circle-twotone': true,
  'question-outlined': true,
  'qwen-filled': true,
  'radar-chart-outlined': true,
  'radius-bottomleft-outlined': true,
  'radius-bottomright-outlined': true,
  'radius-setting-outlined': true,
  'radius-upleft-outlined': true,
  'radius-upright-outlined': true,
  'read-filled': true,
  'read-outlined': true,
  'reconciliation-filled': true,
  'reconciliation-outlined': true,
  'reconciliation-twotone': true,
  'red-envelope-filled': true,
  'red-envelope-outlined': true,
  'red-envelope-twotone': true,
  'reddit-circle-filled': true,
  'reddit-outlined': true,
  'reddit-square-filled': true,
  'redo-outlined': true,
  'reload-outlined': true,
  'replicate-filled': true,
  'rest-filled': true,
  'rest-outlined': true,
  'rest-twotone': true,
  'retweet-outlined': true,
  'right-circle-filled': true,
  'right-circle-outlined': true,
  'right-circle-twotone': true,
  'right-outlined': true,
  'right-square-filled': true,
  'right-square-outlined': true,
  'right-square-twotone': true,
  'rise-outlined': true,
  'robot-filled': true,
  'robot-outlined': true,
  'rocket-filled': true,
  'rocket-outlined': true,
  'rocket-twotone': true,
  'rollback-outlined': true,
  'rotate-left-outlined': true,
  'rotate-right-outlined': true,
  'ruby-outlined': true,
  'safety-certificate-filled': true,
  'safety-certificate-outlined': true,
  'safety-certificate-twotone': true,
  'safety-outlined': true,
  'save-filled': true,
  'save-outlined': true,
  'save-twotone': true,
  'scan-outlined': true,
  'schedule-filled': true,
  'schedule-outlined': true,
  'schedule-twotone': true,
  'scissor-outlined': true,
  'search-outlined': true,
  'security-scan-filled': true,
  'security-scan-outlined': true,
  'security-scan-twotone': true,
  'select-outlined': true,
  'send-outlined': true,
  'setting-filled': true,
  'setting-outlined': true,
  'setting-twotone': true,
  'shake-outlined': true,
  'share-alt-outlined': true,
  'shop-filled': true,
  'shop-outlined': true,
  'shop-twotone': true,
  'shopping-cart-outlined': true,
  'shopping-filled': true,
  'shopping-outlined': true,
  'shopping-twotone': true,
  'shrink-outlined': true,
  'signal-filled': true,
  'signature-filled': true,
  'signature-outlined': true,
  'sisternode-outlined': true,
  'sketch-circle-filled': true,
  'sketch-outlined': true,
  'sketch-square-filled': true,
  'skin-filled': true,
  'skin-outlined': true,
  'skin-twotone': true,
  'skype-filled': true,
  'skype-outlined': true,
  'slack-circle-filled': true,
  'slack-outlined': true,
  'slack-square-filled': true,
  'slack-square-outlined': true,
  'sliders-filled': true,
  'sliders-outlined': true,
  'sliders-twotone': true,
  'small-dash-outlined': true,
  'smile-filled': true,
  'smile-outlined': true,
  'smile-twotone': true,
  'snapchat-filled': true,
  'snippets-filled': true,
  'snippets-outlined': true,
  'snippets-twotone': true,
  'solution-outlined': true,
  'sort-ascending-outlined': true,
  'sort-descending-outlined': true,
  'sound-filled': true,
  'sound-outlined': true,
  'sound-twotone': true,
  'split-cells-outlined': true,
  'spotify-filled': true,
  'spotify-outlined': true,
  'star-filled': true,
  'star-outlined': true,
  'star-twotone': true,
  'step-backward-filled': true,
  'step-backward-outlined': true,
  'step-forward-filled': true,
  'step-forward-outlined': true,
  'stock-outlined': true,
  'stop-filled': true,
  'stop-outlined': true,
  'stop-twotone': true,
  'strikethrough-outlined': true,
  'subnode-outlined': true,
  'sun-filled': true,
  'sun-outlined': true,
  'swap-left-outlined': true,
  'swap-outlined': true,
  'swap-right-outlined': true,
  'switcher-filled': true,
  'switcher-outlined': true,
  'switcher-twotone': true,
  'sync-outlined': true,
  'table-outlined': true,
  'tablet-filled': true,
  'tablet-outlined': true,
  'tablet-twotone': true,
  'tag-filled': true,
  'tag-outlined': true,
  'tag-twotone': true,
  'tags-filled': true,
  'tags-outlined': true,
  'tags-twotone': true,
  'taobao-circle-filled': true,
  'taobao-circle-outlined': true,
  'taobao-outlined': true,
  'taobao-square-filled': true,
  'team-outlined': true,
  'telegram-filled': true,
  'threads-filled': true,
  'thunderbolt-filled': true,
  'thunderbolt-outlined': true,
  'thunderbolt-twotone': true,
  'tik-tok-filled': true,
  'tik-tok-outlined': true,
  'to-top-outlined': true,
  'tool-filled': true,
  'tool-outlined': true,
  'tool-twotone': true,
  'trademark-circle-filled': true,
  'trademark-circle-outlined': true,
  'trademark-circle-twotone': true,
  'trademark-outlined': true,
  'transaction-outlined': true,
  'translation-outlined': true,
  'trophy-filled': true,
  'trophy-outlined': true,
  'trophy-twotone': true,
  'truck-filled': true,
  'truck-outlined': true,
  'twitch-filled': true,
  'twitch-outlined': true,
  'twitter-circle-filled': true,
  'twitter-outlined': true,
  'twitter-square-filled': true,
  'underline-outlined': true,
  'undo-outlined': true,
  'ungroup-outlined': true,
  'unlock-filled': true,
  'unlock-outlined': true,
  'unlock-twotone': true,
  'unordered-list-outlined': true,
  'up-circle-filled': true,
  'up-circle-outlined': true,
  'up-circle-twotone': true,
  'up-outlined': true,
  'up-square-filled': true,
  'up-square-outlined': true,
  'up-square-twotone': true,
  'upload-outlined': true,
  'usb-filled': true,
  'usb-outlined': true,
  'usb-twotone': true,
  'user-add-outlined': true,
  'user-delete-outlined': true,
  'user-outlined': true,
  'user-switch-outlined': true,
  'usergroup-add-outlined': true,
  'usergroup-delete-outlined': true,
  'verified-outlined': true,
  'vertical-align-bottom-outlined': true,
  'vertical-align-middle-outlined': true,
  'vertical-align-top-outlined': true,
  'vertical-left-outlined': true,
  'vertical-right-outlined': true,
  'video-camera-add-outlined': true,
  'video-camera-filled': true,
  'video-camera-outlined': true,
  'video-camera-twotone': true,
  'wallet-filled': true,
  'wallet-outlined': true,
  'wallet-twotone': true,
  'warning-filled': true,
  'warning-outlined': true,
  'warning-twotone': true,
  'wechat-filled': true,
  'wechat-outlined': true,
  'wechat-work-filled': true,
  'wechat-work-outlined': true,
  'weibo-circle-filled': true,
  'weibo-circle-outlined': true,
  'weibo-outlined': true,
  'weibo-square-filled': true,
  'weibo-square-outlined': true,
  'whats-app-outlined': true,
  'wifi-outlined': true,
  'windows-filled': true,
  'windows-outlined': true,
  'woman-outlined': true,
  'x-filled': true,
  'x-outlined': true,
  'yahoo-filled': true,
  'yahoo-outlined': true,
  'youtube-filled': true,
  'youtube-outlined': true,
  'yuque-filled': true,
  'yuque-outlined': true,
  'zhihu-circle-filled': true,
  'zhihu-outlined': true,
  'zhihu-square-filled': true,
  'zoom-in-outlined': true,
  'zoom-out-outlined': true,
} as const;

/**
 * Names upstream has renamed or hidden. Still served, still typed, and
 * deliberately not in the object above: a union compiles to nothing, while
 * every entry in that object ships to every application.
 */
type AntDesignIconAlias =
  | 'account-book'
  | 'account-book-fill'
  | 'account-book-outline'
  | 'aim'
  | 'alert'
  | 'alert-fill'
  | 'alert-outline'
  | 'alibaba'
  | 'alibaba-outline'
  | 'align-center'
  | 'align-center-outline'
  | 'align-left'
  | 'align-left-outline'
  | 'align-right'
  | 'align-right-outline'
  | 'alipay'
  | 'alipay-circle'
  | 'alipay-circle-fill'
  | 'alipay-circle-outline'
  | 'alipay-outline'
  | 'alipay-square'
  | 'alipay-square-fill'
  | 'aliwangwang'
  | 'aliwangwang-fill'
  | 'aliwangwang-outline'
  | 'aliyun'
  | 'aliyun-outline'
  | 'amazon'
  | 'amazon-circle'
  | 'amazon-circle-fill'
  | 'amazon-outline'
  | 'amazon-square'
  | 'amazon-square-fill'
  | 'android'
  | 'android-fill'
  | 'android-outline'
  | 'ant-cloud'
  | 'ant-cloud-outline'
  | 'ant-design'
  | 'ant-design-outline'
  | 'apartment'
  | 'apartment-outline'
  | 'api'
  | 'api-fill'
  | 'api-outline'
  | 'apple'
  | 'apple-fill'
  | 'apple-outline'
  | 'appstore'
  | 'appstore-add'
  | 'appstore-fill'
  | 'appstore-outline'
  | 'area-chart'
  | 'area-chart-outline'
  | 'arrow-down'
  | 'arrow-down-outline'
  | 'arrow-left'
  | 'arrow-left-outline'
  | 'arrow-right'
  | 'arrow-right-outline'
  | 'arrow-up'
  | 'arrow-up-outline'
  | 'arrows-alt'
  | 'arrows-alt-outline'
  | 'audio'
  | 'audio-fill'
  | 'audio-muted'
  | 'audio-outline'
  | 'audit'
  | 'audit-outline'
  | 'backward'
  | 'backward-fill'
  | 'backward-outline'
  | 'bank'
  | 'bank-fill'
  | 'bank-outline'
  | 'bar-chart'
  | 'bar-chart-outline'
  | 'barcode'
  | 'barcode-outline'
  | 'bars'
  | 'bars-outline'
  | 'behance'
  | 'behance-circle'
  | 'behance-circle-fill'
  | 'behance-outline'
  | 'behance-square'
  | 'behance-square-fill'
  | 'behance-square-outline'
  | 'bell'
  | 'bell-fill'
  | 'bell-outline'
  | 'bg-colors'
  | 'bg-colors-outline'
  | 'block'
  | 'block-outline'
  | 'bold'
  | 'bold-outline'
  | 'book'
  | 'book-fill'
  | 'book-outline'
  | 'border'
  | 'border-bottom'
  | 'border-bottom-outline'
  | 'border-horizontal'
  | 'border-horizontal-outline'
  | 'border-inner'
  | 'border-inner-outline'
  | 'border-left'
  | 'border-left-outline'
  | 'border-outer'
  | 'border-outer-outline'
  | 'border-outline'
  | 'border-right'
  | 'border-right-outline'
  | 'border-top'
  | 'border-top-outline'
  | 'border-verticle'
  | 'border-verticle-outline'
  | 'borderless-table'
  | 'box-plot'
  | 'box-plot-fill'
  | 'box-plot-outline'
  | 'branches'
  | 'branches-outline'
  | 'bug'
  | 'bug-fill'
  | 'bug-outline'
  | 'build'
  | 'build-fill'
  | 'build-outline'
  | 'bulb'
  | 'bulb-fill'
  | 'bulb-outline'
  | 'calculator'
  | 'calculator-fill'
  | 'calculator-outline'
  | 'calendar'
  | 'calendar-fill'
  | 'calendar-outline'
  | 'camera'
  | 'camera-fill'
  | 'camera-outline'
  | 'canlendar-twotone'
  | 'car'
  | 'car-fill'
  | 'car-outline'
  | 'caret-down'
  | 'caret-down-fill'
  | 'caret-down-outline'
  | 'caret-left'
  | 'caret-left-fill'
  | 'caret-left-outline'
  | 'caret-right'
  | 'caret-right-fill'
  | 'caret-right-outline'
  | 'caret-up'
  | 'caret-up-fill'
  | 'caret-up-outline'
  | 'carry-out'
  | 'carry-out-fill'
  | 'carry-out-outline'
  | 'check'
  | 'check-circle'
  | 'check-circle-fill'
  | 'check-circle-outline'
  | 'check-outline'
  | 'check-square'
  | 'check-square-fill'
  | 'check-square-outline'
  | 'chrome'
  | 'chrome-fill'
  | 'chrome-outline'
  | 'ci'
  | 'ci-circle'
  | 'ci-circle-fill'
  | 'ci-outline'
  | 'clear'
  | 'clock-circle'
  | 'clock-circle-fill'
  | 'clock-circle-outline'
  | 'close'
  | 'close-circle'
  | 'close-circle-fill'
  | 'close-circle-outline'
  | 'close-outline'
  | 'close-square'
  | 'close-square-fill'
  | 'close-square-outline'
  | 'cloud'
  | 'cloud-download'
  | 'cloud-download-outline'
  | 'cloud-fill'
  | 'cloud-outline'
  | 'cloud-server'
  | 'cloud-server-outline'
  | 'cloud-sync'
  | 'cloud-sync-outline'
  | 'cloud-upload'
  | 'cloud-upload-outline'
  | 'cluster'
  | 'cluster-outline'
  | 'code'
  | 'code-fill'
  | 'code-outline'
  | 'code-sandbox'
  | 'code-sandbox-circle'
  | 'code-sandbox-circle-fill'
  | 'code-sandbox-outline'
  | 'code-sandbox-square'
  | 'code-sandbox-square-fill'
  | 'codepen'
  | 'codepen-circle'
  | 'codepen-circle-fill'
  | 'codepen-circle-outline'
  | 'codepen-outline'
  | 'codepen-square'
  | 'codepen-square-fill'
  | 'coffee'
  | 'coffee-outline'
  | 'colum-height-outline'
  | 'column-height'
  | 'column-height-outline'
  | 'column-width'
  | 'column-width-outline'
  | 'comment'
  | 'compass'
  | 'compass-fill'
  | 'compass-outline'
  | 'compress'
  | 'console-sql'
  | 'contacts'
  | 'contacts-fill'
  | 'contacts-outline'
  | 'container'
  | 'container-fill'
  | 'container-outline'
  | 'control'
  | 'control-fill'
  | 'control-outline'
  | 'copy'
  | 'copy-fill'
  | 'copy-outline'
  | 'copyright'
  | 'copyright-circle'
  | 'copyright-circle-fill'
  | 'copyright-outline'
  | 'credit-card'
  | 'credit-card-fill'
  | 'credit-card-outline'
  | 'crown'
  | 'crown-fill'
  | 'crown-outline'
  | 'customer-service'
  | 'customer-service-fill'
  | 'customer-service-outline'
  | 'dash'
  | 'dash-outline'
  | 'dashboard'
  | 'dashboard-fill'
  | 'dashboard-outline'
  | 'database'
  | 'database-fill'
  | 'database-outline'
  | 'delete'
  | 'delete-column'
  | 'delete-fill'
  | 'delete-outline'
  | 'delete-row'
  | 'delivered-procedure'
  | 'deployment-unit'
  | 'deployment-unit-outline'
  | 'desktop'
  | 'desktop-outline'
  | 'diff'
  | 'diff-fill'
  | 'diff-outline'
  | 'dingding'
  | 'dingding-outline'
  | 'dingtalk'
  | 'dingtalk-circle'
  | 'dingtalk-circle-fill'
  | 'dingtalk-square'
  | 'dingtalk-square-fill'
  | 'disconnect'
  | 'disconnect-outline'
  | 'dislike'
  | 'dislike-fill'
  | 'dislike-outline'
  | 'dollar'
  | 'dollar-circle'
  | 'dollar-circle-fill'
  | 'dollar-outline'
  | 'dot-chart'
  | 'dot-chart-outline'
  | 'double-left'
  | 'double-left-outline'
  | 'double-right'
  | 'double-right-outline'
  | 'down'
  | 'down-circle'
  | 'down-circle-fill'
  | 'down-circle-outline'
  | 'down-outline'
  | 'down-square'
  | 'down-square-fill'
  | 'down-square-outline'
  | 'download'
  | 'download-outline'
  | 'drag'
  | 'drag-outline'
  | 'dribbble'
  | 'dribbble-circle'
  | 'dribbble-circle-fill'
  | 'dribbble-outline'
  | 'dribbble-square'
  | 'dribbble-square-fill'
  | 'dribbble-square-outline'
  | 'dropbox'
  | 'dropbox-circle'
  | 'dropbox-circle-fill'
  | 'dropbox-outline'
  | 'dropbox-square'
  | 'dropbox-square-fill'
  | 'edit'
  | 'edit-fill'
  | 'edit-outline'
  | 'ellipsis'
  | 'ellipsis-outline'
  | 'enter'
  | 'enter-outline'
  | 'environment'
  | 'environment-fill'
  | 'environment-outline'
  | 'euro'
  | 'euro-circle'
  | 'euro-circle-fill'
  | 'euro-outline'
  | 'exception'
  | 'exception-outline'
  | 'exclamation'
  | 'exclamation-circle'
  | 'exclamation-circle-fill'
  | 'exclamation-circle-outline'
  | 'exclamation-outline'
  | 'expand'
  | 'expand-alt'
  | 'experiment'
  | 'experiment-fill'
  | 'experiment-outline'
  | 'export'
  | 'export-outline'
  | 'eye'
  | 'eye-fill'
  | 'eye-invisible'
  | 'eye-invisible-fill'
  | 'eye-invisible-outline'
  | 'eye-outline'
  | 'facebook'
  | 'facebook-fill'
  | 'facebook-outline'
  | 'fall'
  | 'fall-outline'
  | 'fast-backward'
  | 'fast-backward-fill'
  | 'fast-backward-outline'
  | 'fast-forward'
  | 'fast-forward-fill'
  | 'fast-forward-outline'
  | 'field-binary'
  | 'field-number'
  | 'field-string'
  | 'field-time'
  | 'file'
  | 'file-add'
  | 'file-add-fill'
  | 'file-add-outline'
  | 'file-done'
  | 'file-done-outline'
  | 'file-excel'
  | 'file-excel-fill'
  | 'file-excel-outline'
  | 'file-exclamation'
  | 'file-exclamation-fill'
  | 'file-exclamation-outline'
  | 'file-fill'
  | 'file-gif'
  | 'file-image'
  | 'file-image-fill'
  | 'file-image-outline'
  | 'file-jpg'
  | 'file-jpg-outline'
  | 'file-markdown'
  | 'file-markdown-fill'
  | 'file-markdown-outline'
  | 'file-outline'
  | 'file-pdf'
  | 'file-pdf-fill'
  | 'file-pdf-outline'
  | 'file-ppt'
  | 'file-ppt-fill'
  | 'file-ppt-outline'
  | 'file-protect'
  | 'file-protect-outline'
  | 'file-search'
  | 'file-search-outline'
  | 'file-sync'
  | 'file-sync-outline'
  | 'file-text'
  | 'file-text-fill'
  | 'file-text-outline'
  | 'file-unknown'
  | 'file-unknown-fill'
  | 'file-unknown-outline'
  | 'file-word'
  | 'file-word-fill'
  | 'file-word-outline'
  | 'file-zip'
  | 'file-zip-fill'
  | 'file-zip-outline'
  | 'filter'
  | 'filter-fill'
  | 'filter-outline'
  | 'fire'
  | 'fire-fill'
  | 'fire-outline'
  | 'flag'
  | 'flag-fill'
  | 'flag-outline'
  | 'folder'
  | 'folder-add'
  | 'folder-add-fill'
  | 'folder-add-outline'
  | 'folder-fill'
  | 'folder-open'
  | 'folder-open-fill'
  | 'folder-open-outline'
  | 'folder-outline'
  | 'folder-view'
  | 'font-colors'
  | 'font-colors-outline'
  | 'font-size'
  | 'font-size-outline'
  | 'fork'
  | 'fork-outline'
  | 'form'
  | 'form-outline'
  | 'format-painter'
  | 'forward'
  | 'forward-fill'
  | 'forward-outline'
  | 'frown'
  | 'frown-fill'
  | 'frown-outline'
  | 'fullscreen'
  | 'fullscreen-exit'
  | 'fullscreen-exit-outline'
  | 'fullscreen-outline'
  | 'function'
  | 'fund'
  | 'fund-fill'
  | 'fund-outline'
  | 'fund-projection-screen'
  | 'fund-view'
  | 'funnel-plot'
  | 'funnel-plot-fill'
  | 'funnel-plot-outline'
  | 'gateway'
  | 'gateway-outline'
  | 'gif'
  | 'gift'
  | 'gift-fill'
  | 'gift-outline'
  | 'github'
  | 'github-fill'
  | 'github-outline'
  | 'gitlab'
  | 'gitlab-fill'
  | 'gitlab-outline'
  | 'global'
  | 'global-outline'
  | 'gold'
  | 'gold-outline'
  | 'golden'
  | 'golden-fill'
  | 'google'
  | 'google-circle'
  | 'google-circle-fill'
  | 'google-outline'
  | 'google-plus'
  | 'google-plus-circle'
  | 'google-plus-circle-fill'
  | 'google-plus-outline'
  | 'google-plus-square'
  | 'google-plus-square-fill'
  | 'google-square'
  | 'google-square-fill'
  | 'group'
  | 'hdd'
  | 'hdd-fill'
  | 'hdd-outline'
  | 'heart'
  | 'heart-fill'
  | 'heart-outline'
  | 'heat-map'
  | 'heat-map-outline'
  | 'highlight'
  | 'highlight-fill'
  | 'highlight-outline'
  | 'history'
  | 'history-outline'
  | 'home'
  | 'home-fill'
  | 'home-outline'
  | 'hourglass'
  | 'hourglass-fill'
  | 'hourglass-outline'
  | 'html5'
  | 'html5-fill'
  | 'html5-outline'
  | 'idcard'
  | 'idcard-fill'
  | 'idcard-outline'
  | 'ie'
  | 'ie-circle'
  | 'ie-circle-fill'
  | 'ie-outline'
  | 'ie-square'
  | 'ie-square-fill'
  | 'import'
  | 'import-outline'
  | 'inbox'
  | 'inbox-outline'
  | 'info'
  | 'info-circle'
  | 'info-circle-fill'
  | 'info-circle-outline'
  | 'info-outline'
  | 'insert-row-above'
  | 'insert-row-below'
  | 'insert-row-left'
  | 'insert-row-right'
  | 'instagram'
  | 'instagram-fill'
  | 'instagram-outline'
  | 'insurance'
  | 'insurance-fill'
  | 'insurance-outline'
  | 'interaction'
  | 'interaction-fill'
  | 'interaction-outline'
  | 'interation'
  | 'interation-fill'
  | 'interation-outline'
  | 'interation-twotone'
  | 'issues-close'
  | 'issues-close-outline'
  | 'italic'
  | 'italic-outline'
  | 'key'
  | 'key-outline'
  | 'laptop'
  | 'laptop-outline'
  | 'layout'
  | 'layout-fill'
  | 'layout-outline'
  | 'left'
  | 'left-circle'
  | 'left-circle-fill'
  | 'left-circle-outline'
  | 'left-outline'
  | 'left-square'
  | 'left-square-fill'
  | 'left-square-outline'
  | 'like'
  | 'like-fill'
  | 'like-outline'
  | 'line'
  | 'line-chart'
  | 'line-chart-outline'
  | 'line-height'
  | 'line-height-outline'
  | 'line-outline'
  | 'link'
  | 'link-outline'
  | 'linkedin'
  | 'linkedin-fill'
  | 'linkedin-outline'
  | 'loading'
  | 'loading-3-quarters'
  | 'loading-3-quarters-outline'
  | 'loading-outline'
  | 'lock'
  | 'lock-fill'
  | 'lock-outline'
  | 'login'
  | 'login-outline'
  | 'logout'
  | 'logout-outline'
  | 'mac-command'
  | 'mail'
  | 'mail-fill'
  | 'mail-outline'
  | 'man'
  | 'man-outline'
  | 'medicine-box'
  | 'medicine-box-fill'
  | 'medicine-box-outline'
  | 'medium'
  | 'medium-circle'
  | 'medium-circle-fill'
  | 'medium-outline'
  | 'medium-square'
  | 'medium-square-fill'
  | 'medium-workmark'
  | 'medium-workmark-outline'
  | 'meh'
  | 'meh-fill'
  | 'meh-outline'
  | 'menu'
  | 'menu-fold'
  | 'menu-fold-outline'
  | 'menu-outline'
  | 'menu-unfold'
  | 'menu-unfold-outline'
  | 'merge-cells'
  | 'message'
  | 'message-fill'
  | 'message-outline'
  | 'minus'
  | 'minus-circle'
  | 'minus-circle-fill'
  | 'minus-circle-outline'
  | 'minus-outline'
  | 'minus-square'
  | 'minus-square-fill'
  | 'minus-square-outline'
  | 'mobile'
  | 'mobile-fill'
  | 'mobile-outline'
  | 'money-collect'
  | 'money-collect-fill'
  | 'money-collect-outline'
  | 'monitor'
  | 'monitor-outline'
  | 'more'
  | 'more-outline'
  | 'mr-outline'
  | 'node-collapse'
  | 'node-expand'
  | 'node-index'
  | 'notification'
  | 'notification-fill'
  | 'notification-outline'
  | 'number'
  | 'number-outline'
  | 'one-to-one'
  | 'ordered-list'
  | 'ordered-list-outline'
  | 'paper-clip'
  | 'paper-clip-outline'
  | 'partition'
  | 'pause'
  | 'pause-circle'
  | 'pause-circle-fill'
  | 'pause-circle-outline'
  | 'pause-outline'
  | 'pay-circle'
  | 'pay-circle-fill'
  | 'pay-circle-outline'
  | 'percentage'
  | 'percentage-outline'
  | 'phone'
  | 'phone-fill'
  | 'phone-outline'
  | 'pic-center'
  | 'pic-center-outline'
  | 'pic-left'
  | 'pic-left-outline'
  | 'pic-right'
  | 'pic-right-outline'
  | 'picture'
  | 'picture-fill'
  | 'picture-outline'
  | 'pie-chart'
  | 'pie-chart-fill'
  | 'pie-chart-outline'
  | 'play-circle'
  | 'play-circle-fill'
  | 'play-circle-outline'
  | 'play-square'
  | 'play-square-fill'
  | 'play-square-outline'
  | 'plus'
  | 'plus-circle'
  | 'plus-circle-fill'
  | 'plus-circle-outline'
  | 'plus-outline'
  | 'plus-square'
  | 'plus-square-fill'
  | 'plus-square-outline'
  | 'pound'
  | 'pound-circle'
  | 'pound-circle-fill'
  | 'pound-outline'
  | 'poweroff'
  | 'poweroff-outline'
  | 'printer'
  | 'printer-fill'
  | 'printer-outline'
  | 'profile'
  | 'profile-fill'
  | 'profile-outline'
  | 'project'
  | 'project-fill'
  | 'project-outline'
  | 'property-safety'
  | 'property-safety-fill'
  | 'property-safety-outline'
  | 'pull-request'
  | 'pull-request-outline'
  | 'pushpin'
  | 'pushpin-fill'
  | 'pushpin-outline'
  | 'qq'
  | 'qq-circle'
  | 'qq-circle-fill'
  | 'qq-outline'
  | 'qq-square'
  | 'qq-square-fill'
  | 'qrcode'
  | 'qrcode-outline'
  | 'question'
  | 'question-circle'
  | 'question-circle-fill'
  | 'question-circle-outline'
  | 'question-outline'
  | 'radar-chart'
  | 'radar-chart-outline'
  | 'radius-bottomleft'
  | 'radius-bottomleft-outline'
  | 'radius-bottomright'
  | 'radius-bottomright-outline'
  | 'radius-setting'
  | 'radius-setting-outline'
  | 'radius-upleft'
  | 'radius-upleft-outline'
  | 'radius-upright'
  | 'radius-upright-outline'
  | 'read'
  | 'read-fill'
  | 'read-outline'
  | 'reconciliation'
  | 'reconciliation-fill'
  | 'reconciliation-outline'
  | 'red-envelope'
  | 'red-envelope-fill'
  | 'red-envelope-outline'
  | 'reddit'
  | 'reddit-circle'
  | 'reddit-circle-fill'
  | 'reddit-outline'
  | 'reddit-square'
  | 'reddit-square-fill'
  | 'redo'
  | 'redo-outline'
  | 'reload'
  | 'reload-outline'
  | 'reload-time-outline'
  | 'rest'
  | 'rest-fill'
  | 'rest-outline'
  | 'retweet'
  | 'retweet-outline'
  | 'right'
  | 'right-circle'
  | 'right-circle-fill'
  | 'right-circle-outline'
  | 'right-outline'
  | 'right-square'
  | 'right-square-fill'
  | 'right-square-outline'
  | 'rise'
  | 'rise-outline'
  | 'robot'
  | 'robot-outline'
  | 'rocket'
  | 'rocket-fill'
  | 'rocket-outline'
  | 'rollback'
  | 'rollback-outline'
  | 'rotate-left'
  | 'rotate-right'
  | 'safety'
  | 'safety-certificate'
  | 'safety-certificate-fill'
  | 'safety-certificate-outline'
  | 'safety-outline'
  | 'save'
  | 'save-fill'
  | 'save-outline'
  | 'scan'
  | 'scan-outline'
  | 'schedule'
  | 'schedule-fill'
  | 'schedule-outline'
  | 'scissor'
  | 'scissor-outline'
  | 'search'
  | 'search-outline'
  | 'security-scan'
  | 'security-scan-fill'
  | 'security-scan-outline'
  | 'select'
  | 'select-outline'
  | 'send'
  | 'setting'
  | 'setting-fill'
  | 'setting-outline'
  | 'shake'
  | 'shake-outline'
  | 'share-alt'
  | 'share-alt-outline'
  | 'shop'
  | 'shop-fill'
  | 'shop-outline'
  | 'shopping'
  | 'shopping-cart'
  | 'shopping-cart-outline'
  | 'shopping-fill'
  | 'shopping-outline'
  | 'shrink'
  | 'shrink-outline'
  | 'signal'
  | 'sisternode'
  | 'sketch'
  | 'sketch-circle'
  | 'sketch-circle-fill'
  | 'sketch-outline'
  | 'sketch-square'
  | 'sketch-square-fill'
  | 'skin'
  | 'skin-fill'
  | 'skin-outline'
  | 'skype'
  | 'skype-fill'
  | 'skype-outline'
  | 'slack'
  | 'slack-circle'
  | 'slack-circle-fill'
  | 'slack-outline'
  | 'slack-square'
  | 'slack-square-fill'
  | 'slack-square-outline'
  | 'sliders'
  | 'sliders-fill'
  | 'sliders-outline'
  | 'small-dash'
  | 'small-dash-outline'
  | 'smile'
  | 'smile-fill'
  | 'smile-outline'
  | 'snippets'
  | 'snippets-fill'
  | 'snippets-outline'
  | 'solution'
  | 'solution-outline'
  | 'sort-ascending'
  | 'sort-ascending-outline'
  | 'sort-descending'
  | 'sort-descending-outline'
  | 'sound'
  | 'sound-fill'
  | 'sound-outline'
  | 'split-cells'
  | 'star'
  | 'star-fill'
  | 'star-outline'
  | 'step-backward'
  | 'step-backward-fill'
  | 'step-backward-outline'
  | 'step-forward'
  | 'step-forward-fill'
  | 'step-forward-outline'
  | 'stock'
  | 'stock-outline'
  | 'stop'
  | 'stop-fill'
  | 'stop-outline'
  | 'strikethrough'
  | 'strikethrough-outline'
  | 'subnode'
  | 'swap'
  | 'swap-left'
  | 'swap-left-outline'
  | 'swap-outline'
  | 'swap-right'
  | 'swap-right-outline'
  | 'switcher'
  | 'switcher-fill'
  | 'switcher-outline'
  | 'sync'
  | 'sync-outline'
  | 'table'
  | 'table-outline'
  | 'tablet'
  | 'tablet-fill'
  | 'tablet-outline'
  | 'tag'
  | 'tag-fill'
  | 'tag-outline'
  | 'tags'
  | 'tags-fill'
  | 'tags-outline'
  | 'taobao'
  | 'taobao-circle'
  | 'taobao-circle-fill'
  | 'taobao-circle-outline'
  | 'taobao-outline'
  | 'taobao-square'
  | 'taobao-square-fill'
  | 'team'
  | 'team-outline'
  | 'thunderbolt'
  | 'thunderbolt-fill'
  | 'thunderbolt-outline'
  | 'to-top'
  | 'to-top-outline'
  | 'tool'
  | 'tool-fill'
  | 'tool-outline'
  | 'trademark'
  | 'trademark-circle'
  | 'trademark-circle-fill'
  | 'trademark-outline'
  | 'transaction'
  | 'transaction-outline'
  | 'translation'
  | 'trophy'
  | 'trophy-fill'
  | 'trophy-outline'
  | 'twitter'
  | 'twitter-circle'
  | 'twitter-circle-fill'
  | 'twitter-outline'
  | 'twitter-square'
  | 'twitter-square-fill'
  | 'underline'
  | 'underline-outline'
  | 'undo'
  | 'undo-outline'
  | 'ungroup'
  | 'unlock'
  | 'unlock-fill'
  | 'unlock-outline'
  | 'unordered-list'
  | 'unordered-list-outline'
  | 'up'
  | 'up-circle'
  | 'up-circle-fill'
  | 'up-circle-outline'
  | 'up-outline'
  | 'up-square'
  | 'up-square-fill'
  | 'up-square-outline'
  | 'upload'
  | 'upload-outline'
  | 'usb'
  | 'usb-fill'
  | 'usb-outline'
  | 'user'
  | 'user-add'
  | 'user-add-outline'
  | 'user-delete'
  | 'user-delete-outline'
  | 'user-outline'
  | 'user-switch'
  | 'usergroup-add'
  | 'usergroup-add-outline'
  | 'usergroup-delete'
  | 'usergroup-delete-outline'
  | 'verified'
  | 'vertical-align-bottom'
  | 'vertical-align-bottom-outline'
  | 'vertical-align-middle'
  | 'vertical-align-middle-outline'
  | 'vertical-align-top'
  | 'vertical-align-top-outline'
  | 'vertical-left'
  | 'vertical-left-outline'
  | 'vertical-right'
  | 'vertical-right-outline'
  | 'video-camera'
  | 'video-camera-add'
  | 'video-camera-fill'
  | 'video-camera-outline'
  | 'wallet'
  | 'wallet-fill'
  | 'wallet-outline'
  | 'warning'
  | 'warning-fill'
  | 'warning-outline'
  | 'wechat'
  | 'wechat-fill'
  | 'wechat-outline'
  | 'weibo'
  | 'weibo-circle'
  | 'weibo-circle-fill'
  | 'weibo-circle-outline'
  | 'weibo-outline'
  | 'weibo-square'
  | 'weibo-square-fill'
  | 'weibo-square-outline'
  | 'whats-app'
  | 'wifi'
  | 'wifi-outline'
  | 'windows'
  | 'windows-fill'
  | 'windows-outline'
  | 'woman'
  | 'woman-outline'
  | 'yahoo'
  | 'yahoo-fill'
  | 'yahoo-outline'
  | 'youtube'
  | 'youtube-fill'
  | 'youtube-outline'
  | 'yuque'
  | 'yuque-fill'
  | 'yuque-outline'
  | 'zhihu'
  | 'zhihu-circle'
  | 'zhihu-circle-fill'
  | 'zhihu-outline'
  | 'zhihu-square'
  | 'zhihu-square-fill'
  | 'zoom-in'
  | 'zoom-in-outline'
  | 'zoom-out'
  | 'zoom-out-outline';

export type AntDesignIconName = keyof typeof ant_designIconNames | AntDesignIconAlias;
export const AntDesign = createIconSet<AntDesignIconName>('ant-design', ant_designIconNames);
