/**
 * Bpmn Icon Set
 * @see https://icon-sets.iconify.design/bpmn/
 *
 * Auto-generated - do not edit manually
 */

import { createIconSet } from '../createIconSet';

const bpmnIconNames = {
  'ad-hoc-marker': true,
  'business-rule': true,
  'business-rule-task': true,
  'call-activity': true,
  'compensation-marker': true,
  'conditional-flow': true,
  connection: true,
  'connection-multi': true,
  'data-input': true,
  'data-object': true,
  'data-output': true,
  'data-store': true,
  'default-flow': true,
  'end-event': true,
  'end-event-cancel': true,
  'end-event-compensation': true,
  'end-event-error': true,
  'end-event-escalation': true,
  'end-event-link': true,
  'end-event-message': true,
  'end-event-multiple': true,
  'end-event-none': true,
  'end-event-signal': true,
  'end-event-terminate': true,
  'event-subprocess-expanded': true,
  gateway: true,
  'gateway-complex': true,
  'gateway-eventbased': true,
  'gateway-none': true,
  'gateway-or': true,
  'gateway-parallel': true,
  'gateway-xor': true,
  group: true,
  'hand-tool': true,
  'intermediate-event': true,
  'intermediate-event-catch-cancel': true,
  'intermediate-event-catch-compensation': true,
  'intermediate-event-catch-condition': true,
  'intermediate-event-catch-error': true,
  'intermediate-event-catch-escalation': true,
  'intermediate-event-catch-link': true,
  'intermediate-event-catch-message': true,
  'intermediate-event-catch-multiple': true,
  'intermediate-event-catch-non-interrupting-condition': true,
  'intermediate-event-catch-non-interrupting-escalation': true,
  'intermediate-event-catch-non-interrupting-message': true,
  'intermediate-event-catch-non-interrupting-multiple': true,
  'intermediate-event-catch-non-interrupting-parallel-multiple': true,
  'intermediate-event-catch-non-interrupting-signal': true,
  'intermediate-event-catch-non-interrupting-timer': true,
  'intermediate-event-catch-parallel-multiple': true,
  'intermediate-event-catch-signal': true,
  'intermediate-event-catch-timer': true,
  'intermediate-event-non-interrupting': true,
  'intermediate-event-none': true,
  'intermediate-event-throw-compensation': true,
  'intermediate-event-throw-escalation': true,
  'intermediate-event-throw-link': true,
  'intermediate-event-throw-message': true,
  'intermediate-event-throw-multiple': true,
  'intermediate-event-throw-signal': true,
  lane: true,
  'lane-divide-three': true,
  'lane-divide-two': true,
  'lane-insert-above': true,
  'lane-insert-below': true,
  'lasso-tool': true,
  'loop-marker': true,
  manual: true,
  'manual-task': true,
  'parallel-mi-marker': true,
  participant: true,
  receive: true,
  'receive-task': true,
  'screw-wrench': true,
  script: true,
  'script-task': true,
  send: true,
  'send-task': true,
  'sequential-mi-marker': true,
  service: true,
  'service-task': true,
  'space-tool': true,
  'start-event': true,
  'start-event-compensation': true,
  'start-event-condition': true,
  'start-event-error': true,
  'start-event-escalation': true,
  'start-event-message': true,
  'start-event-multiple': true,
  'start-event-non-interrupting': true,
  'start-event-non-interrupting-condition': true,
  'start-event-non-interrupting-escalation': true,
  'start-event-non-interrupting-message': true,
  'start-event-non-interrupting-multiple': true,
  'start-event-non-interrupting-parallel-multiple': true,
  'start-event-non-interrupting-signal': true,
  'start-event-non-interrupting-timer': true,
  'start-event-none': true,
  'start-event-parallel-multiple': true,
  'start-event-signal': true,
  'start-event-timer': true,
  'sub-process-marker': true,
  'subprocess-collapsed': true,
  'subprocess-expanded': true,
  task: true,
  'task-none': true,
  'text-annotation': true,
  transaction: true,
  trash: true,
  user: true,
  'user-task': true,
} as const;

export type BpmnIconName = keyof typeof bpmnIconNames;
export const Bpmn = createIconSet<BpmnIconName>('bpmn', bpmnIconNames);
