/**
 * Bx Icon Set
 * @see https://icon-sets.iconify.design/bx/
 *
 * Auto-generated - do not edit manually
 */

import { createIconSet } from '../createIconSet';

const bxIconNames = {
  abacus: true,
  accessibility: true,
  'add-to-queue': true,
  adjust: true,
  alarm: true,
  'alarm-add': true,
  'alarm-exclamation': true,
  'alarm-off': true,
  'alarm-snooze': true,
  album: true,
  'align-justify': true,
  'align-left': true,
  'align-middle': true,
  'align-right': true,
  analyse: true,
  anchor: true,
  angry: true,
  aperture: true,
  arch: true,
  archive: true,
  'archive-in': true,
  'archive-out': true,
  area: true,
  'arrow-back': true,
  'arrow-from-bottom': true,
  'arrow-from-left': true,
  'arrow-from-right': true,
  'arrow-from-top': true,
  'arrow-to-bottom': true,
  'arrow-to-left': true,
  'arrow-to-right': true,
  'arrow-to-top': true,
  at: true,
  atom: true,
  award: true,
  badge: true,
  'badge-check': true,
  baguette: true,
  ball: true,
  'band-aid': true,
  'bar-chart': true,
  'bar-chart-alt': true,
  'bar-chart-alt-2': true,
  'bar-chart-square': true,
  barcode: true,
  'barcode-reader': true,
  baseball: true,
  basket: true,
  basketball: true,
  bath: true,
  battery: true,
  bed: true,
  'been-here': true,
  beer: true,
  bell: true,
  'bell-minus': true,
  'bell-off': true,
  'bell-plus': true,
  bible: true,
  bitcoin: true,
  blanket: true,
  block: true,
  bluetooth: true,
  body: true,
  bold: true,
  'bolt-circle': true,
  bomb: true,
  bone: true,
  bong: true,
  book: true,
  'book-add': true,
  'book-alt': true,
  'book-bookmark': true,
  'book-content': true,
  'book-heart': true,
  'book-open': true,
  'book-reader': true,
  bookmark: true,
  'bookmark-alt': true,
  'bookmark-alt-minus': true,
  'bookmark-alt-plus': true,
  'bookmark-heart': true,
  'bookmark-minus': true,
  'bookmark-plus': true,
  bookmarks: true,
  'border-all': true,
  'border-bottom': true,
  'border-inner': true,
  'border-left': true,
  'border-none': true,
  'border-outer': true,
  'border-radius': true,
  'border-right': true,
  'border-top': true,
  bot: true,
  'bowl-hot': true,
  'bowl-rice': true,
  'bowling-ball': true,
  box: true,
  bracket: true,
  braille: true,
  brain: true,
  briefcase: true,
  'briefcase-alt': true,
  'briefcase-alt-2': true,
  brightness: true,
  'brightness-half': true,
  broadcast: true,
  brush: true,
  'brush-alt': true,
  bug: true,
  'bug-alt': true,
  building: true,
  'building-house': true,
  buildings: true,
  bulb: true,
  bullseye: true,
  buoy: true,
  bus: true,
  'bus-school': true,
  cabinet: true,
  'cable-car': true,
  cake: true,
  calculator: true,
  calendar: true,
  'calendar-alt': true,
  'calendar-check': true,
  'calendar-edit': true,
  'calendar-event': true,
  'calendar-exclamation': true,
  'calendar-heart': true,
  'calendar-minus': true,
  'calendar-plus': true,
  'calendar-star': true,
  'calendar-week': true,
  'calendar-x': true,
  camera: true,
  'camera-home': true,
  'camera-movie': true,
  'camera-off': true,
  candles: true,
  capsule: true,
  captions: true,
  car: true,
  card: true,
  'caret-down': true,
  'caret-down-circle': true,
  'caret-down-square': true,
  'caret-left': true,
  'caret-left-circle': true,
  'caret-left-square': true,
  'caret-right': true,
  'caret-right-circle': true,
  'caret-right-square': true,
  'caret-up': true,
  'caret-up-circle': true,
  'caret-up-square': true,
  carousel: true,
  cart: true,
  'cart-add': true,
  'cart-alt': true,
  'cart-download': true,
  cast: true,
  category: true,
  'category-alt': true,
  cctv: true,
  certification: true,
  chair: true,
  chalkboard: true,
  chart: true,
  chat: true,
  check: true,
  'check-circle': true,
  'check-double': true,
  'check-shield': true,
  'check-square': true,
  checkbox: true,
  'checkbox-checked': true,
  'checkbox-minus': true,
  'checkbox-square': true,
  cheese: true,
  'chevron-down': true,
  'chevron-down-circle': true,
  'chevron-down-square': true,
  'chevron-left': true,
  'chevron-left-circle': true,
  'chevron-left-square': true,
  'chevron-right': true,
  'chevron-right-circle': true,
  'chevron-right-square': true,
  'chevron-up': true,
  'chevron-up-circle': true,
  'chevron-up-square': true,
  'chevrons-down': true,
  'chevrons-left': true,
  'chevrons-right': true,
  'chevrons-up': true,
  child: true,
  chip: true,
  church: true,
  circle: true,
  'circle-half': true,
  'circle-quarter': true,
  'circle-three-quarter': true,
  clinic: true,
  clipboard: true,
  closet: true,
  cloud: true,
  'cloud-download': true,
  'cloud-drizzle': true,
  'cloud-light-rain': true,
  'cloud-lightning': true,
  'cloud-rain': true,
  'cloud-snow': true,
  'cloud-upload': true,
  code: true,
  'code-alt': true,
  'code-block': true,
  'code-curly': true,
  coffee: true,
  'coffee-togo': true,
  cog: true,
  coin: true,
  'coin-stack': true,
  collapse: true,
  'collapse-alt': true,
  'collapse-horizontal': true,
  'collapse-vertical': true,
  collection: true,
  color: true,
  'color-fill': true,
  columns: true,
  command: true,
  comment: true,
  'comment-add': true,
  'comment-check': true,
  'comment-detail': true,
  'comment-dots': true,
  'comment-edit': true,
  'comment-error': true,
  'comment-minus': true,
  'comment-x': true,
  compass: true,
  confused: true,
  conversation: true,
  cookie: true,
  cool: true,
  copy: true,
  'copy-alt': true,
  copyright: true,
  'credit-card': true,
  'credit-card-alt': true,
  'credit-card-front': true,
  'cricket-ball': true,
  crop: true,
  cross: true,
  crosshair: true,
  crown: true,
  cube: true,
  'cube-alt': true,
  cuboid: true,
  'current-location': true,
  customize: true,
  cut: true,
  cycling: true,
  cylinder: true,
  data: true,
  desktop: true,
  detail: true,
  devices: true,
  dialpad: true,
  'dialpad-alt': true,
  diamond: true,
  'dice-1': true,
  'dice-2': true,
  'dice-3': true,
  'dice-4': true,
  'dice-5': true,
  'dice-6': true,
  directions: true,
  disc: true,
  dish: true,
  dislike: true,
  dizzy: true,
  dna: true,
  'dock-bottom': true,
  'dock-left': true,
  'dock-right': true,
  'dock-top': true,
  dollar: true,
  'dollar-circle': true,
  'donate-blood': true,
  'donate-heart': true,
  'door-open': true,
  'dots-horizontal': true,
  'dots-horizontal-rounded': true,
  'dots-vertical': true,
  'dots-vertical-rounded': true,
  'doughnut-chart': true,
  'down-arrow': true,
  'down-arrow-alt': true,
  'down-arrow-circle': true,
  download: true,
  downvote: true,
  drink: true,
  droplet: true,
  dumbbell: true,
  duplicate: true,
  edit: true,
  'edit-alt': true,
  envelope: true,
  'envelope-open': true,
  equalizer: true,
  eraser: true,
  error: true,
  'error-alt': true,
  'error-circle': true,
  euro: true,
  exclude: true,
  exit: true,
  'exit-fullscreen': true,
  expand: true,
  'expand-alt': true,
  'expand-horizontal': true,
  'expand-vertical': true,
  export: true,
  extension: true,
  face: true,
  'fast-forward': true,
  'fast-forward-circle': true,
  female: true,
  'female-sign': true,
  file: true,
  'file-blank': true,
  'file-find': true,
  film: true,
  filter: true,
  'filter-alt': true,
  fingerprint: true,
  'first-aid': true,
  'first-page': true,
  flag: true,
  folder: true,
  'folder-minus': true,
  'folder-open': true,
  'folder-plus': true,
  font: true,
  'font-color': true,
  'font-family': true,
  'font-size': true,
  'food-menu': true,
  'food-tag': true,
  football: true,
  fork: true,
  fridge: true,
  fullscreen: true,
  game: true,
  'gas-pump': true,
  ghost: true,
  gift: true,
  'git-branch': true,
  'git-commit': true,
  'git-compare': true,
  'git-merge': true,
  'git-pull-request': true,
  'git-repo-forked': true,
  glasses: true,
  'glasses-alt': true,
  globe: true,
  'globe-alt': true,
  grid: true,
  'grid-alt': true,
  'grid-horizontal': true,
  'grid-small': true,
  'grid-vertical': true,
  group: true,
  handicap: true,
  happy: true,
  'happy-alt': true,
  'happy-beaming': true,
  'happy-heart-eyes': true,
  'hard-hat': true,
  hash: true,
  hdd: true,
  heading: true,
  headphone: true,
  health: true,
  heart: true,
  'heart-circle': true,
  'heart-square': true,
  'help-circle': true,
  hide: true,
  highlight: true,
  history: true,
  hive: true,
  home: true,
  'home-alt': true,
  'home-alt-2': true,
  'home-circle': true,
  'home-heart': true,
  'home-smile': true,
  'horizontal-center': true,
  'horizontal-left': true,
  'horizontal-right': true,
  hotel: true,
  hourglass: true,
  'id-card': true,
  image: true,
  'image-add': true,
  'image-alt': true,
  images: true,
  import: true,
  infinite: true,
  'info-circle': true,
  'info-square': true,
  injection: true,
  intersect: true,
  italic: true,
  joystick: true,
  'joystick-alt': true,
  'joystick-button': true,
  key: true,
  knife: true,
  label: true,
  landscape: true,
  laptop: true,
  'last-page': true,
  laugh: true,
  layer: true,
  'layer-minus': true,
  'layer-plus': true,
  layout: true,
  leaf: true,
  'left-arrow': true,
  'left-arrow-alt': true,
  'left-arrow-circle': true,
  'left-down-arrow-circle': true,
  'left-indent': true,
  'left-top-arrow-circle': true,
  lemon: true,
  library: true,
  like: true,
  'line-chart': true,
  'line-chart-down': true,
  link: true,
  'link-alt': true,
  'link-external': true,
  lira: true,
  'list-check': true,
  'list-minus': true,
  'list-ol': true,
  'list-plus': true,
  'list-ul': true,
  loader: true,
  'loader-alt': true,
  'loader-circle': true,
  'location-plus': true,
  lock: true,
  'lock-alt': true,
  'lock-open': true,
  'lock-open-alt': true,
  'log-in': true,
  'log-in-circle': true,
  'log-out': true,
  'log-out-circle': true,
  'low-vision': true,
  magnet: true,
  'mail-send': true,
  male: true,
  'male-female': true,
  'male-sign': true,
  map: true,
  'map-alt': true,
  'map-pin': true,
  mask: true,
  math: true,
  medal: true,
  meh: true,
  'meh-alt': true,
  'meh-blank': true,
  'memory-card': true,
  menu: true,
  'menu-alt-left': true,
  'menu-alt-right': true,
  merge: true,
  message: true,
  'message-add': true,
  'message-alt': true,
  'message-alt-add': true,
  'message-alt-check': true,
  'message-alt-detail': true,
  'message-alt-dots': true,
  'message-alt-edit': true,
  'message-alt-error': true,
  'message-alt-minus': true,
  'message-alt-x': true,
  'message-check': true,
  'message-detail': true,
  'message-dots': true,
  'message-edit': true,
  'message-error': true,
  'message-minus': true,
  'message-rounded': true,
  'message-rounded-add': true,
  'message-rounded-check': true,
  'message-rounded-detail': true,
  'message-rounded-dots': true,
  'message-rounded-edit': true,
  'message-rounded-error': true,
  'message-rounded-minus': true,
  'message-rounded-x': true,
  'message-square': true,
  'message-square-add': true,
  'message-square-check': true,
  'message-square-detail': true,
  'message-square-dots': true,
  'message-square-edit': true,
  'message-square-error': true,
  'message-square-minus': true,
  'message-square-x': true,
  'message-x': true,
  meteor: true,
  microchip: true,
  microphone: true,
  'microphone-off': true,
  minus: true,
  'minus-back': true,
  'minus-circle': true,
  'minus-front': true,
  mobile: true,
  'mobile-alt': true,
  'mobile-landscape': true,
  'mobile-vibration': true,
  money: true,
  'money-withdraw': true,
  moon: true,
  mouse: true,
  'mouse-alt': true,
  move: true,
  'move-horizontal': true,
  'move-vertical': true,
  movie: true,
  'movie-play': true,
  music: true,
  navigation: true,
  'network-chart': true,
  news: true,
  'no-entry': true,
  'no-signal': true,
  note: true,
  notepad: true,
  notification: true,
  'notification-off': true,
  'objects-horizontal-center': true,
  'objects-horizontal-left': true,
  'objects-horizontal-right': true,
  'objects-vertical-bottom': true,
  'objects-vertical-center': true,
  'objects-vertical-top': true,
  outline: true,
  package: true,
  paint: true,
  'paint-roll': true,
  palette: true,
  'paper-plane': true,
  paperclip: true,
  paragraph: true,
  party: true,
  paste: true,
  pause: true,
  'pause-circle': true,
  pen: true,
  pencil: true,
  phone: true,
  'phone-call': true,
  'phone-incoming': true,
  'phone-off': true,
  'phone-outgoing': true,
  'photo-album': true,
  'pie-chart': true,
  'pie-chart-alt': true,
  'pie-chart-alt-2': true,
  pin: true,
  planet: true,
  play: true,
  'play-circle': true,
  plug: true,
  plus: true,
  'plus-circle': true,
  'plus-medical': true,
  podcast: true,
  pointer: true,
  poll: true,
  polygon: true,
  popsicle: true,
  pound: true,
  'power-off': true,
  printer: true,
  pulse: true,
  'purchase-tag': true,
  'purchase-tag-alt': true,
  pyramid: true,
  qr: true,
  'qr-scan': true,
  'question-mark': true,
  radar: true,
  radio: true,
  'radio-circle': true,
  'radio-circle-marked': true,
  receipt: true,
  rectangle: true,
  recycle: true,
  redo: true,
  'reflect-horizontal': true,
  'reflect-vertical': true,
  refresh: true,
  registered: true,
  rename: true,
  repeat: true,
  reply: true,
  'reply-all': true,
  repost: true,
  reset: true,
  restaurant: true,
  revision: true,
  rewind: true,
  'rewind-circle': true,
  rfid: true,
  'right-arrow': true,
  'right-arrow-alt': true,
  'right-arrow-circle': true,
  'right-down-arrow-circle': true,
  'right-indent': true,
  'right-top-arrow-circle': true,
  rocket: true,
  'rotate-left': true,
  'rotate-right': true,
  rss: true,
  ruble: true,
  ruler: true,
  run: true,
  rupee: true,
  sad: true,
  save: true,
  scan: true,
  'scatter-chart': true,
  screenshot: true,
  search: true,
  'search-alt': true,
  'search-alt-2': true,
  'select-multiple': true,
  selection: true,
  send: true,
  server: true,
  'shape-circle': true,
  'shape-polygon': true,
  'shape-square': true,
  'shape-triangle': true,
  share: true,
  'share-alt': true,
  shekel: true,
  shield: true,
  'shield-alt': true,
  'shield-alt-2': true,
  'shield-minus': true,
  'shield-plus': true,
  'shield-quarter': true,
  'shield-x': true,
  shocked: true,
  'shopping-bag': true,
  show: true,
  'show-alt': true,
  shower: true,
  shuffle: true,
  sidebar: true,
  'signal-1': true,
  'signal-2': true,
  'signal-3': true,
  'signal-4': true,
  'signal-5': true,
  sitemap: true,
  'skip-next': true,
  'skip-next-circle': true,
  'skip-previous': true,
  'skip-previous-circle': true,
  sleepy: true,
  slider: true,
  'slider-alt': true,
  slideshow: true,
  smile: true,
  sort: true,
  'sort-a-z': true,
  'sort-alt-2': true,
  'sort-down': true,
  'sort-up': true,
  'sort-z-a': true,
  spa: true,
  'space-bar': true,
  speaker: true,
  'spray-can': true,
  spreadsheet: true,
  square: true,
  'square-rounded': true,
  star: true,
  station: true,
  stats: true,
  sticker: true,
  stop: true,
  'stop-circle': true,
  stopwatch: true,
  store: true,
  'store-alt': true,
  'street-view': true,
  strikethrough: true,
  'subdirectory-left': true,
  'subdirectory-right': true,
  sun: true,
  support: true,
  sushi: true,
  swim: true,
  sync: true,
  tab: true,
  table: true,
  tachometer: true,
  tag: true,
  'tag-alt': true,
  'target-lock': true,
  task: true,
  'task-x': true,
  taxi: true,
  'tennis-ball': true,
  terminal: true,
  'test-tube': true,
  text: true,
  time: true,
  'time-five': true,
  timer: true,
  tired: true,
  'toggle-left': true,
  'toggle-right': true,
  tone: true,
  'traffic-cone': true,
  train: true,
  transfer: true,
  'transfer-alt': true,
  trash: true,
  'trash-alt': true,
  'trending-down': true,
  'trending-up': true,
  trim: true,
  trip: true,
  trophy: true,
  tv: true,
  underline: true,
  undo: true,
  unite: true,
  'universal-access': true,
  unlink: true,
  'up-arrow': true,
  'up-arrow-alt': true,
  'up-arrow-circle': true,
  upload: true,
  'upside-down': true,
  upvote: true,
  usb: true,
  user: true,
  'user-check': true,
  'user-circle': true,
  'user-minus': true,
  'user-pin': true,
  'user-plus': true,
  'user-voice': true,
  'user-x': true,
  vector: true,
  'vertical-bottom': true,
  'vertical-center': true,
  'vertical-top': true,
  vial: true,
  video: true,
  'video-off': true,
  'video-plus': true,
  'video-recording': true,
  voicemail: true,
  volume: true,
  'volume-full': true,
  'volume-low': true,
  'volume-mute': true,
  walk: true,
  wallet: true,
  'wallet-alt': true,
  water: true,
  webcam: true,
  wifi: true,
  'wifi-0': true,
  'wifi-1': true,
  'wifi-2': true,
  'wifi-off': true,
  wind: true,
  window: true,
  'window-alt': true,
  'window-close': true,
  'window-open': true,
  windows: true,
  wine: true,
  'wink-smile': true,
  'wink-tongue': true,
  won: true,
  world: true,
  wrench: true,
  x: true,
  'x-circle': true,
  yen: true,
  'zoom-in': true,
  'zoom-out': true,
} as const;

/**
 * Names upstream has renamed or hidden. Still served, still typed, and
 * deliberately not in the object above: a union compiles to nothing, while
 * every entry in that object ships to every application.
 */
type BxIconAlias =
  | 'bx-abacus'
  | 'bx-accessibility'
  | 'bx-add-to-queue'
  | 'bx-adjust'
  | 'bx-alarm'
  | 'bx-alarm-add'
  | 'bx-alarm-exclamation'
  | 'bx-alarm-off'
  | 'bx-alarm-snooze'
  | 'bx-album'
  | 'bx-align-justify'
  | 'bx-align-left'
  | 'bx-align-middle'
  | 'bx-align-right'
  | 'bx-analyse'
  | 'bx-anchor'
  | 'bx-angry'
  | 'bx-aperture'
  | 'bx-arch'
  | 'bx-archive'
  | 'bx-archive-in'
  | 'bx-archive-out'
  | 'bx-area'
  | 'bx-arrow-back'
  | 'bx-arrow-from-bottom'
  | 'bx-arrow-from-left'
  | 'bx-arrow-from-right'
  | 'bx-arrow-from-top'
  | 'bx-arrow-to-bottom'
  | 'bx-arrow-to-left'
  | 'bx-arrow-to-right'
  | 'bx-arrow-to-top'
  | 'bx-at'
  | 'bx-atom'
  | 'bx-award'
  | 'bx-badge'
  | 'bx-badge-check'
  | 'bx-baguette'
  | 'bx-ball'
  | 'bx-band-aid'
  | 'bx-bar-chart'
  | 'bx-bar-chart-alt'
  | 'bx-bar-chart-alt-2'
  | 'bx-bar-chart-square'
  | 'bx-barcode'
  | 'bx-barcode-reader'
  | 'bx-baseball'
  | 'bx-basket'
  | 'bx-basketball'
  | 'bx-bath'
  | 'bx-battery'
  | 'bx-bed'
  | 'bx-been-here'
  | 'bx-beer'
  | 'bx-bell'
  | 'bx-bell-minus'
  | 'bx-bell-off'
  | 'bx-bell-plus'
  | 'bx-bible'
  | 'bx-bitcoin'
  | 'bx-blanket'
  | 'bx-block'
  | 'bx-bluetooth'
  | 'bx-body'
  | 'bx-bold'
  | 'bx-bolt-circle'
  | 'bx-bomb'
  | 'bx-bone'
  | 'bx-bong'
  | 'bx-book'
  | 'bx-book-add'
  | 'bx-book-alt'
  | 'bx-book-bookmark'
  | 'bx-book-content'
  | 'bx-book-heart'
  | 'bx-book-open'
  | 'bx-book-reader'
  | 'bx-bookmark'
  | 'bx-bookmark-alt'
  | 'bx-bookmark-alt-minus'
  | 'bx-bookmark-alt-plus'
  | 'bx-bookmark-heart'
  | 'bx-bookmark-minus'
  | 'bx-bookmark-plus'
  | 'bx-bookmarks'
  | 'bx-border-all'
  | 'bx-border-bottom'
  | 'bx-border-inner'
  | 'bx-border-left'
  | 'bx-border-none'
  | 'bx-border-outer'
  | 'bx-border-radius'
  | 'bx-border-right'
  | 'bx-border-top'
  | 'bx-bot'
  | 'bx-bowl-hot'
  | 'bx-bowl-rice'
  | 'bx-bowling-ball'
  | 'bx-box'
  | 'bx-bracket'
  | 'bx-braille'
  | 'bx-brain'
  | 'bx-briefcase'
  | 'bx-briefcase-alt'
  | 'bx-briefcase-alt-2'
  | 'bx-brightness'
  | 'bx-brightness-half'
  | 'bx-broadcast'
  | 'bx-brush'
  | 'bx-brush-alt'
  | 'bx-bug'
  | 'bx-bug-alt'
  | 'bx-building'
  | 'bx-building-house'
  | 'bx-buildings'
  | 'bx-bulb'
  | 'bx-bullseye'
  | 'bx-buoy'
  | 'bx-bus'
  | 'bx-bus-school'
  | 'bx-cabinet'
  | 'bx-cable-car'
  | 'bx-cake'
  | 'bx-calculator'
  | 'bx-calendar'
  | 'bx-calendar-alt'
  | 'bx-calendar-check'
  | 'bx-calendar-edit'
  | 'bx-calendar-event'
  | 'bx-calendar-exclamation'
  | 'bx-calendar-heart'
  | 'bx-calendar-minus'
  | 'bx-calendar-plus'
  | 'bx-calendar-star'
  | 'bx-calendar-week'
  | 'bx-calendar-x'
  | 'bx-camera'
  | 'bx-camera-home'
  | 'bx-camera-movie'
  | 'bx-camera-off'
  | 'bx-candles'
  | 'bx-capsule'
  | 'bx-captions'
  | 'bx-car'
  | 'bx-card'
  | 'bx-caret-down'
  | 'bx-caret-down-circle'
  | 'bx-caret-down-square'
  | 'bx-caret-left'
  | 'bx-caret-left-circle'
  | 'bx-caret-left-square'
  | 'bx-caret-right'
  | 'bx-caret-right-circle'
  | 'bx-caret-right-square'
  | 'bx-caret-up'
  | 'bx-caret-up-circle'
  | 'bx-caret-up-square'
  | 'bx-carousel'
  | 'bx-cart'
  | 'bx-cart-add'
  | 'bx-cart-alt'
  | 'bx-cart-download'
  | 'bx-cast'
  | 'bx-category'
  | 'bx-category-alt'
  | 'bx-cctv'
  | 'bx-certification'
  | 'bx-chair'
  | 'bx-chalkboard'
  | 'bx-chart'
  | 'bx-chat'
  | 'bx-check'
  | 'bx-check-circle'
  | 'bx-check-double'
  | 'bx-check-shield'
  | 'bx-check-square'
  | 'bx-checkbox'
  | 'bx-checkbox-checked'
  | 'bx-checkbox-minus'
  | 'bx-checkbox-square'
  | 'bx-cheese'
  | 'bx-chevron-down'
  | 'bx-chevron-down-circle'
  | 'bx-chevron-down-square'
  | 'bx-chevron-left'
  | 'bx-chevron-left-circle'
  | 'bx-chevron-left-square'
  | 'bx-chevron-right'
  | 'bx-chevron-right-circle'
  | 'bx-chevron-right-square'
  | 'bx-chevron-up'
  | 'bx-chevron-up-circle'
  | 'bx-chevron-up-square'
  | 'bx-chevrons-down'
  | 'bx-chevrons-left'
  | 'bx-chevrons-right'
  | 'bx-chevrons-up'
  | 'bx-child'
  | 'bx-chip'
  | 'bx-church'
  | 'bx-circle'
  | 'bx-circle-half'
  | 'bx-circle-quarter'
  | 'bx-circle-three-quarter'
  | 'bx-clinic'
  | 'bx-clipboard'
  | 'bx-closet'
  | 'bx-cloud'
  | 'bx-cloud-download'
  | 'bx-cloud-drizzle'
  | 'bx-cloud-light-rain'
  | 'bx-cloud-lightning'
  | 'bx-cloud-rain'
  | 'bx-cloud-snow'
  | 'bx-cloud-upload'
  | 'bx-code'
  | 'bx-code-alt'
  | 'bx-code-block'
  | 'bx-code-curly'
  | 'bx-coffee'
  | 'bx-coffee-togo'
  | 'bx-cog'
  | 'bx-coin'
  | 'bx-coin-stack'
  | 'bx-collapse'
  | 'bx-collapse-alt'
  | 'bx-collapse-horizontal'
  | 'bx-collapse-vertical'
  | 'bx-collection'
  | 'bx-color'
  | 'bx-color-fill'
  | 'bx-columns'
  | 'bx-command'
  | 'bx-comment'
  | 'bx-comment-add'
  | 'bx-comment-check'
  | 'bx-comment-detail'
  | 'bx-comment-dots'
  | 'bx-comment-edit'
  | 'bx-comment-error'
  | 'bx-comment-minus'
  | 'bx-comment-x'
  | 'bx-compass'
  | 'bx-confused'
  | 'bx-conversation'
  | 'bx-cookie'
  | 'bx-cool'
  | 'bx-copy'
  | 'bx-copy-alt'
  | 'bx-copyright'
  | 'bx-credit-card'
  | 'bx-credit-card-alt'
  | 'bx-credit-card-front'
  | 'bx-cricket-ball'
  | 'bx-crop'
  | 'bx-cross'
  | 'bx-crosshair'
  | 'bx-crown'
  | 'bx-cube'
  | 'bx-cube-alt'
  | 'bx-cuboid'
  | 'bx-current-location'
  | 'bx-customize'
  | 'bx-cut'
  | 'bx-cycling'
  | 'bx-cylinder'
  | 'bx-data'
  | 'bx-desktop'
  | 'bx-detail'
  | 'bx-devices'
  | 'bx-dialpad'
  | 'bx-dialpad-alt'
  | 'bx-diamond'
  | 'bx-dice-1'
  | 'bx-dice-2'
  | 'bx-dice-3'
  | 'bx-dice-4'
  | 'bx-dice-5'
  | 'bx-dice-6'
  | 'bx-directions'
  | 'bx-disc'
  | 'bx-dish'
  | 'bx-dislike'
  | 'bx-dizzy'
  | 'bx-dna'
  | 'bx-dock-bottom'
  | 'bx-dock-left'
  | 'bx-dock-right'
  | 'bx-dock-top'
  | 'bx-dollar'
  | 'bx-dollar-circle'
  | 'bx-donate-blood'
  | 'bx-donate-heart'
  | 'bx-door-open'
  | 'bx-dots-horizontal'
  | 'bx-dots-horizontal-rounded'
  | 'bx-dots-vertical'
  | 'bx-dots-vertical-rounded'
  | 'bx-doughnut-chart'
  | 'bx-down-arrow'
  | 'bx-down-arrow-alt'
  | 'bx-down-arrow-circle'
  | 'bx-download'
  | 'bx-downvote'
  | 'bx-drink'
  | 'bx-droplet'
  | 'bx-dumbbell'
  | 'bx-duplicate'
  | 'bx-edit'
  | 'bx-edit-alt'
  | 'bx-envelope'
  | 'bx-envelope-open'
  | 'bx-equalizer'
  | 'bx-eraser'
  | 'bx-error'
  | 'bx-error-alt'
  | 'bx-error-circle'
  | 'bx-euro'
  | 'bx-exclude'
  | 'bx-exit'
  | 'bx-exit-fullscreen'
  | 'bx-expand'
  | 'bx-expand-alt'
  | 'bx-expand-horizontal'
  | 'bx-expand-vertical'
  | 'bx-export'
  | 'bx-extension'
  | 'bx-face'
  | 'bx-fast-forward'
  | 'bx-fast-forward-circle'
  | 'bx-female'
  | 'bx-female-sign'
  | 'bx-file'
  | 'bx-file-blank'
  | 'bx-file-find'
  | 'bx-film'
  | 'bx-filter'
  | 'bx-filter-alt'
  | 'bx-fingerprint'
  | 'bx-first-aid'
  | 'bx-first-page'
  | 'bx-flag'
  | 'bx-folder'
  | 'bx-folder-minus'
  | 'bx-folder-open'
  | 'bx-folder-plus'
  | 'bx-font'
  | 'bx-font-color'
  | 'bx-font-family'
  | 'bx-font-size'
  | 'bx-food-menu'
  | 'bx-food-tag'
  | 'bx-football'
  | 'bx-fork'
  | 'bx-fridge'
  | 'bx-fullscreen'
  | 'bx-game'
  | 'bx-gas-pump'
  | 'bx-ghost'
  | 'bx-gift'
  | 'bx-git-branch'
  | 'bx-git-commit'
  | 'bx-git-compare'
  | 'bx-git-merge'
  | 'bx-git-pull-request'
  | 'bx-git-repo-forked'
  | 'bx-glasses'
  | 'bx-glasses-alt'
  | 'bx-globe'
  | 'bx-globe-alt'
  | 'bx-grid'
  | 'bx-grid-alt'
  | 'bx-grid-horizontal'
  | 'bx-grid-small'
  | 'bx-grid-vertical'
  | 'bx-group'
  | 'bx-handicap'
  | 'bx-happy'
  | 'bx-happy-alt'
  | 'bx-happy-beaming'
  | 'bx-happy-heart-eyes'
  | 'bx-hard-hat'
  | 'bx-hash'
  | 'bx-hdd'
  | 'bx-heading'
  | 'bx-headphone'
  | 'bx-health'
  | 'bx-heart'
  | 'bx-heart-circle'
  | 'bx-heart-square'
  | 'bx-help-circle'
  | 'bx-hide'
  | 'bx-highlight'
  | 'bx-history'
  | 'bx-hive'
  | 'bx-home'
  | 'bx-home-alt'
  | 'bx-home-alt-2'
  | 'bx-home-circle'
  | 'bx-home-heart'
  | 'bx-home-smile'
  | 'bx-horizontal-center'
  | 'bx-horizontal-left'
  | 'bx-horizontal-right'
  | 'bx-hotel'
  | 'bx-hourglass'
  | 'bx-id-card'
  | 'bx-image'
  | 'bx-image-add'
  | 'bx-image-alt'
  | 'bx-images'
  | 'bx-import'
  | 'bx-infinite'
  | 'bx-info-circle'
  | 'bx-info-square'
  | 'bx-injection'
  | 'bx-intersect'
  | 'bx-italic'
  | 'bx-joystick'
  | 'bx-joystick-alt'
  | 'bx-joystick-button'
  | 'bx-key'
  | 'bx-knife'
  | 'bx-label'
  | 'bx-landscape'
  | 'bx-laptop'
  | 'bx-last-page'
  | 'bx-laugh'
  | 'bx-layer'
  | 'bx-layer-minus'
  | 'bx-layer-plus'
  | 'bx-layout'
  | 'bx-leaf'
  | 'bx-left-arrow'
  | 'bx-left-arrow-alt'
  | 'bx-left-arrow-circle'
  | 'bx-left-down-arrow-circle'
  | 'bx-left-indent'
  | 'bx-left-top-arrow-circle'
  | 'bx-lemon'
  | 'bx-library'
  | 'bx-like'
  | 'bx-line-chart'
  | 'bx-line-chart-down'
  | 'bx-link'
  | 'bx-link-alt'
  | 'bx-link-external'
  | 'bx-lira'
  | 'bx-list-check'
  | 'bx-list-minus'
  | 'bx-list-ol'
  | 'bx-list-plus'
  | 'bx-list-ul'
  | 'bx-loader'
  | 'bx-loader-alt'
  | 'bx-loader-circle'
  | 'bx-location-plus'
  | 'bx-lock'
  | 'bx-lock-alt'
  | 'bx-lock-open'
  | 'bx-lock-open-alt'
  | 'bx-log-in'
  | 'bx-log-in-circle'
  | 'bx-log-out'
  | 'bx-log-out-circle'
  | 'bx-low-vision'
  | 'bx-magnet'
  | 'bx-mail-send'
  | 'bx-male'
  | 'bx-male-female'
  | 'bx-male-sign'
  | 'bx-map'
  | 'bx-map-alt'
  | 'bx-map-pin'
  | 'bx-mask'
  | 'bx-math'
  | 'bx-medal'
  | 'bx-meh'
  | 'bx-meh-alt'
  | 'bx-meh-blank'
  | 'bx-memory-card'
  | 'bx-menu'
  | 'bx-menu-alt-left'
  | 'bx-menu-alt-right'
  | 'bx-merge'
  | 'bx-message'
  | 'bx-message-add'
  | 'bx-message-alt'
  | 'bx-message-alt-add'
  | 'bx-message-alt-check'
  | 'bx-message-alt-detail'
  | 'bx-message-alt-dots'
  | 'bx-message-alt-edit'
  | 'bx-message-alt-error'
  | 'bx-message-alt-minus'
  | 'bx-message-alt-x'
  | 'bx-message-check'
  | 'bx-message-detail'
  | 'bx-message-dots'
  | 'bx-message-edit'
  | 'bx-message-error'
  | 'bx-message-minus'
  | 'bx-message-rounded'
  | 'bx-message-rounded-add'
  | 'bx-message-rounded-check'
  | 'bx-message-rounded-detail'
  | 'bx-message-rounded-dots'
  | 'bx-message-rounded-edit'
  | 'bx-message-rounded-error'
  | 'bx-message-rounded-minus'
  | 'bx-message-rounded-x'
  | 'bx-message-square'
  | 'bx-message-square-add'
  | 'bx-message-square-check'
  | 'bx-message-square-detail'
  | 'bx-message-square-dots'
  | 'bx-message-square-edit'
  | 'bx-message-square-error'
  | 'bx-message-square-minus'
  | 'bx-message-square-x'
  | 'bx-message-x'
  | 'bx-meteor'
  | 'bx-microchip'
  | 'bx-microphone'
  | 'bx-microphone-off'
  | 'bx-minus'
  | 'bx-minus-back'
  | 'bx-minus-circle'
  | 'bx-minus-front'
  | 'bx-mobile'
  | 'bx-mobile-alt'
  | 'bx-mobile-landscape'
  | 'bx-mobile-vibration'
  | 'bx-money'
  | 'bx-money-withdraw'
  | 'bx-moon'
  | 'bx-mouse'
  | 'bx-mouse-alt'
  | 'bx-move'
  | 'bx-move-horizontal'
  | 'bx-move-vertical'
  | 'bx-movie'
  | 'bx-movie-play'
  | 'bx-music'
  | 'bx-navigation'
  | 'bx-network-chart'
  | 'bx-news'
  | 'bx-no-entry'
  | 'bx-no-signal'
  | 'bx-note'
  | 'bx-notepad'
  | 'bx-notification'
  | 'bx-notification-off'
  | 'bx-objects-horizontal-center'
  | 'bx-objects-horizontal-left'
  | 'bx-objects-horizontal-right'
  | 'bx-objects-vertical-bottom'
  | 'bx-objects-vertical-center'
  | 'bx-objects-vertical-top'
  | 'bx-outline'
  | 'bx-package'
  | 'bx-paint'
  | 'bx-paint-roll'
  | 'bx-palette'
  | 'bx-paper-plane'
  | 'bx-paperclip'
  | 'bx-paragraph'
  | 'bx-party'
  | 'bx-paste'
  | 'bx-pause'
  | 'bx-pause-circle'
  | 'bx-pen'
  | 'bx-pencil'
  | 'bx-phone'
  | 'bx-phone-call'
  | 'bx-phone-incoming'
  | 'bx-phone-off'
  | 'bx-phone-outgoing'
  | 'bx-photo-album'
  | 'bx-pie-chart'
  | 'bx-pie-chart-alt'
  | 'bx-pie-chart-alt-2'
  | 'bx-pin'
  | 'bx-planet'
  | 'bx-play'
  | 'bx-play-circle'
  | 'bx-plug'
  | 'bx-plus'
  | 'bx-plus-circle'
  | 'bx-plus-medical'
  | 'bx-podcast'
  | 'bx-pointer'
  | 'bx-poll'
  | 'bx-polygon'
  | 'bx-popsicle'
  | 'bx-pound'
  | 'bx-power-off'
  | 'bx-printer'
  | 'bx-pulse'
  | 'bx-purchase-tag'
  | 'bx-purchase-tag-alt'
  | 'bx-pyramid'
  | 'bx-qr'
  | 'bx-qr-scan'
  | 'bx-question-mark'
  | 'bx-radar'
  | 'bx-radio'
  | 'bx-radio-circle'
  | 'bx-radio-circle-marked'
  | 'bx-receipt'
  | 'bx-rectangle'
  | 'bx-recycle'
  | 'bx-redo'
  | 'bx-reflect-horizontal'
  | 'bx-reflect-vertical'
  | 'bx-refresh'
  | 'bx-registered'
  | 'bx-rename'
  | 'bx-repeat'
  | 'bx-reply'
  | 'bx-reply-all'
  | 'bx-repost'
  | 'bx-reset'
  | 'bx-restaurant'
  | 'bx-revision'
  | 'bx-rewind'
  | 'bx-rewind-circle'
  | 'bx-rfid'
  | 'bx-right-arrow'
  | 'bx-right-arrow-alt'
  | 'bx-right-arrow-circle'
  | 'bx-right-down-arrow-circle'
  | 'bx-right-indent'
  | 'bx-right-top-arrow-circle'
  | 'bx-rocket'
  | 'bx-rotate-left'
  | 'bx-rotate-right'
  | 'bx-rss'
  | 'bx-ruble'
  | 'bx-ruler'
  | 'bx-run'
  | 'bx-rupee'
  | 'bx-sad'
  | 'bx-save'
  | 'bx-scan'
  | 'bx-scatter-chart'
  | 'bx-screenshot'
  | 'bx-search'
  | 'bx-search-alt'
  | 'bx-search-alt-2'
  | 'bx-select-multiple'
  | 'bx-selection'
  | 'bx-send'
  | 'bx-server'
  | 'bx-shape-circle'
  | 'bx-shape-polygon'
  | 'bx-shape-square'
  | 'bx-shape-triangle'
  | 'bx-share'
  | 'bx-share-alt'
  | 'bx-shekel'
  | 'bx-shield'
  | 'bx-shield-alt'
  | 'bx-shield-alt-2'
  | 'bx-shield-minus'
  | 'bx-shield-plus'
  | 'bx-shield-quarter'
  | 'bx-shield-x'
  | 'bx-shocked'
  | 'bx-shopping-bag'
  | 'bx-show'
  | 'bx-show-alt'
  | 'bx-shower'
  | 'bx-shuffle'
  | 'bx-sidebar'
  | 'bx-signal-1'
  | 'bx-signal-2'
  | 'bx-signal-3'
  | 'bx-signal-4'
  | 'bx-signal-5'
  | 'bx-sitemap'
  | 'bx-skip-next'
  | 'bx-skip-next-circle'
  | 'bx-skip-previous'
  | 'bx-skip-previous-circle'
  | 'bx-sleepy'
  | 'bx-slider'
  | 'bx-slider-alt'
  | 'bx-slideshow'
  | 'bx-smile'
  | 'bx-sort'
  | 'bx-sort-a-z'
  | 'bx-sort-alt-2'
  | 'bx-sort-down'
  | 'bx-sort-up'
  | 'bx-sort-z-a'
  | 'bx-spa'
  | 'bx-space-bar'
  | 'bx-speaker'
  | 'bx-spray-can'
  | 'bx-spreadsheet'
  | 'bx-square'
  | 'bx-square-rounded'
  | 'bx-star'
  | 'bx-station'
  | 'bx-stats'
  | 'bx-sticker'
  | 'bx-stop'
  | 'bx-stop-circle'
  | 'bx-stopwatch'
  | 'bx-store'
  | 'bx-store-alt'
  | 'bx-street-view'
  | 'bx-strikethrough'
  | 'bx-subdirectory-left'
  | 'bx-subdirectory-right'
  | 'bx-sun'
  | 'bx-support'
  | 'bx-sushi'
  | 'bx-swim'
  | 'bx-sync'
  | 'bx-tab'
  | 'bx-table'
  | 'bx-tachometer'
  | 'bx-tag'
  | 'bx-tag-alt'
  | 'bx-target-lock'
  | 'bx-task'
  | 'bx-task-x'
  | 'bx-taxi'
  | 'bx-tennis-ball'
  | 'bx-terminal'
  | 'bx-test-tube'
  | 'bx-text'
  | 'bx-time'
  | 'bx-time-five'
  | 'bx-timer'
  | 'bx-tired'
  | 'bx-toggle-left'
  | 'bx-toggle-right'
  | 'bx-tone'
  | 'bx-traffic-cone'
  | 'bx-train'
  | 'bx-transfer'
  | 'bx-transfer-alt'
  | 'bx-trash'
  | 'bx-trash-alt'
  | 'bx-trending-down'
  | 'bx-trending-up'
  | 'bx-trim'
  | 'bx-trip'
  | 'bx-trophy'
  | 'bx-tv'
  | 'bx-underline'
  | 'bx-undo'
  | 'bx-unite'
  | 'bx-universal-access'
  | 'bx-unlink'
  | 'bx-up-arrow'
  | 'bx-up-arrow-alt'
  | 'bx-up-arrow-circle'
  | 'bx-upload'
  | 'bx-upside-down'
  | 'bx-upvote'
  | 'bx-usb'
  | 'bx-user'
  | 'bx-user-check'
  | 'bx-user-circle'
  | 'bx-user-minus'
  | 'bx-user-pin'
  | 'bx-user-plus'
  | 'bx-user-voice'
  | 'bx-user-x'
  | 'bx-vector'
  | 'bx-vertical-bottom'
  | 'bx-vertical-center'
  | 'bx-vertical-top'
  | 'bx-vial'
  | 'bx-video'
  | 'bx-video-off'
  | 'bx-video-plus'
  | 'bx-video-recording'
  | 'bx-voicemail'
  | 'bx-volume'
  | 'bx-volume-full'
  | 'bx-volume-low'
  | 'bx-volume-mute'
  | 'bx-walk'
  | 'bx-wallet'
  | 'bx-wallet-alt'
  | 'bx-water'
  | 'bx-webcam'
  | 'bx-wifi'
  | 'bx-wifi-0'
  | 'bx-wifi-1'
  | 'bx-wifi-2'
  | 'bx-wifi-off'
  | 'bx-wind'
  | 'bx-window'
  | 'bx-window-alt'
  | 'bx-window-close'
  | 'bx-window-open'
  | 'bx-windows'
  | 'bx-wine'
  | 'bx-wink-smile'
  | 'bx-wink-tongue'
  | 'bx-won'
  | 'bx-world'
  | 'bx-wrench'
  | 'bx-x'
  | 'bx-x-circle'
  | 'bx-yen'
  | 'bx-zoom-in'
  | 'bx-zoom-out'
  | 'bxl-500px'
  | 'bxl-99designs'
  | 'bxl-adobe'
  | 'bxl-airbnb'
  | 'bxl-algolia'
  | 'bxl-amazon'
  | 'bxl-android'
  | 'bxl-angular'
  | 'bxl-apple'
  | 'bxl-audible'
  | 'bxl-aws'
  | 'bxl-baidu'
  | 'bxl-behance'
  | 'bxl-bing'
  | 'bxl-bitcoin'
  | 'bxl-blender'
  | 'bxl-blogger'
  | 'bxl-bootstrap'
  | 'bxl-c-plus-plus'
  | 'bxl-chrome'
  | 'bxl-codepen'
  | 'bxl-creative-commons'
  | 'bxl-css3'
  | 'bxl-dailymotion'
  | 'bxl-dev-to'
  | 'bxl-deviantart'
  | 'bxl-digg'
  | 'bxl-digitalocean'
  | 'bxl-discord'
  | 'bxl-discord-alt'
  | 'bxl-discourse'
  | 'bxl-django'
  | 'bxl-docker'
  | 'bxl-dribbble'
  | 'bxl-dropbox'
  | 'bxl-drupal'
  | 'bxl-ebay'
  | 'bxl-edge'
  | 'bxl-etsy'
  | 'bxl-facebook'
  | 'bxl-facebook-circle'
  | 'bxl-facebook-square'
  | 'bxl-figma'
  | 'bxl-firebase'
  | 'bxl-firefox'
  | 'bxl-flask'
  | 'bxl-flickr'
  | 'bxl-flickr-square'
  | 'bxl-flutter'
  | 'bxl-foursquare'
  | 'bxl-git'
  | 'bxl-github'
  | 'bxl-gitlab'
  | 'bxl-gmail'
  | 'bxl-go-lang'
  | 'bxl-google'
  | 'bxl-google-cloud'
  | 'bxl-google-plus'
  | 'bxl-google-plus-circle'
  | 'bxl-heroku'
  | 'bxl-html5'
  | 'bxl-imdb'
  | 'bxl-instagram'
  | 'bxl-instagram-alt'
  | 'bxl-internet-explorer'
  | 'bxl-invision'
  | 'bxl-java'
  | 'bxl-javascript'
  | 'bxl-joomla'
  | 'bxl-jquery'
  | 'bxl-jsfiddle'
  | 'bxl-kickstarter'
  | 'bxl-kubernetes'
  | 'bxl-less'
  | 'bxl-linkedin'
  | 'bxl-linkedin-square'
  | 'bxl-magento'
  | 'bxl-mailchimp'
  | 'bxl-markdown'
  | 'bxl-mastercard'
  | 'bxl-mastodon'
  | 'bxl-medium'
  | 'bxl-medium-old'
  | 'bxl-medium-square'
  | 'bxl-messenger'
  | 'bxl-meta'
  | 'bxl-microsoft'
  | 'bxl-microsoft-teams'
  | 'bxl-netlify'
  | 'bxl-nodejs'
  | 'bxl-ok-ru'
  | 'bxl-opera'
  | 'bxl-patreon'
  | 'bxl-paypal'
  | 'bxl-periscope'
  | 'bxl-php'
  | 'bxl-pinterest'
  | 'bxl-pinterest-alt'
  | 'bxl-play-store'
  | 'bxl-pocket'
  | 'bxl-product-hunt'
  | 'bxl-python'
  | 'bxl-quora'
  | 'bxl-react'
  | 'bxl-redbubble'
  | 'bxl-reddit'
  | 'bxl-redux'
  | 'bxl-sass'
  | 'bxl-shopify'
  | 'bxl-sketch'
  | 'bxl-skype'
  | 'bxl-slack'
  | 'bxl-slack-old'
  | 'bxl-snapchat'
  | 'bxl-soundcloud'
  | 'bxl-spotify'
  | 'bxl-spring-boot'
  | 'bxl-squarespace'
  | 'bxl-stack-overflow'
  | 'bxl-steam'
  | 'bxl-stripe'
  | 'bxl-tailwind-css'
  | 'bxl-telegram'
  | 'bxl-tiktok'
  | 'bxl-trello'
  | 'bxl-trip-advisor'
  | 'bxl-tumblr'
  | 'bxl-tux'
  | 'bxl-twitch'
  | 'bxl-twitter'
  | 'bxl-unity'
  | 'bxl-unsplash'
  | 'bxl-upwork'
  | 'bxl-venmo'
  | 'bxl-vimeo'
  | 'bxl-visa'
  | 'bxl-visual-studio'
  | 'bxl-vk'
  | 'bxl-vuejs'
  | 'bxl-whatsapp'
  | 'bxl-whatsapp-square'
  | 'bxl-wikipedia'
  | 'bxl-windows'
  | 'bxl-wix'
  | 'bxl-wordpress'
  | 'bxl-yahoo'
  | 'bxl-yelp'
  | 'bxl-youtube'
  | 'bxl-zoom'
  | 'bxs-add-to-queue'
  | 'bxs-adjust'
  | 'bxs-adjust-alt'
  | 'bxs-alarm'
  | 'bxs-alarm-add'
  | 'bxs-alarm-exclamation'
  | 'bxs-alarm-off'
  | 'bxs-alarm-snooze'
  | 'bxs-album'
  | 'bxs-ambulance'
  | 'bxs-analyse'
  | 'bxs-angry'
  | 'bxs-arch'
  | 'bxs-archive'
  | 'bxs-archive-in'
  | 'bxs-archive-out'
  | 'bxs-area'
  | 'bxs-arrow-from-bottom'
  | 'bxs-arrow-from-left'
  | 'bxs-arrow-from-right'
  | 'bxs-arrow-from-top'
  | 'bxs-arrow-to-bottom'
  | 'bxs-arrow-to-left'
  | 'bxs-arrow-to-right'
  | 'bxs-arrow-to-top'
  | 'bxs-award'
  | 'bxs-baby-carriage'
  | 'bxs-backpack'
  | 'bxs-badge'
  | 'bxs-badge-check'
  | 'bxs-badge-dollar'
  | 'bxs-baguette'
  | 'bxs-ball'
  | 'bxs-band-aid'
  | 'bxs-bank'
  | 'bxs-bar-chart-alt-2'
  | 'bxs-bar-chart-square'
  | 'bxs-barcode'
  | 'bxs-baseball'
  | 'bxs-basket'
  | 'bxs-basketball'
  | 'bxs-bath'
  | 'bxs-battery'
  | 'bxs-battery-charging'
  | 'bxs-battery-full'
  | 'bxs-battery-low'
  | 'bxs-bed'
  | 'bxs-been-here'
  | 'bxs-beer'
  | 'bxs-bell'
  | 'bxs-bell-minus'
  | 'bxs-bell-off'
  | 'bxs-bell-plus'
  | 'bxs-bell-ring'
  | 'bxs-bible'
  | 'bxs-binoculars'
  | 'bxs-blanket'
  | 'bxs-bolt'
  | 'bxs-bolt-circle'
  | 'bxs-bomb'
  | 'bxs-bone'
  | 'bxs-bong'
  | 'bxs-book'
  | 'bxs-book-add'
  | 'bxs-book-alt'
  | 'bxs-book-bookmark'
  | 'bxs-book-content'
  | 'bxs-book-heart'
  | 'bxs-book-open'
  | 'bxs-book-reader'
  | 'bxs-bookmark'
  | 'bxs-bookmark-alt'
  | 'bxs-bookmark-alt-minus'
  | 'bxs-bookmark-alt-plus'
  | 'bxs-bookmark-heart'
  | 'bxs-bookmark-minus'
  | 'bxs-bookmark-plus'
  | 'bxs-bookmark-star'
  | 'bxs-bookmarks'
  | 'bxs-bot'
  | 'bxs-bowl-hot'
  | 'bxs-bowl-rice'
  | 'bxs-bowling-ball'
  | 'bxs-box'
  | 'bxs-brain'
  | 'bxs-briefcase'
  | 'bxs-briefcase-alt'
  | 'bxs-briefcase-alt-2'
  | 'bxs-brightness'
  | 'bxs-brightness-half'
  | 'bxs-brush'
  | 'bxs-brush-alt'
  | 'bxs-bug'
  | 'bxs-bug-alt'
  | 'bxs-building'
  | 'bxs-building-house'
  | 'bxs-buildings'
  | 'bxs-bulb'
  | 'bxs-bullseye'
  | 'bxs-buoy'
  | 'bxs-bus'
  | 'bxs-bus-school'
  | 'bxs-business'
  | 'bxs-cabinet'
  | 'bxs-cable-car'
  | 'bxs-cake'
  | 'bxs-calculator'
  | 'bxs-calendar'
  | 'bxs-calendar-alt'
  | 'bxs-calendar-check'
  | 'bxs-calendar-edit'
  | 'bxs-calendar-event'
  | 'bxs-calendar-exclamation'
  | 'bxs-calendar-heart'
  | 'bxs-calendar-minus'
  | 'bxs-calendar-plus'
  | 'bxs-calendar-star'
  | 'bxs-calendar-week'
  | 'bxs-calendar-x'
  | 'bxs-camera'
  | 'bxs-camera-home'
  | 'bxs-camera-movie'
  | 'bxs-camera-off'
  | 'bxs-camera-plus'
  | 'bxs-capsule'
  | 'bxs-captions'
  | 'bxs-car'
  | 'bxs-car-battery'
  | 'bxs-car-crash'
  | 'bxs-car-garage'
  | 'bxs-car-mechanic'
  | 'bxs-car-wash'
  | 'bxs-card'
  | 'bxs-caret-down-circle'
  | 'bxs-caret-down-square'
  | 'bxs-caret-left-circle'
  | 'bxs-caret-left-square'
  | 'bxs-caret-right-circle'
  | 'bxs-caret-right-square'
  | 'bxs-caret-up-circle'
  | 'bxs-caret-up-square'
  | 'bxs-carousel'
  | 'bxs-cart'
  | 'bxs-cart-add'
  | 'bxs-cart-alt'
  | 'bxs-cart-download'
  | 'bxs-cat'
  | 'bxs-category'
  | 'bxs-category-alt'
  | 'bxs-cctv'
  | 'bxs-certification'
  | 'bxs-chalkboard'
  | 'bxs-chart'
  | 'bxs-chat'
  | 'bxs-check-circle'
  | 'bxs-check-shield'
  | 'bxs-check-square'
  | 'bxs-checkbox'
  | 'bxs-checkbox-checked'
  | 'bxs-checkbox-minus'
  | 'bxs-chess'
  | 'bxs-chevron-down'
  | 'bxs-chevron-down-circle'
  | 'bxs-chevron-down-square'
  | 'bxs-chevron-left'
  | 'bxs-chevron-left-circle'
  | 'bxs-chevron-left-square'
  | 'bxs-chevron-right'
  | 'bxs-chevron-right-circle'
  | 'bxs-chevron-right-square'
  | 'bxs-chevron-up'
  | 'bxs-chevron-up-circle'
  | 'bxs-chevron-up-square'
  | 'bxs-chevrons-down'
  | 'bxs-chevrons-left'
  | 'bxs-chevrons-right'
  | 'bxs-chevrons-up'
  | 'bxs-chip'
  | 'bxs-church'
  | 'bxs-circle'
  | 'bxs-circle-half'
  | 'bxs-circle-quarter'
  | 'bxs-circle-three-quarter'
  | 'bxs-city'
  | 'bxs-clinic'
  | 'bxs-cloud'
  | 'bxs-cloud-download'
  | 'bxs-cloud-lightning'
  | 'bxs-cloud-rain'
  | 'bxs-cloud-upload'
  | 'bxs-coffee'
  | 'bxs-coffee-alt'
  | 'bxs-coffee-togo'
  | 'bxs-cog'
  | 'bxs-coin'
  | 'bxs-coin-stack'
  | 'bxs-collection'
  | 'bxs-color-fill'
  | 'bxs-comment'
  | 'bxs-comment-add'
  | 'bxs-comment-check'
  | 'bxs-comment-detail'
  | 'bxs-comment-dots'
  | 'bxs-comment-edit'
  | 'bxs-comment-error'
  | 'bxs-comment-minus'
  | 'bxs-comment-x'
  | 'bxs-compass'
  | 'bxs-component'
  | 'bxs-confused'
  | 'bxs-contact'
  | 'bxs-conversation'
  | 'bxs-cookie'
  | 'bxs-cool'
  | 'bxs-copy'
  | 'bxs-copy-alt'
  | 'bxs-copyright'
  | 'bxs-coupon'
  | 'bxs-credit-card'
  | 'bxs-credit-card-alt'
  | 'bxs-credit-card-front'
  | 'bxs-cricket-ball'
  | 'bxs-crop'
  | 'bxs-crown'
  | 'bxs-cube'
  | 'bxs-cube-alt'
  | 'bxs-cuboid'
  | 'bxs-customize'
  | 'bxs-cylinder'
  | 'bxs-dashboard'
  | 'bxs-data'
  | 'bxs-detail'
  | 'bxs-devices'
  | 'bxs-diamond'
  | 'bxs-dice-1'
  | 'bxs-dice-2'
  | 'bxs-dice-3'
  | 'bxs-dice-4'
  | 'bxs-dice-5'
  | 'bxs-dice-6'
  | 'bxs-direction-left'
  | 'bxs-direction-right'
  | 'bxs-directions'
  | 'bxs-disc'
  | 'bxs-discount'
  | 'bxs-dish'
  | 'bxs-dislike'
  | 'bxs-dizzy'
  | 'bxs-dock-bottom'
  | 'bxs-dock-left'
  | 'bxs-dock-right'
  | 'bxs-dock-top'
  | 'bxs-dog'
  | 'bxs-dollar-circle'
  | 'bxs-donate-blood'
  | 'bxs-donate-heart'
  | 'bxs-door-open'
  | 'bxs-doughnut-chart'
  | 'bxs-down-arrow'
  | 'bxs-down-arrow-alt'
  | 'bxs-down-arrow-circle'
  | 'bxs-down-arrow-square'
  | 'bxs-download'
  | 'bxs-downvote'
  | 'bxs-drink'
  | 'bxs-droplet'
  | 'bxs-droplet-half'
  | 'bxs-dryer'
  | 'bxs-duplicate'
  | 'bxs-edit'
  | 'bxs-edit-alt'
  | 'bxs-edit-location'
  | 'bxs-eject'
  | 'bxs-envelope'
  | 'bxs-envelope-open'
  | 'bxs-eraser'
  | 'bxs-error'
  | 'bxs-error-alt'
  | 'bxs-error-circle'
  | 'bxs-ev-station'
  | 'bxs-exit'
  | 'bxs-extension'
  | 'bxs-eyedropper'
  | 'bxs-face'
  | 'bxs-face-mask'
  | 'bxs-factory'
  | 'bxs-fast-forward-circle'
  | 'bxs-file'
  | 'bxs-file-archive'
  | 'bxs-file-blank'
  | 'bxs-file-css'
  | 'bxs-file-doc'
  | 'bxs-file-export'
  | 'bxs-file-find'
  | 'bxs-file-gif'
  | 'bxs-file-html'
  | 'bxs-file-image'
  | 'bxs-file-import'
  | 'bxs-file-jpg'
  | 'bxs-file-js'
  | 'bxs-file-json'
  | 'bxs-file-md'
  | 'bxs-file-pdf'
  | 'bxs-file-plus'
  | 'bxs-file-png'
  | 'bxs-file-txt'
  | 'bxs-film'
  | 'bxs-filter-alt'
  | 'bxs-first-aid'
  | 'bxs-flag'
  | 'bxs-flag-alt'
  | 'bxs-flag-checkered'
  | 'bxs-flame'
  | 'bxs-flask'
  | 'bxs-florist'
  | 'bxs-folder'
  | 'bxs-folder-minus'
  | 'bxs-folder-open'
  | 'bxs-folder-plus'
  | 'bxs-food-menu'
  | 'bxs-fridge'
  | 'bxs-game'
  | 'bxs-gas-pump'
  | 'bxs-ghost'
  | 'bxs-gift'
  | 'bxs-graduation'
  | 'bxs-grid'
  | 'bxs-grid-alt'
  | 'bxs-group'
  | 'bxs-guitar-amp'
  | 'bxs-hand'
  | 'bxs-hand-down'
  | 'bxs-hand-left'
  | 'bxs-hand-right'
  | 'bxs-hand-up'
  | 'bxs-happy'
  | 'bxs-happy-alt'
  | 'bxs-happy-beaming'
  | 'bxs-happy-heart-eyes'
  | 'bxs-hdd'
  | 'bxs-heart'
  | 'bxs-heart-circle'
  | 'bxs-heart-square'
  | 'bxs-help-circle'
  | 'bxs-hide'
  | 'bxs-home'
  | 'bxs-home-circle'
  | 'bxs-home-heart'
  | 'bxs-home-smile'
  | 'bxs-hot'
  | 'bxs-hotel'
  | 'bxs-hourglass'
  | 'bxs-hourglass-bottom'
  | 'bxs-hourglass-top'
  | 'bxs-id-card'
  | 'bxs-image'
  | 'bxs-image-add'
  | 'bxs-image-alt'
  | 'bxs-inbox'
  | 'bxs-info-circle'
  | 'bxs-info-square'
  | 'bxs-injection'
  | 'bxs-institution'
  | 'bxs-invader'
  | 'bxs-joystick'
  | 'bxs-joystick-alt'
  | 'bxs-joystick-button'
  | 'bxs-key'
  | 'bxs-keyboard'
  | 'bxs-label'
  | 'bxs-landmark'
  | 'bxs-landscape'
  | 'bxs-laugh'
  | 'bxs-layer'
  | 'bxs-layer-minus'
  | 'bxs-layer-plus'
  | 'bxs-layout'
  | 'bxs-leaf'
  | 'bxs-left-arrow'
  | 'bxs-left-arrow-alt'
  | 'bxs-left-arrow-circle'
  | 'bxs-left-arrow-square'
  | 'bxs-left-down-arrow-circle'
  | 'bxs-left-top-arrow-circle'
  | 'bxs-lemon'
  | 'bxs-like'
  | 'bxs-location-plus'
  | 'bxs-lock'
  | 'bxs-lock-alt'
  | 'bxs-lock-open'
  | 'bxs-lock-open-alt'
  | 'bxs-log-in'
  | 'bxs-log-in-circle'
  | 'bxs-log-out'
  | 'bxs-log-out-circle'
  | 'bxs-low-vision'
  | 'bxs-magic-wand'
  | 'bxs-magnet'
  | 'bxs-map'
  | 'bxs-map-alt'
  | 'bxs-map-pin'
  | 'bxs-mask'
  | 'bxs-medal'
  | 'bxs-megaphone'
  | 'bxs-meh'
  | 'bxs-meh-alt'
  | 'bxs-meh-blank'
  | 'bxs-memory-card'
  | 'bxs-message'
  | 'bxs-message-add'
  | 'bxs-message-alt'
  | 'bxs-message-alt-add'
  | 'bxs-message-alt-check'
  | 'bxs-message-alt-detail'
  | 'bxs-message-alt-dots'
  | 'bxs-message-alt-edit'
  | 'bxs-message-alt-error'
  | 'bxs-message-alt-minus'
  | 'bxs-message-alt-x'
  | 'bxs-message-check'
  | 'bxs-message-detail'
  | 'bxs-message-dots'
  | 'bxs-message-edit'
  | 'bxs-message-error'
  | 'bxs-message-minus'
  | 'bxs-message-rounded'
  | 'bxs-message-rounded-add'
  | 'bxs-message-rounded-check'
  | 'bxs-message-rounded-detail'
  | 'bxs-message-rounded-dots'
  | 'bxs-message-rounded-edit'
  | 'bxs-message-rounded-error'
  | 'bxs-message-rounded-minus'
  | 'bxs-message-rounded-x'
  | 'bxs-message-square'
  | 'bxs-message-square-add'
  | 'bxs-message-square-check'
  | 'bxs-message-square-detail'
  | 'bxs-message-square-dots'
  | 'bxs-message-square-edit'
  | 'bxs-message-square-error'
  | 'bxs-message-square-minus'
  | 'bxs-message-square-x'
  | 'bxs-message-x'
  | 'bxs-meteor'
  | 'bxs-microchip'
  | 'bxs-microphone'
  | 'bxs-microphone-alt'
  | 'bxs-microphone-off'
  | 'bxs-minus-circle'
  | 'bxs-minus-square'
  | 'bxs-mobile'
  | 'bxs-mobile-vibration'
  | 'bxs-moon'
  | 'bxs-mouse'
  | 'bxs-mouse-alt'
  | 'bxs-movie'
  | 'bxs-movie-play'
  | 'bxs-music'
  | 'bxs-navigation'
  | 'bxs-network-chart'
  | 'bxs-news'
  | 'bxs-no-entry'
  | 'bxs-note'
  | 'bxs-notepad'
  | 'bxs-notification'
  | 'bxs-notification-off'
  | 'bxs-offer'
  | 'bxs-package'
  | 'bxs-paint'
  | 'bxs-paint-roll'
  | 'bxs-palette'
  | 'bxs-paper-plane'
  | 'bxs-parking'
  | 'bxs-party'
  | 'bxs-paste'
  | 'bxs-pen'
  | 'bxs-pencil'
  | 'bxs-phone'
  | 'bxs-phone-call'
  | 'bxs-phone-incoming'
  | 'bxs-phone-off'
  | 'bxs-phone-outgoing'
  | 'bxs-photo-album'
  | 'bxs-piano'
  | 'bxs-pie-chart'
  | 'bxs-pie-chart-alt'
  | 'bxs-pie-chart-alt-2'
  | 'bxs-pin'
  | 'bxs-pizza'
  | 'bxs-plane'
  | 'bxs-plane-alt'
  | 'bxs-plane-land'
  | 'bxs-plane-take-off'
  | 'bxs-planet'
  | 'bxs-playlist'
  | 'bxs-plug'
  | 'bxs-plus-circle'
  | 'bxs-plus-square'
  | 'bxs-pointer'
  | 'bxs-polygon'
  | 'bxs-popsicle'
  | 'bxs-printer'
  | 'bxs-purchase-tag'
  | 'bxs-purchase-tag-alt'
  | 'bxs-pyramid'
  | 'bxs-quote-alt-left'
  | 'bxs-quote-alt-right'
  | 'bxs-quote-left'
  | 'bxs-quote-right'
  | 'bxs-quote-single-left'
  | 'bxs-quote-single-right'
  | 'bxs-radiation'
  | 'bxs-radio'
  | 'bxs-receipt'
  | 'bxs-rectangle'
  | 'bxs-registered'
  | 'bxs-rename'
  | 'bxs-report'
  | 'bxs-rewind-circle'
  | 'bxs-right-arrow'
  | 'bxs-right-arrow-alt'
  | 'bxs-right-arrow-circle'
  | 'bxs-right-arrow-square'
  | 'bxs-right-down-arrow-circle'
  | 'bxs-right-top-arrow-circle'
  | 'bxs-rocket'
  | 'bxs-ruler'
  | 'bxs-sad'
  | 'bxs-save'
  | 'bxs-school'
  | 'bxs-search'
  | 'bxs-search-alt-2'
  | 'bxs-select-multiple'
  | 'bxs-send'
  | 'bxs-server'
  | 'bxs-shapes'
  | 'bxs-share'
  | 'bxs-share-alt'
  | 'bxs-shield'
  | 'bxs-shield-alt-2'
  | 'bxs-shield-x'
  | 'bxs-ship'
  | 'bxs-shocked'
  | 'bxs-shopping-bag'
  | 'bxs-shopping-bag-alt'
  | 'bxs-shopping-bags'
  | 'bxs-show'
  | 'bxs-skip-next-circle'
  | 'bxs-skip-previous-circle'
  | 'bxs-skull'
  | 'bxs-sleepy'
  | 'bxs-slideshow'
  | 'bxs-smile'
  | 'bxs-sort-alt'
  | 'bxs-spa'
  | 'bxs-speaker'
  | 'bxs-spray-can'
  | 'bxs-spreadsheet'
  | 'bxs-square'
  | 'bxs-square-rounded'
  | 'bxs-star'
  | 'bxs-star-half'
  | 'bxs-sticker'
  | 'bxs-stopwatch'
  | 'bxs-store'
  | 'bxs-store-alt'
  | 'bxs-sun'
  | 'bxs-t-shirt'
  | 'bxs-tachometer'
  | 'bxs-tag'
  | 'bxs-tag-alt'
  | 'bxs-tag-x'
  | 'bxs-taxi'
  | 'bxs-tennis-ball'
  | 'bxs-terminal'
  | 'bxs-thermometer'
  | 'bxs-time'
  | 'bxs-time-five'
  | 'bxs-timer'
  | 'bxs-tired'
  | 'bxs-to-top'
  | 'bxs-toggle-left'
  | 'bxs-toggle-right'
  | 'bxs-tone'
  | 'bxs-torch'
  | 'bxs-traffic'
  | 'bxs-traffic-barrier'
  | 'bxs-traffic-cone'
  | 'bxs-train'
  | 'bxs-trash'
  | 'bxs-trash-alt'
  | 'bxs-tree'
  | 'bxs-tree-alt'
  | 'bxs-trophy'
  | 'bxs-truck'
  | 'bxs-tv'
  | 'bxs-up-arrow'
  | 'bxs-up-arrow-alt'
  | 'bxs-up-arrow-circle'
  | 'bxs-up-arrow-square'
  | 'bxs-upside-down'
  | 'bxs-upvote'
  | 'bxs-user'
  | 'bxs-user-account'
  | 'bxs-user-badge'
  | 'bxs-user-check'
  | 'bxs-user-circle'
  | 'bxs-user-detail'
  | 'bxs-user-minus'
  | 'bxs-user-pin'
  | 'bxs-user-plus'
  | 'bxs-user-rectangle'
  | 'bxs-user-voice'
  | 'bxs-user-x'
  | 'bxs-vector'
  | 'bxs-vial'
  | 'bxs-video'
  | 'bxs-video-off'
  | 'bxs-video-plus'
  | 'bxs-video-recording'
  | 'bxs-videos'
  | 'bxs-virus'
  | 'bxs-virus-block'
  | 'bxs-volume'
  | 'bxs-volume-full'
  | 'bxs-volume-low'
  | 'bxs-volume-mute'
  | 'bxs-wallet'
  | 'bxs-wallet-alt'
  | 'bxs-washer'
  | 'bxs-watch'
  | 'bxs-watch-alt'
  | 'bxs-webcam'
  | 'bxs-widget'
  | 'bxs-window-alt'
  | 'bxs-wine'
  | 'bxs-wink-smile'
  | 'bxs-wink-tongue'
  | 'bxs-wrench'
  | 'bxs-x-circle'
  | 'bxs-x-square'
  | 'bxs-yin-yang'
  | 'bxs-zap'
  | 'bxs-zoom-in'
  | 'bxs-zoom-out';

export type BxIconName = keyof typeof bxIconNames | BxIconAlias;
export const Bx = createIconSet<BxIconName>('bx', bxIconNames);
