/**
 * Bytesize Icon Set
 * @see https://icon-sets.iconify.design/bytesize/
 *
 * Auto-generated - do not edit manually
 */

import { createIconSet } from '../createIconSet';

const bytesizeIconNames = {
  activity: true,
  alert: true,
  archive: true,
  'arrow-bottom': true,
  'arrow-left': true,
  'arrow-right': true,
  'arrow-top': true,
  backwards: true,
  bag: true,
  ban: true,
  bell: true,
  book: true,
  bookmark: true,
  calendar: true,
  camera: true,
  'caret-bottom': true,
  'caret-left': true,
  'caret-right': true,
  'caret-top': true,
  cart: true,
  checkmark: true,
  'chevron-bottom': true,
  'chevron-left': true,
  'chevron-right': true,
  'chevron-top': true,
  clipboard: true,
  clock: true,
  close: true,
  code: true,
  compose: true,
  creditcard: true,
  desktop: true,
  download: true,
  edit: true,
  eject: true,
  'ellipsis-horizontal': true,
  'ellipsis-vertical': true,
  end: true,
  export: true,
  external: true,
  eye: true,
  feed: true,
  file: true,
  filter: true,
  flag: true,
  folder: true,
  'folder-open': true,
  forwards: true,
  fullscreen: true,
  'fullscreen-exit': true,
  gift: true,
  github: true,
  heart: true,
  home: true,
  import: true,
  inbox: true,
  info: true,
  lightning: true,
  link: true,
  location: true,
  lock: true,
  mail: true,
  menu: true,
  message: true,
  microphone: true,
  minus: true,
  mobile: true,
  moon: true,
  move: true,
  music: true,
  mute: true,
  options: true,
  paperclip: true,
  pause: true,
  photo: true,
  play: true,
  plus: true,
  portfolio: true,
  print: true,
  reload: true,
  reply: true,
  search: true,
  send: true,
  settings: true,
  'sign-in': true,
  'sign-out': true,
  star: true,
  start: true,
  tag: true,
  telephone: true,
  trash: true,
  twitter: true,
  unlock: true,
  upload: true,
  user: true,
  video: true,
  volume: true,
  work: true,
  'zoom-in': true,
  'zoom-out': true,
  'zoom-reset': true,
} as const;

export type BytesizeIconName = keyof typeof bytesizeIconNames;
export const Bytesize = createIconSet<BytesizeIconName>('bytesize', bytesizeIconNames);
