/**
 * Codex Icon Set
 * @see https://icon-sets.iconify.design/codex/
 *
 * Auto-generated - do not edit manually
 */

import { createIconSet } from '../createIconSet';

const codexIconNames = {
  'add-background': true,
  'add-border': true,
  'align-center': true,
  'align-justify': true,
  'align-left': true,
  'align-right': true,
  bold: true,
  brackets: true,
  'brackets-vertical': true,
  check: true,
  checklist: true,
  'chevron-down': true,
  'chevron-left': true,
  'chevron-right': true,
  'chevron-up': true,
  clipboard: true,
  collapse: true,
  color: true,
  copy: true,
  cross: true,
  'curly-brackets': true,
  delimiter: true,
  'direction-down-right': true,
  'direction-left-down': true,
  'direction-right-down': true,
  'direction-up-right': true,
  'dot-circle': true,
  'etc-horisontal': true,
  'etc-vertical': true,
  file: true,
  gift: true,
  globe: true,
  h1: true,
  h2: true,
  h3: true,
  h4: true,
  h5: true,
  h6: true,
  heading: true,
  heart: true,
  hidden: true,
  html: true,
  instagram: true,
  italic: true,
  link: true,
  linkedin: true,
  'list-bulleted': true,
  'list-numbered': true,
  loader: true,
  marker: true,
  menu: true,
  'menu-small': true,
  picture: true,
  play: true,
  plus: true,
  question: true,
  quote: true,
  redo: true,
  'remove-background': true,
  replace: true,
  save: true,
  search: true,
  star: true,
  stretch: true,
  strikethrough: true,
  table: true,
  'table-with-headings': true,
  'table-without-headings': true,
  text: true,
  translate: true,
  trash: true,
  twitter: true,
  underline: true,
  undo: true,
  unlink: true,
  user: true,
  'users-group': true,
  warning: true,
} as const;

export type CodexIconName = keyof typeof codexIconNames;
export const Codex = createIconSet<CodexIconName>('codex', codexIconNames);
