/**
 * DuoIcons Icon Set
 * @see https://icon-sets.iconify.design/duo-icons/
 *
 * Auto-generated - do not edit manually
 */

import { createIconSet } from '../createIconSet';

const duo_iconsIconNames = {
  'add-circle': true,
  airplay: true,
  'alert-octagon': true,
  'alert-triangle': true,
  'align-bottom': true,
  'align-center': true,
  android: true,
  app: true,
  'app-dots': true,
  apple: true,
  approved: true,
  appstore: true,
  award: true,
  'baby-carriage': true,
  bank: true,
  battery: true,
  bell: true,
  'bell-badge': true,
  book: true,
  'book-2': true,
  'book-3': true,
  bookmark: true,
  box: true,
  'box-2': true,
  bread: true,
  bridge: true,
  briefcase: true,
  brush: true,
  'brush-2': true,
  bug: true,
  building: true,
  bus: true,
  cake: true,
  calendar: true,
  camera: true,
  'camera-square': true,
  campground: true,
  candle: true,
  car: true,
  certificate: true,
  'chart-pie': true,
  'check-circle': true,
  chip: true,
  clapperboard: true,
  clipboard: true,
  clock: true,
  'cloud-lightning': true,
  'cloud-snow': true,
  'coin-stack': true,
  compass: true,
  'computer-camera': true,
  'computer-camera-off': true,
  confetti: true,
  'credit-card': true,
  'currency-euro': true,
  dashboard: true,
  discount: true,
  disk: true,
  file: true,
  fire: true,
  'folder-open': true,
  'folder-upload': true,
  'g-translate': true,
  'id-card': true,
  info: true,
  lamp: true,
  'lamp-2': true,
  location: true,
  marker: true,
  menu: true,
  message: true,
  'message-2': true,
  'message-3': true,
  'moon-2': true,
  'moon-stars': true,
  palette: true,
  rocket: true,
  settings: true,
  'shopping-bag': true,
  slideshow: true,
  smartphone: true,
  'smartphone-vibration': true,
  smartwatch: true,
  sun: true,
  target: true,
  toggle: true,
  translation: true,
  'upload-file': true,
  user: true,
  'user-card': true,
  world: true,
} as const;

export type DuoIconsIconName = keyof typeof duo_iconsIconNames;
export const DuoIcons = createIconSet<DuoIconsIconName>('duo-icons', duo_iconsIconNames);
