/**
 * Ei Icon Set
 * @see https://icon-sets.iconify.design/ei/
 *
 * Auto-generated - do not edit manually
 */

import { createIconSet } from '../createIconSet';

const eiIconNames = {
  archive: true,
  'arrow-down': true,
  'arrow-left': true,
  'arrow-right': true,
  'arrow-up': true,
  bell: true,
  calendar: true,
  camera: true,
  cart: true,
  chart: true,
  check: true,
  'chevron-down': true,
  'chevron-left': true,
  'chevron-right': true,
  'chevron-up': true,
  clock: true,
  close: true,
  'close-o': true,
  comment: true,
  'credit-card': true,
  envelope: true,
  exclamation: true,
  'external-link': true,
  eye: true,
  gear: true,
  heart: true,
  image: true,
  like: true,
  link: true,
  location: true,
  lock: true,
  minus: true,
  navicon: true,
  paperclip: true,
  pencil: true,
  play: true,
  plus: true,
  pointer: true,
  question: true,
  redo: true,
  refresh: true,
  retweet: true,
  'sc-facebook': true,
  'sc-github': true,
  'sc-google-plus': true,
  'sc-instagram': true,
  'sc-linkedin': true,
  'sc-odnoklassniki': true,
  'sc-pinterest': true,
  'sc-skype': true,
  'sc-soundcloud': true,
  'sc-telegram': true,
  'sc-tumblr': true,
  'sc-twitter': true,
  'sc-vimeo': true,
  'sc-vk': true,
  'sc-youtube': true,
  search: true,
  'share-apple': true,
  'share-google': true,
  spinner: true,
  'spinner-2': true,
  'spinner-3': true,
  star: true,
  tag: true,
  trash: true,
  trophy: true,
  undo: true,
  unlock: true,
  user: true,
} as const;

export type EiIconName = keyof typeof eiIconNames;
export const Ei = createIconSet<EiIconName>('ei', eiIconNames);
