/**
 * EntypoSocial Icon Set
 * @see https://icon-sets.iconify.design/entypo-social/
 *
 * Auto-generated - do not edit manually
 */

import { createIconSet } from '../createIconSet';

const entypo_socialIconNames = {
  _500px: '500px',
  '_500px-with-circle': '500px-with-circle',
  basecamp: true,
  behance: true,
  'creative-cloud': true,
  dribbble: true,
  'dribbble-with-circle': true,
  dropbox: true,
  evernote: true,
  facebook: true,
  'facebook-with-circle': true,
  flattr: true,
  flickr: true,
  'flickr-with-circle': true,
  foursquare: true,
  github: true,
  'github-with-circle': true,
  google: true,
  'google-drive': true,
  'google-hangouts': true,
  'google-with-circle': true,
  grooveshark: true,
  icloud: true,
  instagram: true,
  'instagram-with-circle': true,
  lastfm: true,
  'lastfm-with-circle': true,
  linkedin: true,
  'linkedin-with-circle': true,
  medium: true,
  'medium-with-circle': true,
  mixi: true,
  onedrive: true,
  paypal: true,
  picasa: true,
  pinterest: true,
  'pinterest-with-circle': true,
  qq: true,
  'qq-with-circle': true,
  raft: true,
  'raft-with-circle': true,
  rainbow: true,
  rdio: true,
  'rdio-with-circle': true,
  renren: true,
  scribd: true,
  'sina-weibo': true,
  skype: true,
  'skype-with-circle': true,
  slideshare: true,
  smashing: true,
  soundcloud: true,
  spotify: true,
  'spotify-with-circle': true,
  stumbleupon: true,
  'stumbleupon-with-circle': true,
  swarm: true,
  tripadvisor: true,
  tumblr: true,
  'tumblr-with-circle': true,
  twitter: true,
  'twitter-with-circle': true,
  vimeo: true,
  'vimeo-with-circle': true,
  vine: true,
  'vine-with-circle': true,
  vk: true,
  'vk-alternitive': true,
  'vk-with-circle': true,
  xing: true,
  'xing-with-circle': true,
  yelp: true,
  youko: true,
  'youko-with-circle': true,
  youtube: true,
  'youtube-with-circle': true,
} as const;

export type EntypoSocialIconName = keyof typeof entypo_socialIconNames;
export const EntypoSocial = createIconSet<EntypoSocialIconName>(
  'entypo-social',
  entypo_socialIconNames
);
