/**
 * Et Icon Set
 * @see https://icon-sets.iconify.design/et/
 *
 * Auto-generated - do not edit manually
 */

import { createIconSet } from '../createIconSet';

const etIconNames = {
  adjustments: true,
  alarmclock: true,
  anchor: true,
  aperture: true,
  attachments: true,
  bargraph: true,
  basket: true,
  beaker: true,
  bike: true,
  'book-open': true,
  briefcase: true,
  browser: true,
  calendar: true,
  camera: true,
  caution: true,
  chat: true,
  'circle-compass': true,
  clipboard: true,
  clock: true,
  cloud: true,
  compass: true,
  desktop: true,
  dial: true,
  document: true,
  documents: true,
  download: true,
  dribbble: true,
  edit: true,
  envelope: true,
  expand: true,
  facebook: true,
  flag: true,
  focus: true,
  gears: true,
  genius: true,
  gift: true,
  global: true,
  globe: true,
  googleplus: true,
  grid: true,
  happy: true,
  hazardous: true,
  heart: true,
  hotairballoon: true,
  hourglass: true,
  key: true,
  laptop: true,
  layers: true,
  lifesaver: true,
  lightbulb: true,
  linegraph: true,
  linkedin: true,
  lock: true,
  'magnifying-glass': true,
  map: true,
  'map-pin': true,
  megaphone: true,
  mic: true,
  mobile: true,
  newspaper: true,
  notebook: true,
  paintbrush: true,
  paperclip: true,
  pencil: true,
  phone: true,
  picture: true,
  pictures: true,
  piechart: true,
  presentation: true,
  pricetags: true,
  printer: true,
  'profile-female': true,
  'profile-male': true,
  puzzle: true,
  quote: true,
  recycle: true,
  refresh: true,
  ribbon: true,
  rss: true,
  sad: true,
  scissors: true,
  scope: true,
  search: true,
  shield: true,
  speedometer: true,
  strategy: true,
  streetsign: true,
  tablet: true,
  telescope: true,
  toolbox: true,
  tools: true,
  'tools-2': true,
  traget: true,
  trophy: true,
  tumblr: true,
  twitter: true,
  upload: true,
  video: true,
  wallet: true,
  wine: true,
} as const;

export type EtIconName = keyof typeof etIconNames;
export const Et = createIconSet<EtIconName>('et', etIconNames);
