/**
 * FlatUi Icon Set
 * @see https://icon-sets.iconify.design/flat-ui/
 *
 * Auto-generated - do not edit manually
 */

import { createIconSet } from '../createIconSet';

const flat_uiIconNames = {
  android: true,
  android1: true,
  'app-store': true,
  arrow: true,
  art: true,
  bag: true,
  basket: true,
  book: true,
  bowling: true,
  box: true,
  brush: true,
  building: true,
  bulb: true,
  button: true,
  calculator: true,
  calendar: true,
  camera: true,
  car: true,
  card: true,
  chair: true,
  chat: true,
  clipboard: true,
  clocks: true,
  compas: true,
  converse: true,
  cup: true,
  dj: true,
  donut: true,
  dude: true,
  dynamite: true,
  earth: true,
  egg: true,
  eye: true,
  file: true,
  fit: true,
  flag: true,
  flask: true,
  flower: true,
  games: true,
  'gift-box': true,
  girl: true,
  goal: true,
  google: true,
  graph: true,
  icecream: true,
  imac: true,
  ipad: true,
  iphone: true,
  key: true,
  lettersymbol: true,
  lock: true,
  loop: true,
  macbook: true,
  magic: true,
  magicmouse: true,
  mail: true,
  map: true,
  medal: true,
  mic: true,
  money: true,
  mortarboard: true,
  mountain: true,
  news: true,
  'paper-bag': true,
  pc: true,
  pencil: true,
  pencils: true,
  picture: true,
  pig: true,
  pills: true,
  play: true,
  printer: true,
  responsive: true,
  retina: true,
  ring: true,
  rocket: true,
  rss: true,
  safe: true,
  save: true,
  search: true,
  settings: true,
  shield: true,
  shirt: true,
  skateboard: true,
  spray: true,
  storage: true,
  support: true,
  ticket: true,
  'toilet-paper': true,
  touch: true,
  trash: true,
  'trip-bag': true,
  trunk: true,
  ubmrella: true,
  'user-interface': true,
  video: true,
  weather: true,
  'wi-fi': true,
  wine: true,
  yinyang: true,
} as const;

export type FlatUiIconName = keyof typeof flat_uiIconNames;
export const FlatUi = createIconSet<FlatUiIconName>('flat-ui', flat_uiIconNames);
