/**
 * Healthicons Icon Set
 * @see https://icon-sets.iconify.design/healthicons/
 *
 * Auto-generated - do not edit manually
 */

import { createIconSet } from '../createIconSet';

const healthiconsIconNames = {
  'blood-a-n': true,
  'blood-a-n-24px': true,
  'blood-a-n-outline': true,
  'blood-a-n-outline-24px': true,
  'blood-a-p': true,
  'blood-a-p-24px': true,
  'blood-a-p-outline': true,
  'blood-a-p-outline-24px': true,
  'blood-ab-n': true,
  'blood-ab-n-24px': true,
  'blood-ab-n-outline': true,
  'blood-ab-n-outline-24px': true,
  'blood-ab-p': true,
  'blood-ab-p-24px': true,
  'blood-ab-p-outline': true,
  'blood-ab-p-outline-24px': true,
  'blood-b-n': true,
  'blood-b-n-24px': true,
  'blood-b-n-outline': true,
  'blood-b-n-outline-24px': true,
  'blood-b-p': true,
  'blood-b-p-24px': true,
  'blood-b-p-outline': true,
  'blood-b-p-outline-24px': true,
  'blood-bag': true,
  'blood-bag-24px': true,
  'blood-bag-outline': true,
  'blood-bag-outline-24px': true,
  'blood-o-n': true,
  'blood-o-n-24px': true,
  'blood-o-n-outline': true,
  'blood-o-n-outline-24px': true,
  'blood-o-p': true,
  'blood-o-p-24px': true,
  'blood-o-p-outline': true,
  'blood-o-p-outline-24px': true,
  'blood-rh-n': true,
  'blood-rh-n-24px': true,
  'blood-rh-n-outline': true,
  'blood-rh-n-outline-24px': true,
  'blood-rh-p': true,
  'blood-rh-p-24px': true,
  'blood-rh-p-outline': true,
  'blood-rh-p-outline-24px': true,
  antibody: true,
  'antibody-24px': true,
  'antibody-outline': true,
  'antibody-outline-24px': true,
  anus: true,
  'anus-24px': true,
  'anus-outline': true,
  'anus-outline-24px': true,
  arm: true,
  'arm-24px': true,
  'arm-outline': true,
  'arm-outline-24px': true,
  bacteria: true,
  'bacteria-24px': true,
  'bacteria-outline': true,
  'bacteria-outline-24px': true,
  bladder: true,
  'bladder-24px': true,
  'bladder-outline': true,
  'bladder-outline-24px': true,
  'blood-cells': true,
  'blood-cells-24px': true,
  'blood-cells-outline': true,
  'blood-cells-outline-24px': true,
  'blood-drop': true,
  'blood-drop-24px': true,
  'blood-drop-outline': true,
  'blood-drop-outline-24px': true,
  'blood-vessel': true,
  'blood-vessel-outline': true,
  body: true,
  'body-24px': true,
  'body-outline': true,
  'body-outline-24px': true,
  breasts: true,
  'breasts-outline': true,
  'cell-nuclei': true,
  'cell-nuclei-24px': true,
  'cell-nuclei-outline': true,
  'cell-nuclei-outline-24px': true,
  colon: true,
  'colon-outline': true,
  dna: true,
  'dna-24px': true,
  'dna-outline': true,
  'dna-outline-24px': true,
  ear: true,
  'ear-24px': true,
  'ear-outline': true,
  'ear-outline-24px': true,
  enzyme: true,
  'enzyme-24px': true,
  'enzyme-outline': true,
  'enzyme-outline-24px': true,
  eye: true,
  'eye-24px': true,
  'eye-outline': true,
  'eye-outline-24px': true,
  'female-reproductive-system': true,
  'female-reproductive-system-24px': true,
  'female-reproductive-system-outline': true,
  'female-reproductive-system-outline-24px': true,
  foot: true,
  'foot-24px': true,
  'foot-outline': true,
  'foot-outline-24px': true,
  gallbladder: true,
  'gallbladder-24px': true,
  'gallbladder-outline': true,
  'gallbladder-outline-24px': true,
  head: true,
  'head-24px': true,
  'head-outline': true,
  'head-outline-24px': true,
  'heart-organ': true,
  'heart-organ-24px': true,
  'heart-organ-outline': true,
  'heart-organ-outline-24px': true,
  intestine: true,
  'intestine-24px': true,
  'intestine-outline': true,
  'intestine-outline-24px': true,
  joints: true,
  'joints-24px': true,
  'joints-outline': true,
  'joints-outline-24px': true,
  kidneys: true,
  'kidneys-24px': true,
  'kidneys-outline': true,
  'kidneys-outline-24px': true,
  leg: true,
  'leg-24px': true,
  'leg-outline': true,
  'leg-outline-24px': true,
  liver: true,
  'liver-24px': true,
  'liver-alt': true,
  'liver-alt-24px': true,
  'liver-alt-outline': true,
  'liver-alt-outline-24px': true,
  'liver-outline': true,
  'liver-outline-24px': true,
  lungs: true,
  'lungs-24px': true,
  'lungs-outline': true,
  'lungs-outline-24px': true,
  'lymph-nodes': true,
  'lymph-nodes-outline': true,
  mouth: true,
  'mouth-24px': true,
  'mouth-outline': true,
  'mouth-outline-24px': true,
  nerve: true,
  'nerve-outline': true,
  neurology: true,
  'neurology-24px': true,
  'neurology-outline': true,
  'neurology-outline-24px': true,
  nose: true,
  'nose-24px': true,
  'nose-outline': true,
  'nose-outline-24px': true,
  pancreas: true,
  'pancreas-24px': true,
  'pancreas-outline': true,
  'pancreas-outline-24px': true,
  penis: true,
  'penis-24px': true,
  'penis-alt': true,
  'penis-alt-24px': true,
  'penis-alt-outline': true,
  'penis-alt-outline-24px': true,
  'penis-outline': true,
  'penis-outline-24px': true,
  prostate: true,
  'prostate-24px': true,
  'prostate-outline': true,
  'prostate-outline-24px': true,
  skeleton: true,
  'skeleton-24px': true,
  'skeleton-outline': true,
  'skeleton-outline-24px': true,
  skull: true,
  'skull-24px': true,
  'skull-outline': true,
  'skull-outline-24px': true,
  spine: true,
  'spine-24px': true,
  'spine-outline': true,
  'spine-outline-24px': true,
  spleen: true,
  'spleen-24px': true,
  'spleen-outline': true,
  'spleen-outline-24px': true,
  stomach: true,
  'stomach-24px': true,
  'stomach-outline': true,
  'stomach-outline-24px': true,
  testicles: true,
  'testicles-24px': true,
  'testicles-outline': true,
  'testicles-outline-24px': true,
  thyroid: true,
  'thyroid-24px': true,
  'thyroid-outline': true,
  'thyroid-outline-24px': true,
  tissue: true,
  'tissue-24px': true,
  'tissue-outline': true,
  'tissue-outline-24px': true,
  tooth: true,
  'tooth-24px': true,
  'tooth-outline': true,
  'tooth-outline-24px': true,
  tumour: true,
  'tumour-24px': true,
  'tumour-outline': true,
  'tumour-outline-24px': true,
  vagina: true,
  'vagina-alt': true,
  'vagina-alt-24px': true,
  'vagina-alt-outline': true,
  'vagina-alt-outline-24px': true,
  'vagina-outline': true,
  allergies: true,
  'allergies-24px': true,
  'allergies-outline': true,
  'allergies-outline-24px': true,
  'autoimmune-disease': true,
  'autoimmune-disease-24px': true,
  'autoimmune-disease-outline': true,
  'autoimmune-disease-outline-24px': true,
  'back-pain': true,
  'back-pain-24px': true,
  'back-pain-outline': true,
  'back-pain-outline-24px': true,
  'bladder-cancer': true,
  'bladder-cancer-outline': true,
  burn: true,
  'burn-outline': true,
  'cancerous-cell-nuclei': true,
  'cancerous-cell-nuclei-outline': true,
  'cervical-cancer': true,
  'cervical-cancer-24px': true,
  'cervical-cancer-outline': true,
  'cervical-cancer-outline-24px': true,
  'chemical-burn': true,
  'chemical-burn-outline': true,
  chills: true,
  'chills-24px': true,
  'chills-fever': true,
  'chills-fever-outline': true,
  'chills-outline': true,
  'chills-outline-24px': true,
  chlamydia: true,
  'chlamydia-alt': true,
  'chlamydia-alt-outline': true,
  'chlamydia-outline': true,
  'colorectal-cancer': true,
  'colorectal-cancer-outline': true,
  'coughing-alt': true,
  'coughing-alt-24px': true,
  'coughing-alt-outline': true,
  'coughing-alt-outline-24px': true,
  deaf: true,
  'deaf-24px': true,
  'deaf-outline': true,
  'deaf-outline-24px': true,
  diarrhea: true,
  'diarrhea-24px': true,
  'diarrhea-outline': true,
  'diarrhea-outline-24px': true,
  'dry-eyes': true,
  'dry-eyes-outline': true,
  'dry-mouth': true,
  'dry-mouth-outline': true,
  gonorrhea: true,
  'gonorrhea-24px': true,
  'gonorrhea-alt': true,
  'gonorrhea-alt-outline': true,
  'gonorrhea-outline': true,
  'gonorrhea-outline-24px': true,
  headache: true,
  'headache-24px': true,
  'headache-outline': true,
  'headache-outline-24px': true,
  'hiv-ind': true,
  'hiv-ind-outline': true,
  'hiv-neg': true,
  'hiv-neg-outline': true,
  'hiv-pos': true,
  'hiv-pos-outline': true,
  hpv: true,
  'hpv-outline': true,
  'intestinal-pain': true,
  'intestinal-pain-24px': true,
  'intestinal-pain-outline': true,
  'intestinal-pain-outline-24px': true,
  'loss-smell': true,
  'loss-smell-outline': true,
  'low-vision': true,
  'low-vision-24px': true,
  'low-vision-outline': true,
  'low-vision-outline-24px': true,
  lymphoma: true,
  'lymphoma-outline': true,
  malnutrition: true,
  'malnutrition-outline': true,
  nausea: true,
  'nausea-outline': true,
  'oesophagus-cancer': true,
  'oesophagus-cancer-outline': true,
  overweight: true,
  'overweight-24px': true,
  'overweight-outline': true,
  'overweight-outline-24px': true,
  pain: true,
  'pain-outline': true,
  'pancreatic-cancer': true,
  'pancreatic-cancer-outline': true,
  pneumonia: true,
  'pneumonia-24px': true,
  'pneumonia-outline': true,
  'pneumonia-outline-24px': true,
  'prostate-cancer': true,
  'prostate-cancer-outline': true,
  ribbon: true,
  'ribbon-24px': true,
  'ribbon-outline': true,
  'ribbon-outline-24px': true,
  'skin-cancer': true,
  'skin-cancer-outline': true,
  sti: true,
  'sti-outline': true,
  'stomach-cancer': true,
  'stomach-cancer-outline': true,
  'syphilis-alt': true,
  'syphilis-alt-outline': true,
  tb: true,
  'tb-24px': true,
  'tb-outline': true,
  'tb-outline-24px': true,
  'thyroid-cancer': true,
  'thyroid-cancer-outline': true,
  underweight: true,
  'underweight-24px': true,
  'underweight-outline': true,
  'underweight-outline-24px': true,
  'varicose-vein': true,
  'varicose-vein-24px': true,
  'varicose-vein-outline': true,
  'varicose-vein-outline-24px': true,
  vih: true,
  'vih-1-24px': true,
  'vih-1-outline-24px': true,
  'vih-24px': true,
  'vih-outline': true,
  'vih-outline-24px': true,
  'viral-lung-infection': true,
  'viral-lung-infection-outline': true,
  vomiting: true,
  'vomiting-24px': true,
  'vomiting-outline': true,
  'vomiting-outline-24px': true,
  'contraceptive-diaphragm': true,
  'contraceptive-diaphragm-24px': true,
  'contraceptive-diaphragm-outline': true,
  'contraceptive-diaphragm-outline-24px': true,
  'contraceptive-injection': true,
  'contraceptive-injection-24px': true,
  'contraceptive-injection-outline': true,
  'contraceptive-injection-outline-24px': true,
  'contraceptive-patch': true,
  'contraceptive-patch-24px': true,
  'contraceptive-patch-outline': true,
  'contraceptive-patch-outline-24px': true,
  'contraceptive-voucher': true,
  'contraceptive-voucher-24px': true,
  'contraceptive-voucher-outline': true,
  'contraceptive-voucher-outline-24px': true,
  'copper-iud': true,
  'copper-iud-24px': true,
  'copper-iud-outline': true,
  'copper-iud-outline-24px': true,
  'family-planning': true,
  'family-planning-24px': true,
  'family-planning-outline': true,
  'family-planning-outline-24px': true,
  'female-condom': true,
  'female-condom-24px': true,
  'female-condom-outline': true,
  'female-condom-outline-24px': true,
  'hormonal-ring': true,
  'hormonal-ring-24px': true,
  'hormonal-ring-outline': true,
  'hormonal-ring-outline-24px': true,
  implant: true,
  'implant-24px': true,
  'implant-outline': true,
  'implant-outline-24px': true,
  iud: true,
  'iud-24px': true,
  'iud-outline': true,
  'iud-outline-24px': true,
  'male-condom': true,
  'male-condom-24px': true,
  'male-condom-outline': true,
  'male-condom-outline-24px': true,
  'oral-contraception-pillsx21': true,
  'oral-contraception-pillsx21-24px': true,
  'oral-contraception-pillsx21-outline': true,
  'oral-contraception-pillsx21-outline-24px': true,
  'oral-contraception-pillsx28': true,
  'oral-contraception-pillsx28-outline': true,
  'sayana-press': true,
  'sayana-press-24px': true,
  'sayana-press-outline': true,
  'sayana-press-outline-24px': true,
  sperm: true,
  'sperm-24px': true,
  'sperm-outline': true,
  'sperm-outline-24px': true,
  'asthma-inhaler': true,
  'asthma-inhaler-outline': true,
  'blood-pressure': true,
  'blood-pressure-2': true,
  'blood-pressure-2-outline': true,
  'blood-pressure-monitor': true,
  'blood-pressure-monitor-24px': true,
  'blood-pressure-monitor-outline': true,
  'blood-pressure-monitor-outline-24px': true,
  'blood-pressure-outline': true,
  'breast-pump': true,
  'breast-pump-outline': true,
  cane: true,
  'cane-outline': true,
  cast: true,
  'cast-outline': true,
  'clinical-a': true,
  'clinical-a-outline': true,
  'cochlear-implant': true,
  'cochlear-implant-outline': true,
  'cold-chain': true,
  'cold-chain-outline': true,
  'contact-lenses': true,
  'contact-lenses-24px': true,
  'contact-lenses-outline': true,
  'contact-lenses-outline-24px': true,
  'cpap-machine': true,
  'cpap-machine-24px': true,
  'cpap-machine-outline': true,
  'cpap-machine-outline-24px': true,
  'cpap-masks': true,
  'cpap-masks-24px': true,
  'cpap-masks-outline': true,
  'cpap-masks-outline-24px': true,
  'cpap-tubes': true,
  'cpap-tubes-24px': true,
  'cpap-tubes-outline': true,
  'cpap-tubes-outline-24px': true,
  crutches: true,
  'crutches-outline': true,
  defibrillator: true,
  'defibrillator-24px': true,
  'defibrillator-outline': true,
  'defibrillator-outline-24px': true,
  'dental-hygiene': true,
  'dental-hygiene-outline': true,
  'diabetes-measure': true,
  'diabetes-measure-24px': true,
  'diabetes-measure-outline': true,
  'diabetes-measure-outline-24px': true,
  dialysis: true,
  'dialysis-outline': true,
  ecmo: true,
  'ecmo-24px': true,
  'ecmo-outline': true,
  'ecmo-outline-24px': true,
  'endotracheal-tube': true,
  'endotracheal-tube-outline': true,
  'hearing-aid': true,
  'hearing-aid-outline': true,
  hospitalized: true,
  'hospitalized-24px': true,
  'hospitalized-outline': true,
  'hospitalized-outline-24px': true,
  'infusion-pump': true,
  'infusion-pump-24px': true,
  'infusion-pump-outline': true,
  'infusion-pump-outline-24px': true,
  inpatient: true,
  'inpatient-24px': true,
  'inpatient-outline': true,
  'inpatient-outline-24px': true,
  'intravenous-bag': true,
  'intravenous-bag-24px': true,
  'intravenous-bag-outline': true,
  'intravenous-bag-outline-24px': true,
  'intravenous-drip': true,
  'intravenous-drip-outline': true,
  laryngoscope: true,
  'laryngoscope-outline': true,
  llin: true,
  'llin-24px': true,
  'llin-outline': true,
  'llin-outline-24px': true,
  'medical-sample': true,
  'medical-sample-outline': true,
  'medicine-bottle': true,
  'medicine-bottle-outline': true,
  'medicine-mortar': true,
  'medicine-mortar-outline': true,
  microscope: true,
  'microscope-24px': true,
  'microscope-outline': true,
  'microscope-outline-24px': true,
  'microscope-with-specimen': true,
  'microscope-with-specimen-outline': true,
  mobile: true,
  'mobile-24px': true,
  'mobile-outline': true,
  'mobile-outline-24px': true,
  observation: true,
  'observation-24px': true,
  'observation-outline': true,
  'observation-outline-24px': true,
  odontology: true,
  'odontology-implant': true,
  'odontology-implant-outline': true,
  'odontology-outline': true,
  orthotics: true,
  'orthotics-outline': true,
  'oxygen-tank': true,
  'oxygen-tank-24px': true,
  'oxygen-tank-outline': true,
  'oxygen-tank-outline-24px': true,
  'patient-band': true,
  'patient-band-alt': true,
  'patient-band-alt-outline': true,
  'patient-band-outline': true,
  'ppe-santizer-alt': true,
  'ppe-santizer-alt-outline': true,
  'pulse-oximeter': true,
  'pulse-oximeter-alt': true,
  'pulse-oximeter-alt-outline': true,
  'pulse-oximeter-outline': true,
  sling: true,
  'sling-outline': true,
  sonogram: true,
  'sonogram-outline': true,
  staples: true,
  'staples-24px': true,
  'staples-outline': true,
  'staples-outline-24px': true,
  stent: true,
  'stent-outline': true,
  stethoscope: true,
  'stethoscope-24px': true,
  'stethoscope-outline': true,
  'stethoscope-outline-24px': true,
  stitches: true,
  'stitches-24px': true,
  'stitches-outline': true,
  'stitches-outline-24px': true,
  'surgical-sterilization': true,
  'surgical-sterilization-outline': true,
  syringe: true,
  'syringe-24px': true,
  'syringe-outline': true,
  'syringe-outline-24px': true,
  'syringe-vaccine': true,
  'syringe-vaccine-outline': true,
  tac: true,
  'tac-outline': true,
  'test-tubes': true,
  'test-tubes-24px': true,
  'test-tubes-outline': true,
  'test-tubes-outline-24px': true,
  thermometer: true,
  'thermometer-digital': true,
  'thermometer-digital-24px': true,
  'thermometer-digital-outline': true,
  'thermometer-digital-outline-24px': true,
  'thermometer-outline': true,
  'toilet-paper': true,
  'toilet-paper-outline': true,
  'treated-water': true,
  'treated-water-outline': true,
  'ultrasound-scanner': true,
  'ultrasound-scanner-outline': true,
  'urine-sample': true,
  'urine-sample-outline': true,
  ventilator: true,
  'ventilator-24px': true,
  'ventilator-alt': true,
  'ventilator-alt-24px': true,
  'ventilator-alt-outline': true,
  'ventilator-alt-outline-24px': true,
  'ventilator-outline': true,
  'ventilator-outline-24px': true,
  'virus-lab-research-syringe': true,
  'virus-lab-research-syringe-outline': true,
  'virus-lab-research-test-tube': true,
  'virus-lab-research-test-tube-outline': true,
  'virus-sanitizer-spray': true,
  'virus-sanitizer-spray-outline': true,
  weight: true,
  'weight-24px': true,
  'weight-outline': true,
  'weight-outline-24px': true,
  wheelchair: true,
  'wheelchair-24px': true,
  'wheelchair-alt': true,
  'wheelchair-alt-24px': true,
  'wheelchair-alt-outline': true,
  'wheelchair-alt-outline-24px': true,
  'wheelchair-outline': true,
  'wheelchair-outline-24px': true,
  xray: true,
  'xray-24px': true,
  'xray-outline': true,
  'xray-outline-24px': true,
  biopsy: true,
  'biopsy-24px': true,
  'biopsy-outline': true,
  'biopsy-outline-24px': true,
  'cone-test-on-nets': true,
  'cone-test-on-nets-outline': true,
  'cone-test-on-walls': true,
  'cone-test-on-walls-outline': true,
  'discriminating-concentration-bioassays': true,
  'discriminating-concentration-bioassays-outline': true,
  'hiv-self-test': true,
  'hiv-self-test-outline': true,
  'intensity-concentration-bioassays': true,
  'intensity-concentration-bioassays-outline': true,
  'malaria-microscope': true,
  'malaria-microscope-outline': true,
  'malaria-mixed-microscope': true,
  'malaria-mixed-microscope-outline': true,
  'malaria-pf-microscope': true,
  'malaria-pf-microscope-outline': true,
  'malaria-pv-microscope': true,
  'malaria-pv-microscope-outline': true,
  'malaria-testing': true,
  'malaria-testing-outline': true,
  'mosquito-collection': true,
  'mosquito-collection-outline': true,
  'rdt-result': true,
  'rdt-result-invalid': true,
  'rdt-result-invalid-outline': true,
  'rdt-result-mixed': true,
  'rdt-result-mixed-invalid': true,
  'rdt-result-mixed-invalid-outline': true,
  'rdt-result-mixed-invalid-rectangular': true,
  'rdt-result-mixed-invalid-rectangular-outline': true,
  'rdt-result-mixed-outline': true,
  'rdt-result-mixed-rectangular': true,
  'rdt-result-mixed-rectangular-outline': true,
  'rdt-result-neg': true,
  'rdt-result-neg-invalid': true,
  'rdt-result-neg-invalid-outline': true,
  'rdt-result-neg-invalid-rectangular': true,
  'rdt-result-neg-invalid-rectangular-outline': true,
  'rdt-result-neg-outline': true,
  'rdt-result-neg-rectangular': true,
  'rdt-result-neg-rectangular-outline': true,
  'rdt-result-no-test': true,
  'rdt-result-no-test-outline': true,
  'rdt-result-outline': true,
  'rdt-result-pf': true,
  'rdt-result-pf-invalid': true,
  'rdt-result-pf-invalid-outline': true,
  'rdt-result-pf-invalid-rectangular': true,
  'rdt-result-pf-invalid-rectangular-outline': true,
  'rdt-result-pf-outline': true,
  'rdt-result-pf-rectangular': true,
  'rdt-result-pf-rectangular-outline': true,
  'rdt-result-positive': true,
  'rdt-result-positive-outline': true,
  'rdt-result-pv': true,
  'rdt-result-pv-invalid': true,
  'rdt-result-pv-invalid-outline': true,
  'rdt-result-pv-invalid-rectangular': true,
  'rdt-result-pv-invalid-rectangular-outline': true,
  'rdt-result-pv-outline': true,
  'rdt-result-pv-rectangular': true,
  'rdt-result-pv-rectangular-outline': true,
  'synergist-insecticide-bioassays': true,
  'synergist-insecticide-bioassays-outline': true,
  angry: true,
  'angry-24px': true,
  'angry-outline': true,
  'angry-outline-24px': true,
  bandaged: true,
  'bandaged-24px': true,
  'bandaged-outline': true,
  'bandaged-outline-24px': true,
  calm: true,
  'calm-24px': true,
  'calm-outline': true,
  'calm-outline-24px': true,
  confused: true,
  'confused-24px': true,
  'confused-outline': true,
  'confused-outline-24px': true,
  coughing: true,
  'coughing-24px': true,
  'coughing-outline': true,
  'coughing-outline-24px': true,
  crying: true,
  'crying-24px': true,
  'crying-outline': true,
  'crying-outline-24px': true,
  dizzy: true,
  'dizzy-24px': true,
  'dizzy-outline': true,
  'dizzy-outline-24px': true,
  expectorate: true,
  'expectorate-24px': true,
  'expectorate-outline': true,
  'expectorate-outline-24px': true,
  eyeglasses: true,
  'eyeglasses-24px': true,
  'eyeglasses-outline': true,
  'eyeglasses-outline-24px': true,
  fever: true,
  'fever-24px': true,
  'fever-outline': true,
  'fever-outline-24px': true,
  happy: true,
  'happy-24px': true,
  'happy-outline': true,
  'happy-outline-24px': true,
  'loudly-crying': true,
  'loudly-crying-24px': true,
  'loudly-crying-outline': true,
  'loudly-crying-outline-24px': true,
  masked: true,
  'masked-24px': true,
  'masked-outline': true,
  'masked-outline-24px': true,
  measles: true,
  'measles-24px': true,
  'measles-outline': true,
  'measles-outline-24px': true,
  nauseous: true,
  'nauseous-24px': true,
  'nauseous-outline': true,
  'nauseous-outline-24px': true,
  nervous: true,
  'nervous-24px': true,
  'nervous-outline': true,
  'nervous-outline-24px': true,
  neutral: true,
  'neutral-24px': true,
  'neutral-outline': true,
  'neutral-outline-24px': true,
  'not-ok': true,
  'not-ok-24px': true,
  'not-ok-outline': true,
  'not-ok-outline-24px': true,
  ok: true,
  'ok-24px': true,
  'ok-outline': true,
  'ok-outline-24px': true,
  sad: true,
  'sad-24px': true,
  'sad-outline': true,
  'sad-outline-24px': true,
  sleepy: true,
  'sleepy-24px': true,
  'sleepy-outline': true,
  'sleepy-outline-24px': true,
  sweating: true,
  'sweating-24px': true,
  'sweating-outline': true,
  'sweating-outline-24px': true,
  tongue: true,
  'tongue-24px': true,
  'tongue-outline': true,
  'tongue-outline-24px': true,
  vomitting: true,
  'vomitting-24px': true,
  'vomitting-outline': true,
  'vomitting-outline-24px': true,
  woozy: true,
  'woozy-24px': true,
  'woozy-outline': true,
  'woozy-outline-24px': true,
  exercise: true,
  'exercise-bicycle': true,
  'exercise-bicycle-outline': true,
  'exercise-outline': true,
  running: true,
  'running-24px': true,
  'running-outline': true,
  'running-outline-24px': true,
  swim: true,
  'swim-outline': true,
  'walk-supported': true,
  'walk-supported-24px': true,
  'walk-supported-outline': true,
  'walk-supported-outline-24px': true,
  walking: true,
  'walking-24px': true,
  'walking-outline': true,
  'walking-outline-24px': true,
  weights: true,
  'weights-outline': true,
  'chart-bar': true,
  'chart-bar-24px': true,
  'chart-bar-outline': true,
  'chart-bar-outline-24px': true,
  'chart-bar-stacked': true,
  'chart-bar-stacked-24px': true,
  'chart-bar-stacked-outline': true,
  'chart-bar-stacked-outline-24px': true,
  'chart-cured-decreasing': true,
  'chart-cured-decreasing-24px': true,
  'chart-cured-decreasing-outline': true,
  'chart-cured-decreasing-outline-24px': true,
  'chart-cured-increasing': true,
  'chart-cured-increasing-24px': true,
  'chart-cured-increasing-outline': true,
  'chart-cured-increasing-outline-24px': true,
  'chart-death-rate-decreasing': true,
  'chart-death-rate-decreasing-24px': true,
  'chart-death-rate-decreasing-outline': true,
  'chart-death-rate-decreasing-outline-24px': true,
  'chart-death-rate-increasing': true,
  'chart-death-rate-increasing-24px': true,
  'chart-death-rate-increasing-outline': true,
  'chart-death-rate-increasing-outline-24px': true,
  'chart-death-rate-stable': true,
  'chart-death-rate-stable-24px': true,
  'chart-death-rate-stable-outline': true,
  'chart-death-rate-stable-outline-24px': true,
  'chart-infected-decreasing': true,
  'chart-infected-decreasing-24px': true,
  'chart-infected-decreasing-outline': true,
  'chart-infected-decreasing-outline-24px': true,
  'chart-infected-increasing': true,
  'chart-infected-increasing-24px': true,
  'chart-infected-increasing-outline': true,
  'chart-infected-increasing-outline-24px': true,
  'chart-infected-stable': true,
  'chart-infected-stable-24px': true,
  'chart-infected-stable-outline': true,
  'chart-infected-stable-outline-24px': true,
  'chart-line': true,
  'chart-line-24px': true,
  'chart-line-outline': true,
  'chart-line-outline-24px': true,
  'chart-line-stacked': true,
  'chart-line-stacked-24px': true,
  'chart-line-stacked-outline': true,
  'chart-line-stacked-outline-24px': true,
  'chart-pie': true,
  'chart-pie-24px': true,
  'chart-pie-outline': true,
  'chart-pie-outline-24px': true,
  'blister-pills-oval-x1': true,
  'blister-pills-oval-x1-outline': true,
  'blister-pills-oval-x14': true,
  'blister-pills-oval-x14-outline': true,
  'blister-pills-oval-x16': true,
  'blister-pills-oval-x16-outline': true,
  'blister-pills-oval-x4': true,
  'blister-pills-oval-x4-outline': true,
  'blister-pills-round-x1': true,
  'blister-pills-round-x1-outline': true,
  'blister-pills-round-x14': true,
  'blister-pills-round-x14-outline': true,
  'blister-pills-round-x16': true,
  'blister-pills-round-x16-24px': true,
  'blister-pills-round-x16-outline': true,
  'blister-pills-round-x16-outline-24px': true,
  'blister-pills-round-x4': true,
  'blister-pills-round-x4-outline': true,
  medicines: true,
  'medicines-24px': true,
  'medicines-outline': true,
  'medicines-outline-24px': true,
  'pill-1': true,
  'pill-1-24px': true,
  'pill-1-outline': true,
  'pill-1-outline-24px': true,
  'pills-2': true,
  'pills-2-24px': true,
  'pills-2-outline': true,
  'pills-2-outline-24px': true,
  'pills-3': true,
  'pills-3-24px': true,
  'pills-3-outline': true,
  'pills-3-outline-24px': true,
  'pills-4': true,
  'pills-4-24px': true,
  'pills-4-outline': true,
  'pills-4-outline-24px': true,
  alcohol: true,
  'alcohol-cessation': true,
  'alcohol-cessation-outline': true,
  'alcohol-outline': true,
  'baby-formula': true,
  'baby-formula-outline': true,
  carbohydrates: true,
  'carbohydrates-outline': true,
  dairy: true,
  'dairy-outline': true,
  fruits: true,
  'fruits-outline': true,
  gluten: true,
  'gluten-free': true,
  'gluten-free-outline': true,
  'gluten-outline': true,
  'hot-meal': true,
  'hot-meal-24px': true,
  'hot-meal-outline': true,
  'hot-meal-outline-24px': true,
  lactose: true,
  'lactose-free': true,
  'lactose-free-outline': true,
  'lactose-outline': true,
  nutrition: true,
  'nutrition-24px': true,
  'nutrition-outline': true,
  'nutrition-outline-24px': true,
  'sodium-free': true,
  'sodium-free-outline': true,
  sugar: true,
  'sugar-alt': true,
  'sugar-alt-outline': true,
  'sugar-free': true,
  'sugar-free-24px': true,
  'sugar-free-outline': true,
  'sugar-free-outline-24px': true,
  'sugar-outline': true,
  'unhealthy-food': true,
  'unhealthy-food-24px': true,
  'unhealthy-food-outline': true,
  'unhealthy-food-outline-24px': true,
  vegetables: true,
  'vegetables-outline': true,
  'award-trophy': true,
  'award-trophy-outline': true,
  'bandage-adhesive': true,
  'bandage-adhesive-outline': true,
  bills: true,
  'bills-outline': true,
  book: true,
  'book-outline': true,
  calendar: true,
  'calendar-outline': true,
  cleaning: true,
  'cleaning-outline': true,
  coins: true,
  'coins-outline': true,
  construction: true,
  'construction-outline': true,
  'credit-card': true,
  'credit-card-outline': true,
  'desktop-app': true,
  'desktop-app-outline': true,
  'health-worker-form': true,
  'health-worker-form-outline': true,
  'i-certificate-paper': true,
  'i-certificate-paper-outline': true,
  'i-utensils': true,
  'i-utensils-outline': true,
  'insurance-card': true,
  'insurance-card-outline': true,
  justice: true,
  'justice-24px': true,
  'justice-outline': true,
  'justice-outline-24px': true,
  laptop: true,
  'laptop-outline': true,
  megaphone: true,
  'megaphone-outline': true,
  'money-bag': true,
  'money-bag-outline': true,
  phone: true,
  'phone-outline': true,
  'prescription-document': true,
  'prescription-document-outline': true,
  'rdt-result-out-stock': true,
  'rdt-result-out-stock-outline': true,
  'register-book': true,
  'register-book-outline': true,
  'running-water': true,
  'running-water-24px': true,
  'running-water-outline': true,
  'running-water-outline-24px': true,
  spreadsheets: true,
  'spreadsheets-outline': true,
  'stock-out': true,
  'stock-out-outline': true,
  umbrella: true,
  'umbrella-outline': true,
  agriculture: true,
  'agriculture-outline': true,
  'agriculture-worker': true,
  'agriculture-worker-alt': true,
  'agriculture-worker-alt-outline': true,
  'agriculture-worker-outline': true,
  ancv: true,
  'ancv-outline': true,
  asthma: true,
  'asthma-outline': true,
  'baby-0203-alt': true,
  'baby-0203-alt-24px': true,
  'baby-0203-alt-outline': true,
  'baby-0203-alt-outline-24px': true,
  'baby-0203m': true,
  'baby-0203m-24px': true,
  'baby-0203m-outline': true,
  'baby-0203m-outline-24px': true,
  'baby-0306m': true,
  'baby-0306m-24px': true,
  'baby-0306m-outline': true,
  'baby-0306m-outline-24px': true,
  'baby-female-0203m-alt': true,
  'baby-female-0203m-alt-outline': true,
  'baby-female-0306m': true,
  'baby-female-0306m-outline': true,
  'baby-female-0609m': true,
  'baby-female-0609m-outline': true,
  'baby-male-0203m-alt': true,
  'baby-male-0203m-alt-outline': true,
  'baby-male-0306m': true,
  'baby-male-0306m-outline': true,
  'baby-male-0609m': true,
  'baby-male-0609m-outline': true,
  'boy-0105y': true,
  'boy-0105y-24px': true,
  'boy-0105y-outline': true,
  'boy-0105y-outline-24px': true,
  'boy-1015y': true,
  'boy-1015y-outline': true,
  'call-centre': true,
  'call-centre-outline': true,
  'child-care': true,
  'child-care-outline': true,
  'child-cognition': true,
  'child-cognition-outline': true,
  'child-program': true,
  'child-program-outline': true,
  'city-worker': true,
  'city-worker-outline': true,
  'clean-hands': true,
  'clean-hands-outline': true,
  'community-healthworker': true,
  'community-healthworker-24px': true,
  'community-healthworker-outline': true,
  'community-healthworker-outline-24px': true,
  'construction-worker': true,
  'construction-worker-outline': true,
  cpr: true,
  'cpr-outline': true,
  'crisis-response-center-person': true,
  'crisis-response-center-person-outline': true,
  'diabetes-24px': true,
  'diabetes-outline-24px': true,
  doctor: true,
  'doctor-24px': true,
  'doctor-female': true,
  'doctor-female-outline': true,
  'doctor-male': true,
  'doctor-male-outline': true,
  'doctor-outline': true,
  'doctor-outline-24px': true,
  'domestic-worker': true,
  'domestic-worker-alt': true,
  'domestic-worker-alt-outline': true,
  'domestic-worker-outline': true,
  elderly: true,
  'elderly-outline': true,
  'exercise-yoga': true,
  'exercise-yoga-outline': true,
  'factory-worker': true,
  'factory-worker-outline': true,
  'female-and-male': true,
  'female-and-male-outline': true,
  'female-sex-worker': true,
  'female-sex-worker-outline': true,
  fetus: true,
  'fetus-24px': true,
  'fetus-outline': true,
  'fetus-outline-24px': true,
  'girl-0105y': true,
  'girl-0105y-24px': true,
  'girl-0105y-outline': true,
  'girl-0105y-outline-24px': true,
  'girl-1015y': true,
  'girl-1015y-outline': true,
  'group-discussion-meeting': true,
  'group-discussion-meeting-outline': true,
  'group-discussion-meetingx3': true,
  'group-discussion-meetingx3-outline': true,
  'health-worker': true,
  'health-worker-24px': true,
  'health-worker-outline': true,
  'health-worker-outline-24px': true,
  'i-groups-perspective-crowd': true,
  'i-groups-perspective-crowd-outline': true,
  'i-training-class': true,
  'i-training-class-24px': true,
  'i-training-class-outline': true,
  'i-training-class-outline-24px': true,
  'male-and-female': true,
  'male-and-female-24px': true,
  'male-and-female-outline': true,
  'male-and-female-outline-24px': true,
  'male-sex-worker': true,
  'male-sex-worker-outline': true,
  man: true,
  'man-24px': true,
  'man-outline': true,
  'man-outline-24px': true,
  'mental-disorders': true,
  'mental-disorders-outline': true,
  'military-worker': true,
  'military-worker-outline': true,
  'miner-worker': true,
  'miner-worker-alt': true,
  'miner-worker-alt-outline': true,
  'miner-worker-outline': true,
  msm: true,
  'msm-outline': true,
  'neuro-surgery': true,
  'neuro-surgery-outline': true,
  nurse: true,
  'nurse-outline': true,
  officer: true,
  'officer-outline': true,
  'old-man': true,
  'old-man-24px': true,
  'old-man-outline': true,
  'old-man-outline-24px': true,
  'old-woman': true,
  'old-woman-24px': true,
  'old-woman-outline': true,
  'old-woman-outline-24px': true,
  outpatient: true,
  'outpatient-outline': true,
  'pediatric-surgery': true,
  'pediatric-surgery-outline': true,
  people: true,
  'people-outline': true,
  person: true,
  'person-outline': true,
  'plantation-worker': true,
  'plantation-worker-alt': true,
  'plantation-worker-alt-outline': true,
  'plantation-worker-outline': true,
  pregnant: true,
  'pregnant-0812w': true,
  'pregnant-0812w-outline': true,
  'pregnant-2426w': true,
  'pregnant-2426w-outline': true,
  'pregnant-24px': true,
  'pregnant-32w': true,
  'pregnant-32w-outline': true,
  'pregnant-3638w': true,
  'pregnant-3638w-outline': true,
  'pregnant-outline': true,
  'pregnant-outline-24px': true,
  prisoner: true,
  'prisoner-outline': true,
  pwid: true,
  'pwid-outline': true,
  refused: true,
  'refused-24px': true,
  'refused-outline': true,
  'refused-outline-24px': true,
  'regular-patient': true,
  'regular-patient-outline': true,
  rmnh: true,
  'rmnh-outline': true,
  'security-worker': true,
  'security-worker-outline': true,
  spraying: true,
  'spraying-outline': true,
  'surveilance-officer': true,
  'surveilance-officer-24px': true,
  'surveilance-officer-outline': true,
  'surveilance-officer-outline-24px': true,
  symptom: true,
  'symptom-24px': true,
  'symptom-outline': true,
  'symptom-outline-24px': true,
  traumatism: true,
  'traumatism-outline': true,
  travel: true,
  'travel-alt': true,
  'travel-alt-outline': true,
  'travel-outline': true,
  'truck-driver': true,
  'truck-driver-outline': true,
  'wash-hands': true,
  'wash-hands-outline': true,
  'water-sanitation': true,
  'water-sanitation-24px': true,
  'water-sanitation-outline': true,
  'water-sanitation-outline-24px': true,
  woman: true,
  'woman-24px': true,
  'woman-outline': true,
  'woman-outline-24px': true,
  'world-care': true,
  'world-care-outline': true,
  'young-people': true,
  'young-people-outline': true,
  'ambulatory-clinic': true,
  'ambulatory-clinic-24px': true,
  'ambulatory-clinic-outline': true,
  'ambulatory-clinic-outline-24px': true,
  church: true,
  'church-outline': true,
  city: true,
  'city-outline': true,
  'emergency-operations-center': true,
  'emergency-operations-center-outline': true,
  'emergency-post': true,
  'emergency-post-24px': true,
  'emergency-post-outline': true,
  'emergency-post-outline-24px': true,
  forest: true,
  'forest-outline': true,
  'forest-persons': true,
  'forest-persons-outline': true,
  home: true,
  'home-alt': true,
  'home-alt-outline': true,
  'home-outline': true,
  hospital: true,
  'hospital-24px': true,
  'hospital-outline': true,
  'hospital-outline-24px': true,
  letrina: true,
  'letrina-alt': true,
  'letrina-alt-outline': true,
  'letrina-outline': true,
  'market-stall': true,
  'market-stall-outline': true,
  'ministry-of-health': true,
  'ministry-of-health-24px': true,
  'ministry-of-health-outline': true,
  'ministry-of-health-outline-24px': true,
  mosque: true,
  'mosque-outline': true,
  'palm-branches-roof': true,
  'palm-branches-roof-outline': true,
  'proper-roof': true,
  'proper-roof-outline': true,
  'rural-post': true,
  'rural-post-24px': true,
  'rural-post-alt': true,
  'rural-post-alt-24px': true,
  'rural-post-alt-outline': true,
  'rural-post-alt-outline-24px': true,
  'rural-post-outline': true,
  'rural-post-outline-24px': true,
  temple: true,
  'temple-alt': true,
  'temple-alt-outline': true,
  'temple-outline': true,
  village: true,
  'village-24px': true,
  'village-outline': true,
  'village-outline-24px': true,
  'disinfecting-wipes': true,
  'disinfecting-wipes-24px': true,
  'disinfecting-wipes-outline': true,
  'disinfecting-wipes-outline-24px': true,
  'hand-wipe-paper': true,
  'hand-wipe-paper-outline': true,
  'ppe-apron': true,
  'ppe-apron-24px': true,
  'ppe-apron-outline': true,
  'ppe-apron-outline-24px': true,
  'ppe-face-mask': true,
  'ppe-face-mask-24px': true,
  'ppe-face-mask-outline': true,
  'ppe-face-mask-outline-24px': true,
  'ppe-face-shield': true,
  'ppe-face-shield-alt': true,
  'ppe-face-shield-alt-24px': true,
  'ppe-face-shield-alt-outline': true,
  'ppe-face-shield-alt-outline-24px': true,
  'ppe-face-shield-outline': true,
  'ppe-gloves': true,
  'ppe-gloves-24px': true,
  'ppe-gloves-outline': true,
  'ppe-gloves-outline-24px': true,
  'ppe-goggles': true,
  'ppe-goggles-24px': true,
  'ppe-goggles-outline': true,
  'ppe-goggles-outline-24px': true,
  'ppe-gown': true,
  'ppe-gown-outline': true,
  'ppe-mask': true,
  'ppe-mask-24px': true,
  'ppe-mask-n95': true,
  'ppe-mask-n95-24px': true,
  'ppe-mask-n95-outline': true,
  'ppe-mask-n95-outline-24px': true,
  'ppe-mask-outline': true,
  'ppe-mask-outline-24px': true,
  'ppe-sanitizer': true,
  'ppe-sanitizer-24px': true,
  'ppe-sanitizer-outline': true,
  'ppe-sanitizer-outline-24px': true,
  'ppe-suit': true,
  'ppe-suit-24px': true,
  'ppe-suit-outline': true,
  'ppe-suit-outline-24px': true,
  respirator: true,
  'respirator-24px': true,
  'respirator-outline': true,
  'respirator-outline-24px': true,
  'circle-large': true,
  'circle-large-outline': true,
  'circle-medium': true,
  'circle-medium-outline': true,
  'circle-small': true,
  'circle-small-outline': true,
  'information-campaign': true,
  'information-campaign-outline': true,
  'square-large': true,
  'square-large-outline': true,
  'square-medium': true,
  'square-medium-outline': true,
  'square-small': true,
  'square-small-outline': true,
  'star-large': true,
  'star-large-outline': true,
  'star-medium': true,
  'star-medium-outline': true,
  'star-small': true,
  'star-small-outline': true,
  'triangle-inverted-large': true,
  'triangle-inverted-large-outline': true,
  'triangle-inverted-medium': true,
  'triangle-inverted-medium-outline': true,
  'triangle-inverted-small': true,
  'triangle-inverted-small-outline': true,
  'triangle-large': true,
  'triangle-large-outline': true,
  'triangle-medium': true,
  'triangle-medium-outline': true,
  'triangle-small': true,
  'triangle-small-outline': true,
  'accident-and-emergency': true,
  'accident-and-emergency-outline': true,
  admissions: true,
  'admissions-outline': true,
  'biochemistry-laboratory': true,
  'biochemistry-laboratory-outline': true,
  'burn-unit': true,
  'burn-unit-outline': true,
  cardiology: true,
  'cardiology-outline': true,
  chaplaincy: true,
  'chaplaincy-outline': true,
  'coronary-care-unit': true,
  'coronary-care-unit-outline': true,
  'critical-care': true,
  'critical-care-outline': true,
  'discharge-lounge': true,
  'discharge-lounge-outline': true,
  'ears-nose-and-throat': true,
  'ears-nose-and-throat-outline': true,
  endocrinology: true,
  'endocrinology-outline': true,
  'finance-dept': true,
  'finance-dept-outline': true,
  gastroenterology: true,
  'gastroenterology-outline': true,
  'general-surgery': true,
  'general-surgery-outline': true,
  geriatrics: true,
  'geriatrics-outline': true,
  gym: true,
  'gym-outline': true,
  gynecology: true,
  'gynecology-outline': true,
  hematology: true,
  'hematology-laboratory': true,
  'hematology-laboratory-outline': true,
  'hematology-outline': true,
  hepatology: true,
  'hepatology-outline': true,
  'human-resoruces': true,
  'human-resoruces-outline': true,
  'intensive-care-unit': true,
  'intensive-care-unit-outline': true,
  'medical-records': true,
  'medical-records-outline': true,
  nephrology: true,
  'nephrology-outline': true,
  obstetricsmonia: true,
  'obstetricsmonia-outline': true,
  'occupational-therapy': true,
  'occupational-therapy-outline': true,
  oncology: true,
  'oncology-outline': true,
  opthalmology: true,
  'opthalmology-outline': true,
  orthopaedics: true,
  'orthopaedics-outline': true,
  'outpatient-department': true,
  'outpatient-department-outline': true,
  'pain-managment': true,
  'pain-managment-outline': true,
  pediatrics: true,
  'pediatrics-outline': true,
  'physical-therapy': true,
  'physical-therapy-outline': true,
  psychology: true,
  'psychology-outline': true,
  radiology: true,
  'radiology-outline': true,
  respirology: true,
  'respirology-outline': true,
  rheumatology: true,
  'rheumatology-outline': true,
  'social-work': true,
  'social-work-outline': true,
  sonography: true,
  'sonography-outline': true,
  'speech-language-therapy': true,
  'speech-language-therapy-outline': true,
  urology: true,
  'urology-outline': true,
  'vascular-surgery': true,
  'vascular-surgery-outline': true,
  _2g: '2g',
  '_2g-outline': '2g-outline',
  _3g: '3g',
  '_3g-outline': '3g-outline',
  alert: true,
  'alert-circle': true,
  'alert-circle-outline': true,
  'alert-outline': true,
  'alert-triangle': true,
  'alert-triangle-outline': true,
  'american-sign-language': true,
  'american-sign-language-24px': true,
  'american-sign-language-outline': true,
  'american-sign-language-outline-24px': true,
  'arm-circumference': true,
  'arm-circumference-outline': true,
  'artificial-intelligence': true,
  'artificial-intelligence-outline': true,
  'assembly-point': true,
  'assembly-point-outline': true,
  'award-ribbon': true,
  'award-ribbon-outline': true,
  'bio-pharma': true,
  'bio-pharma-outline': true,
  biomarker: true,
  'biomarker-24px': true,
  'biomarker-outline': true,
  'biomarker-outline-24px': true,
  'blood-transfusion': true,
  'blood-transfusion-outline': true,
  'body-mass-index': true,
  'body-mass-index-outline': true,
  'breeding-sites': true,
  'breeding-sites-outline': true,
  'calendar-quarantine': true,
  'calendar-quarantine-outline': true,
  cancel: true,
  'cancel-24px': true,
  'cancel-outline': true,
  'cancel-outline-24px': true,
  cannabis: true,
  'cannabis-outline': true,
  cardiogram: true,
  'cardiogram-24px': true,
  'cardiogram-e': true,
  'cardiogram-e-outline': true,
  'cardiogram-outline': true,
  'cardiogram-outline-24px': true,
  cholera: true,
  'cholera-outline': true,
  'clinical-f': true,
  'clinical-f-24px': true,
  'clinical-f-outline': true,
  'clinical-f-outline-24px': true,
  'clinical-fe': true,
  'clinical-fe-outline': true,
  'close-policy-gaps': true,
  'close-policy-gaps-24px': true,
  'close-policy-gaps-alt': true,
  'close-policy-gaps-alt-24px': true,
  'close-policy-gaps-alt-outline': true,
  'close-policy-gaps-alt-outline-24px': true,
  'close-policy-gaps-outline': true,
  'close-policy-gaps-outline-24px': true,
  communication: true,
  'communication-outline': true,
  'community-meeting': true,
  'community-meeting-24px': true,
  'community-meeting-outline': true,
  'community-meeting-outline-24px': true,
  'contact-support': true,
  'contact-support-outline': true,
  database: true,
  'database-outline': true,
  death: true,
  'death-24px': true,
  'death-alt': true,
  'death-alt-24px': true,
  'death-alt-outline': true,
  'death-alt-outline-24px': true,
  'death-alt2': true,
  'death-alt2-outline': true,
  'death-outline': true,
  'death-outline-24px': true,
  default: true,
  'default-outline': true,
  'dhis2-logo': true,
  'dhis2-logo-outline': true,
  diabetes: true,
  'diabetes-outline': true,
  diagnostics: true,
  'diagnostics-24px': true,
  'diagnostics-outline': true,
  'diagnostics-outline-24px': true,
  discharge: true,
  'discharge-outline': true,
  'ear-nose-throat': true,
  'ear-nose-throat-outline': true,
  'eco-care': true,
  'eco-care-outline': true,
  electricity: true,
  'electricity-outline': true,
  entry: true,
  'entry-outline': true,
  'excel-logo': true,
  'excel-logo-outline': true,
  female: true,
  'female-24px': true,
  'female-outline': true,
  'female-outline-24px': true,
  'fhir-logo': true,
  'fhir-logo-outline': true,
  fingerprint: true,
  'fingerprint-24px': true,
  'fingerprint-outline': true,
  'fingerprint-outline-24px': true,
  forum: true,
  'forum-outline': true,
  'geo-location': true,
  'geo-location-24px': true,
  'geo-location-outline': true,
  'geo-location-outline-24px': true,
  'global-pandemic': true,
  'global-pandemic-outline': true,
  globe: true,
  'globe-24px': true,
  'globe-outline': true,
  'globe-outline-24px': true,
  'guide-dog': true,
  'guide-dog-outline': true,
  hazardous: true,
  'hazardous-24px': true,
  'hazardous-outline': true,
  'hazardous-outline-24px': true,
  'head-circumference': true,
  'head-circumference-outline': true,
  health: true,
  'health-24px': true,
  'health-alt': true,
  'health-alt-24px': true,
  'health-alt-outline': true,
  'health-alt-outline-24px': true,
  'health-data-security': true,
  'health-data-security-outline': true,
  'health-data-sync': true,
  'health-data-sync-outline': true,
  'health-literacy': true,
  'health-literacy-outline': true,
  'health-outline': true,
  'health-outline-24px': true,
  'health-vulnerability-through-social-determinants': true,
  'health-vulnerability-through-social-determinants-24px': true,
  'health-vulnerability-through-social-determinants-outline': true,
  'health-vulnerability-through-social-determinants-outline-24px': true,
  'healthcare-it': true,
  'healthcare-it-outline': true,
  heart: true,
  'heart-24px': true,
  'heart-cardiogram': true,
  'heart-cardiogram-24px': true,
  'heart-cardiogram-outline': true,
  'heart-cardiogram-outline-24px': true,
  'heart-outline': true,
  'heart-outline-24px': true,
  heartbeat: true,
  'heartbeat-24px': true,
  'heartbeat-outline': true,
  'heartbeat-outline-24px': true,
  height: true,
  'height-outline': true,
  'high-bars': true,
  'high-bars-outline': true,
  'high-level': true,
  'high-level-24px': true,
  'high-level-outline': true,
  'high-level-outline-24px': true,
  'hl7v2-logo': true,
  'hl7v2-logo-24px': true,
  'hl7v2-logo-outline': true,
  'hl7v2-logo-outline-24px': true,
  'home-quarantine': true,
  'home-quarantine-24px': true,
  'home-quarantine-outline': true,
  'home-quarantine-outline-24px': true,
  hospice: true,
  'hospice-24px': true,
  'hospice-outline': true,
  'hospice-outline-24px': true,
  'hospital-symbol': true,
  'hospital-symbol-24px': true,
  'hospital-symbol-outline': true,
  'hospital-symbol-outline-24px': true,
  'i-documents-accepted': true,
  'i-documents-accepted-24px': true,
  'i-documents-accepted-outline': true,
  'i-documents-accepted-outline-24px': true,
  'i-documents-denied': true,
  'i-documents-denied-24px': true,
  'i-documents-denied-outline': true,
  'i-documents-denied-outline-24px': true,
  'i-exam-multiple-choice': true,
  'i-exam-multiple-choice-outline': true,
  'i-exam-qualification': true,
  'i-exam-qualification-outline': true,
  'i-note-action': true,
  'i-note-action-outline': true,
  'i-schedule-school-date-time': true,
  'i-schedule-school-date-time-outline': true,
  icd: true,
  'icd-10': true,
  'icd-10-outline': true,
  'icd-11': true,
  'icd-11-outline': true,
  'icd-9': true,
  'icd-9-outline': true,
  'icd-outline': true,
  imm: true,
  'imm-outline': true,
  info: true,
  'info-24px': true,
  'info-outline': true,
  'info-outline-24px': true,
  'insecticide-resistance': true,
  'insecticide-resistance-outline': true,
  'integrated-data-and-research': true,
  'integrated-data-and-research-24px': true,
  'integrated-data-and-research-outline': true,
  'integrated-data-and-research-outline-24px': true,
  interoperability: true,
  'interoperability-outline': true,
  'job-status-level': true,
  'job-status-level-24px': true,
  'job-status-level-outline': true,
  'job-status-level-outline-24px': true,
  'lab-search': true,
  'lab-search-outline': true,
  lactation: true,
  'lactation-24px': true,
  'lactation-outline': true,
  'lactation-outline-24px': true,
  'life-science': true,
  'life-science-24px': true,
  'life-science-outline': true,
  'life-science-outline-24px': true,
  loinc: true,
  'loinc-outline': true,
  'low-bars': true,
  'low-bars-outline': true,
  'low-income-level': true,
  'low-income-level-24px': true,
  'low-income-level-outline': true,
  'low-income-level-outline-24px': true,
  'low-level': true,
  'low-level-24px': true,
  'low-level-outline': true,
  'low-level-outline-24px': true,
  'magic-wand': true,
  'magic-wand-24px': true,
  'magic-wand-outline': true,
  'magic-wand-outline-24px': true,
  'magnifying-glass': true,
  'magnifying-glass-outline': true,
  male: true,
  'male-24px': true,
  'male-outline': true,
  'male-outline-24px': true,
  'medical-advice': true,
  'medical-advice-outline': true,
  'medical-search': true,
  'medical-search-outline': true,
  'medium-bars': true,
  'medium-bars-outline': true,
  'medium-level': true,
  'medium-level-24px': true,
  'medium-level-outline': true,
  'medium-level-outline-24px': true,
  'mental-health': true,
  'mental-health-24px': true,
  'mental-health-outline': true,
  'mental-health-outline-24px': true,
  'nappy-diaper': true,
  'nappy-diaper-24px': true,
  'nappy-diaper-outline': true,
  'nappy-diaper-outline-24px': true,
  negative: true,
  'negative-24px': true,
  'negative-outline': true,
  'negative-outline-24px': true,
  'network-4g': true,
  'network-4g-outline': true,
  'network-5g': true,
  'network-5g-outline': true,
  no: true,
  'no-24px': true,
  'no-outline': true,
  'no-outline-24px': true,
  'openmrs-logo': true,
  'openmrs-logo-outline': true,
  outbreak: true,
  'outbreak-24px': true,
  'outbreak-outline': true,
  'outbreak-outline-24px': true,
  'palliative-care': true,
  'palliative-care-24px': true,
  'palliative-care-outline': true,
  'palliative-care-outline-24px': true,
  'paved-road': true,
  'paved-road-24px': true,
  'paved-road-alt': true,
  'paved-road-alt-24px': true,
  'paved-road-alt-outline': true,
  'paved-road-alt-outline-24px': true,
  'paved-road-outline': true,
  'paved-road-outline-24px': true,
  peace: true,
  'peace-24px': true,
  'peace-outline': true,
  'peace-outline-24px': true,
  pharmacy: true,
  'pharmacy-24px': true,
  'pharmacy-alt': true,
  'pharmacy-alt-outline': true,
  'pharmacy-outline': true,
  'pharmacy-outline-24px': true,
  poison: true,
  'poison-24px': true,
  'poison-outline': true,
  'poison-outline-24px': true,
  polygon: true,
  'polygon-24px': true,
  'polygon-outline': true,
  'polygon-outline-24px': true,
  positive: true,
  'positive-24px': true,
  'positive-outline': true,
  'positive-outline-24px': true,
  'provider-fst': true,
  'provider-fst-24px': true,
  'provider-fst-outline': true,
  'provider-fst-outline-24px': true,
  'qr-code': true,
  'qr-code-outline': true,
  question: true,
  'question-24px': true,
  'question-circle': true,
  'question-circle-24px': true,
  'question-circle-outline': true,
  'question-circle-outline-24px': true,
  'question-outline': true,
  'question-outline-24px': true,
  'question-triangle': true,
  'question-triangle-24px': true,
  'question-triangle-outline': true,
  'question-triangle-outline-24px': true,
  referral: true,
  'referral-outline': true,
  'resilient-and-migration-sensitive-health-system': true,
  'resilient-and-migration-sensitive-health-system-24px': true,
  'resilient-and-migration-sensitive-health-system-outline': true,
  'resilient-and-migration-sensitive-health-system-outline-24px': true,
  'risk-analysis': true,
  'risk-analysis-24px': true,
  'risk-analysis-outline': true,
  'risk-analysis-outline-24px': true,
  'running-water-alt': true,
  'running-water-alt-outline': true,
  rx: true,
  'rx-outline': true,
  'secure-communication': true,
  'secure-communication-outline': true,
  'sexual-reproductive-health': true,
  'sexual-reproductive-health-outline': true,
  'simple-logo': true,
  'simple-logo-outline': true,
  smoking: true,
  'smoking-24px': true,
  'smoking-cessation': true,
  'smoking-cessation-24px': true,
  'smoking-cessation-alt': true,
  'smoking-cessation-alt-outline': true,
  'smoking-cessation-outline': true,
  'smoking-cessation-outline-24px': true,
  'smoking-outline': true,
  'smoking-outline-24px': true,
  'social-distancing': true,
  'social-distancing-alt': true,
  'social-distancing-alt-outline': true,
  'social-distancing-outline': true,
  stop: true,
  'stop-outline': true,
  tally: true,
  'tally-outline': true,
  telemedicine: true,
  'telemedicine-outline': true,
  transgender: true,
  'transgender-outline': true,
  'ui-folder': true,
  'ui-folder-family': true,
  'ui-folder-family-outline': true,
  'ui-folder-outline': true,
  'ui-menu': true,
  'ui-menu-grid': true,
  'ui-menu-grid-outline': true,
  'ui-menu-outline': true,
  'ui-preferences': true,
  'ui-preferences-outline': true,
  'ui-secure': true,
  'ui-secure-outline': true,
  'ui-settings': true,
  'ui-settings-outline': true,
  'ui-user-profile': true,
  'ui-user-profile-outline': true,
  'ui-zoom': true,
  'ui-zoom-in': true,
  'ui-zoom-in-outline': true,
  'ui-zoom-out': true,
  'ui-zoom-out-outline': true,
  'ui-zoom-outline': true,
  'un-paved-road': true,
  'un-paved-road-outline': true,
  video: true,
  'video-24px': true,
  'video-outline': true,
  'video-outline-24px': true,
  virus: true,
  'virus-24px': true,
  'virus-alt': true,
  'virus-alt-24px': true,
  'virus-alt-outline': true,
  'virus-alt-outline-24px': true,
  'virus-mutation': true,
  'virus-mutation-outline': true,
  'virus-outline': true,
  'virus-outline-24px': true,
  'virus-patient': true,
  'virus-patient-outline': true,
  'virus-research': true,
  'virus-research-alt': true,
  'virus-research-alt-outline': true,
  'virus-research-outline': true,
  'virus-shield': true,
  'virus-shield-outline': true,
  'waist-circumference': true,
  'waist-circumference-outline': true,
  'water-treatment': true,
  'water-treatment-outline': true,
  yes: true,
  'yes-outline': true,
  _0: '0',
  '_0-outline': '0-outline',
  _1: '1',
  '_1-outline': '1-outline',
  _2: '2',
  '_2-outline': '2-outline',
  _3: '3',
  '_3-outline': '3-outline',
  _4: '4',
  '_4-outline': '4-outline',
  _5: '5',
  '_5-outline': '5-outline',
  _6: '6',
  '_6-outline': '6-outline',
  _7: '7',
  '_7-outline': '7-outline',
  _8: '8',
  '_8-outline': '8-outline',
  _9: '9',
  '_9-outline': '9-outline',
  a: true,
  'a-outline': true,
  b: true,
  'b-outline': true,
  c: true,
  'c-outline': true,
  d: true,
  'd-outline': true,
  dollar: true,
  'dollar-outline': true,
  e: true,
  'e-outline': true,
  euro: true,
  'euro-outline': true,
  f: true,
  'f-outline': true,
  g: true,
  'g-outline': true,
  ghana: true,
  'ghana-outline': true,
  h: true,
  'h-outline': true,
  i: true,
  'i-outline': true,
  j: true,
  'j-outline': true,
  k: true,
  'k-outline': true,
  l: true,
  'l-outline': true,
  m: true,
  'm-outline': true,
  n: true,
  'n-outline': true,
  naira: true,
  'naira-outline': true,
  o: true,
  'o-outline': true,
  p: true,
  'p-outline': true,
  peso: true,
  'peso-outline': true,
  pound: true,
  'pound-outline': true,
  q: true,
  'q-outline': true,
  'question-mark': true,
  'question-mark-outline': true,
  r: true,
  'r-outline': true,
  ruble: true,
  'ruble-outline': true,
  rupee: true,
  'rupee-outline': true,
  s: true,
  's-outline': true,
  t: true,
  't-outline': true,
  u: true,
  'u-outline': true,
  v: true,
  'v-outline': true,
  w: true,
  'w-outline': true,
  warning: true,
  'warning-outline': true,
  won: true,
  'won-outline': true,
  x: true,
  'x-outline': true,
  y: true,
  'y-outline': true,
  yen: true,
  'yen-outline': true,
  z: true,
  'z-outline': true,
  _4x4: '4x4',
  '_4x4-outline': '4x4-outline',
  ambulance: true,
  'ambulance-24px': true,
  'ambulance-outline': true,
  'ambulance-outline-24px': true,
  'basic-motorcycle': true,
  'basic-motorcycle-outline': true,
  bike: true,
  'bike-outline': true,
  'cross-country-motorcycle': true,
  'cross-country-motorcycle-outline': true,
  drone: true,
  'drone-24px': true,
  'drone-outline': true,
  'drone-outline-24px': true,
  helicopter: true,
  'helicopter-24px': true,
  'helicopter-outline': true,
  'helicopter-outline-24px': true,
  machinery: true,
  'machinery-outline': true,
  'mobile-clinic': true,
  'mobile-clinic-24px': true,
  'mobile-clinic-outline': true,
  'mobile-clinic-outline-24px': true,
  'small-plane': true,
  'small-plane-outline': true,
  'vespa-motorcycle': true,
  'vespa-motorcycle-outline': true,
  war: true,
  'war-outline': true,
  'animal-bat': true,
  'animal-bat-outline': true,
  'animal-chicken': true,
  'animal-chicken-outline': true,
  'animal-cow': true,
  'animal-cow-outline': true,
  'animal-donkey': true,
  'animal-donkey-outline': true,
  'animal-mosquitos': true,
  'animal-mosquitos-outline': true,
  'animal-pig': true,
  'animal-pig-outline': true,
  'animal-rat': true,
  'animal-rat-outline': true,
  'animal-snake': true,
  'animal-snake-outline': true,
  'animal-spider': true,
  'animal-spider-outline': true,
  'animal-tick': true,
  'animal-tick-outline': true,
  mosquito: true,
  'mosquito-24px': true,
  'mosquito-outline': true,
  'mosquito-outline-24px': true,
} as const;

/**
 * Names upstream has renamed or hidden. Still served, still typed, and
 * deliberately not in the object above: a union compiles to nothing, while
 * every entry in that object ships to every application.
 */
type HealthiconsIconAlias =
  | '0-negative'
  | '02x-outline'
  | '1-negative'
  | '12x-outline'
  | '2-negative'
  | '22x-outline'
  | '2g-negative'
  | '2g2x-outline'
  | '2x-outline'
  | '3-negative'
  | '32x-outline'
  | '3g-negative'
  | '3g2x-outline'
  | '4-negative'
  | '42x-outline'
  | '4x4-negative'
  | '4x42x-outline'
  | '5-negative'
  | '52x-outline'
  | '6-negative'
  | '62x-outline'
  | '7-negative'
  | '72x-outline'
  | '8-negative'
  | '82x-outline'
  | '9-negative'
  | '92x-outline'
  | 'a-negative'
  | 'a2x-outline'
  | 'accident-and-emergency-negative'
  | 'accident-and-emergency2x-outline'
  | 'admissions-negative'
  | 'admissions2x-outline'
  | 'agriculture-negative'
  | 'agriculture-worker-alt-negative'
  | 'agriculture-worker-alt2x-outline'
  | 'agriculture-worker-negative'
  | 'agriculture-worker2x-outline'
  | 'agriculture2x-outline'
  | 'alcohol-cessation-negative'
  | 'alcohol-cessation2x-outline'
  | 'alcohol-negative'
  | 'alcohol2x-outline'
  | 'alert-circle-negative'
  | 'alert-circle2x-outline'
  | 'alert-negative'
  | 'alert-triangle-negative'
  | 'alert-triangle2x-outline'
  | 'alert2x-outline'
  | 'allergies-negative'
  | 'ambulance-negative'
  | 'ambulance2x-outline'
  | 'ambulatory-clinic-negative'
  | 'ambulatory-clinic2x-outline'
  | 'ancv-negative'
  | 'ancv2x-outline'
  | 'angry-negative'
  | 'angry2x-outline'
  | 'animal-bat-negative'
  | 'animal-bat2x-outline'
  | 'animal-chicken-negative'
  | 'animal-chicken2x-outline'
  | 'animal-cow-negative'
  | 'animal-cow2x-outline'
  | 'animal-donkey-negative'
  | 'animal-donkey2x-outline'
  | 'animal-mosquitos-negative'
  | 'animal-mosquitos2x-outline'
  | 'animal-pig-negative'
  | 'animal-pig2x-outline'
  | 'animal-rat-negative'
  | 'animal-rat2x-outline'
  | 'animal-snake2x-outline'
  | 'animal-spider-negative'
  | 'animal-spider2x-outline'
  | 'animal-tick-negative'
  | 'animal-tick2x-outline'
  | 'anus-negative'
  | 'arm-circumference2x-outline'
  | 'arm-negative'
  | 'artificial-intelligence2x-outline'
  | 'assembly-point-negative'
  | 'assembly-point2x-outline'
  | 'asthma-inhaler-negative'
  | 'asthma-inhaler2x-outline'
  | 'asthma-negative'
  | 'asthma2x-outline'
  | 'award-ribbon-negative'
  | 'award-ribbon2x-outline'
  | 'award-trophy-negative'
  | 'award-trophy2x-outline'
  | 'b-negative'
  | 'b2x-outline'
  | 'baby-0203-alt-negative'
  | 'baby-0203-alt2x-outline'
  | 'baby-0203m-negative'
  | 'baby-0203m2x-outline'
  | 'baby-0306m-negative'
  | 'baby-0306m2x-outline'
  | 'baby-female-0203m'
  | 'baby-female-0203m-alt-negative'
  | 'baby-female-0203m-alt2x-outline'
  | 'baby-female-0203m-negative'
  | 'baby-female-0203m-outline'
  | 'baby-female-0306m-negative'
  | 'baby-female-0306m2x-outline'
  | 'baby-female-0609m-negative'
  | 'baby-female-0609m2x-outline'
  | 'baby-formula-negative'
  | 'baby-formula2x-outline'
  | 'baby-male-0203m'
  | 'baby-male-0203m-alt-negative'
  | 'baby-male-0203m-alt2x-outline'
  | 'baby-male-0203m-negative'
  | 'baby-male-0203m-outline'
  | 'baby-male-0306m-negative'
  | 'baby-male-0306m2x-outline'
  | 'baby-male-0609m-negative'
  | 'baby-male-0609m2x-outline'
  | 'back-pain-negative'
  | 'bacteria-negative'
  | 'bandage-adhesive-negative'
  | 'bandage-adhesive2x-outline'
  | 'bandaged-negative'
  | 'bandaged2x-outline'
  | 'basic-motorcycle-negative'
  | 'basic-motorcycle2x-outline'
  | 'bike-negative'
  | 'bike2x-outline'
  | 'bills-negative'
  | 'bills2x-outline'
  | 'bio-pharma2x-outline'
  | 'biochemistry-laboratory-negative'
  | 'biochemistry-laboratory2x-outline'
  | 'biomarker2x-outline'
  | 'biopsy2x-outline'
  | 'bladder-negative'
  | 'blister-pills-oval-x1-negative'
  | 'blister-pills-oval-x12x-outline'
  | 'blister-pills-oval-x14-negative'
  | 'blister-pills-oval-x142x-outline'
  | 'blister-pills-oval-x16-negative'
  | 'blister-pills-oval-x162x-outline'
  | 'blister-pills-oval-x4-negative'
  | 'blister-pills-oval-x42x-outline'
  | 'blister-pills-round-x1-negative'
  | 'blister-pills-round-x12x-outline'
  | 'blister-pills-round-x14-negative'
  | 'blister-pills-round-x142x-outline'
  | 'blister-pills-round-x16-negative'
  | 'blister-pills-round-x162x-outline'
  | 'blister-pills-round-x4-negative'
  | 'blister-pills-round-x42x-outline'
  | 'blood-a-n-negative'
  | 'blood-a-p-negative'
  | 'blood-ab-n-negative'
  | 'blood-ab-p-negative'
  | 'blood-b-n-negative'
  | 'blood-b-p-negative'
  | 'blood-bag-negative'
  | 'blood-cells-negative'
  | 'blood-drop-negative'
  | 'blood-o-n-negative'
  | 'blood-o-p-negative'
  | 'blood-pressure-2-negative'
  | 'blood-pressure-22x-outline'
  | 'blood-pressure-monitor-negative'
  | 'blood-pressure-monitor2x-outline'
  | 'blood-pressure-negative'
  | 'blood-pressure2x-outline'
  | 'blood-rh-n-negative'
  | 'blood-rh-p-negative'
  | 'blood-transfusion2x-outline'
  | 'blood-vessel-negative'
  | 'body-mass-index2x-outline'
  | 'body-negative'
  | 'book-negative'
  | 'book2x-outline'
  | 'boy-0105y-negative'
  | 'boy-0105y2x-outline'
  | 'boy-1015y-negative'
  | 'boy-1015y2x-outline'
  | 'breast-pump-negative'
  | 'breast-pump2x-outline'
  | 'breeding-sites-negative'
  | 'breeding-sites2x-outline'
  | 'burn-negative'
  | 'burn-unit-negative'
  | 'burn-unit2x-outline'
  | 'c-negative'
  | 'c2x-outline'
  | 'calendar-negative'
  | 'calendar-quarantine-negative'
  | 'calendar-quarantine2x-outline'
  | 'calendar2x-outline'
  | 'call-centre-negative'
  | 'call-centre2x-outline'
  | 'calm-negative'
  | 'calm2x-outline'
  | 'cancel-negative'
  | 'cancel2x-outline'
  | 'cane-negative'
  | 'cane2x-outline'
  | 'cannabis-negative'
  | 'cannabis2x-outline'
  | 'carbohydrates-negative'
  | 'carbohydrates2x-outline'
  | 'cardiogram-e-negative'
  | 'cardiogram-e2x-outline'
  | 'cardiogram-negative'
  | 'cardiogram2x-outline'
  | 'cardiology-negative'
  | 'cardiology2x-outline'
  | 'cast-negative'
  | 'cast2x-outline'
  | 'cervical-cancer-negative'
  | 'chaplaincy-negative'
  | 'chaplaincy2x-outline'
  | 'chart-bar-negative'
  | 'chart-bar-stacked-negative'
  | 'chart-bar-stacked2x-outline'
  | 'chart-bar2x-outline'
  | 'chart-cured-decreasing-negative'
  | 'chart-cured-decreasing2x-outline'
  | 'chart-cured-increasing-negative'
  | 'chart-cured-increasing2x-outline'
  | 'chart-death-rate-decreasing-negative'
  | 'chart-death-rate-decreasing2x-outline'
  | 'chart-death-rate-increasing-negative'
  | 'chart-death-rate-increasing2x-outline'
  | 'chart-death-rate-stable-negative'
  | 'chart-death-rate-stable2x-outline'
  | 'chart-infected-decreasing-negative'
  | 'chart-infected-decreasing2x-outline'
  | 'chart-infected-increasing-negative'
  | 'chart-infected-increasing2x-outline'
  | 'chart-infected-stable-negative'
  | 'chart-infected-stable2x-outline'
  | 'chart-line-negative'
  | 'chart-line-stacked-negative'
  | 'chart-line-stacked2x-outline'
  | 'chart-line2x-outline'
  | 'chart-pie-negative'
  | 'chart-pie2x-outline'
  | 'chemical-burn-negative'
  | 'child-care-negative'
  | 'child-care2x-outline'
  | 'child-cognition-negative'
  | 'child-cognition2x-outline'
  | 'child-program-negative'
  | 'child-program2x-outline'
  | 'chills-fever-negative'
  | 'chills-negative'
  | 'cholera-negative'
  | 'cholera2x-outline'
  | 'church-negative'
  | 'church2x-outline'
  | 'circle-large-negative'
  | 'circle-large2x-outline'
  | 'circle-medium-negative'
  | 'circle-medium2x-outline'
  | 'circle-small-negative'
  | 'circle-small2x-outline'
  | 'city-negative'
  | 'city-worker-negative'
  | 'city-worker2x-outline'
  | 'city2x-outline'
  | 'clean-hands-negative'
  | 'clean-hands2x-outline'
  | 'cleaning-negative'
  | 'cleaning2x-outline'
  | 'clinical-a-negative'
  | 'clinical-a2x-outline'
  | 'clinical-f-negative'
  | 'clinical-f2x-outline'
  | 'clinical-fe-negative'
  | 'clinical-fe2x-outline'
  | 'close-policy-gaps-alt2x-outline'
  | 'close-policy-gaps2x-outline'
  | 'cochlear-implant2x-outline'
  | 'coins-negative'
  | 'coins2x-outline'
  | 'cold-chain-negative'
  | 'cold-chain2x-outline'
  | 'communication-negative'
  | 'communication2x-outline'
  | 'community-healthworker-negative'
  | 'community-healthworker2x-outline'
  | 'community-meeting-negative'
  | 'community-meeting2x-outline'
  | 'cone-test-on-nets-negative'
  | 'cone-test-on-nets2x-outline'
  | 'cone-test-on-walls-negative'
  | 'cone-test-on-walls2x-outline'
  | 'confused-negative'
  | 'confused2x-outline'
  | 'construction-negative'
  | 'construction-worker-negative'
  | 'construction-worker2x-outline'
  | 'construction2x-outline'
  | 'contact-lenses-negative'
  | 'contact-lenses2x-outline'
  | 'contact-support-negative'
  | 'contact-support2x-outline'
  | 'contraceptive-diaphragm-negative'
  | 'contraceptive-diaphragm2x-outline'
  | 'contraceptive-injection-negative'
  | 'contraceptive-injection2x-outline'
  | 'contraceptive-patch-negative'
  | 'contraceptive-patch2x-outline'
  | 'contraceptive-voucher-negative'
  | 'contraceptive-voucher2x-outline'
  | 'copper-iud-negative'
  | 'copper-iud2x-outline'
  | 'coronary-care-unit-negative'
  | 'coronary-care-unit2x-outline'
  | 'coughing-alt-negative'
  | 'coughing-negative'
  | 'coughing2x-outline'
  | 'cpap-machine2x-outline'
  | 'cpap-tubes2x-outline'
  | 'cpr-negative'
  | 'cpr2x-outline'
  | 'credit-card-negative'
  | 'credit-card2x-outline'
  | 'crisis-response-center-person-negative'
  | 'crisis-response-center-person2x-outline'
  | 'critical-care-negative'
  | 'critical-care2x-outline'
  | 'cross-country-motorcycle-negative'
  | 'cross-country-motorcycle2x-outline'
  | 'crutches-negative'
  | 'crutches2x-outline'
  | 'crying-negative'
  | 'crying2x-outline'
  | 'd-negative'
  | 'd2x-outline'
  | 'dairy-negative'
  | 'dairy2x-outline'
  | 'database-negative'
  | 'database2x-outline'
  | 'deaf-negative'
  | 'death-alt-negative'
  | 'death-alt2-negative'
  | 'death-alt22x-outline'
  | 'death-alt2x-outline'
  | 'death-negative'
  | 'death2x-outline'
  | 'default-negative'
  | 'default2x-outline'
  | 'defibrilator'
  | 'defibrilator-negative'
  | 'defibrilator-outline'
  | 'defibrillator-negative'
  | 'defibrillator2x-outline'
  | 'dental-hygiene-negative'
  | 'dental-hygiene2x-outline'
  | 'desktop-app-negative'
  | 'desktop-app2x-outline'
  | 'dhis2-logo-negative'
  | 'dhis2-logo2x-outline'
  | 'diabetes-measure-negative'
  | 'diabetes-measure2x-outline'
  | 'diabetes-negative'
  | 'diabetes2x-outline'
  | 'diagnostics2x-outline'
  | 'diarrhea-negative'
  | 'discharge-lounge-negative'
  | 'discharge-lounge2x-outline'
  | 'discharge-negative'
  | 'discharge2x-outline'
  | 'discriminating-concentration-bioassays-negative'
  | 'discriminating-concentration-bioassays2x-outline'
  | 'disinfecting-wipes-negative'
  | 'disinfecting-wipes2x-outline'
  | 'dizzy-negative'
  | 'dizzy2x-outline'
  | 'dna-negative'
  | 'doctor-female-negative'
  | 'doctor-female2x-outline'
  | 'doctor-male-negative'
  | 'doctor-male2x-outline'
  | 'doctor-negative'
  | 'doctor2x-outline'
  | 'dollar-negative'
  | 'dollar2x-outline'
  | 'domestic-worker-alt-negative'
  | 'domestic-worker-alt2x-outline'
  | 'domestic-worker-negative'
  | 'domestic-worker2x-outline'
  | 'donkey'
  | 'donkey-negative'
  | 'donkey-outline'
  | 'drone-negative'
  | 'drone2x-outline'
  | 'e-1-negative'
  | 'e-1-outline'
  | 'e-2-negative'
  | 'e-negative'
  | 'e2x-outline'
  | 'ear-negative'
  | 'ears-nose-and-throat-negative'
  | 'ears-nose-and-throat2x-outline'
  | 'ecmo2x-outline'
  | 'eco-care-negative'
  | 'eco-care2x-outline'
  | 'elderly-negative'
  | 'elderly2x-outline'
  | 'electricity-negative'
  | 'electricity2x-outline'
  | 'emergency-operations-center-negative'
  | 'emergency-operations-center2x-outline'
  | 'emergency-post-negative'
  | 'emergency-post2x-outline'
  | 'endocrinology-negative'
  | 'endocrinology2x-outline'
  | 'endotracheal-tube2x-outline'
  | 'entry-negative'
  | 'entry-negative-negative'
  | 'entry-outline-outline'
  | 'entry-positive'
  | 'entry2x-outline'
  | 'enzyme-negative'
  | 'excel-logo-negative'
  | 'excel-logo2x-outline'
  | 'exercise-bicycle-negative'
  | 'exercise-bicycle2x-outline'
  | 'exercise-negative'
  | 'exercise-running'
  | 'exercise-running-negative'
  | 'exercise-running-outline'
  | 'exercise-walk-supported'
  | 'exercise-walk-supported-negative'
  | 'exercise-walk-supported-outline'
  | 'exercise-walking'
  | 'exercise-walking-negative'
  | 'exercise-walking-outline'
  | 'exercise-weights'
  | 'exercise-weights-negative'
  | 'exercise-weights-outline'
  | 'exercise-yoga-negative'
  | 'exercise-yoga2x-outline'
  | 'exercise2x-outline'
  | 'expectorate-negative'
  | 'expectorate2x-outline'
  | 'eye-negative'
  | 'eyeglasses-negative'
  | 'eyeglasses2x-outline'
  | 'eyes'
  | 'eyes-negative'
  | 'eyes-outline'
  | 'f-negative'
  | 'f2x-outline'
  | 'factory-worker-negative'
  | 'factory-worker2x-outline'
  | 'family-planning-negative'
  | 'family-planning2x-outline'
  | 'female-and-male-negative'
  | 'female-and-male2x-outline'
  | 'female-condom-negative'
  | 'female-condom2x-outline'
  | 'female-reproductive-system-negative'
  | 'female-sex-worker-negative'
  | 'female-sex-worker2x-outline'
  | 'female2x-outline'
  | 'fetus-negative'
  | 'fetus2x-outline'
  | 'fever-negative'
  | 'fever2x-outline'
  | 'fhir-logo-negative'
  | 'fhir-logo2x-outline'
  | 'finance-dept-negative'
  | 'finance-dept2x-outline'
  | 'fingerprint-negative'
  | 'fingerprint2x-outline'
  | 'foot-negative'
  | 'forest-negative'
  | 'forest-persons-negative'
  | 'forest-persons2x-outline'
  | 'forest2x-outline'
  | 'forum-negative'
  | 'forum2x-outline'
  | 'fruits-negative'
  | 'fruits2x-outline'
  | 'g-negative'
  | 'g2x-outline'
  | 'gallbladder-negative'
  | 'gastroenterology-negative'
  | 'gastroenterology2x-outline'
  | 'general-surgery-negative'
  | 'general-surgery2x-outline'
  | 'geo-location-negative'
  | 'geo-location2x-outline'
  | 'geriatrics-negative'
  | 'geriatrics2x-outline'
  | 'ghana-negative'
  | 'ghana2x-outline'
  | 'girl-0105y-negative'
  | 'girl-0105y2x-outline'
  | 'girl-1015y-negative'
  | 'girl-1015y2x-outline'
  | 'global-pandemic-negative'
  | 'global-pandemic2x-outline'
  | 'globe-negative'
  | 'globe2x-outline'
  | 'gluten-free-negative'
  | 'gluten-free2x-outline'
  | 'gluten-negative'
  | 'gluten2x-outline'
  | 'group-discussion-meeting-negative'
  | 'group-discussion-meeting2x-outline'
  | 'group-discussion-meetingx3-negative'
  | 'group-discussion-meetingx32x-outline'
  | 'guide-dog-negative'
  | 'guide-dog2x-outline'
  | 'gym-negative'
  | 'gym2x-outline'
  | 'gynecology-negative'
  | 'gynecology2x-outline'
  | 'h-negative'
  | 'h2x-outline'
  | 'hand-wipe-paper-negative'
  | 'hand-wipe-paper2x-outline'
  | 'happy-negative'
  | 'happy2x-outline'
  | 'hazardous-negative'
  | 'hazardous2x-outline'
  | 'head-circumference2x-outline'
  | 'headache-negative'
  | 'headache2x-outline'
  | 'health-1'
  | 'health-1-negative'
  | 'health-1-outline'
  | 'health-alt-negative'
  | 'health-alt2x-outline'
  | 'health-data-security-negative'
  | 'health-data-security2x-outline'
  | 'health-data-sync-negative'
  | 'health-data-sync2x-outline'
  | 'health-literacy-negative'
  | 'health-literacy2x-outline'
  | 'health-negative'
  | 'health-vulnerability-through-social-determinants2x-outline'
  | 'health-worker-form-negative'
  | 'health-worker-form2x-outline'
  | 'health-worker-negative'
  | 'health-worker2x-outline'
  | 'health2x-outline'
  | 'healthcare-it2x-outline'
  | 'hearing-aid-negative'
  | 'hearing-aid2x-outline'
  | 'heart-cardiogram-negative'
  | 'heart-cardiogram2x-outline'
  | 'heart-negative'
  | 'heart-organ-negative'
  | 'heart2x-outline'
  | 'heartbeat-negative'
  | 'heartbeat2x-outline'
  | 'height2x-outline'
  | 'helicopter-negative'
  | 'helicopter2x-outline'
  | 'hematology-laboratory-negative'
  | 'hematology-laboratory2x-outline'
  | 'hematology-negative'
  | 'hematology2x-outline'
  | 'hepatology-negative'
  | 'hepatology2x-outline'
  | 'high-bars-negative'
  | 'high-bars2x-outline'
  | 'high-level-negative'
  | 'high-level2x-outline'
  | 'hiv-ind-negative'
  | 'hiv-ind2x-outline'
  | 'hiv-neg-negative'
  | 'hiv-neg2x-outline'
  | 'hiv-pos-negative'
  | 'hiv-pos2x-outline'
  | 'hiv-self-test-negative'
  | 'hiv-self-test2x-outline'
  | 'hl7v2-logo2x-outline'
  | 'home-alt-negative'
  | 'home-alt2x-outline'
  | 'home-negative'
  | 'home-quarantine-negative'
  | 'home-quarantine2x-outline'
  | 'home2x-outline'
  | 'hormonal-ring-negative'
  | 'hormonal-ring2x-outline'
  | 'hospice-negative'
  | 'hospice2x-outline'
  | 'hospital-negative'
  | 'hospital-symbol-negative'
  | 'hospital-symbol2x-outline'
  | 'hospital2x-outline'
  | 'hospitalized-negative'
  | 'hospitalized2x-outline'
  | 'hot-meal-negative'
  | 'hot-meal2x-outline'
  | 'hpv-negative'
  | 'hpv2x-outline'
  | 'human-resoruces-negative'
  | 'human-resoruces2x-outline'
  | 'i-certificate-paper-negative'
  | 'i-certificate-paper2x-outline'
  | 'i-documents-accepted-negative'
  | 'i-documents-accepted2x-outline'
  | 'i-documents-denied-negative'
  | 'i-documents-denied2x-outline'
  | 'i-exam-multiple-choice-negative'
  | 'i-exam-multiple-choice2x-outline'
  | 'i-exam-qualification-negative'
  | 'i-exam-qualification2x-outline'
  | 'i-groups-perspective-crowd-negative'
  | 'i-groups-perspective-crowd2x-outline'
  | 'i-negative'
  | 'i-note-action-negative'
  | 'i-note-action2x-outline'
  | 'i-schedule-school-date-time-negative'
  | 'i-schedule-school-date-time2x-outline'
  | 'i-training-class-negative'
  | 'i-training-class2x-outline'
  | 'i-utensils-negative'
  | 'i-utensils2x-outline'
  | 'i2x-outline'
  | 'icd-102x-outline'
  | 'icd-112x-outline'
  | 'icd-92x-outline'
  | 'icd2x-outline'
  | 'imm-negative'
  | 'imm2x-outline'
  | 'implant-negative'
  | 'implant2x-outline'
  | 'info-negative'
  | 'info2x-outline'
  | 'information-campaign-negative'
  | 'information-campaign2x-outline'
  | 'infusion-pump2x-outline'
  | 'inpatient-negative'
  | 'inpatient2x-outline'
  | 'insecticide-resistance-negative'
  | 'insecticide-resistance2x-outline'
  | 'insurance-card2x-outline'
  | 'integrated-data-and-research2x-outline'
  | 'intensity-concentration-bioassays-negative'
  | 'intensity-concentration-bioassays2x-outline'
  | 'intensive-care-unit-negative'
  | 'intensive-care-unit2x-outline'
  | 'interoperability-negative'
  | 'interoperability2x-outline'
  | 'intestinal-pain-negative'
  | 'intestinal-pain2x-outline'
  | 'intestine-negative'
  | 'intravenous-bag-negative'
  | 'intravenous-bag2x-outline'
  | 'intravenous-drip2x-outline'
  | 'iud-negative'
  | 'iud2x-outline'
  | 'j-negative'
  | 'j2x-outline'
  | 'job-status-level2x-outline'
  | 'joints-negative'
  | 'justice-negative'
  | 'justice2x-outline'
  | 'k-negative'
  | 'k2x-outline'
  | 'kidneys-negative'
  | 'l-negative'
  | 'l2x-outline'
  | 'lab-search2x-outline'
  | 'lactation-negative'
  | 'lactation2x-outline'
  | 'lactose-free-negative'
  | 'lactose-free2x-outline'
  | 'lactose-negative'
  | 'lactose2x-outline'
  | 'laptop2x-outline'
  | 'laryngoscope2x-outline'
  | 'leg-negative'
  | 'letrina-alt-negative'
  | 'letrina-alt2x-outline'
  | 'letrina-negative'
  | 'letrina2x-outline'
  | 'life-science2x-outline'
  | 'liver-1-24px'
  | 'liver-1-outline-24px'
  | 'liver-alt-negative'
  | 'liver-negative'
  | 'llin-negative'
  | 'llin2x-outline'
  | 'loinc2x-outline'
  | 'loss-smell-negative'
  | 'loss-smell2x-outline'
  | 'loudly-crying-negative'
  | 'loudly-crying2x-outline'
  | 'low-bars-negative'
  | 'low-bars2x-outline'
  | 'low-income-level2x-outline'
  | 'low-level-negative'
  | 'low-level2x-outline'
  | 'low-vision-negative'
  | 'low-vision2x-outline'
  | 'lungs-negative'
  | 'lymph-nodes-negative'
  | 'lymphoma2x-outline'
  | 'm-negative'
  | 'm2x-outline'
  | 'machinery-negative'
  | 'machinery2x-outline'
  | 'magic-wand2x-outline'
  | 'magnifying-glass-negative'
  | 'magnifying-glass2x-outline'
  | 'malaria-microscope-negative'
  | 'malaria-microscope2x-outline'
  | 'malaria-mixed-microscope-negative'
  | 'malaria-mixed-microscope2x-outline'
  | 'malaria-outbreak'
  | 'malaria-outbreak-negative'
  | 'malaria-outbreak-outline'
  | 'malaria-pf-microscope-negative'
  | 'malaria-pf-microscope2x-outline'
  | 'malaria-pv-microscope-negative'
  | 'malaria-pv-microscope2x-outline'
  | 'malaria-testing-negative'
  | 'malaria-testing2x-outline'
  | 'male-and-female-negative'
  | 'male-and-female2x-outline'
  | 'male-condom-negative'
  | 'male-condom2x-outline'
  | 'male-sex-worker-negative'
  | 'male-sex-worker2x-outline'
  | 'male2x-outline'
  | 'malnutrition2x-outline'
  | 'man-negative'
  | 'man2x-outline'
  | 'market-stall-negative'
  | 'market-stall2x-outline'
  | 'mask'
  | 'mask-negative'
  | 'mask-outline'
  | 'masked-negative'
  | 'masked2x-outline'
  | 'measles-negative'
  | 'measles2x-outline'
  | 'medical-advice-negative'
  | 'medical-advice2x-outline'
  | 'medical-records-negative'
  | 'medical-records2x-outline'
  | 'medical-sample-negative'
  | 'medical-sample2x-outline'
  | 'medical-search-1'
  | 'medical-search-1-negative'
  | 'medical-search-1-outline'
  | 'medical-search-negative'
  | 'medical-search2x-outline'
  | 'medicine-bottle-negative'
  | 'medicine-bottle2x-outline'
  | 'medicine-mortar-negative'
  | 'medicine-mortar2x-outline'
  | 'medicines-negative'
  | 'medicines2x-outline'
  | 'medium-bars-negative'
  | 'medium-bars2x-outline'
  | 'medium-level-negative'
  | 'medium-level2x-outline'
  | 'megaphone-negative'
  | 'megaphone2x-outline'
  | 'mental-disorders-negative'
  | 'mental-disorders2x-outline'
  | 'mental-health2x-outline'
  | 'microscope-negative'
  | 'microscope-with-specimen2x-outline'
  | 'microscope2x-outline'
  | 'military-worker-negative'
  | 'military-worker2x-outline'
  | 'miner-worker-alt-negative'
  | 'miner-worker-alt2x-outline'
  | 'miner-worker-negative'
  | 'miner-worker2x-outline'
  | 'ministry-of-health-negative'
  | 'ministry-of-health2x-outline'
  | 'mobile-clinic-negative'
  | 'mobile-clinic2x-outline'
  | 'mobile-negative'
  | 'mobile2x-outline'
  | 'money-bag-negative'
  | 'money-bag2x-outline'
  | 'mosque-negative'
  | 'mosque2x-outline'
  | 'mosquito-collection-negative'
  | 'mosquito-collection2x-outline'
  | 'mosquito-negative'
  | 'mosquito2x-outline'
  | 'mouth-negative'
  | 'msm-negative'
  | 'msm2x-outline'
  | 'n-negative'
  | 'n2x-outline'
  | 'nausea-negative'
  | 'nausea2x-outline'
  | 'nauseous-negative'
  | 'nauseous2x-outline'
  | 'negative-negative'
  | 'negative2x-outline'
  | 'nephrology-negative'
  | 'nephrology2x-outline'
  | 'nerve-negative'
  | 'nervous-negative'
  | 'nervous2x-outline'
  | 'network-4g-negative'
  | 'network-4g2x-outline'
  | 'network-5g-negative'
  | 'network-5g2x-outline'
  | 'neuro-surgery-negative'
  | 'neuro-surgery2x-outline'
  | 'neurology-negative'
  | 'neutral-negative'
  | 'neutral2x-outline'
  | 'no-negative'
  | 'no2x-outline'
  | 'nose-negative'
  | 'not-ok-negative'
  | 'not-ok2x-outline'
  | 'nurse-negative'
  | 'nurse2x-outline'
  | 'nutrition-negative'
  | 'nutrition2x-outline'
  | 'o-negative'
  | 'o2x-outline'
  | 'observation-negative'
  | 'observation2x-outline'
  | 'obstetricsmonia-negative'
  | 'obstetricsmonia2x-outline'
  | 'occupational-therapy2x-outline'
  | 'odontology-implant-negative'
  | 'odontology-implant2x-outline'
  | 'odontology-negative'
  | 'odontology2x-outline'
  | 'oesophagus-cancer2x-outline'
  | 'officer-negative'
  | 'officer2x-outline'
  | 'ok-negative'
  | 'ok2x-outline'
  | 'old-man-negative'
  | 'old-man2x-outline'
  | 'old-woman-negative'
  | 'old-woman2x-outline'
  | 'oncology-negative'
  | 'oncology2x-outline'
  | 'openmrs-logo-negative'
  | 'openmrs-logo2x-outline'
  | 'opthalmology-negative'
  | 'opthalmology2x-outline'
  | 'oral-contraception-pillsx21-negative'
  | 'oral-contraception-pillsx212x-outline'
  | 'oral-contraception-pillsx28-negative'
  | 'oral-contraception-pillsx282x-outline'
  | 'orthopaedics-negative'
  | 'orthopaedics2x-outline'
  | 'orthotics2x-outline'
  | 'outbreak-negative'
  | 'outbreak2x-outline'
  | 'outpatient-department-negative'
  | 'outpatient-department2x-outline'
  | 'outpatient-negative'
  | 'outpatient2x-outline'
  | 'overweight-negative'
  | 'overweight2x-outline'
  | 'oxygen-tank-negative'
  | 'oxygen-tank2x-outline'
  | 'p-negative'
  | 'p2x-outline'
  | 'pain-managment-negative'
  | 'pain-managment2x-outline'
  | 'pain-negative'
  | 'pain2x-outline'
  | 'palliative-care-negative'
  | 'palliative-care2x-outline'
  | 'palm-branches-roof-negative'
  | 'palm-branches-roof2x-outline'
  | 'pancreas-negative'
  | 'pancreatic-cancer2x-outline'
  | 'patient-band-alt-negative'
  | 'patient-band-alt2x-outline'
  | 'patient-band-negative'
  | 'patient-band2x-outline'
  | 'paved-road-1-negative'
  | 'paved-road-alt-negative'
  | 'paved-road-alt2x-outline'
  | 'paved-road-negative'
  | 'paved-road2x-outline'
  | 'peace-negative'
  | 'peace2x-outline'
  | 'pediatric-surgery-negative'
  | 'pediatric-surgery2x-outline'
  | 'pediatrics-negative'
  | 'pediatrics2x-outline'
  | 'penis-alt-negative'
  | 'penis-negative'
  | 'people-negative'
  | 'people2x-outline'
  | 'person-negative'
  | 'person2x-outline'
  | 'pharmacy-alt-negative'
  | 'pharmacy-alt2x-outline'
  | 'pharmacy-negative'
  | 'pharmacy2x-outline'
  | 'phone-negative'
  | 'phone2x-outline'
  | 'physical-therapy-negative'
  | 'physical-therapy2x-outline'
  | 'pill-1-negative'
  | 'pill-12x-outline'
  | 'pills-2-negative'
  | 'pills-22x-outline'
  | 'pills-3-negative'
  | 'pills-32x-outline'
  | 'pills-4-negative'
  | 'pills-42x-outline'
  | 'plantation-worker-alt-negative'
  | 'plantation-worker-alt2x-outline'
  | 'plantation-worker-negative'
  | 'plantation-worker2x-outline'
  | 'pneumonia-negative'
  | 'pneumonia2x-outline'
  | 'poison-negative'
  | 'poison2x-outline'
  | 'polygon-negative'
  | 'polygon2x-outline'
  | 'positive-negative'
  | 'positive2x-outline'
  | 'ppe-apron-negative'
  | 'ppe-apron2x-outline'
  | 'ppe-face-mask-negative'
  | 'ppe-face-mask2x-outline'
  | 'ppe-face-shield-alt-negative'
  | 'ppe-face-shield-alt2x-outline'
  | 'ppe-face-shield-negative'
  | 'ppe-face-shield2x-outline'
  | 'ppe-gloves-negative'
  | 'ppe-gloves2x-outline'
  | 'ppe-goggles-negative'
  | 'ppe-goggles2x-outline'
  | 'ppe-gown-negative'
  | 'ppe-gown2x-outline'
  | 'ppe-mask-n95-negative'
  | 'ppe-mask-n952x-outline'
  | 'ppe-mask-negative'
  | 'ppe-mask2x-outline'
  | 'ppe-sanitizer-negative'
  | 'ppe-sanitizer2x-outline'
  | 'ppe-santizer-alt-negative'
  | 'ppe-santizer-alt2x-outline'
  | 'ppe-suit-negative'
  | 'ppe-suit2x-outline'
  | 'pregnant-0812w-negative'
  | 'pregnant-0812w2x-outline'
  | 'pregnant-2426w-negative'
  | 'pregnant-2426w2x-outline'
  | 'pregnant-32w-negative'
  | 'pregnant-32w2x-outline'
  | 'pregnant-3638w-negative'
  | 'pregnant-3638w2x-outline'
  | 'pregnant-negative'
  | 'pregnant2x-outline'
  | 'prescription-document-negative'
  | 'prescription-document2x-outline'
  | 'prisoner-negative'
  | 'prisoner2x-outline'
  | 'proper-roof-negative'
  | 'proper-roof2x-outline'
  | 'prostate-cancer2x-outline'
  | 'provider-fst-negative'
  | 'provider-fst2x-outline'
  | 'psychology-negative'
  | 'psychology2x-outline'
  | 'pulse-oximeter-alt-negative'
  | 'pulse-oximeter-alt2x-outline'
  | 'pulse-oximeter-negative'
  | 'pulse-oximeter2x-outline'
  | 'pwid-negative'
  | 'pwid2x-outline'
  | 'q-negative'
  | 'q2x-outline'
  | 'qr-code2x-outline'
  | 'question-circle-negative'
  | 'question-circle2x-outline'
  | 'question-mark-negative'
  | 'question-mark2x-outline'
  | 'question-negative'
  | 'question-triangle-negative'
  | 'question-triangle2x-outline'
  | 'question2x-outline'
  | 'r-negative'
  | 'r2x-outline'
  | 'radiology-negative'
  | 'radiology2x-outline'
  | 'rdt-result-invalid-negative'
  | 'rdt-result-invalid2x-outline'
  | 'rdt-result-mixed-invalid-negative'
  | 'rdt-result-mixed-invalid-rectangular-negative'
  | 'rdt-result-mixed-invalid-rectangular2x-outline'
  | 'rdt-result-mixed-invalid2x-outline'
  | 'rdt-result-mixed-negative'
  | 'rdt-result-mixed-rectangular-negative'
  | 'rdt-result-mixed-rectangular2x-outline'
  | 'rdt-result-mixed2x-outline'
  | 'rdt-result-neg-invalid-negative'
  | 'rdt-result-neg-invalid-rectangular-negative'
  | 'rdt-result-neg-invalid-rectangular2x-outline'
  | 'rdt-result-neg-invalid2x-outline'
  | 'rdt-result-neg-negative'
  | 'rdt-result-neg-rectangular-negative'
  | 'rdt-result-neg-rectangular2x-outline'
  | 'rdt-result-neg2x-outline'
  | 'rdt-result-negative'
  | 'rdt-result-negative-negative'
  | 'rdt-result-no-test-negative'
  | 'rdt-result-no-test2x-outline'
  | 'rdt-result-out-stock-negative'
  | 'rdt-result-out-stock2x-outline'
  | 'rdt-result-pf-invalid-negative'
  | 'rdt-result-pf-invalid-rectangular-negative'
  | 'rdt-result-pf-invalid-rectangular2x-outline'
  | 'rdt-result-pf-invalid2x-outline'
  | 'rdt-result-pf-negative'
  | 'rdt-result-pf-rectangular-negative'
  | 'rdt-result-pf-rectangular2x-outline'
  | 'rdt-result-pf2x-outline'
  | 'rdt-result-positive-negative'
  | 'rdt-result-positive2x-outline'
  | 'rdt-result-pv-invalid-negative'
  | 'rdt-result-pv-invalid-rectangular-negative'
  | 'rdt-result-pv-invalid-rectangular2x-outline'
  | 'rdt-result-pv-invalid2x-outline'
  | 'rdt-result-pv-negative'
  | 'rdt-result-pv-rectangular-negative'
  | 'rdt-result-pv-rectangular2x-outline'
  | 'rdt-result-pv2x-outline'
  | 'rdt-result2x-outline'
  | 'referral-negative'
  | 'referral2x-outline'
  | 'refused-negative'
  | 'refused2x-outline'
  | 'register-book-negative'
  | 'register-book2x-outline'
  | 'regular-patient2x-outline'
  | 'resilient-and-migration-sensitive-health-system2x-outline'
  | 'respirator-negative'
  | 'respirator2x-outline'
  | 'respirology-negative'
  | 'respirology2x-outline'
  | 'rheumatology-negative'
  | 'rheumatology2x-outline'
  | 'ribbon-negative'
  | 'ribbon2x-outline'
  | 'risk-analysis2x-outline'
  | 'rmnh-negative'
  | 'rmnh2x-outline'
  | 'running-negative'
  | 'running-water-alt-negative'
  | 'running-water-alt2x-outline'
  | 'running-water-negative'
  | 'running-water2x-outline'
  | 'running2x-outline'
  | 'rupee-negative'
  | 'rupee2x-outline'
  | 'rural-post-alt-negative'
  | 'rural-post-alt2x-outline'
  | 'rural-post-negative'
  | 'rural-post2x-outline'
  | 'rx-negative'
  | 'rx2x-outline'
  | 's-negative'
  | 's2x-outline'
  | 'sad-negative'
  | 'sad2x-outline'
  | 'sanitizer'
  | 'sanitizer-negative'
  | 'sanitizer-outline'
  | 'sayana-press-negative'
  | 'sayana-press2x-outline'
  | 'secure-communication-negative'
  | 'secure-communication2x-outline'
  | 'security-worker-negative'
  | 'security-worker2x-outline'
  | 'sexual-reproductive-health-negative'
  | 'sexual-reproductive-health2x-outline'
  | 'simple-logo-negative'
  | 'simple-logo2x-outline'
  | 'skeleton-negative'
  | 'skin-cancer2x-outline'
  | 'skull-negative'
  | 'sleepy-negative'
  | 'sleepy2x-outline'
  | 'sling-negative'
  | 'sling2x-outline'
  | 'small-plane-negative'
  | 'small-plane2x-outline'
  | 'smoking-cessation-alt-negative'
  | 'smoking-cessation-alt2x-outline'
  | 'smoking-cessation-negative'
  | 'smoking-cessation2x-outline'
  | 'smoking-negative'
  | 'smoking2x-outline'
  | 'social-distancing-alt-negative'
  | 'social-distancing-alt2x-outline'
  | 'social-distancing-negative'
  | 'social-distancing2x-outline'
  | 'social-work-negative'
  | 'social-work2x-outline'
  | 'sodium-free-negative'
  | 'sodium-free2x-outline'
  | 'sonogram-negative'
  | 'sonogram2x-outline'
  | 'sonography-negative'
  | 'sonography2x-outline'
  | 'speech-language-therapy-negative'
  | 'speech-language-therapy2x-outline'
  | 'sperm-negative'
  | 'sperm2x-outline'
  | 'spine-negative'
  | 'spleen-negative'
  | 'spraying-negative'
  | 'spraying2x-outline'
  | 'spreadsheets-negative'
  | 'spreadsheets2x-outline'
  | 'square-large-negative'
  | 'square-large2x-outline'
  | 'square-medium-negative'
  | 'square-medium2x-outline'
  | 'square-small-negative'
  | 'square-small2x-outline'
  | 'staples2x-outline'
  | 'star-large-negative'
  | 'star-large2x-outline'
  | 'star-medium-negative'
  | 'star-medium2x-outline'
  | 'star-small-negative'
  | 'star-small2x-outline'
  | 'stent-negative'
  | 'stent2x-outline'
  | 'stethoscope-negative'
  | 'stethoscope2x-outline'
  | 'sti-negative'
  | 'sti2x-outline'
  | 'stitches2x-outline'
  | 'stock-out-negative'
  | 'stock-out2x-outline'
  | 'stomach-cancer2x-outline'
  | 'stomach-negative'
  | 'stop-negative'
  | 'stop2x-outline'
  | 'sugar-alt-negative'
  | 'sugar-alt2x-outline'
  | 'sugar-free2x-outline'
  | 'sugar-negative'
  | 'sugar2x-outline'
  | 'surgical-sterilization-negative'
  | 'surgical-sterilization2x-outline'
  | 'surveilance-officer2x-outline'
  | 'sweating-negative'
  | 'sweating2x-outline'
  | 'swim-negative'
  | 'swim2x-outline'
  | 'symptom-negative'
  | 'symptom2x-outline'
  | 'synergist-insecticide-bioassays-negative'
  | 'synergist-insecticide-bioassays2x-outline'
  | 'syphilis-alt2x-outline'
  | 'syringe-negative'
  | 'syringe-vaccine-negative'
  | 'syringe-vaccine2x-outline'
  | 'syringe2x-outline'
  | 't-negative'
  | 't2x-outline'
  | 'tac-negative'
  | 'tac2x-outline'
  | 'tally-negative'
  | 'tally2x-outline'
  | 'tb-negative'
  | 'tb2x-outline'
  | 'telemedicine-negative'
  | 'telemedicine2x-outline'
  | 'temple-alt-negative'
  | 'temple-alt2x-outline'
  | 'temple-negative'
  | 'temple2x-outline'
  | 'test-tubes-negative'
  | 'test-tubes2x-outline'
  | 'testicles-negative'
  | 'thermometer-digital-negative'
  | 'thermometer-digital2x-outline'
  | 'thermometer-negative'
  | 'thermometer2x-outline'
  | 'thyroid-cancer2x-outline'
  | 'toilet-paper-negative'
  | 'toilet-paper2x-outline'
  | 'tongue-negative'
  | 'tongue2x-outline'
  | 'tooth-negative'
  | 'transgender-negative'
  | 'transgender2x-outline'
  | 'traumatism-negative'
  | 'traumatism2x-outline'
  | 'travel-alt-negative'
  | 'travel-alt2x-outline'
  | 'travel-negative'
  | 'travel2x-outline'
  | 'treated-water-negative'
  | 'treated-water2x-outline'
  | 'triangle-inverted-large2x-outline'
  | 'triangle-inverted-medium2x-outline'
  | 'triangle-inverted-small2x-outline'
  | 'triangle-large-negative'
  | 'triangle-large2x-outline'
  | 'triangle-medium-negative'
  | 'triangle-medium2x-outline'
  | 'triangle-small-negative'
  | 'triangle-small2x-outline'
  | 'truck-driver-negative'
  | 'truck-driver2x-outline'
  | 'u-negative'
  | 'u2x-outline'
  | 'ui-folder-family-negative'
  | 'ui-folder-family2x-outline'
  | 'ui-folder-negative'
  | 'ui-folder2x-outline'
  | 'ui-menu-grid-negative'
  | 'ui-menu-grid2x-outline'
  | 'ui-menu-negative'
  | 'ui-menu2x-outline'
  | 'ui-preferences-negative'
  | 'ui-preferences2x-outline'
  | 'ui-secure-negative'
  | 'ui-secure2x-outline'
  | 'ui-settings-negative'
  | 'ui-settings2x-outline'
  | 'ui-user-profile-negative'
  | 'ui-user-profile2x-outline'
  | 'ui-zoom-in-negative'
  | 'ui-zoom-in2x-outline'
  | 'ui-zoom-negative'
  | 'ui-zoom-out-negative'
  | 'ui-zoom-out2x-outline'
  | 'ui-zoom2x-outline'
  | 'ultrasound-scanner-negative'
  | 'ultrasound-scanner2x-outline'
  | 'umbrella-negative'
  | 'umbrella2x-outline'
  | 'un-paved-road-negative'
  | 'un-paved-road2x-outline'
  | 'underweight-negative'
  | 'underweight2x-outline'
  | 'unhealthy-food-negative'
  | 'unhealthy-food2x-outline'
  | 'urine-sample2x-outline'
  | 'urology-negative'
  | 'urology2x-outline'
  | 'v-negative'
  | 'v2x-outline'
  | 'vagina-alt-negative'
  | 'varicose-vein-negative'
  | 'varicose-vein2x-outline'
  | 'vascular-surgery-negative'
  | 'vascular-surgery2x-outline'
  | 'vegetables2x-outline'
  | 'ventilator-alt-negative'
  | 'ventilator-alt2x-outline'
  | 'ventilator-negative'
  | 'ventilator2x-outline'
  | 'vespa-motorcycle-negative'
  | 'vespa-motorcycle2x-outline'
  | 'vih-negative'
  | 'vih2x-outline'
  | 'village-negative'
  | 'village2x-outline'
  | 'viral-lung-infection-negative'
  | 'viral-lung-infection2x-outline'
  | 'virus-alt-negative'
  | 'virus-alt2x-outline'
  | 'virus-lab-research-syringe-negative'
  | 'virus-lab-research-syringe2x-outline'
  | 'virus-lab-research-test-tube-negative'
  | 'virus-lab-research-test-tube2x-outline'
  | 'virus-mutation-negative'
  | 'virus-mutation2x-outline'
  | 'virus-negative'
  | 'virus-patient-negative'
  | 'virus-patient2x-outline'
  | 'virus-research-alt-negative'
  | 'virus-research-alt2x-outline'
  | 'virus-research-negative'
  | 'virus-research2x-outline'
  | 'virus-sanitizer-spray-negative'
  | 'virus-sanitizer-spray2x-outline'
  | 'virus-shield-negative'
  | 'virus-shield2x-outline'
  | 'virus2x-outline'
  | 'vomiting-negative'
  | 'vomiting2x-outline'
  | 'vomitting-negative'
  | 'vomitting2x-outline'
  | 'w-negative'
  | 'w2x-outline'
  | 'waist-circumference2x-outline'
  | 'walk-supported-negative'
  | 'walk-supported2x-outline'
  | 'walking-negative'
  | 'walking2x-outline'
  | 'war-negative'
  | 'war2x-outline'
  | 'warning-negative'
  | 'wash-hands-negative'
  | 'wash-hands2x-outline'
  | 'water-sanitation-negative'
  | 'water-sanitation2x-outline'
  | 'water-treatment-negative'
  | 'water-treatment2x-outline'
  | 'weight-negative'
  | 'weight2x-outline'
  | 'weights-negative'
  | 'weights2x-outline'
  | 'wheelchair-alt-negative'
  | 'wheelchair-alt2x-outline'
  | 'wheelchair-negative'
  | 'wheelchair2x-outline'
  | 'wold-care'
  | 'wold-care-negative'
  | 'wold-care-outline'
  | 'woman-negative'
  | 'woman2x-outline'
  | 'woozy-negative'
  | 'woozy2x-outline'
  | 'world-care-negative'
  | 'world-care2x-outline'
  | 'x-negative'
  | 'x2x-outline'
  | 'xray-negative'
  | 'xray2x-outline'
  | 'y-negative'
  | 'y2x-outline'
  | 'yen-negative'
  | 'yen2x-outline'
  | 'yes-negative'
  | 'yes2x-outline'
  | 'young-people-negative'
  | 'young-people2x-outline'
  | 'z-negative'
  | 'z2x-outline';

export type HealthiconsIconName = keyof typeof healthiconsIconNames | HealthiconsIconAlias;
export const Healthicons = createIconSet<HealthiconsIconName>('healthicons', healthiconsIconNames);
