/**
 * HeroiconsOutline Icon Set
 * @see https://icon-sets.iconify.design/heroicons-outline/
 *
 * Auto-generated - do not edit manually
 */

import { createIconSet } from '../createIconSet';

const heroicons_outlineIconNames = {
  'academic-cap': true,
  adjustments: true,
  annotation: true,
  archive: true,
  'arrow-circle-down': true,
  'arrow-circle-left': true,
  'arrow-circle-right': true,
  'arrow-circle-up': true,
  'arrow-down': true,
  'arrow-left': true,
  'arrow-narrow-down': true,
  'arrow-narrow-left': true,
  'arrow-narrow-right': true,
  'arrow-narrow-up': true,
  'arrow-right': true,
  'arrow-sm-down': true,
  'arrow-sm-left': true,
  'arrow-sm-right': true,
  'arrow-sm-up': true,
  'arrow-up': true,
  'arrows-expand': true,
  'at-symbol': true,
  backspace: true,
  'badge-check': true,
  ban: true,
  beaker: true,
  bell: true,
  'book-open': true,
  bookmark: true,
  'bookmark-alt': true,
  briefcase: true,
  cake: true,
  calculator: true,
  calendar: true,
  camera: true,
  cash: true,
  'chart-bar': true,
  'chart-pie': true,
  'chart-square-bar': true,
  chat: true,
  'chat-alt': true,
  'chat-alt-2': true,
  check: true,
  'check-circle': true,
  'chevron-double-down': true,
  'chevron-double-left': true,
  'chevron-double-right': true,
  'chevron-double-up': true,
  'chevron-down': true,
  'chevron-left': true,
  'chevron-right': true,
  'chevron-up': true,
  chip: true,
  clipboard: true,
  'clipboard-check': true,
  'clipboard-copy': true,
  'clipboard-list': true,
  clock: true,
  cloud: true,
  'cloud-download': true,
  'cloud-upload': true,
  code: true,
  cog: true,
  collection: true,
  'color-swatch': true,
  'credit-card': true,
  cube: true,
  'cube-transparent': true,
  'currency-bangladeshi': true,
  'currency-dollar': true,
  'currency-euro': true,
  'currency-pound': true,
  'currency-rupee': true,
  'currency-yen': true,
  'cursor-click': true,
  database: true,
  'desktop-computer': true,
  'device-mobile': true,
  'device-tablet': true,
  document: true,
  'document-add': true,
  'document-download': true,
  'document-duplicate': true,
  'document-remove': true,
  'document-report': true,
  'document-search': true,
  'document-text': true,
  'dots-circle-horizontal': true,
  'dots-horizontal': true,
  'dots-vertical': true,
  download: true,
  duplicate: true,
  'emoji-happy': true,
  'emoji-sad': true,
  exclamation: true,
  'exclamation-circle': true,
  'external-link': true,
  eye: true,
  'eye-off': true,
  'fast-forward': true,
  film: true,
  filter: true,
  'finger-print': true,
  fire: true,
  flag: true,
  folder: true,
  'folder-add': true,
  'folder-download': true,
  'folder-open': true,
  'folder-remove': true,
  gift: true,
  globe: true,
  'globe-alt': true,
  hand: true,
  hashtag: true,
  heart: true,
  home: true,
  identification: true,
  inbox: true,
  'inbox-in': true,
  'information-circle': true,
  key: true,
  library: true,
  'light-bulb': true,
  'lightning-bolt': true,
  link: true,
  'location-marker': true,
  'lock-closed': true,
  'lock-open': true,
  login: true,
  logout: true,
  mail: true,
  'mail-open': true,
  map: true,
  menu: true,
  'menu-alt-1': true,
  'menu-alt-2': true,
  'menu-alt-3': true,
  'menu-alt-4': true,
  microphone: true,
  minus: true,
  'minus-circle': true,
  'minus-sm': true,
  moon: true,
  'music-note': true,
  newspaper: true,
  'office-building': true,
  'paper-airplane': true,
  'paper-clip': true,
  pause: true,
  pencil: true,
  'pencil-alt': true,
  phone: true,
  'phone-incoming': true,
  'phone-missed-call': true,
  'phone-outgoing': true,
  photograph: true,
  play: true,
  plus: true,
  'plus-circle': true,
  'plus-sm': true,
  'presentation-chart-bar': true,
  'presentation-chart-line': true,
  printer: true,
  puzzle: true,
  qrcode: true,
  'question-mark-circle': true,
  'receipt-refund': true,
  'receipt-tax': true,
  refresh: true,
  reply: true,
  rewind: true,
  rss: true,
  save: true,
  'save-as': true,
  scale: true,
  scissors: true,
  search: true,
  'search-circle': true,
  selector: true,
  server: true,
  share: true,
  'shield-check': true,
  'shield-exclamation': true,
  'shopping-bag': true,
  'shopping-cart': true,
  'sort-ascending': true,
  'sort-descending': true,
  sparkles: true,
  speakerphone: true,
  star: true,
  'status-offline': true,
  'status-online': true,
  stop: true,
  sun: true,
  support: true,
  'switch-horizontal': true,
  'switch-vertical': true,
  table: true,
  tag: true,
  template: true,
  terminal: true,
  'thumb-down': true,
  'thumb-up': true,
  ticket: true,
  translate: true,
  trash: true,
  'trending-down': true,
  'trending-up': true,
  truck: true,
  upload: true,
  user: true,
  'user-add': true,
  'user-circle': true,
  'user-group': true,
  'user-remove': true,
  users: true,
  variable: true,
  'video-camera': true,
  'view-boards': true,
  'view-grid': true,
  'view-grid-add': true,
  'view-list': true,
  'volume-off': true,
  'volume-up': true,
  wifi: true,
  x: true,
  'x-circle': true,
  'zoom-in': true,
  'zoom-out': true,
} as const;

/**
 * Names upstream has renamed or hidden. Still served, still typed, and
 * deliberately not in the object above: a union compiles to nothing, while
 * every entry in that object ships to every application.
 */
type HeroiconsOutlineIconAlias =
  | 'adjustments-horizontal'
  | 'adjustments-vertical'
  | 'archive-box'
  | 'archive-box-arrow-down'
  | 'archive-box-x-mark'
  | 'arrow-down-circle'
  | 'arrow-down-left'
  | 'arrow-down-on-square'
  | 'arrow-down-on-square-stack'
  | 'arrow-down-right'
  | 'arrow-down-tray'
  | 'arrow-left-circle'
  | 'arrow-left-on-rectangle'
  | 'arrow-long-down'
  | 'arrow-long-left'
  | 'arrow-long-right'
  | 'arrow-long-up'
  | 'arrow-path'
  | 'arrow-right-circle'
  | 'arrow-right-on-rectangle'
  | 'arrow-top-right-on-square'
  | 'arrow-trending-down'
  | 'arrow-trending-up'
  | 'arrow-up-circle'
  | 'arrow-up-left'
  | 'arrow-up-on-square'
  | 'arrow-up-on-square-stack'
  | 'arrow-up-right'
  | 'arrow-up-tray'
  | 'arrow-uturn-down'
  | 'arrow-uturn-left'
  | 'arrow-uturn-right'
  | 'arrow-uturn-up'
  | 'arrows-pointing-in'
  | 'arrows-pointing-out'
  | 'arrows-right-left'
  | 'arrows-up-down'
  | 'backward'
  | 'banknotes'
  | 'bars-2'
  | 'bars-3'
  | 'bars-3-bottom-left'
  | 'bars-3-bottom-right'
  | 'bars-3-center-left'
  | 'bars-4'
  | 'bell-alert'
  | 'bell-slash'
  | 'bell-snooze'
  | 'bolt'
  | 'bolt-slash'
  | 'bookmark-slash'
  | 'bookmark-square'
  | 'building-library'
  | 'building-office'
  | 'building-office-2'
  | 'building-storefront'
  | 'calendar-days'
  | 'chart-bar-square'
  | 'chat-bubble-bottom-center'
  | 'chat-bubble-bottom-center-text'
  | 'chat-bubble-left'
  | 'chat-bubble-left-ellipsis'
  | 'chat-bubble-left-right'
  | 'chat-bubble-oval-left'
  | 'chat-bubble-oval-left-ellipsis'
  | 'check-badge'
  | 'circle-stack'
  | 'clipboard-document'
  | 'clipboard-document-check'
  | 'clipboard-document-list'
  | 'cloud-arrow-down'
  | 'cloud-arrow-up'
  | 'code-bracket'
  | 'code-bracket-square'
  | 'cog-6-tooth'
  | 'cog-8-tooth'
  | 'command-line'
  | 'computer-desktop'
  | 'cpu-chip'
  | 'cursor-arrow-rays'
  | 'cursor-arrow-ripple'
  | 'device-phone-mobile'
  | 'document-arrow-down'
  | 'document-arrow-up'
  | 'document-chart-bar'
  | 'document-check'
  | 'document-magnifying-glass'
  | 'document-minus'
  | 'document-plus'
  | 'ellipsis-horizontal'
  | 'ellipsis-horizontal-circle'
  | 'ellipsis-vertical'
  | 'envelope'
  | 'envelope-open'
  | 'exclaimation-circle'
  | 'exclaimation-triangle'
  | 'eye-slash'
  | 'face-frown'
  | 'face-smile'
  | 'folder-arrow-down'
  | 'folder-minus'
  | 'folder-plus'
  | 'forward'
  | 'funnel'
  | 'gif'
  | 'gift-top'
  | 'globe-americas'
  | 'globe-asia-australia'
  | 'globe-europe-africa'
  | 'hand-raised'
  | 'hand-thumb-down'
  | 'hand-thumb-up'
  | 'home-modern'
  | 'inbox-arrow-down'
  | 'inbox-stack'
  | 'language'
  | 'lifebuoy'
  | 'list-bullet'
  | 'magnifying-glass'
  | 'magnifying-glass-circle'
  | 'magnifying-glass-minus'
  | 'magnifying-glass-plus'
  | 'map-pin'
  | 'megaphone'
  | 'musical-note'
  | 'no-symbol'
  | 'pencil-square'
  | 'phone-arrow-down-left'
  | 'phone-arrow-up-right'
  | 'phone-x-mark'
  | 'photo'
  | 'play-pause'
  | 'puzzle-piece'
  | 'qr-code'
  | 'queue-list'
  | 'radio'
  | 'receipt-percent'
  | 'rectangle-group'
  | 'rectangle-stack'
  | 'server-stack'
  | 'signal'
  | 'signal-slash'
  | 'speaker-wave'
  | 'speaker-x-mark'
  | 'square-2-stack'
  | 'squares-2x2'
  | 'squares-plus'
  | 'swatch'
  | 'table-cells'
  | 'user-plus'
  | 'video-camera-slash'
  | 'view-columns'
  | 'wrench'
  | 'wrench-screwdriver'
  | 'x-mark';

export type HeroiconsOutlineIconName =
  | keyof typeof heroicons_outlineIconNames
  | HeroiconsOutlineIconAlias;
export const HeroiconsOutline = createIconSet<HeroiconsOutlineIconName>(
  'heroicons-outline',
  heroicons_outlineIconNames
);
