/**
 * Il Icon Set
 * @see https://icon-sets.iconify.design/il/
 *
 * Auto-generated - do not edit manually
 */

import { createIconSet } from '../createIconSet';

const ilIconNames = {
  'add-user': true,
  'arrow-down': true,
  'arrow-left': true,
  'arrow-right': true,
  'arrow-up': true,
  attachment: true,
  basket: true,
  behance: true,
  bell: true,
  book: true,
  box: true,
  brightness: true,
  bucket: true,
  calendar: true,
  camera: true,
  card: true,
  cart: true,
  clock: true,
  cloud: true,
  cog: true,
  comment: true,
  compass: true,
  contrast: true,
  controls: true,
  conversation: true,
  cup: true,
  dashboard: true,
  dialog: true,
  dribbble: true,
  drop: true,
  dropbox: true,
  ellipsis: true,
  email: true,
  envelope: true,
  eye: true,
  facebook: true,
  file: true,
  flag: true,
  folder: true,
  github: true,
  'google-plus': true,
  grid: true,
  heart: true,
  house: true,
  image: true,
  inbox: true,
  instagram: true,
  layers: true,
  linkedin: true,
  location: true,
  lock: true,
  market: true,
  menu: true,
  mic: true,
  mobile: true,
  money: true,
  moon: true,
  music: true,
  notification: true,
  paypal: true,
  pencil: true,
  pie: true,
  pin: true,
  refresh: true,
  ribbon: true,
  search: true,
  select: true,
  'small-arrow-down': true,
  'small-arrow-left': true,
  'small-arrow-right': true,
  'small-arrow-up': true,
  tablet: true,
  tag: true,
  thumbs: true,
  'triangle-down': true,
  'triangle-up': true,
  twitter: true,
  unlock: true,
  url: true,
  user: true,
  users: true,
  videocamera: true,
  world: true,
  youtube: true,
} as const;

export type IlIconName = keyof typeof ilIconNames;
export const Il = createIconSet<IlIconName>('il', ilIconNames);
