/**
 * Ion Icon Set
 * @see https://icon-sets.iconify.design/ion/
 *
 * Auto-generated - do not edit manually
 */

import { createIconSet } from '../createIconSet';

const ionIconNames = {
  accessibility: true,
  'accessibility-outline': true,
  'accessibility-sharp': true,
  add: true,
  'add-circle': true,
  'add-circle-outline': true,
  'add-circle-sharp': true,
  'add-outline': true,
  'add-sharp': true,
  airplane: true,
  'airplane-outline': true,
  'airplane-sharp': true,
  alarm: true,
  'alarm-outline': true,
  'alarm-sharp': true,
  albums: true,
  'albums-outline': true,
  'albums-sharp': true,
  alert: true,
  'alert-circle': true,
  'alert-circle-outline': true,
  'alert-circle-sharp': true,
  'alert-outline': true,
  'alert-sharp': true,
  'american-football': true,
  'american-football-outline': true,
  'american-football-sharp': true,
  analytics: true,
  'analytics-outline': true,
  'analytics-sharp': true,
  aperture: true,
  'aperture-outline': true,
  'aperture-sharp': true,
  apps: true,
  'apps-outline': true,
  'apps-sharp': true,
  archive: true,
  'archive-outline': true,
  'archive-sharp': true,
  'arrow-back': true,
  'arrow-back-circle': true,
  'arrow-back-circle-outline': true,
  'arrow-back-circle-sharp': true,
  'arrow-back-outline': true,
  'arrow-back-sharp': true,
  'arrow-down': true,
  'arrow-down-circle': true,
  'arrow-down-circle-outline': true,
  'arrow-down-circle-sharp': true,
  'arrow-down-left-box': true,
  'arrow-down-left-box-outline': true,
  'arrow-down-left-box-sharp': true,
  'arrow-down-outline': true,
  'arrow-down-right-box': true,
  'arrow-down-right-box-outline': true,
  'arrow-down-right-box-sharp': true,
  'arrow-down-sharp': true,
  'arrow-forward': true,
  'arrow-forward-circle': true,
  'arrow-forward-circle-outline': true,
  'arrow-forward-circle-sharp': true,
  'arrow-forward-outline': true,
  'arrow-forward-sharp': true,
  'arrow-redo': true,
  'arrow-redo-circle': true,
  'arrow-redo-circle-outline': true,
  'arrow-redo-circle-sharp': true,
  'arrow-redo-outline': true,
  'arrow-redo-sharp': true,
  'arrow-undo': true,
  'arrow-undo-circle': true,
  'arrow-undo-circle-outline': true,
  'arrow-undo-circle-sharp': true,
  'arrow-undo-outline': true,
  'arrow-undo-sharp': true,
  'arrow-up': true,
  'arrow-up-circle': true,
  'arrow-up-circle-outline': true,
  'arrow-up-circle-sharp': true,
  'arrow-up-left-box': true,
  'arrow-up-left-box-outline': true,
  'arrow-up-left-box-sharp': true,
  'arrow-up-outline': true,
  'arrow-up-right-box': true,
  'arrow-up-right-box-outline': true,
  'arrow-up-right-box-sharp': true,
  'arrow-up-sharp': true,
  at: true,
  'at-circle': true,
  'at-circle-outline': true,
  'at-circle-sharp': true,
  'at-outline': true,
  'at-sharp': true,
  attach: true,
  'attach-outline': true,
  'attach-sharp': true,
  backspace: true,
  'backspace-outline': true,
  'backspace-sharp': true,
  bag: true,
  'bag-add': true,
  'bag-add-outline': true,
  'bag-add-sharp': true,
  'bag-check': true,
  'bag-check-outline': true,
  'bag-check-sharp': true,
  'bag-handle': true,
  'bag-handle-outline': true,
  'bag-handle-sharp': true,
  'bag-outline': true,
  'bag-remove': true,
  'bag-remove-outline': true,
  'bag-remove-sharp': true,
  'bag-sharp': true,
  balloon: true,
  'balloon-outline': true,
  'balloon-sharp': true,
  ban: true,
  'ban-outline': true,
  'ban-sharp': true,
  bandage: true,
  'bandage-outline': true,
  'bandage-sharp': true,
  'bar-chart': true,
  'bar-chart-outline': true,
  'bar-chart-sharp': true,
  barbell: true,
  'barbell-outline': true,
  'barbell-sharp': true,
  barcode: true,
  'barcode-outline': true,
  'barcode-sharp': true,
  baseball: true,
  'baseball-outline': true,
  'baseball-sharp': true,
  basket: true,
  'basket-outline': true,
  'basket-sharp': true,
  basketball: true,
  'basketball-outline': true,
  'basketball-sharp': true,
  'battery-charging': true,
  'battery-charging-outline': true,
  'battery-charging-sharp': true,
  'battery-dead': true,
  'battery-dead-outline': true,
  'battery-dead-sharp': true,
  'battery-full': true,
  'battery-full-outline': true,
  'battery-full-sharp': true,
  'battery-half': true,
  'battery-half-outline': true,
  'battery-half-sharp': true,
  beaker: true,
  'beaker-outline': true,
  'beaker-sharp': true,
  bed: true,
  'bed-outline': true,
  'bed-sharp': true,
  beer: true,
  'beer-outline': true,
  'beer-sharp': true,
  bicycle: true,
  'bicycle-outline': true,
  'bicycle-sharp': true,
  binoculars: true,
  'binoculars-outline': true,
  'binoculars-sharp': true,
  bluetooth: true,
  'bluetooth-outline': true,
  'bluetooth-sharp': true,
  boat: true,
  'boat-outline': true,
  'boat-sharp': true,
  body: true,
  'body-outline': true,
  'body-sharp': true,
  bonfire: true,
  'bonfire-outline': true,
  'bonfire-sharp': true,
  book: true,
  'book-outline': true,
  'book-sharp': true,
  bookmark: true,
  'bookmark-outline': true,
  'bookmark-sharp': true,
  bookmarks: true,
  'bookmarks-outline': true,
  'bookmarks-sharp': true,
  'bowling-ball': true,
  'bowling-ball-outline': true,
  'bowling-ball-sharp': true,
  briefcase: true,
  'briefcase-outline': true,
  'briefcase-sharp': true,
  browsers: true,
  'browsers-outline': true,
  'browsers-sharp': true,
  brush: true,
  'brush-outline': true,
  'brush-sharp': true,
  bug: true,
  'bug-outline': true,
  'bug-sharp': true,
  build: true,
  'build-outline': true,
  'build-sharp': true,
  bulb: true,
  'bulb-outline': true,
  'bulb-sharp': true,
  bus: true,
  'bus-outline': true,
  'bus-sharp': true,
  business: true,
  'business-outline': true,
  'business-sharp': true,
  cafe: true,
  'cafe-outline': true,
  'cafe-sharp': true,
  calculator: true,
  'calculator-outline': true,
  'calculator-sharp': true,
  calendar: true,
  'calendar-clear': true,
  'calendar-clear-outline': true,
  'calendar-clear-sharp': true,
  'calendar-number': true,
  'calendar-number-outline': true,
  'calendar-number-sharp': true,
  'calendar-outline': true,
  'calendar-sharp': true,
  call: true,
  'call-outline': true,
  'call-sharp': true,
  camera: true,
  'camera-outline': true,
  'camera-reverse': true,
  'camera-reverse-outline': true,
  'camera-reverse-sharp': true,
  'camera-sharp': true,
  car: true,
  'car-outline': true,
  'car-sharp': true,
  'car-sport': true,
  'car-sport-outline': true,
  'car-sport-sharp': true,
  card: true,
  'card-outline': true,
  'card-sharp': true,
  'caret-back': true,
  'caret-back-circle': true,
  'caret-back-circle-outline': true,
  'caret-back-circle-sharp': true,
  'caret-back-outline': true,
  'caret-back-sharp': true,
  'caret-down': true,
  'caret-down-circle': true,
  'caret-down-circle-outline': true,
  'caret-down-circle-sharp': true,
  'caret-down-outline': true,
  'caret-down-sharp': true,
  'caret-forward': true,
  'caret-forward-circle': true,
  'caret-forward-circle-outline': true,
  'caret-forward-circle-sharp': true,
  'caret-forward-outline': true,
  'caret-forward-sharp': true,
  'caret-up': true,
  'caret-up-circle': true,
  'caret-up-circle-outline': true,
  'caret-up-circle-sharp': true,
  'caret-up-outline': true,
  'caret-up-sharp': true,
  cart: true,
  'cart-outline': true,
  'cart-sharp': true,
  cash: true,
  'cash-outline': true,
  'cash-sharp': true,
  cellular: true,
  'cellular-outline': true,
  'cellular-sharp': true,
  chatbox: true,
  'chatbox-ellipses': true,
  'chatbox-ellipses-outline': true,
  'chatbox-ellipses-sharp': true,
  'chatbox-outline': true,
  'chatbox-sharp': true,
  chatbubble: true,
  'chatbubble-ellipses': true,
  'chatbubble-ellipses-outline': true,
  'chatbubble-ellipses-sharp': true,
  'chatbubble-outline': true,
  'chatbubble-sharp': true,
  chatbubbles: true,
  'chatbubbles-outline': true,
  'chatbubbles-sharp': true,
  checkbox: true,
  'checkbox-outline': true,
  'checkbox-sharp': true,
  checkmark: true,
  'checkmark-circle': true,
  'checkmark-circle-outline': true,
  'checkmark-circle-sharp': true,
  'checkmark-done': true,
  'checkmark-done-circle': true,
  'checkmark-done-circle-outline': true,
  'checkmark-done-circle-sharp': true,
  'checkmark-done-outline': true,
  'checkmark-done-sharp': true,
  'checkmark-outline': true,
  'checkmark-sharp': true,
  'chevron-back': true,
  'chevron-back-circle': true,
  'chevron-back-circle-outline': true,
  'chevron-back-circle-sharp': true,
  'chevron-back-outline': true,
  'chevron-back-sharp': true,
  'chevron-collapse': true,
  'chevron-collapse-outline': true,
  'chevron-collapse-sharp': true,
  'chevron-down': true,
  'chevron-down-circle': true,
  'chevron-down-circle-outline': true,
  'chevron-down-circle-sharp': true,
  'chevron-down-outline': true,
  'chevron-down-sharp': true,
  'chevron-expand': true,
  'chevron-expand-outline': true,
  'chevron-expand-sharp': true,
  'chevron-forward': true,
  'chevron-forward-circle': true,
  'chevron-forward-circle-outline': true,
  'chevron-forward-circle-sharp': true,
  'chevron-forward-outline': true,
  'chevron-forward-sharp': true,
  'chevron-up': true,
  'chevron-up-circle': true,
  'chevron-up-circle-outline': true,
  'chevron-up-circle-sharp': true,
  'chevron-up-outline': true,
  'chevron-up-sharp': true,
  clipboard: true,
  'clipboard-outline': true,
  'clipboard-sharp': true,
  close: true,
  'close-circle': true,
  'close-circle-outline': true,
  'close-circle-sharp': true,
  'close-outline': true,
  'close-sharp': true,
  cloud: true,
  'cloud-circle': true,
  'cloud-circle-outline': true,
  'cloud-circle-sharp': true,
  'cloud-done': true,
  'cloud-done-outline': true,
  'cloud-done-sharp': true,
  'cloud-download': true,
  'cloud-download-outline': true,
  'cloud-download-sharp': true,
  'cloud-offline': true,
  'cloud-offline-outline': true,
  'cloud-offline-sharp': true,
  'cloud-outline': true,
  'cloud-sharp': true,
  'cloud-upload': true,
  'cloud-upload-outline': true,
  'cloud-upload-sharp': true,
  cloudy: true,
  'cloudy-night': true,
  'cloudy-night-outline': true,
  'cloudy-night-sharp': true,
  'cloudy-outline': true,
  'cloudy-sharp': true,
  code: true,
  'code-download': true,
  'code-download-outline': true,
  'code-download-sharp': true,
  'code-outline': true,
  'code-sharp': true,
  'code-slash': true,
  'code-slash-outline': true,
  'code-slash-sharp': true,
  'code-working': true,
  'code-working-outline': true,
  'code-working-sharp': true,
  cog: true,
  'cog-outline': true,
  'cog-sharp': true,
  'color-fill': true,
  'color-fill-outline': true,
  'color-fill-sharp': true,
  'color-filter': true,
  'color-filter-outline': true,
  'color-filter-sharp': true,
  'color-palette': true,
  'color-palette-outline': true,
  'color-palette-sharp': true,
  'color-wand': true,
  'color-wand-outline': true,
  'color-wand-sharp': true,
  compass: true,
  'compass-outline': true,
  'compass-sharp': true,
  construct: true,
  'construct-outline': true,
  'construct-sharp': true,
  contract: true,
  'contract-outline': true,
  'contract-sharp': true,
  contrast: true,
  'contrast-outline': true,
  'contrast-sharp': true,
  copy: true,
  'copy-outline': true,
  'copy-sharp': true,
  create: true,
  'create-outline': true,
  'create-sharp': true,
  crop: true,
  'crop-outline': true,
  'crop-sharp': true,
  cube: true,
  'cube-outline': true,
  'cube-sharp': true,
  cut: true,
  'cut-outline': true,
  'cut-sharp': true,
  desktop: true,
  'desktop-outline': true,
  'desktop-sharp': true,
  diamond: true,
  'diamond-outline': true,
  'diamond-sharp': true,
  dice: true,
  'dice-outline': true,
  'dice-sharp': true,
  disc: true,
  'disc-outline': true,
  'disc-sharp': true,
  document: true,
  'document-attach': true,
  'document-attach-outline': true,
  'document-attach-sharp': true,
  'document-lock': true,
  'document-lock-outline': true,
  'document-lock-sharp': true,
  'document-outline': true,
  'document-sharp': true,
  'document-text': true,
  'document-text-outline': true,
  'document-text-sharp': true,
  documents: true,
  'documents-outline': true,
  'documents-sharp': true,
  download: true,
  'download-outline': true,
  'download-sharp': true,
  duplicate: true,
  'duplicate-outline': true,
  'duplicate-sharp': true,
  ear: true,
  'ear-outline': true,
  'ear-sharp': true,
  earth: true,
  'earth-outline': true,
  'earth-sharp': true,
  easel: true,
  'easel-outline': true,
  'easel-sharp': true,
  egg: true,
  'egg-outline': true,
  'egg-sharp': true,
  ellipse: true,
  'ellipse-outline': true,
  'ellipse-sharp': true,
  'ellipsis-horizontal': true,
  'ellipsis-horizontal-circle': true,
  'ellipsis-horizontal-circle-outline': true,
  'ellipsis-horizontal-circle-sharp': true,
  'ellipsis-horizontal-outline': true,
  'ellipsis-horizontal-sharp': true,
  'ellipsis-vertical': true,
  'ellipsis-vertical-circle': true,
  'ellipsis-vertical-circle-outline': true,
  'ellipsis-vertical-circle-sharp': true,
  'ellipsis-vertical-outline': true,
  'ellipsis-vertical-sharp': true,
  enter: true,
  'enter-outline': true,
  'enter-sharp': true,
  exit: true,
  'exit-outline': true,
  'exit-sharp': true,
  expand: true,
  'expand-outline': true,
  'expand-sharp': true,
  'extension-puzzle': true,
  'extension-puzzle-outline': true,
  'extension-puzzle-sharp': true,
  eye: true,
  'eye-off': true,
  'eye-off-outline': true,
  'eye-off-sharp': true,
  'eye-outline': true,
  'eye-sharp': true,
  eyedrop: true,
  'eyedrop-outline': true,
  'eyedrop-sharp': true,
  'fast-food': true,
  'fast-food-outline': true,
  'fast-food-sharp': true,
  female: true,
  'female-outline': true,
  'female-sharp': true,
  'file-tray': true,
  'file-tray-full': true,
  'file-tray-full-outline': true,
  'file-tray-full-sharp': true,
  'file-tray-outline': true,
  'file-tray-sharp': true,
  'file-tray-stacked': true,
  'file-tray-stacked-outline': true,
  'file-tray-stacked-sharp': true,
  film: true,
  'film-outline': true,
  'film-sharp': true,
  filter: true,
  'filter-circle': true,
  'filter-circle-outline': true,
  'filter-circle-sharp': true,
  'filter-outline': true,
  'filter-sharp': true,
  'finger-print': true,
  'finger-print-outline': true,
  'finger-print-sharp': true,
  fish: true,
  'fish-outline': true,
  'fish-sharp': true,
  fitness: true,
  'fitness-outline': true,
  'fitness-sharp': true,
  flag: true,
  'flag-outline': true,
  'flag-sharp': true,
  flame: true,
  'flame-outline': true,
  'flame-sharp': true,
  flash: true,
  'flash-off': true,
  'flash-off-outline': true,
  'flash-off-sharp': true,
  'flash-outline': true,
  'flash-sharp': true,
  flashlight: true,
  'flashlight-outline': true,
  'flashlight-sharp': true,
  flask: true,
  'flask-outline': true,
  'flask-sharp': true,
  flower: true,
  'flower-outline': true,
  'flower-sharp': true,
  folder: true,
  'folder-open': true,
  'folder-open-outline': true,
  'folder-open-sharp': true,
  'folder-outline': true,
  'folder-sharp': true,
  football: true,
  'football-outline': true,
  'football-sharp': true,
  footsteps: true,
  'footsteps-outline': true,
  'footsteps-sharp': true,
  funnel: true,
  'funnel-outline': true,
  'funnel-sharp': true,
  'game-controller': true,
  'game-controller-outline': true,
  'game-controller-sharp': true,
  gift: true,
  'gift-outline': true,
  'gift-sharp': true,
  'git-branch': true,
  'git-branch-outline': true,
  'git-branch-sharp': true,
  'git-commit': true,
  'git-commit-outline': true,
  'git-commit-sharp': true,
  'git-compare': true,
  'git-compare-outline': true,
  'git-compare-sharp': true,
  'git-merge': true,
  'git-merge-outline': true,
  'git-merge-sharp': true,
  'git-network': true,
  'git-network-outline': true,
  'git-network-sharp': true,
  'git-pull-request': true,
  'git-pull-request-outline': true,
  'git-pull-request-sharp': true,
  glasses: true,
  'glasses-outline': true,
  'glasses-sharp': true,
  globe: true,
  'globe-outline': true,
  'globe-sharp': true,
  golf: true,
  'golf-outline': true,
  'golf-sharp': true,
  grid: true,
  'grid-outline': true,
  'grid-sharp': true,
  hammer: true,
  'hammer-outline': true,
  'hammer-sharp': true,
  'hand-left': true,
  'hand-left-outline': true,
  'hand-left-sharp': true,
  'hand-right': true,
  'hand-right-outline': true,
  'hand-right-sharp': true,
  happy: true,
  'happy-outline': true,
  'happy-sharp': true,
  'hardware-chip': true,
  'hardware-chip-outline': true,
  'hardware-chip-sharp': true,
  headset: true,
  'headset-outline': true,
  'headset-sharp': true,
  heart: true,
  'heart-circle': true,
  'heart-circle-outline': true,
  'heart-circle-sharp': true,
  'heart-dislike': true,
  'heart-dislike-circle': true,
  'heart-dislike-circle-outline': true,
  'heart-dislike-circle-sharp': true,
  'heart-dislike-outline': true,
  'heart-dislike-sharp': true,
  'heart-half': true,
  'heart-half-outline': true,
  'heart-half-sharp': true,
  'heart-outline': true,
  'heart-sharp': true,
  help: true,
  'help-buoy': true,
  'help-buoy-outline': true,
  'help-buoy-sharp': true,
  'help-circle': true,
  'help-circle-outline': true,
  'help-circle-sharp': true,
  'help-outline': true,
  'help-sharp': true,
  home: true,
  'home-outline': true,
  'home-sharp': true,
  hourglass: true,
  'hourglass-outline': true,
  'hourglass-sharp': true,
  'ice-cream': true,
  'ice-cream-outline': true,
  'ice-cream-sharp': true,
  'id-card': true,
  'id-card-outline': true,
  'id-card-sharp': true,
  image: true,
  'image-outline': true,
  'image-sharp': true,
  images: true,
  'images-outline': true,
  'images-sharp': true,
  infinite: true,
  'infinite-outline': true,
  'infinite-sharp': true,
  information: true,
  'information-circle': true,
  'information-circle-outline': true,
  'information-circle-sharp': true,
  'information-outline': true,
  'information-sharp': true,
  'invert-mode': true,
  'invert-mode-outline': true,
  'invert-mode-sharp': true,
  journal: true,
  'journal-outline': true,
  'journal-sharp': true,
  key: true,
  'key-outline': true,
  'key-sharp': true,
  keypad: true,
  'keypad-outline': true,
  'keypad-sharp': true,
  language: true,
  'language-outline': true,
  'language-sharp': true,
  laptop: true,
  'laptop-outline': true,
  'laptop-sharp': true,
  layers: true,
  'layers-outline': true,
  'layers-sharp': true,
  leaf: true,
  'leaf-outline': true,
  'leaf-sharp': true,
  library: true,
  'library-outline': true,
  'library-sharp': true,
  link: true,
  'link-outline': true,
  'link-sharp': true,
  list: true,
  'list-circle': true,
  'list-circle-outline': true,
  'list-circle-sharp': true,
  'list-outline': true,
  'list-sharp': true,
  locate: true,
  'locate-outline': true,
  'locate-sharp': true,
  location: true,
  'location-outline': true,
  'location-sharp': true,
  'lock-closed': true,
  'lock-closed-outline': true,
  'lock-closed-sharp': true,
  'lock-open': true,
  'lock-open-outline': true,
  'lock-open-sharp': true,
  'log-in': true,
  'log-in-outline': true,
  'log-in-sharp': true,
  'log-out': true,
  'log-out-outline': true,
  'log-out-sharp': true,
  'logo-alipay': true,
  'logo-amazon': true,
  'logo-amplify': true,
  'logo-android': true,
  'logo-angular': true,
  'logo-appflow': true,
  'logo-apple': true,
  'logo-apple-appstore': true,
  'logo-apple-ar': true,
  'logo-behance': true,
  'logo-bitbucket': true,
  'logo-bitcoin': true,
  'logo-buffer': true,
  'logo-capacitor': true,
  'logo-chrome': true,
  'logo-closed-captioning': true,
  'logo-codepen': true,
  'logo-css3': true,
  'logo-designernews': true,
  'logo-deviantart': true,
  'logo-discord': true,
  'logo-docker': true,
  'logo-dribbble': true,
  'logo-dropbox': true,
  'logo-edge': true,
  'logo-electron': true,
  'logo-euro': true,
  'logo-facebook': true,
  'logo-figma': true,
  'logo-firebase': true,
  'logo-firefox': true,
  'logo-flickr': true,
  'logo-foursquare': true,
  'logo-github': true,
  'logo-gitlab': true,
  'logo-google': true,
  'logo-google-playstore': true,
  'logo-hackernews': true,
  'logo-html5': true,
  'logo-instagram': true,
  'logo-ionic': true,
  'logo-ionitron': true,
  'logo-javascript': true,
  'logo-laravel': true,
  'logo-linkedin': true,
  'logo-markdown': true,
  'logo-mastodon': true,
  'logo-medium': true,
  'logo-microsoft': true,
  'logo-no-smoking': true,
  'logo-nodejs': true,
  'logo-npm': true,
  'logo-octocat': true,
  'logo-paypal': true,
  'logo-pinterest': true,
  'logo-playstation': true,
  'logo-pwa': true,
  'logo-python': true,
  'logo-react': true,
  'logo-reddit': true,
  'logo-rss': true,
  'logo-sass': true,
  'logo-skype': true,
  'logo-slack': true,
  'logo-snapchat': true,
  'logo-soundcloud': true,
  'logo-stackoverflow': true,
  'logo-steam': true,
  'logo-stencil': true,
  'logo-tableau': true,
  'logo-threads': true,
  'logo-tiktok': true,
  'logo-trapeze': true,
  'logo-tumblr': true,
  'logo-tux': true,
  'logo-twitch': true,
  'logo-twitter': true,
  'logo-usd': true,
  'logo-venmo': true,
  'logo-vercel': true,
  'logo-vimeo': true,
  'logo-vk': true,
  'logo-vue': true,
  'logo-web-component': true,
  'logo-wechat': true,
  'logo-whatsapp': true,
  'logo-windows': true,
  'logo-wordpress': true,
  'logo-x': true,
  'logo-xbox': true,
  'logo-xing': true,
  'logo-yahoo': true,
  'logo-yen': true,
  'logo-youtube': true,
  magnet: true,
  'magnet-outline': true,
  'magnet-sharp': true,
  mail: true,
  'mail-open': true,
  'mail-open-outline': true,
  'mail-open-sharp': true,
  'mail-outline': true,
  'mail-sharp': true,
  'mail-unread': true,
  'mail-unread-outline': true,
  'mail-unread-sharp': true,
  male: true,
  'male-female': true,
  'male-female-outline': true,
  'male-female-sharp': true,
  'male-outline': true,
  'male-sharp': true,
  man: true,
  'man-outline': true,
  'man-sharp': true,
  map: true,
  'map-outline': true,
  'map-sharp': true,
  medal: true,
  'medal-outline': true,
  'medal-sharp': true,
  medical: true,
  'medical-outline': true,
  'medical-sharp': true,
  medkit: true,
  'medkit-outline': true,
  'medkit-sharp': true,
  megaphone: true,
  'megaphone-outline': true,
  'megaphone-sharp': true,
  menu: true,
  'menu-outline': true,
  'menu-sharp': true,
  mic: true,
  'mic-circle': true,
  'mic-circle-outline': true,
  'mic-circle-sharp': true,
  'mic-off': true,
  'mic-off-circle': true,
  'mic-off-circle-outline': true,
  'mic-off-circle-sharp': true,
  'mic-off-outline': true,
  'mic-off-sharp': true,
  'mic-outline': true,
  'mic-sharp': true,
  moon: true,
  'moon-outline': true,
  'moon-sharp': true,
  move: true,
  'move-outline': true,
  'move-sharp': true,
  'musical-note': true,
  'musical-note-outline': true,
  'musical-note-sharp': true,
  'musical-notes': true,
  'musical-notes-outline': true,
  'musical-notes-sharp': true,
  navigate: true,
  'navigate-circle': true,
  'navigate-circle-outline': true,
  'navigate-circle-sharp': true,
  'navigate-outline': true,
  'navigate-sharp': true,
  newspaper: true,
  'newspaper-outline': true,
  'newspaper-sharp': true,
  notifications: true,
  'notifications-circle': true,
  'notifications-circle-outline': true,
  'notifications-circle-sharp': true,
  'notifications-off': true,
  'notifications-off-circle': true,
  'notifications-off-circle-outline': true,
  'notifications-off-circle-sharp': true,
  'notifications-off-outline': true,
  'notifications-off-sharp': true,
  'notifications-outline': true,
  'notifications-sharp': true,
  nuclear: true,
  'nuclear-outline': true,
  'nuclear-sharp': true,
  nutrition: true,
  'nutrition-outline': true,
  'nutrition-sharp': true,
  open: true,
  'open-outline': true,
  'open-sharp': true,
  options: true,
  'options-outline': true,
  'options-sharp': true,
  'paper-plane': true,
  'paper-plane-outline': true,
  'paper-plane-sharp': true,
  'partly-sunny': true,
  'partly-sunny-outline': true,
  'partly-sunny-sharp': true,
  pause: true,
  'pause-circle': true,
  'pause-circle-outline': true,
  'pause-circle-sharp': true,
  'pause-outline': true,
  'pause-sharp': true,
  paw: true,
  'paw-outline': true,
  'paw-sharp': true,
  pencil: true,
  'pencil-outline': true,
  'pencil-sharp': true,
  people: true,
  'people-circle': true,
  'people-circle-outline': true,
  'people-circle-sharp': true,
  'people-outline': true,
  'people-sharp': true,
  person: true,
  'person-add': true,
  'person-add-outline': true,
  'person-add-sharp': true,
  'person-circle': true,
  'person-circle-outline': true,
  'person-circle-sharp': true,
  'person-outline': true,
  'person-remove': true,
  'person-remove-outline': true,
  'person-remove-sharp': true,
  'person-sharp': true,
  'phone-landscape': true,
  'phone-landscape-outline': true,
  'phone-landscape-sharp': true,
  'phone-portrait': true,
  'phone-portrait-outline': true,
  'phone-portrait-sharp': true,
  'pie-chart': true,
  'pie-chart-outline': true,
  'pie-chart-sharp': true,
  pin: true,
  'pin-outline': true,
  'pin-sharp': true,
  pint: true,
  'pint-outline': true,
  'pint-sharp': true,
  pizza: true,
  'pizza-outline': true,
  'pizza-sharp': true,
  planet: true,
  'planet-outline': true,
  'planet-sharp': true,
  play: true,
  'play-back': true,
  'play-back-circle': true,
  'play-back-circle-outline': true,
  'play-back-circle-sharp': true,
  'play-back-outline': true,
  'play-back-sharp': true,
  'play-circle': true,
  'play-circle-outline': true,
  'play-circle-sharp': true,
  'play-forward': true,
  'play-forward-circle': true,
  'play-forward-circle-outline': true,
  'play-forward-circle-sharp': true,
  'play-forward-outline': true,
  'play-forward-sharp': true,
  'play-outline': true,
  'play-sharp': true,
  'play-skip-back': true,
  'play-skip-back-circle': true,
  'play-skip-back-circle-outline': true,
  'play-skip-back-circle-sharp': true,
  'play-skip-back-outline': true,
  'play-skip-back-sharp': true,
  'play-skip-forward': true,
  'play-skip-forward-circle': true,
  'play-skip-forward-circle-outline': true,
  'play-skip-forward-circle-sharp': true,
  'play-skip-forward-outline': true,
  'play-skip-forward-sharp': true,
  podium: true,
  'podium-outline': true,
  'podium-sharp': true,
  power: true,
  'power-outline': true,
  'power-sharp': true,
  pricetag: true,
  'pricetag-outline': true,
  'pricetag-sharp': true,
  pricetags: true,
  'pricetags-outline': true,
  'pricetags-sharp': true,
  print: true,
  'print-outline': true,
  'print-sharp': true,
  prism: true,
  'prism-outline': true,
  'prism-sharp': true,
  pulse: true,
  'pulse-outline': true,
  'pulse-sharp': true,
  push: true,
  'push-outline': true,
  'push-sharp': true,
  'qr-code': true,
  'qr-code-outline': true,
  'qr-code-sharp': true,
  radio: true,
  'radio-button-off': true,
  'radio-button-off-outline': true,
  'radio-button-off-sharp': true,
  'radio-button-on': true,
  'radio-button-on-outline': true,
  'radio-button-on-sharp': true,
  'radio-outline': true,
  'radio-sharp': true,
  rainy: true,
  'rainy-outline': true,
  'rainy-sharp': true,
  reader: true,
  'reader-outline': true,
  'reader-sharp': true,
  receipt: true,
  'receipt-outline': true,
  'receipt-sharp': true,
  recording: true,
  'recording-outline': true,
  'recording-sharp': true,
  refresh: true,
  'refresh-circle': true,
  'refresh-circle-outline': true,
  'refresh-circle-sharp': true,
  'refresh-outline': true,
  'refresh-sharp': true,
  reload: true,
  'reload-circle': true,
  'reload-circle-outline': true,
  'reload-circle-sharp': true,
  'reload-outline': true,
  'reload-sharp': true,
  remove: true,
  'remove-circle': true,
  'remove-circle-outline': true,
  'remove-circle-sharp': true,
  'remove-outline': true,
  'remove-sharp': true,
  'reorder-four': true,
  'reorder-four-outline': true,
  'reorder-four-sharp': true,
  'reorder-three': true,
  'reorder-three-outline': true,
  'reorder-three-sharp': true,
  'reorder-two': true,
  'reorder-two-outline': true,
  'reorder-two-sharp': true,
  repeat: true,
  'repeat-outline': true,
  'repeat-sharp': true,
  resize: true,
  'resize-outline': true,
  'resize-sharp': true,
  restaurant: true,
  'restaurant-outline': true,
  'restaurant-sharp': true,
  'return-down-back': true,
  'return-down-back-outline': true,
  'return-down-back-sharp': true,
  'return-down-forward': true,
  'return-down-forward-outline': true,
  'return-down-forward-sharp': true,
  'return-up-back': true,
  'return-up-back-outline': true,
  'return-up-back-sharp': true,
  'return-up-forward': true,
  'return-up-forward-outline': true,
  'return-up-forward-sharp': true,
  ribbon: true,
  'ribbon-outline': true,
  'ribbon-sharp': true,
  rocket: true,
  'rocket-outline': true,
  'rocket-sharp': true,
  rose: true,
  'rose-outline': true,
  'rose-sharp': true,
  sad: true,
  'sad-outline': true,
  'sad-sharp': true,
  save: true,
  'save-outline': true,
  'save-sharp': true,
  scale: true,
  'scale-outline': true,
  'scale-sharp': true,
  scan: true,
  'scan-circle': true,
  'scan-circle-outline': true,
  'scan-circle-sharp': true,
  'scan-outline': true,
  'scan-sharp': true,
  school: true,
  'school-outline': true,
  'school-sharp': true,
  search: true,
  'search-circle': true,
  'search-circle-outline': true,
  'search-circle-sharp': true,
  'search-outline': true,
  'search-sharp': true,
  send: true,
  'send-outline': true,
  'send-sharp': true,
  server: true,
  'server-outline': true,
  'server-sharp': true,
  settings: true,
  'settings-outline': true,
  'settings-sharp': true,
  shapes: true,
  'shapes-outline': true,
  'shapes-sharp': true,
  share: true,
  'share-outline': true,
  'share-sharp': true,
  'share-social': true,
  'share-social-outline': true,
  'share-social-sharp': true,
  shield: true,
  'shield-checkmark': true,
  'shield-checkmark-outline': true,
  'shield-checkmark-sharp': true,
  'shield-half': true,
  'shield-half-outline': true,
  'shield-half-sharp': true,
  'shield-outline': true,
  'shield-sharp': true,
  shirt: true,
  'shirt-outline': true,
  'shirt-sharp': true,
  shuffle: true,
  'shuffle-outline': true,
  'shuffle-sharp': true,
  skull: true,
  'skull-outline': true,
  'skull-sharp': true,
  snow: true,
  'snow-outline': true,
  'snow-sharp': true,
  sparkles: true,
  'sparkles-outline': true,
  'sparkles-sharp': true,
  speedometer: true,
  'speedometer-outline': true,
  'speedometer-sharp': true,
  square: true,
  'square-outline': true,
  'square-sharp': true,
  star: true,
  'star-half': true,
  'star-half-outline': true,
  'star-half-sharp': true,
  'star-outline': true,
  'star-sharp': true,
  'stats-chart': true,
  'stats-chart-outline': true,
  'stats-chart-sharp': true,
  stop: true,
  'stop-circle': true,
  'stop-circle-outline': true,
  'stop-circle-sharp': true,
  'stop-outline': true,
  'stop-sharp': true,
  stopwatch: true,
  'stopwatch-outline': true,
  'stopwatch-sharp': true,
  storefront: true,
  'storefront-outline': true,
  'storefront-sharp': true,
  subway: true,
  'subway-outline': true,
  'subway-sharp': true,
  sunny: true,
  'sunny-outline': true,
  'sunny-sharp': true,
  'swap-horizontal': true,
  'swap-horizontal-outline': true,
  'swap-horizontal-sharp': true,
  'swap-vertical': true,
  'swap-vertical-outline': true,
  'swap-vertical-sharp': true,
  sync: true,
  'sync-circle': true,
  'sync-circle-outline': true,
  'sync-circle-sharp': true,
  'sync-outline': true,
  'sync-sharp': true,
  'tablet-landscape': true,
  'tablet-landscape-outline': true,
  'tablet-landscape-sharp': true,
  'tablet-portrait': true,
  'tablet-portrait-outline': true,
  'tablet-portrait-sharp': true,
  telescope: true,
  'telescope-outline': true,
  'telescope-sharp': true,
  tennisball: true,
  'tennisball-outline': true,
  'tennisball-sharp': true,
  terminal: true,
  'terminal-outline': true,
  'terminal-sharp': true,
  text: true,
  'text-outline': true,
  'text-sharp': true,
  thermometer: true,
  'thermometer-outline': true,
  'thermometer-sharp': true,
  'thumbs-down': true,
  'thumbs-down-outline': true,
  'thumbs-down-sharp': true,
  'thumbs-up': true,
  'thumbs-up-outline': true,
  'thumbs-up-sharp': true,
  thunderstorm: true,
  'thunderstorm-outline': true,
  'thunderstorm-sharp': true,
  ticket: true,
  'ticket-outline': true,
  'ticket-sharp': true,
  time: true,
  'time-outline': true,
  'time-sharp': true,
  timer: true,
  'timer-outline': true,
  'timer-sharp': true,
  today: true,
  'today-outline': true,
  'today-sharp': true,
  toggle: true,
  'toggle-outline': true,
  'toggle-sharp': true,
  'trail-sign': true,
  'trail-sign-outline': true,
  'trail-sign-sharp': true,
  train: true,
  'train-outline': true,
  'train-sharp': true,
  transgender: true,
  'transgender-outline': true,
  'transgender-sharp': true,
  trash: true,
  'trash-bin': true,
  'trash-bin-outline': true,
  'trash-bin-sharp': true,
  'trash-outline': true,
  'trash-sharp': true,
  'trending-down': true,
  'trending-down-outline': true,
  'trending-down-sharp': true,
  'trending-up': true,
  'trending-up-outline': true,
  'trending-up-sharp': true,
  triangle: true,
  'triangle-outline': true,
  'triangle-sharp': true,
  trophy: true,
  'trophy-outline': true,
  'trophy-sharp': true,
  tv: true,
  'tv-outline': true,
  'tv-sharp': true,
  umbrella: true,
  'umbrella-outline': true,
  'umbrella-sharp': true,
  unlink: true,
  'unlink-outline': true,
  'unlink-sharp': true,
  videocam: true,
  'videocam-off': true,
  'videocam-off-outline': true,
  'videocam-off-sharp': true,
  'videocam-outline': true,
  'videocam-sharp': true,
  'volume-high': true,
  'volume-high-outline': true,
  'volume-high-sharp': true,
  'volume-low': true,
  'volume-low-outline': true,
  'volume-low-sharp': true,
  'volume-medium': true,
  'volume-medium-outline': true,
  'volume-medium-sharp': true,
  'volume-mute': true,
  'volume-mute-outline': true,
  'volume-mute-sharp': true,
  'volume-off': true,
  'volume-off-outline': true,
  'volume-off-sharp': true,
  walk: true,
  'walk-outline': true,
  'walk-sharp': true,
  wallet: true,
  'wallet-outline': true,
  'wallet-sharp': true,
  warning: true,
  'warning-outline': true,
  'warning-sharp': true,
  watch: true,
  'watch-outline': true,
  'watch-sharp': true,
  water: true,
  'water-outline': true,
  'water-sharp': true,
  wifi: true,
  'wifi-outline': true,
  'wifi-sharp': true,
  wine: true,
  'wine-outline': true,
  'wine-sharp': true,
  woman: true,
  'woman-outline': true,
  'woman-sharp': true,
} as const;

/**
 * Names upstream has renamed or hidden. Still served, still typed, and
 * deliberately not in the object above: a union compiles to nothing, while
 * every entry in that object ships to every application.
 */
type IonIconAlias =
  | 'alert-circled'
  | 'android-add'
  | 'android-add-circle'
  | 'android-alarm-clock'
  | 'android-alert'
  | 'android-apps'
  | 'android-archive'
  | 'android-arrow-back'
  | 'android-arrow-down'
  | 'android-arrow-dropdown'
  | 'android-arrow-dropdown-circle'
  | 'android-arrow-dropleft'
  | 'android-arrow-dropleft-circle'
  | 'android-arrow-dropright'
  | 'android-arrow-dropright-circle'
  | 'android-arrow-dropup'
  | 'android-arrow-dropup-circle'
  | 'android-arrow-forward'
  | 'android-arrow-up'
  | 'android-attach'
  | 'android-bar'
  | 'android-bicycle'
  | 'android-boat'
  | 'android-bookmark'
  | 'android-bulb'
  | 'android-bus'
  | 'android-calendar'
  | 'android-call'
  | 'android-camera'
  | 'android-cancel'
  | 'android-car'
  | 'android-cart'
  | 'android-chat'
  | 'android-checkbox'
  | 'android-checkbox-blank'
  | 'android-checkbox-outline'
  | 'android-checkbox-outline-blank'
  | 'android-checkmark-circle'
  | 'android-clipboard'
  | 'android-close'
  | 'android-cloud'
  | 'android-cloud-circle'
  | 'android-cloud-done'
  | 'android-cloud-outline'
  | 'android-color-palette'
  | 'android-compass'
  | 'android-contact'
  | 'android-contacts'
  | 'android-contract'
  | 'android-create'
  | 'android-delete'
  | 'android-desktop'
  | 'android-document'
  | 'android-done'
  | 'android-done-all'
  | 'android-download'
  | 'android-drafts'
  | 'android-exit'
  | 'android-expand'
  | 'android-favorite'
  | 'android-favorite-outline'
  | 'android-film'
  | 'android-folder'
  | 'android-folder-open'
  | 'android-funnel'
  | 'android-globe'
  | 'android-hand'
  | 'android-hangout'
  | 'android-happy'
  | 'android-home'
  | 'android-image'
  | 'android-laptop'
  | 'android-list'
  | 'android-locate'
  | 'android-lock'
  | 'android-mail'
  | 'android-map'
  | 'android-menu'
  | 'android-microphone'
  | 'android-microphone-off'
  | 'android-more-horizontal'
  | 'android-more-vertical'
  | 'android-navigate'
  | 'android-notifications'
  | 'android-notifications-none'
  | 'android-notifications-off'
  | 'android-open'
  | 'android-options'
  | 'android-people'
  | 'android-person'
  | 'android-person-add'
  | 'android-phone-landscape'
  | 'android-phone-portrait'
  | 'android-pin'
  | 'android-plane'
  | 'android-playstore'
  | 'android-print'
  | 'android-radio-button-off'
  | 'android-radio-button-on'
  | 'android-refresh'
  | 'android-remove'
  | 'android-remove-circle'
  | 'android-restaurant'
  | 'android-sad'
  | 'android-search'
  | 'android-send'
  | 'android-settings'
  | 'android-share'
  | 'android-share-alt'
  | 'android-star'
  | 'android-star-half'
  | 'android-star-outline'
  | 'android-stopwatch'
  | 'android-subway'
  | 'android-sunny'
  | 'android-sync'
  | 'android-textsms'
  | 'android-time'
  | 'android-train'
  | 'android-unlock'
  | 'android-upload'
  | 'android-volume-down'
  | 'android-volume-mute'
  | 'android-volume-off'
  | 'android-volume-up'
  | 'android-walk'
  | 'android-warning'
  | 'android-watch'
  | 'android-wifi'
  | 'arrow-down-a'
  | 'arrow-down-b'
  | 'arrow-down-c'
  | 'arrow-expand'
  | 'arrow-graph-down-left'
  | 'arrow-graph-down-right'
  | 'arrow-graph-up-left'
  | 'arrow-graph-up-right'
  | 'arrow-left-a'
  | 'arrow-left-b'
  | 'arrow-left-c'
  | 'arrow-move'
  | 'arrow-resize'
  | 'arrow-return-left'
  | 'arrow-return-right'
  | 'arrow-right-a'
  | 'arrow-right-b'
  | 'arrow-right-c'
  | 'arrow-shrink'
  | 'arrow-swap'
  | 'arrow-up-a'
  | 'arrow-up-b'
  | 'arrow-up-c'
  | 'asterisk'
  | 'battery-empty'
  | 'battery-low'
  | 'bowtie'
  | 'chatbox-working'
  | 'chatboxes'
  | 'chatbubble-ellipses-filled'
  | 'chatbubble-working'
  | 'checkmark-circled'
  | 'checkmark-round'
  | 'chevron-left'
  | 'chevron-right'
  | 'clock'
  | 'close-circled'
  | 'close-round'
  | 'closed-captioning'
  | 'coffee'
  | 'compose'
  | 'connection-bars'
  | 'drag'
  | 'edit'
  | 'eject'
  | 'email'
  | 'email-unread'
  | 'erlenmeyer-flask'
  | 'erlenmeyer-flask-bubbles'
  | 'eye-disabled'
  | 'filing'
  | 'film-marker'
  | 'fireball'
  | 'fork'
  | 'fork-repo'
  | 'forward'
  | 'gear-a'
  | 'gear-b'
  | 'headphone'
  | 'heart-broken'
  | 'help-circled'
  | 'icecream'
  | 'information-circled'
  | 'ionic'
  | 'ios-add'
  | 'ios-add-circle'
  | 'ios-add-circle-outline'
  | 'ios-airplane'
  | 'ios-alarm'
  | 'ios-alarm-outline'
  | 'ios-albums'
  | 'ios-albums-outline'
  | 'ios-alert'
  | 'ios-american-football'
  | 'ios-americanfootball'
  | 'ios-americanfootball-outline'
  | 'ios-analytics'
  | 'ios-analytics-outline'
  | 'ios-aperture'
  | 'ios-apps'
  | 'ios-appstore'
  | 'ios-archive'
  | 'ios-arrow-back'
  | 'ios-arrow-down'
  | 'ios-arrow-dropdown'
  | 'ios-arrow-dropdown-circle'
  | 'ios-arrow-dropleft'
  | 'ios-arrow-dropleft-circle'
  | 'ios-arrow-dropright'
  | 'ios-arrow-dropright-circle'
  | 'ios-arrow-dropup'
  | 'ios-arrow-dropup-circle'
  | 'ios-arrow-forward'
  | 'ios-arrow-left'
  | 'ios-arrow-right'
  | 'ios-arrow-round-back'
  | 'ios-arrow-round-down'
  | 'ios-arrow-round-forward'
  | 'ios-arrow-round-up'
  | 'ios-arrow-thin-down'
  | 'ios-arrow-thin-left'
  | 'ios-arrow-thin-right'
  | 'ios-arrow-thin-up'
  | 'ios-arrow-up'
  | 'ios-at'
  | 'ios-at-outline'
  | 'ios-attach'
  | 'ios-backspace'
  | 'ios-barcode'
  | 'ios-barcode-outline'
  | 'ios-baseball'
  | 'ios-baseball-outline'
  | 'ios-basket'
  | 'ios-basketball'
  | 'ios-basketball-outline'
  | 'ios-battery-charging'
  | 'ios-battery-dead'
  | 'ios-battery-full'
  | 'ios-beaker'
  | 'ios-bed'
  | 'ios-beer'
  | 'ios-bell'
  | 'ios-bell-outline'
  | 'ios-bicycle'
  | 'ios-bluetooth'
  | 'ios-boat'
  | 'ios-body'
  | 'ios-body-outline'
  | 'ios-bolt'
  | 'ios-bolt-outline'
  | 'ios-bonfire'
  | 'ios-book'
  | 'ios-book-outline'
  | 'ios-bookmark'
  | 'ios-bookmarks'
  | 'ios-bookmarks-outline'
  | 'ios-bowtie'
  | 'ios-box'
  | 'ios-box-outline'
  | 'ios-briefcase'
  | 'ios-briefcase-outline'
  | 'ios-browsers'
  | 'ios-browsers-outline'
  | 'ios-brush'
  | 'ios-bug'
  | 'ios-build'
  | 'ios-bulb'
  | 'ios-bus'
  | 'ios-business'
  | 'ios-cafe'
  | 'ios-calculator'
  | 'ios-calculator-outline'
  | 'ios-calendar'
  | 'ios-calendar-outline'
  | 'ios-call'
  | 'ios-camera'
  | 'ios-camera-outline'
  | 'ios-car'
  | 'ios-card'
  | 'ios-cart'
  | 'ios-cart-outline'
  | 'ios-cash'
  | 'ios-cellular'
  | 'ios-chatboxes'
  | 'ios-chatboxes-outline'
  | 'ios-chatbubble'
  | 'ios-chatbubble-outline'
  | 'ios-chatbubbles'
  | 'ios-checkbox'
  | 'ios-checkbox-outline'
  | 'ios-checkmark'
  | 'ios-checkmark-circle'
  | 'ios-checkmark-circle-outline'
  | 'ios-checkmark-empty'
  | 'ios-checkmark-outline'
  | 'ios-circle-filled'
  | 'ios-circle-outline'
  | 'ios-clipboard'
  | 'ios-clock'
  | 'ios-clock-outline'
  | 'ios-close'
  | 'ios-close-circle'
  | 'ios-close-circle-outline'
  | 'ios-close-empty'
  | 'ios-close-outline'
  | 'ios-cloud'
  | 'ios-cloud-circle'
  | 'ios-cloud-done'
  | 'ios-cloud-download'
  | 'ios-cloud-download-outline'
  | 'ios-cloud-outline'
  | 'ios-cloud-upload'
  | 'ios-cloud-upload-outline'
  | 'ios-cloudy'
  | 'ios-cloudy-night'
  | 'ios-cloudy-night-outline'
  | 'ios-cloudy-outline'
  | 'ios-code'
  | 'ios-code-download'
  | 'ios-code-working'
  | 'ios-cog'
  | 'ios-cog-outline'
  | 'ios-color-fill'
  | 'ios-color-filter'
  | 'ios-color-filter-outline'
  | 'ios-color-palette'
  | 'ios-color-wand'
  | 'ios-color-wand-outline'
  | 'ios-compass'
  | 'ios-compose'
  | 'ios-compose-outline'
  | 'ios-construct'
  | 'ios-contact'
  | 'ios-contact-outline'
  | 'ios-contacts'
  | 'ios-contract'
  | 'ios-contrast'
  | 'ios-copy'
  | 'ios-copy-outline'
  | 'ios-create'
  | 'ios-crop'
  | 'ios-crop-strong'
  | 'ios-cube'
  | 'ios-cut'
  | 'ios-desktop'
  | 'ios-disc'
  | 'ios-document'
  | 'ios-done-all'
  | 'ios-download'
  | 'ios-download-outline'
  | 'ios-drag'
  | 'ios-easel'
  | 'ios-egg'
  | 'ios-email'
  | 'ios-email-outline'
  | 'ios-exit'
  | 'ios-expand'
  | 'ios-eye'
  | 'ios-eye-off'
  | 'ios-eye-outline'
  | 'ios-fastforward'
  | 'ios-fastforward-outline'
  | 'ios-female'
  | 'ios-filing'
  | 'ios-filing-outline'
  | 'ios-film'
  | 'ios-film-outline'
  | 'ios-finger-print'
  | 'ios-fitness'
  | 'ios-flag'
  | 'ios-flag-outline'
  | 'ios-flame'
  | 'ios-flame-outline'
  | 'ios-flash'
  | 'ios-flash-off'
  | 'ios-flashlight'
  | 'ios-flask'
  | 'ios-flask-outline'
  | 'ios-flower'
  | 'ios-flower-outline'
  | 'ios-folder'
  | 'ios-folder-open'
  | 'ios-folder-outline'
  | 'ios-football'
  | 'ios-football-outline'
  | 'ios-funnel'
  | 'ios-game-controller-a'
  | 'ios-game-controller-a-outline'
  | 'ios-game-controller-b'
  | 'ios-game-controller-b-outline'
  | 'ios-gear'
  | 'ios-gear-outline'
  | 'ios-gift'
  | 'ios-git-branch'
  | 'ios-git-commit'
  | 'ios-git-compare'
  | 'ios-git-merge'
  | 'ios-git-network'
  | 'ios-git-pull-request'
  | 'ios-glasses'
  | 'ios-glasses-outline'
  | 'ios-globe'
  | 'ios-grid'
  | 'ios-grid-view'
  | 'ios-grid-view-outline'
  | 'ios-hammer'
  | 'ios-hand'
  | 'ios-happy'
  | 'ios-headset'
  | 'ios-heart'
  | 'ios-heart-dislike'
  | 'ios-heart-empty'
  | 'ios-heart-half'
  | 'ios-heart-outline'
  | 'ios-help'
  | 'ios-help-buoy'
  | 'ios-help-circle'
  | 'ios-help-circle-outline'
  | 'ios-help-empty'
  | 'ios-help-outline'
  | 'ios-home'
  | 'ios-home-outline'
  | 'ios-hourglass'
  | 'ios-ice-cream'
  | 'ios-image'
  | 'ios-images'
  | 'ios-infinite'
  | 'ios-infinite-outline'
  | 'ios-information'
  | 'ios-information-circle'
  | 'ios-information-circle-outline'
  | 'ios-information-empty'
  | 'ios-information-outline'
  | 'ios-ionic-outline'
  | 'ios-jet'
  | 'ios-journal'
  | 'ios-key'
  | 'ios-keypad'
  | 'ios-keypad-outline'
  | 'ios-laptop'
  | 'ios-leaf'
  | 'ios-lightbulb'
  | 'ios-lightbulb-outline'
  | 'ios-link'
  | 'ios-list'
  | 'ios-list-box'
  | 'ios-list-outline'
  | 'ios-locate'
  | 'ios-location'
  | 'ios-location-outline'
  | 'ios-lock'
  | 'ios-locked'
  | 'ios-locked-outline'
  | 'ios-log-in'
  | 'ios-log-out'
  | 'ios-loop'
  | 'ios-loop-strong'
  | 'ios-magnet'
  | 'ios-mail'
  | 'ios-mail-open'
  | 'ios-mail-unread'
  | 'ios-male'
  | 'ios-man'
  | 'ios-map'
  | 'ios-medal'
  | 'ios-medical'
  | 'ios-medical-outline'
  | 'ios-medkit'
  | 'ios-medkit-outline'
  | 'ios-megaphone'
  | 'ios-menu'
  | 'ios-mic'
  | 'ios-mic-off'
  | 'ios-mic-outline'
  | 'ios-microphone'
  | 'ios-minus'
  | 'ios-minus-empty'
  | 'ios-minus-outline'
  | 'ios-monitor'
  | 'ios-monitor-outline'
  | 'ios-moon'
  | 'ios-moon-outline'
  | 'ios-more'
  | 'ios-more-outline'
  | 'ios-move'
  | 'ios-musical-note'
  | 'ios-musical-notes'
  | 'ios-navigate'
  | 'ios-navigate-outline'
  | 'ios-notifications'
  | 'ios-notifications-off'
  | 'ios-notifications-outline'
  | 'ios-nuclear'
  | 'ios-nutrition'
  | 'ios-nutrition-outline'
  | 'ios-open'
  | 'ios-options'
  | 'ios-outlet'
  | 'ios-paper'
  | 'ios-paper-outline'
  | 'ios-paper-plane'
  | 'ios-paperplane'
  | 'ios-paperplane-outline'
  | 'ios-partly-sunny'
  | 'ios-partlysunny'
  | 'ios-partlysunny-outline'
  | 'ios-pause'
  | 'ios-pause-outline'
  | 'ios-paw'
  | 'ios-paw-outline'
  | 'ios-people'
  | 'ios-people-outline'
  | 'ios-person'
  | 'ios-person-add'
  | 'ios-person-outline'
  | 'ios-personadd'
  | 'ios-personadd-outline'
  | 'ios-phone-landscape'
  | 'ios-phone-portrait'
  | 'ios-photos'
  | 'ios-photos-outline'
  | 'ios-pie'
  | 'ios-pie-outline'
  | 'ios-pin'
  | 'ios-pint'
  | 'ios-pint-outline'
  | 'ios-pizza'
  | 'ios-planet'
  | 'ios-play'
  | 'ios-play-circle'
  | 'ios-play-outline'
  | 'ios-plus'
  | 'ios-plus-empty'
  | 'ios-plus-outline'
  | 'ios-podium'
  | 'ios-power'
  | 'ios-pricetag'
  | 'ios-pricetag-outline'
  | 'ios-pricetags'
  | 'ios-pricetags-outline'
  | 'ios-print'
  | 'ios-printer'
  | 'ios-printer-outline'
  | 'ios-pulse'
  | 'ios-pulse-strong'
  | 'ios-qr-scanner'
  | 'ios-quote'
  | 'ios-radio'
  | 'ios-radio-button-off'
  | 'ios-radio-button-on'
  | 'ios-rainy'
  | 'ios-rainy-outline'
  | 'ios-recording'
  | 'ios-recording-outline'
  | 'ios-redo'
  | 'ios-redo-outline'
  | 'ios-refresh'
  | 'ios-refresh-circle'
  | 'ios-refresh-empty'
  | 'ios-refresh-outline'
  | 'ios-reload'
  | 'ios-remove'
  | 'ios-remove-circle'
  | 'ios-remove-circle-outline'
  | 'ios-reorder'
  | 'ios-repeat'
  | 'ios-resize'
  | 'ios-restaurant'
  | 'ios-return-left'
  | 'ios-return-right'
  | 'ios-reverse-camera'
  | 'ios-reverse-camera-outline'
  | 'ios-rewind'
  | 'ios-rewind-outline'
  | 'ios-ribbon'
  | 'ios-rocket'
  | 'ios-rose'
  | 'ios-rose-outline'
  | 'ios-sad'
  | 'ios-save'
  | 'ios-school'
  | 'ios-search'
  | 'ios-search-strong'
  | 'ios-send'
  | 'ios-settings'
  | 'ios-settings-strong'
  | 'ios-share'
  | 'ios-share-alt'
  | 'ios-shirt'
  | 'ios-shuffle'
  | 'ios-shuffle-strong'
  | 'ios-skip-backward'
  | 'ios-skip-forward'
  | 'ios-skipbackward'
  | 'ios-skipbackward-outline'
  | 'ios-skipforward'
  | 'ios-skipforward-outline'
  | 'ios-snow'
  | 'ios-snowy'
  | 'ios-speedometer'
  | 'ios-speedometer-outline'
  | 'ios-square'
  | 'ios-square-outline'
  | 'ios-star'
  | 'ios-star-half'
  | 'ios-star-outline'
  | 'ios-stats'
  | 'ios-stopwatch'
  | 'ios-stopwatch-outline'
  | 'ios-subway'
  | 'ios-sunny'
  | 'ios-sunny-outline'
  | 'ios-swap'
  | 'ios-switch'
  | 'ios-sync'
  | 'ios-tablet-landscape'
  | 'ios-tablet-portrait'
  | 'ios-telephone'
  | 'ios-telephone-outline'
  | 'ios-tennisball'
  | 'ios-tennisball-outline'
  | 'ios-text'
  | 'ios-thermometer'
  | 'ios-thumbs-down'
  | 'ios-thumbs-up'
  | 'ios-thunderstorm'
  | 'ios-thunderstorm-outline'
  | 'ios-time'
  | 'ios-time-outline'
  | 'ios-timer'
  | 'ios-timer-outline'
  | 'ios-today'
  | 'ios-toggle'
  | 'ios-toggle-outline'
  | 'ios-train'
  | 'ios-transgender'
  | 'ios-trash'
  | 'ios-trash-outline'
  | 'ios-trending-down'
  | 'ios-trending-up'
  | 'ios-trophy'
  | 'ios-tv'
  | 'ios-umbrella'
  | 'ios-undo'
  | 'ios-undo-outline'
  | 'ios-unlock'
  | 'ios-unlocked'
  | 'ios-unlocked-outline'
  | 'ios-upload'
  | 'ios-upload-outline'
  | 'ios-videocam'
  | 'ios-videocam-outline'
  | 'ios-volume-high'
  | 'ios-volume-low'
  | 'ios-volume-mute'
  | 'ios-volume-off'
  | 'ios-walk'
  | 'ios-wallet'
  | 'ios-warning'
  | 'ios-watch'
  | 'ios-water'
  | 'ios-wifi'
  | 'ios-wine'
  | 'ios-wineglass'
  | 'ios-wineglass-outline'
  | 'ios-woman'
  | 'ios-world'
  | 'ios-world-outline'
  | 'ipad'
  | 'iphone'
  | 'ipod'
  | 'jet'
  | 'knife'
  | 'levels'
  | 'lightbulb'
  | 'load-a'
  | 'load-b'
  | 'load-c'
  | 'load-d'
  | 'lock-combination'
  | 'locked'
  | 'logo-amazon-outline'
  | 'logo-amplify-outline'
  | 'logo-android-outline'
  | 'logo-angular-outline'
  | 'logo-apple-appstore-outline'
  | 'logo-apple-outline'
  | 'logo-bitbucket-outline'
  | 'logo-buffer-62'
  | 'logo-buffer-62-outline'
  | 'logo-buffer-63'
  | 'logo-buffer-63-outline'
  | 'logo-capacitor-outline'
  | 'logo-chrome-outline'
  | 'logo-closed-captioning-outline'
  | 'logo-codepen-outline'
  | 'logo-css3-outline'
  | 'logo-designernews-outline'
  | 'logo-dribbble-outline'
  | 'logo-dropbox-outline'
  | 'logo-edge-outline'
  | 'logo-electron-outline'
  | 'logo-euro-outline'
  | 'logo-facebook-outline'
  | 'logo-firebase-outline'
  | 'logo-firefox-outline'
  | 'logo-flickr-outline'
  | 'logo-foursquare-outline'
  | 'logo-freebsd-devil'
  | 'logo-game-controller-a'
  | 'logo-game-controller-b'
  | 'logo-github-outline'
  | 'logo-google-outline'
  | 'logo-google-playstore-outline'
  | 'logo-googleplus'
  | 'logo-hackernews-outline'
  | 'logo-html5-outline'
  | 'logo-instagram-outline'
  | 'logo-ionic-outline'
  | 'logo-ionitron-outline'
  | 'logo-javascript-outline'
  | 'logo-laravel-outline'
  | 'logo-linkedin-outline'
  | 'logo-markdown-outline'
  | 'logo-model-s'
  | 'logo-no-smoking-outline'
  | 'logo-nodejs-outline'
  | 'logo-npm-outline'
  | 'logo-octocat-outline'
  | 'logo-pinterest-outline'
  | 'logo-playstation-outline'
  | 'logo-polymer'
  | 'logo-pwa-outline'
  | 'logo-python-outline'
  | 'logo-react-outline'
  | 'logo-reddit-outline'
  | 'logo-rss-outline'
  | 'logo-sass-outline'
  | 'logo-skype-outline'
  | 'logo-slack-outline'
  | 'logo-snapchat-outline'
  | 'logo-stackoverflow-outline'
  | 'logo-steam-outline'
  | 'logo-stencil-outline'
  | 'logo-tumblr-outline'
  | 'logo-tux-outline'
  | 'logo-twitch-outline'
  | 'logo-twitter-outline'
  | 'logo-usd-outline'
  | 'logo-vimeo-outline'
  | 'logo-vk-outline'
  | 'logo-vue-outline'
  | 'logo-web-component-outline'
  | 'logo-whatsapp-outline'
  | 'logo-windows-outline'
  | 'logo-wordpress-outline'
  | 'logo-xbox-outline'
  | 'logo-xing-outline'
  | 'logo-yahoo-outline'
  | 'logo-yen-outline'
  | 'logo-youtube-outline'
  | 'loop'
  | 'mail-notification'
  | 'mail-notification-outline'
  | 'mail-notification-sharp'
  | 'md-add'
  | 'md-add-circle'
  | 'md-add-circle-outline'
  | 'md-airplane'
  | 'md-alarm'
  | 'md-albums'
  | 'md-alert'
  | 'md-american-football'
  | 'md-analytics'
  | 'md-aperture'
  | 'md-apps'
  | 'md-appstore'
  | 'md-archive'
  | 'md-arrow-back'
  | 'md-arrow-down'
  | 'md-arrow-dropdown'
  | 'md-arrow-dropdown-circle'
  | 'md-arrow-dropleft'
  | 'md-arrow-dropleft-circle'
  | 'md-arrow-dropright'
  | 'md-arrow-dropright-circle'
  | 'md-arrow-dropup'
  | 'md-arrow-dropup-circle'
  | 'md-arrow-forward'
  | 'md-arrow-round-back'
  | 'md-arrow-round-down'
  | 'md-arrow-round-forward'
  | 'md-arrow-round-up'
  | 'md-arrow-up'
  | 'md-at'
  | 'md-attach'
  | 'md-backspace'
  | 'md-barcode'
  | 'md-baseball'
  | 'md-basket'
  | 'md-basketball'
  | 'md-battery-charging'
  | 'md-battery-dead'
  | 'md-battery-full'
  | 'md-beaker'
  | 'md-bed'
  | 'md-beer'
  | 'md-bicycle'
  | 'md-bluetooth'
  | 'md-boat'
  | 'md-body'
  | 'md-bonfire'
  | 'md-book'
  | 'md-bookmark'
  | 'md-bookmarks'
  | 'md-bowtie'
  | 'md-briefcase'
  | 'md-browsers'
  | 'md-brush'
  | 'md-bug'
  | 'md-build'
  | 'md-bulb'
  | 'md-bus'
  | 'md-business'
  | 'md-cafe'
  | 'md-calculator'
  | 'md-calendar'
  | 'md-call'
  | 'md-camera'
  | 'md-car'
  | 'md-card'
  | 'md-cart'
  | 'md-cash'
  | 'md-cellular'
  | 'md-chatboxes'
  | 'md-chatbubbles'
  | 'md-checkbox'
  | 'md-checkbox-outline'
  | 'md-checkmark'
  | 'md-checkmark-circle'
  | 'md-checkmark-circle-outline'
  | 'md-clipboard'
  | 'md-clock'
  | 'md-close'
  | 'md-close-circle'
  | 'md-close-circle-outline'
  | 'md-cloud'
  | 'md-cloud-circle'
  | 'md-cloud-done'
  | 'md-cloud-download'
  | 'md-cloud-outline'
  | 'md-cloud-upload'
  | 'md-cloudy'
  | 'md-cloudy-night'
  | 'md-code'
  | 'md-code-download'
  | 'md-code-working'
  | 'md-cog'
  | 'md-color-fill'
  | 'md-color-filter'
  | 'md-color-palette'
  | 'md-color-wand'
  | 'md-compass'
  | 'md-construct'
  | 'md-contact'
  | 'md-contacts'
  | 'md-contract'
  | 'md-contrast'
  | 'md-copy'
  | 'md-create'
  | 'md-crop'
  | 'md-cube'
  | 'md-cut'
  | 'md-desktop'
  | 'md-disc'
  | 'md-document'
  | 'md-done-all'
  | 'md-download'
  | 'md-easel'
  | 'md-egg'
  | 'md-exit'
  | 'md-expand'
  | 'md-eye'
  | 'md-eye-off'
  | 'md-fastforward'
  | 'md-female'
  | 'md-filing'
  | 'md-film'
  | 'md-finger-print'
  | 'md-fitness'
  | 'md-flag'
  | 'md-flame'
  | 'md-flash'
  | 'md-flash-off'
  | 'md-flashlight'
  | 'md-flask'
  | 'md-flower'
  | 'md-folder'
  | 'md-folder-open'
  | 'md-football'
  | 'md-funnel'
  | 'md-gift'
  | 'md-git-branch'
  | 'md-git-commit'
  | 'md-git-compare'
  | 'md-git-merge'
  | 'md-git-network'
  | 'md-git-pull-request'
  | 'md-glasses'
  | 'md-globe'
  | 'md-grid'
  | 'md-hammer'
  | 'md-hand'
  | 'md-happy'
  | 'md-headset'
  | 'md-heart'
  | 'md-heart-dislike'
  | 'md-heart-empty'
  | 'md-heart-half'
  | 'md-help'
  | 'md-help-buoy'
  | 'md-help-circle'
  | 'md-help-circle-outline'
  | 'md-home'
  | 'md-hourglass'
  | 'md-ice-cream'
  | 'md-image'
  | 'md-images'
  | 'md-infinite'
  | 'md-information'
  | 'md-information-circle'
  | 'md-information-circle-outline'
  | 'md-jet'
  | 'md-journal'
  | 'md-key'
  | 'md-keypad'
  | 'md-laptop'
  | 'md-leaf'
  | 'md-link'
  | 'md-list'
  | 'md-list-box'
  | 'md-locate'
  | 'md-lock'
  | 'md-log-in'
  | 'md-log-out'
  | 'md-magnet'
  | 'md-mail'
  | 'md-mail-open'
  | 'md-mail-unread'
  | 'md-male'
  | 'md-man'
  | 'md-map'
  | 'md-medal'
  | 'md-medical'
  | 'md-medkit'
  | 'md-megaphone'
  | 'md-menu'
  | 'md-mic'
  | 'md-mic-off'
  | 'md-microphone'
  | 'md-moon'
  | 'md-more'
  | 'md-move'
  | 'md-musical-note'
  | 'md-musical-notes'
  | 'md-navigate'
  | 'md-notifications'
  | 'md-notifications-off'
  | 'md-notifications-outline'
  | 'md-nuclear'
  | 'md-nutrition'
  | 'md-open'
  | 'md-options'
  | 'md-outlet'
  | 'md-paper'
  | 'md-paper-plane'
  | 'md-partly-sunny'
  | 'md-pause'
  | 'md-paw'
  | 'md-people'
  | 'md-person'
  | 'md-person-add'
  | 'md-phone-landscape'
  | 'md-phone-portrait'
  | 'md-photos'
  | 'md-pie'
  | 'md-pin'
  | 'md-pint'
  | 'md-pizza'
  | 'md-planet'
  | 'md-play'
  | 'md-play-circle'
  | 'md-podium'
  | 'md-power'
  | 'md-pricetag'
  | 'md-pricetags'
  | 'md-print'
  | 'md-pulse'
  | 'md-qr-scanner'
  | 'md-quote'
  | 'md-radio'
  | 'md-radio-button-off'
  | 'md-radio-button-on'
  | 'md-rainy'
  | 'md-recording'
  | 'md-redo'
  | 'md-refresh'
  | 'md-refresh-circle'
  | 'md-remove'
  | 'md-remove-circle'
  | 'md-remove-circle-outline'
  | 'md-reorder'
  | 'md-repeat'
  | 'md-resize'
  | 'md-restaurant'
  | 'md-return-left'
  | 'md-return-right'
  | 'md-reverse-camera'
  | 'md-rewind'
  | 'md-ribbon'
  | 'md-rocket'
  | 'md-rose'
  | 'md-sad'
  | 'md-save'
  | 'md-school'
  | 'md-search'
  | 'md-send'
  | 'md-settings'
  | 'md-share'
  | 'md-share-alt'
  | 'md-shirt'
  | 'md-shuffle'
  | 'md-skip-backward'
  | 'md-skip-forward'
  | 'md-snow'
  | 'md-speedometer'
  | 'md-square'
  | 'md-square-outline'
  | 'md-star'
  | 'md-star-half'
  | 'md-star-outline'
  | 'md-stats'
  | 'md-stopwatch'
  | 'md-subway'
  | 'md-sunny'
  | 'md-swap'
  | 'md-switch'
  | 'md-sync'
  | 'md-tablet-landscape'
  | 'md-tablet-portrait'
  | 'md-tennisball'
  | 'md-text'
  | 'md-thermometer'
  | 'md-thumbs-down'
  | 'md-thumbs-up'
  | 'md-thunderstorm'
  | 'md-time'
  | 'md-timer'
  | 'md-today'
  | 'md-train'
  | 'md-transgender'
  | 'md-trash'
  | 'md-trending-down'
  | 'md-trending-up'
  | 'md-trophy'
  | 'md-tv'
  | 'md-umbrella'
  | 'md-undo'
  | 'md-unlock'
  | 'md-videocam'
  | 'md-volume-high'
  | 'md-volume-low'
  | 'md-volume-mute'
  | 'md-volume-off'
  | 'md-walk'
  | 'md-wallet'
  | 'md-warning'
  | 'md-watch'
  | 'md-water'
  | 'md-wifi'
  | 'md-wine'
  | 'md-woman'
  | 'merge'
  | 'mic-a'
  | 'mic-b'
  | 'mic-c'
  | 'minus'
  | 'minus-circled'
  | 'minus-round'
  | 'model-s'
  | 'monitor'
  | 'more'
  | 'mouse'
  | 'music-note'
  | 'navicon'
  | 'navicon-round'
  | 'network'
  | 'no-smoking'
  | 'notifcations'
  | 'outlet'
  | 'paintbrush'
  | 'paintbucket'
  | 'paper-airplane'
  | 'paperclip'
  | 'person-stalker'
  | 'pie-graph'
  | 'pinpoint'
  | 'plane'
  | 'playstation'
  | 'plus'
  | 'plus-circled'
  | 'plus-round'
  | 'pound'
  | 'printer'
  | 'pull-request'
  | 'qr-scanner'
  | 'quote'
  | 'radio-off'
  | 'radio-off-outline'
  | 'radio-off-sharp'
  | 'radio-on'
  | 'radio-on-outline'
  | 'radio-on-sharp'
  | 'radio-waves'
  | 'record'
  | 'reply'
  | 'reply-all'
  | 'ribbon-a'
  | 'ribbon-b'
  | 'scissors'
  | 'skip-backward'
  | 'skip-forward'
  | 'social-android'
  | 'social-android-outline'
  | 'social-angular'
  | 'social-angular-outline'
  | 'social-apple'
  | 'social-apple-outline'
  | 'social-bitcoin'
  | 'social-bitcoin-outline'
  | 'social-buffer'
  | 'social-buffer-outline'
  | 'social-chrome'
  | 'social-chrome-outline'
  | 'social-codepen'
  | 'social-codepen-outline'
  | 'social-css3'
  | 'social-css3-outline'
  | 'social-designernews'
  | 'social-designernews-outline'
  | 'social-dribbble'
  | 'social-dribbble-outline'
  | 'social-dropbox'
  | 'social-dropbox-outline'
  | 'social-euro'
  | 'social-euro-outline'
  | 'social-facebook'
  | 'social-facebook-outline'
  | 'social-foursquare'
  | 'social-foursquare-outline'
  | 'social-freebsd-devil'
  | 'social-github'
  | 'social-github-outline'
  | 'social-google'
  | 'social-google-outline'
  | 'social-googleplus'
  | 'social-googleplus-outline'
  | 'social-hackernews'
  | 'social-hackernews-outline'
  | 'social-html5'
  | 'social-html5-outline'
  | 'social-instagram'
  | 'social-instagram-outline'
  | 'social-javascript'
  | 'social-javascript-outline'
  | 'social-linkedin'
  | 'social-linkedin-outline'
  | 'social-markdown'
  | 'social-nodejs'
  | 'social-octocat'
  | 'social-pinterest'
  | 'social-pinterest-outline'
  | 'social-python'
  | 'social-reddit'
  | 'social-reddit-outline'
  | 'social-rss'
  | 'social-rss-outline'
  | 'social-sass'
  | 'social-skype'
  | 'social-skype-outline'
  | 'social-snapchat'
  | 'social-snapchat-outline'
  | 'social-tumblr'
  | 'social-tumblr-outline'
  | 'social-tux'
  | 'social-twitch'
  | 'social-twitch-outline'
  | 'social-twitter'
  | 'social-twitter-outline'
  | 'social-usd'
  | 'social-usd-outline'
  | 'social-vimeo'
  | 'social-vimeo-outline'
  | 'social-whatsapp'
  | 'social-whatsapp-outline'
  | 'social-windows'
  | 'social-windows-outline'
  | 'social-wordpress'
  | 'social-wordpress-outline'
  | 'social-yahoo'
  | 'social-yahoo-outline'
  | 'social-yen'
  | 'social-yen-outline'
  | 'social-youtube'
  | 'social-youtube-outline'
  | 'soup-can'
  | 'soup-can-outline'
  | 'speakerphone'
  | 'spoon'
  | 'stats-bars'
  | 'steam'
  | 'switch'
  | 'switch-outline'
  | 'switch-sharp'
  | 'thumbsdown'
  | 'thumbsup'
  | 'toggle-filled'
  | 'trash-a'
  | 'trash-b'
  | 'tshirt'
  | 'tshirt-outline'
  | 'university'
  | 'unlocked'
  | 'upload'
  | 'usb'
  | 'videocamera'
  | 'wand'
  | 'waterdrop'
  | 'wineglass'
  | 'wrench'
  | 'xbox';

export type IonIconName = keyof typeof ionIconNames | IonIconAlias;
export const Ion = createIconSet<IonIconName>('ion', ionIconNames);
