/**
 * Iwwa Icon Set
 * @see https://icon-sets.iconify.design/iwwa/
 *
 * Auto-generated - do not edit manually
 */

import { createIconSet } from '../createIconSet';

const iwwaIconNames = {
  add: true,
  'add-15m': true,
  'add-1d': true,
  'add-1m': true,
  'add-1w': true,
  'add-1y': true,
  alarm: true,
  'alarm-o': true,
  alert: true,
  'angle-left': true,
  'arrow-down': true,
  'arrow-left': true,
  'arrow-right': true,
  'arrow-up': true,
  assign: true,
  bad: true,
  'bad-o': true,
  box: true,
  calendar: true,
  chart: true,
  'chart-style1': true,
  'chart-style2': true,
  'chart-style3': true,
  'chart-style4': true,
  circumflex: true,
  clone: true,
  close: true,
  'close-braket': true,
  co2: true,
  confront: true,
  'connection-o': true,
  'consumption-o': true,
  csv: true,
  danger: true,
  dashboard: true,
  delete: true,
  delta: true,
  divide: true,
  'drag-drop': true,
  duplicate: true,
  edit: true,
  expand: true,
  export: true,
  'file-csv': true,
  'file-pdf': true,
  'file-png': true,
  'file-xsl': true,
  filter: true,
  flag: true,
  gauge: true,
  good: true,
  'good-o': true,
  help: true,
  history: true,
  humidity: true,
  info: true,
  information: true,
  'innowatio-logo': true,
  lightbulb: true,
  'list-favourite': true,
  lock: true,
  logout: true,
  map: true,
  menu: true,
  merge: true,
  'middle-o': true,
  middling: true,
  minus: true,
  monitoring: true,
  month: true,
  multiply: true,
  'number-asc': true,
  'number-desc': true,
  'open-braket': true,
  option: true,
  'option-horizontal': true,
  pause: true,
  percentage: true,
  pinch: true,
  png: true,
  power: true,
  'remote-control-o': true,
  'remove-15m': true,
  'remove-1d': true,
  'remove-1m': true,
  'remove-1w': true,
  'remove-1y': true,
  reset: true,
  search: true,
  settings: true,
  'sort-by': true,
  'square-root': true,
  star: true,
  'star-o': true,
  swipe: true,
  tag: true,
  'text-asc': true,
  'text-desc': true,
  thermometer: true,
  trash: true,
  upload: true,
  user: true,
  'user-functions': true,
  week: true,
  year: true,
} as const;

export type IwwaIconName = keyof typeof iwwaIconNames;
export const Iwwa = createIconSet<IwwaIconName>('iwwa', iwwaIconNames);
