/**
 * Maki Icon Set
 * @see https://icon-sets.iconify.design/maki/
 *
 * Auto-generated - do not edit manually
 */

import { createIconSet } from '../createIconSet';

const makiIconNames = {
  aerialway: true,
  airfield: true,
  airport: true,
  'alcohol-shop': true,
  'american-football': true,
  'amusement-park': true,
  'animal-shelter': true,
  aquarium: true,
  arrow: true,
  'art-gallery': true,
  attraction: true,
  bakery: true,
  bank: true,
  'bank-jp': true,
  bar: true,
  barrier: true,
  baseball: true,
  basketball: true,
  bbq: true,
  beach: true,
  beer: true,
  bicycle: true,
  'bicycle-share': true,
  'blood-bank': true,
  'bowling-alley': true,
  bridge: true,
  building: true,
  'building-alt1': true,
  bus: true,
  cafe: true,
  campsite: true,
  car: true,
  'car-rental': true,
  'car-repair': true,
  casino: true,
  castle: true,
  'castle-jp': true,
  caution: true,
  cemetery: true,
  'cemetery-jp': true,
  'charging-station': true,
  cinema: true,
  circle: true,
  'circle-stroked': true,
  city: true,
  'clothing-store': true,
  college: true,
  'college-jp': true,
  commercial: true,
  'communications-tower': true,
  confectionery: true,
  construction: true,
  convenience: true,
  cricket: true,
  cross: true,
  dam: true,
  danger: true,
  defibrillator: true,
  dentist: true,
  diamond: true,
  doctor: true,
  'dog-park': true,
  'drinking-water': true,
  elevator: true,
  embassy: true,
  'emergency-phone': true,
  entrance: true,
  'entrance-alt1': true,
  farm: true,
  'fast-food': true,
  fence: true,
  ferry: true,
  'ferry-jp': true,
  'fire-station': true,
  'fire-station-jp': true,
  'fitness-centre': true,
  florist: true,
  fuel: true,
  furniture: true,
  gaming: true,
  garden: true,
  'garden-centre': true,
  gate: true,
  gift: true,
  globe: true,
  golf: true,
  grocery: true,
  hairdresser: true,
  harbor: true,
  hardware: true,
  heart: true,
  heliport: true,
  'highway-rest-area': true,
  historic: true,
  home: true,
  'horse-riding': true,
  hospital: true,
  'hospital-jp': true,
  'hot-spring': true,
  'ice-cream': true,
  industry: true,
  information: true,
  'jewelry-store': true,
  karaoke: true,
  landmark: true,
  'landmark-jp': true,
  landuse: true,
  laundry: true,
  library: true,
  'lift-gate': true,
  lighthouse: true,
  'lighthouse-jp': true,
  lodging: true,
  logging: true,
  marae: true,
  marker: true,
  'marker-stroked': true,
  'mobile-phone': true,
  monument: true,
  'monument-jp': true,
  mountain: true,
  museum: true,
  music: true,
  natural: true,
  nightclub: true,
  'observation-tower': true,
  optician: true,
  paint: true,
  park: true,
  'park-alt1': true,
  parking: true,
  'parking-garage': true,
  'parking-paid': true,
  pharmacy: true,
  'picnic-site': true,
  pitch: true,
  'place-of-worship': true,
  playground: true,
  police: true,
  'police-jp': true,
  post: true,
  'post-jp': true,
  prison: true,
  racetrack: true,
  'racetrack-boat': true,
  'racetrack-cycling': true,
  'racetrack-horse': true,
  rail: true,
  'rail-light': true,
  'rail-metro': true,
  'ranger-station': true,
  recycling: true,
  'religious-buddhist': true,
  'religious-christian': true,
  'religious-jewish': true,
  'religious-muslim': true,
  'religious-shinto': true,
  'residential-community': true,
  restaurant: true,
  'restaurant-bbq': true,
  'restaurant-noodle': true,
  'restaurant-pizza': true,
  'restaurant-seafood': true,
  'restaurant-sushi': true,
  'road-accident': true,
  roadblock: true,
  rocket: true,
  school: true,
  'school-jp': true,
  scooter: true,
  shelter: true,
  shoe: true,
  shop: true,
  skateboard: true,
  skiing: true,
  slaughterhouse: true,
  slipway: true,
  snowmobile: true,
  soccer: true,
  square: true,
  'square-stroked': true,
  stadium: true,
  star: true,
  'star-stroked': true,
  suitcase: true,
  swimming: true,
  'table-tennis': true,
  taxi: true,
  teahouse: true,
  telephone: true,
  tennis: true,
  terminal: true,
  theatre: true,
  toilet: true,
  toll: true,
  town: true,
  'town-hall': true,
  triangle: true,
  'triangle-stroked': true,
  tunnel: true,
  veterinary: true,
  viewpoint: true,
  village: true,
  volcano: true,
  volleyball: true,
  warehouse: true,
  'waste-basket': true,
  watch: true,
  water: true,
  waterfall: true,
  watermill: true,
  wetland: true,
  wheelchair: true,
  windmill: true,
  zoo: true,
} as const;

/**
 * Names upstream has renamed or hidden. Still served, still typed, and
 * deliberately not in the object above: a union compiles to nothing, while
 * every entry in that object ships to every application.
 */
type MakiIconAlias =
  | 'aerialway-11'
  | 'aerialway-15'
  | 'airfield-11'
  | 'airfield-15'
  | 'airport-11'
  | 'airport-15'
  | 'alcohol-shop-11'
  | 'alcohol-shop-15'
  | 'america-football-11'
  | 'america-football-15'
  | 'american-football-11'
  | 'american-football-15'
  | 'amusement-park-11'
  | 'amusement-park-15'
  | 'aquarium-11'
  | 'aquarium-15'
  | 'art-gallery-11'
  | 'art-gallery-15'
  | 'attraction-11'
  | 'attraction-15'
  | 'bakery-11'
  | 'bakery-15'
  | 'bank-11'
  | 'bank-15'
  | 'bank-jp-11'
  | 'bank-jp-15'
  | 'bar-11'
  | 'bar-15'
  | 'barrier-11'
  | 'barrier-15'
  | 'baseball-11'
  | 'baseball-15'
  | 'basketball-11'
  | 'basketball-15'
  | 'bbq-11'
  | 'bbq-15'
  | 'beach-11'
  | 'beach-15'
  | 'beer-11'
  | 'beer-15'
  | 'bicycle-11'
  | 'bicycle-15'
  | 'bicycle-share-11'
  | 'bicycle-share-15'
  | 'blood-bank-11'
  | 'blood-bank-15'
  | 'bowling-alley-11'
  | 'bowling-alley-15'
  | 'bridge-11'
  | 'bridge-15'
  | 'buddhism-11'
  | 'buddhism-15'
  | 'building-11'
  | 'building-15'
  | 'building-alt1-11'
  | 'building-alt1-15'
  | 'bus-11'
  | 'bus-15'
  | 'cafe-11'
  | 'cafe-15'
  | 'campsite-11'
  | 'campsite-15'
  | 'car-11'
  | 'car-15'
  | 'car-rental-11'
  | 'car-rental-15'
  | 'car-repair-11'
  | 'car-repair-15'
  | 'casino-11'
  | 'casino-15'
  | 'castle-11'
  | 'castle-15'
  | 'castle-jp-11'
  | 'castle-jp-15'
  | 'cemetery-11'
  | 'cemetery-15'
  | 'cemetery-jp-11'
  | 'cemetery-jp-15'
  | 'charging-station-11'
  | 'charging-station-15'
  | 'cinema-11'
  | 'cinema-15'
  | 'circle-11'
  | 'circle-15'
  | 'circle-stroked-11'
  | 'circle-stroked-15'
  | 'city-11'
  | 'city-15'
  | 'clothing-store-11'
  | 'clothing-store-15'
  | 'college-11'
  | 'college-15'
  | 'college-jp-11'
  | 'college-jp-15'
  | 'commercial-11'
  | 'commercial-15'
  | 'communications-tower-11'
  | 'communications-tower-15'
  | 'confectionary-11'
  | 'confectionary-15'
  | 'confectionery-11'
  | 'confectionery-15'
  | 'convenience-11'
  | 'convenience-15'
  | 'convenience-store-11'
  | 'convenience-store-15'
  | 'cricket-11'
  | 'cricket-15'
  | 'cross-11'
  | 'cross-15'
  | 'dam-11'
  | 'dam-15'
  | 'danger-11'
  | 'danger-15'
  | 'defibrillator-11'
  | 'defibrillator-15'
  | 'dentist-11'
  | 'dentist-15'
  | 'doctor-11'
  | 'doctor-15'
  | 'dog-park-11'
  | 'dog-park-15'
  | 'drinking-water-11'
  | 'drinking-water-15'
  | 'embassy-11'
  | 'embassy-15'
  | 'emergency-phone-11'
  | 'emergency-phone-15'
  | 'entrance-11'
  | 'entrance-15'
  | 'entrance-alt1-11'
  | 'entrance-alt1-15'
  | 'farm-11'
  | 'farm-15'
  | 'fast-food-11'
  | 'fast-food-15'
  | 'fence-11'
  | 'fence-15'
  | 'ferry-11'
  | 'ferry-15'
  | 'fire-station-11'
  | 'fire-station-15'
  | 'fire-station-jp-11'
  | 'fire-station-jp-15'
  | 'fitness-center-11'
  | 'fitness-center-15'
  | 'fitness-centre-11'
  | 'fitness-centre-15'
  | 'florist-11'
  | 'florist-15'
  | 'fuel-11'
  | 'fuel-15'
  | 'furniture-11'
  | 'furniture-15'
  | 'gaming-11'
  | 'gaming-15'
  | 'garden-11'
  | 'garden-15'
  | 'garden-center-11'
  | 'garden-center-15'
  | 'garden-centre-11'
  | 'garden-centre-15'
  | 'gift-11'
  | 'gift-15'
  | 'globe-11'
  | 'globe-15'
  | 'golf-11'
  | 'golf-15'
  | 'grocery-11'
  | 'grocery-15'
  | 'hairdresser-11'
  | 'hairdresser-15'
  | 'harbor-11'
  | 'harbor-15'
  | 'hardware-11'
  | 'hardware-15'
  | 'heart-11'
  | 'heart-15'
  | 'heliport-11'
  | 'heliport-15'
  | 'home-11'
  | 'home-15'
  | 'horse-riding-11'
  | 'horse-riding-15'
  | 'hospital-11'
  | 'hospital-15'
  | 'hospital-jp-11'
  | 'hospital-jp-15'
  | 'ice-cream-11'
  | 'ice-cream-15'
  | 'industry-11'
  | 'industry-15'
  | 'information-11'
  | 'information-15'
  | 'jewelry-11'
  | 'jewelry-15'
  | 'jewelry-store-11'
  | 'jewelry-store-15'
  | 'karaoke-11'
  | 'karaoke-15'
  | 'landmark-11'
  | 'landmark-15'
  | 'landmark-jp-11'
  | 'landmark-jp-15'
  | 'landuse-11'
  | 'landuse-15'
  | 'laundry-11'
  | 'laundry-15'
  | 'library-11'
  | 'library-15'
  | 'lighthouse-11'
  | 'lighthouse-15'
  | 'lodging-11'
  | 'lodging-15'
  | 'logging-11'
  | 'logging-15'
  | 'marker-11'
  | 'marker-15'
  | 'marker-stroked-11'
  | 'marker-stroked-15'
  | 'mobile-phone-11'
  | 'mobile-phone-15'
  | 'monument-11'
  | 'monument-15'
  | 'mountain-11'
  | 'mountain-15'
  | 'museum-11'
  | 'museum-15'
  | 'music-11'
  | 'music-15'
  | 'natural-11'
  | 'natural-15'
  | 'optician-11'
  | 'optician-15'
  | 'paint-11'
  | 'paint-15'
  | 'park-11'
  | 'park-15'
  | 'park-alt1-11'
  | 'park-alt1-15'
  | 'parking-11'
  | 'parking-15'
  | 'parking-garage-11'
  | 'parking-garage-15'
  | 'pharmacy-11'
  | 'pharmacy-15'
  | 'picnic-site-11'
  | 'picnic-site-15'
  | 'pitch-11'
  | 'pitch-15'
  | 'place-of-worship-11'
  | 'place-of-worship-15'
  | 'playground-11'
  | 'playground-15'
  | 'police-11'
  | 'police-15'
  | 'police-jp-11'
  | 'police-jp-15'
  | 'post-11'
  | 'post-15'
  | 'post-jp-11'
  | 'post-jp-15'
  | 'prison-11'
  | 'prison-15'
  | 'rail-11'
  | 'rail-15'
  | 'rail-light-11'
  | 'rail-light-15'
  | 'rail-metro-11'
  | 'rail-metro-15'
  | 'ranger-station-11'
  | 'ranger-station-15'
  | 'recycling-11'
  | 'recycling-15'
  | 'religious-buddhist-11'
  | 'religious-buddhist-15'
  | 'religious-christian-11'
  | 'religious-christian-15'
  | 'religious-jewish-11'
  | 'religious-jewish-15'
  | 'religious-muslim-11'
  | 'religious-muslim-15'
  | 'religious-shinto-11'
  | 'religious-shinto-15'
  | 'residential-community-11'
  | 'residential-community-15'
  | 'restaurant-11'
  | 'restaurant-15'
  | 'restaurant-noodle-11'
  | 'restaurant-noodle-15'
  | 'restaurant-pizza-11'
  | 'restaurant-pizza-15'
  | 'restaurant-seafood-11'
  | 'restaurant-seafood-15'
  | 'roadblock-11'
  | 'roadblock-15'
  | 'rocket-11'
  | 'rocket-15'
  | 'school-11'
  | 'school-15'
  | 'school-jp-11'
  | 'school-jp-15'
  | 'scooter-11'
  | 'scooter-15'
  | 'shelter-11'
  | 'shelter-15'
  | 'shoe-11'
  | 'shoe-15'
  | 'shop-11'
  | 'shop-15'
  | 'skateboard-11'
  | 'skateboard-15'
  | 'skiing-11'
  | 'skiing-15'
  | 'slaughterhouse-11'
  | 'slaughterhouse-15'
  | 'slipway-11'
  | 'slipway-15'
  | 'snowmobile-11'
  | 'snowmobile-15'
  | 'soccer-11'
  | 'soccer-15'
  | 'square-11'
  | 'square-15'
  | 'square-stroked-11'
  | 'square-stroked-15'
  | 'stadium-11'
  | 'stadium-15'
  | 'star-11'
  | 'star-15'
  | 'star-stroked-11'
  | 'star-stroked-15'
  | 'suitcase-11'
  | 'suitcase-15'
  | 'sushi-11'
  | 'sushi-15'
  | 'swimming-11'
  | 'swimming-15'
  | 'table-tennis-11'
  | 'table-tennis-15'
  | 'teahouse-11'
  | 'teahouse-15'
  | 'telephone-11'
  | 'telephone-15'
  | 'tennis-11'
  | 'tennis-15'
  | 'theatre-11'
  | 'theatre-15'
  | 'toilet-11'
  | 'toilet-15'
  | 'toll-booth'
  | 'town-11'
  | 'town-15'
  | 'town-hall-11'
  | 'town-hall-15'
  | 'triangle-11'
  | 'triangle-15'
  | 'triangle-stroked-11'
  | 'triangle-stroked-15'
  | 'veterinary-11'
  | 'veterinary-15'
  | 'viewpoint-11'
  | 'viewpoint-15'
  | 'village-11'
  | 'village-15'
  | 'volcano-11'
  | 'volcano-15'
  | 'volleyball-11'
  | 'volleyball-15'
  | 'warehouse-11'
  | 'warehouse-15'
  | 'waste-basket-11'
  | 'waste-basket-15'
  | 'watch-11'
  | 'watch-15'
  | 'water-11'
  | 'water-15'
  | 'waterfall-11'
  | 'waterfall-15'
  | 'watermill-11'
  | 'watermill-15'
  | 'wetland-11'
  | 'wetland-15'
  | 'wheelchair-11'
  | 'wheelchair-15'
  | 'windmill-11'
  | 'windmill-15'
  | 'zoo-11'
  | 'zoo-15';

export type MakiIconName = keyof typeof makiIconNames | MakiIconAlias;
export const Maki = createIconSet<MakiIconName>('maki', makiIconNames);
