/**
 * MaterialIconTheme Icon Set
 * @see https://icon-sets.iconify.design/material-icon-theme/
 *
 * Auto-generated - do not edit manually
 */

import { createIconSet } from '../createIconSet';

const material_icon_themeIconNames = {
  _3d: '3d',
  abap: true,
  abc: true,
  actionscript: true,
  ada: true,
  'adobe-illustrator': true,
  'adobe-illustrator-light': true,
  'adobe-photoshop': true,
  'adobe-photoshop-light': true,
  'adobe-swc': true,
  adonis: true,
  advpl: true,
  agent: true,
  amplify: true,
  android: true,
  angular: true,
  antlr: true,
  apiblueprint: true,
  apollo: true,
  applescript: true,
  'apps-script': true,
  appveyor: true,
  appwrite: true,
  architecture: true,
  arduino: true,
  asciidoc: true,
  assembly: true,
  astro: true,
  'astro-config': true,
  astyle: true,
  audio: true,
  aurelia: true,
  authors: true,
  auto: true,
  'auto-light': true,
  autohotkey: true,
  autoit: true,
  azure: true,
  'azure-pipelines': true,
  babel: true,
  ballerina: true,
  bashly: true,
  'bashly-hook': true,
  bazel: true,
  bbx: true,
  beancount: true,
  'bench-js': true,
  'bench-jsx': true,
  'bench-ts': true,
  bibliography: true,
  'bibtex-style': true,
  bicep: true,
  biome: true,
  bitbucket: true,
  bithound: true,
  blender: true,
  blink: true,
  'blink-light': true,
  blitz: true,
  bower: true,
  brainfuck: true,
  browserlist: true,
  'browserlist-light': true,
  bruno: true,
  buck: true,
  bucklescript: true,
  buildkite: true,
  bun: true,
  'bun-light': true,
  c: true,
  c3: true,
  cabal: true,
  caddy: true,
  cadence: true,
  cairo: true,
  cake: true,
  capacitor: true,
  capnp: true,
  cbx: true,
  cds: true,
  certificate: true,
  changelog: true,
  chess: true,
  'chess-light': true,
  chromatic: true,
  chrome: true,
  circleci: true,
  'circleci-light': true,
  citation: true,
  clangd: true,
  claude: true,
  cline: true,
  clojure: true,
  cloudfoundry: true,
  cmake: true,
  coala: true,
  cobol: true,
  coconut: true,
  'code-climate': true,
  'code-climate-light': true,
  codecov: true,
  codeowners: true,
  'coderabbit-ai': true,
  coffee: true,
  coldfusion: true,
  coloredpetrinets: true,
  command: true,
  commitizen: true,
  commitlint: true,
  concourse: true,
  conduct: true,
  console: true,
  contentlayer: true,
  context: true,
  contributing: true,
  controller: true,
  copilot: true,
  'copilot-light': true,
  cpp: true,
  craco: true,
  credits: true,
  crystal: true,
  'crystal-light': true,
  csharp: true,
  css: true,
  'css-map': true,
  cucumber: true,
  cuda: true,
  cue: true,
  cursor: true,
  'cursor-light': true,
  cypress: true,
  d: true,
  dart: true,
  'dart-generated': true,
  database: true,
  deepsource: true,
  denizenscript: true,
  deno: true,
  'deno-light': true,
  dependabot: true,
  'dependencies-update': true,
  dhall: true,
  diff: true,
  dinophp: true,
  disc: true,
  django: true,
  dll: true,
  docker: true,
  'doctex-installer': true,
  document: true,
  dotjs: true,
  drawio: true,
  drizzle: true,
  drone: true,
  'drone-light': true,
  duc: true,
  dune: true,
  edge: true,
  editorconfig: true,
  ejs: true,
  elixir: true,
  elm: true,
  email: true,
  ember: true,
  epub: true,
  erlang: true,
  esbuild: true,
  eslint: true,
  excalidraw: true,
  exe: true,
  expo: true,
  'expo-light': true,
  fastlane: true,
  favicon: true,
  figma: true,
  firebase: true,
  flash: true,
  flow: true,
  'folder-admin': true,
  'folder-android': true,
  'folder-angular': true,
  'folder-animation': true,
  'folder-ansible': true,
  'folder-api': true,
  'folder-apollo': true,
  'folder-app': true,
  'folder-appwrite': true,
  'folder-archive': true,
  'folder-assembly': true,
  'folder-astro': true,
  'folder-atom': true,
  'folder-attachment': true,
  'folder-audio': true,
  'folder-aurelia': true,
  'folder-aws': true,
  'folder-azure-pipelines': true,
  'folder-backup': true,
  'folder-base': true,
  'folder-batch': true,
  'folder-benchmark': true,
  'folder-bibliography': true,
  'folder-bicep': true,
  'folder-blender': true,
  'folder-bloc': true,
  'folder-bower': true,
  'folder-buildkite': true,
  'folder-cart': true,
  'folder-changesets': true,
  'folder-ci': true,
  'folder-circleci': true,
  'folder-class': true,
  'folder-claude': true,
  'folder-client': true,
  'folder-cline': true,
  'folder-cloud-functions': true,
  'folder-cloudflare': true,
  'folder-cluster': true,
  'folder-cobol': true,
  'folder-command': true,
  'folder-components': true,
  'folder-config': true,
  'folder-connection': true,
  'folder-console': true,
  'folder-constant': true,
  'folder-container': true,
  'folder-content': true,
  'folder-context': true,
  'folder-contract': true,
  'folder-controller': true,
  'folder-core': true,
  'folder-coverage': true,
  'folder-css': true,
  'folder-cue': true,
  'folder-cursor': true,
  'folder-cursor-light': true,
  'folder-custom': true,
  'folder-cypress': true,
  'folder-dal': true,
  'folder-dart': true,
  'folder-database': true,
  'folder-debug': true,
  'folder-decorators': true,
  'folder-delta': true,
  'folder-desktop': true,
  'folder-directive': true,
  'folder-dist': true,
  'folder-docker': true,
  'folder-docs': true,
  'folder-download': true,
  'folder-drizzle': true,
  'folder-dump': true,
  'folder-element': true,
  'folder-enum': true,
  'folder-environment': true,
  'folder-error': true,
  'folder-eslint': true,
  'folder-event': true,
  'folder-examples': true,
  'folder-expo': true,
  'folder-export': true,
  'folder-fastlane': true,
  'folder-favicon': true,
  'folder-features': true,
  'folder-filter': true,
  'folder-firebase': true,
  'folder-firestore': true,
  'folder-flow': true,
  'folder-flutter': true,
  'folder-font': true,
  'folder-forgejo': true,
  'folder-form': true,
  'folder-functions': true,
  'folder-gamemaker': true,
  'folder-gemini-ai': true,
  'folder-generator': true,
  'folder-gh-workflows': true,
  'folder-git': true,
  'folder-gitea': true,
  'folder-github': true,
  'folder-gitlab': true,
  'folder-global': true,
  'folder-go': true,
  'folder-godot': true,
  'folder-gradle': true,
  'folder-graphql': true,
  'folder-guard': true,
  'folder-gulp': true,
  'folder-helm': true,
  'folder-helper': true,
  'folder-home': true,
  'folder-hook': true,
  'folder-husky': true,
  'folder-i18n': true,
  'folder-images': true,
  'folder-import': true,
  'folder-include': true,
  'folder-input': true,
  'folder-intellij': true,
  'folder-intellij-light': true,
  'folder-interceptor': true,
  'folder-interface': true,
  'folder-ios': true,
  'folder-java': true,
  'folder-javascript': true,
  'folder-jinja': true,
  'folder-jinja-light': true,
  'folder-job': true,
  'folder-json': true,
  'folder-jupyter': true,
  'folder-keys': true,
  'folder-kotlin': true,
  'folder-kubernetes': true,
  'folder-kusto': true,
  'folder-layout': true,
  'folder-lefthook': true,
  'folder-less': true,
  'folder-lib': true,
  'folder-license': true,
  'folder-link': true,
  'folder-linux': true,
  'folder-liquibase': true,
  'folder-log': true,
  'folder-lottie': true,
  'folder-lua': true,
  'folder-luau': true,
  'folder-macos': true,
  'folder-mail': true,
  'folder-mappings': true,
  'folder-markdown': true,
  'folder-mercurial': true,
  'folder-messages': true,
  'folder-meta': true,
  'folder-metro': true,
  'folder-middleware': true,
  'folder-migrations': true,
  'folder-mjml': true,
  'folder-mobile': true,
  'folder-mock': true,
  'folder-mojo': true,
  'folder-molecule': true,
  'folder-moon': true,
  'folder-netlify': true,
  'folder-next': true,
  'folder-nginx': true,
  'folder-ngrx-store': true,
  'folder-node': true,
  'folder-nuxt': true,
  'folder-obsidian': true,
  'folder-opencode': true,
  'folder-organism': true,
  'folder-other': true,
  'folder-packages': true,
  'folder-pdf': true,
  'folder-pdm': true,
  'folder-php': true,
  'folder-phpmailer': true,
  'folder-pipe': true,
  'folder-plastic': true,
  'folder-plugin': true,
  'folder-policy': true,
  'folder-postman': true,
  'folder-powershell': true,
  'folder-prisma': true,
  'folder-private': true,
  'folder-project': true,
  'folder-prompts': true,
  'folder-proto': true,
  'folder-public': true,
  'folder-python': true,
  'folder-pytorch': true,
  'folder-quasar': true,
  'folder-queue': true,
  'folder-r': true,
  'folder-react-components': true,
  'folder-redux-reducer': true,
  'folder-repository': true,
  'folder-resolver': true,
  'folder-resource': true,
  'folder-review': true,
  'folder-robot': true,
  'folder-routes': true,
  'folder-rules': true,
  'folder-rust': true,
  'folder-salt': true,
  'folder-sandbox': true,
  'folder-sass': true,
  'folder-scala': true,
  'folder-scons': true,
  'folder-scripts': true,
  'folder-secure': true,
  'folder-seeders': true,
  'folder-server': true,
  'folder-serverless': true,
  'folder-shader': true,
  'folder-shared': true,
  'folder-simulations': true,
  'folder-skills': true,
  'folder-snapcraft': true,
  'folder-snippet': true,
  'folder-src': true,
  'folder-src-tauri': true,
  'folder-stack': true,
  'folder-stencil': true,
  'folder-store': true,
  'folder-storybook': true,
  'folder-stylus': true,
  'folder-sublime': true,
  'folder-supabase': true,
  'folder-svelte': true,
  'folder-svg': true,
  'folder-syntax': true,
  'folder-target': true,
  'folder-taskfile': true,
  'folder-tasks': true,
  'folder-television': true,
  'folder-temp': true,
  'folder-template': true,
  'folder-terraform': true,
  'folder-test': true,
  'folder-theme': true,
  'folder-toc': true,
  'folder-tools': true,
  'folder-trash': true,
  'folder-trigger': true,
  'folder-turborepo': true,
  'folder-typescript': true,
  'folder-ui': true,
  'folder-unity': true,
  'folder-update': true,
  'folder-upload': true,
  'folder-utils': true,
  'folder-vercel': true,
  'folder-verdaccio': true,
  'folder-video': true,
  'folder-views': true,
  'folder-vm': true,
  'folder-vscode': true,
  'folder-vue': true,
  'folder-vue-directives': true,
  'folder-vuepress': true,
  'folder-vuex-store': true,
  'folder-wakatime': true,
  'folder-webpack': true,
  'folder-windows': true,
  'folder-wordpress': true,
  'folder-yarn': true,
  'folder-zeabur': true,
  'folder-zed': true,
  font: true,
  forth: true,
  fortran: true,
  foxpro: true,
  freemarker: true,
  fsharp: true,
  fusebox: true,
  gamemaker: true,
  garden: true,
  gatsby: true,
  gcp: true,
  gemfile: true,
  gemini: true,
  'gemini-ai': true,
  git: true,
  'github-actions-workflow': true,
  'github-sponsors': true,
  gitlab: true,
  gitpod: true,
  gleam: true,
  gnuplot: true,
  go: true,
  'go-gopher': true,
  'go-mod': true,
  godot: true,
  'godot-assets': true,
  google: true,
  gradle: true,
  'grafana-alloy': true,
  grain: true,
  graphcool: true,
  graphql: true,
  gridsome: true,
  groovy: true,
  grunt: true,
  gulp: true,
  h: true,
  hack: true,
  hadolint: true,
  haml: true,
  handlebars: true,
  happo: true,
  hardhat: true,
  harmonix: true,
  haskell: true,
  haxe: true,
  hcl: true,
  'hcl-light': true,
  helm: true,
  heroku: true,
  hex: true,
  hip: true,
  histoire: true,
  hjson: true,
  horusec: true,
  hosts: true,
  'hosts-light': true,
  hpp: true,
  html: true,
  http: true,
  huff: true,
  'huff-light': true,
  hurl: true,
  husky: true,
  i18n: true,
  idris: true,
  'ifanr-cloud': true,
  image: true,
  imba: true,
  installation: true,
  ionic: true,
  istanbul: true,
  jar: true,
  java: true,
  javaclass: true,
  javascript: true,
  'javascript-map': true,
  jenkins: true,
  jest: true,
  jinja: true,
  'jinja-light': true,
  jsconfig: true,
  json: true,
  'json-schema': true,
  jsr: true,
  'jsr-light': true,
  julia: true,
  jupyter: true,
  just: true,
  karma: true,
  kcl: true,
  key: true,
  keystatic: true,
  kivy: true,
  kl: true,
  knip: true,
  kotlin: true,
  kubernetes: true,
  kusto: true,
  label: true,
  laravel: true,
  latexmk: true,
  lbx: true,
  lean: true,
  lefthook: true,
  lerna: true,
  less: true,
  liara: true,
  lib: true,
  license: true,
  lighthouse: true,
  lilypond: true,
  lintstaged: true,
  liquid: true,
  lisp: true,
  livescript: true,
  lock: true,
  log: true,
  lolcode: true,
  lottie: true,
  lua: true,
  luau: true,
  lynx: true,
  lyric: true,
  macaulay2: true,
  makefile: true,
  markdoc: true,
  'markdoc-config': true,
  markdown: true,
  markdownlint: true,
  markojs: true,
  mathematica: true,
  matlab: true,
  maven: true,
  mdsvex: true,
  mdx: true,
  mercurial: true,
  merlin: true,
  mermaid: true,
  meson: true,
  metro: true,
  minecraft: true,
  'minecraft-fabric': true,
  mint: true,
  mjml: true,
  mocha: true,
  modernizr: true,
  mojo: true,
  moon: true,
  moonscript: true,
  mrpack: true,
  mxml: true,
  'nano-staged': true,
  'nano-staged-light': true,
  ndst: true,
  nest: true,
  netlify: true,
  'netlify-light': true,
  next: true,
  'next-light': true,
  nginx: true,
  'ngrx-actions': true,
  'ngrx-effects': true,
  'ngrx-entity': true,
  'ngrx-reducer': true,
  'ngrx-selectors': true,
  'ngrx-state': true,
  nim: true,
  nix: true,
  nodejs: true,
  'nodejs-alt': true,
  nodemon: true,
  npm: true,
  nuget: true,
  nunjucks: true,
  nuxt: true,
  nx: true,
  'objective-c': true,
  'objective-cpp': true,
  ocaml: true,
  odin: true,
  onnx: true,
  opa: true,
  opam: true,
  openapi: true,
  'openapi-light': true,
  opencode: true,
  'opencode-light': true,
  opentofu: true,
  'opentofu-light': true,
  otne: true,
  oxc: true,
  packship: true,
  palette: true,
  panda: true,
  parcel: true,
  pascal: true,
  pawn: true,
  payload: true,
  'payload-light': true,
  pdf: true,
  pdm: true,
  percy: true,
  perl: true,
  php: true,
  'php-cs-fixer': true,
  'php-elephant': true,
  'php-elephant-pink': true,
  phpstan: true,
  phpunit: true,
  pinejs: true,
  pipeline: true,
  pkl: true,
  plastic: true,
  playwright: true,
  plop: true,
  'pm2-ecosystem': true,
  pnpm: true,
  'pnpm-light': true,
  poetry: true,
  postcss: true,
  posthtml: true,
  powerpoint: true,
  powershell: true,
  'pre-commit': true,
  prettier: true,
  prisma: true,
  processing: true,
  prolog: true,
  prompt: true,
  proto: true,
  protractor: true,
  pug: true,
  puppet: true,
  puppeteer: true,
  purescript: true,
  python: true,
  'python-misc': true,
  pytorch: true,
  qsharp: true,
  quarto: true,
  quasar: true,
  quokka: true,
  qwik: true,
  r: true,
  racket: true,
  raml: true,
  razor: true,
  rbxmk: true,
  rc: true,
  react: true,
  'react-ts': true,
  readme: true,
  reason: true,
  red: true,
  'redux-action': true,
  'redux-reducer': true,
  'redux-selector': true,
  'redux-store': true,
  regedit: true,
  remark: true,
  remix: true,
  'remix-light': true,
  renovate: true,
  replit: true,
  rescript: true,
  'rescript-interface': true,
  restql: true,
  riot: true,
  roadmap: true,
  roblox: true,
  robot: true,
  robots: true,
  rocket: true,
  rojo: true,
  rolldown: true,
  rollup: true,
  rome: true,
  routing: true,
  rspec: true,
  rstack: true,
  rubocop: true,
  'rubocop-light': true,
  ruby: true,
  ruff: true,
  rust: true,
  salesforce: true,
  salt: true,
  san: true,
  sas: true,
  sass: true,
  sbt: true,
  scala: true,
  scheme: true,
  scons: true,
  'scons-light': true,
  screwdriver: true,
  search: true,
  'semantic-release': true,
  'semantic-release-light': true,
  semgrep: true,
  sentry: true,
  sequelize: true,
  serverless: true,
  settings: true,
  shader: true,
  shellcheck: true,
  'shellcheck-light': true,
  silverstripe: true,
  simulink: true,
  siyuan: true,
  sketch: true,
  skill: true,
  slim: true,
  slint: true,
  slug: true,
  smarty: true,
  sml: true,
  snakemake: true,
  snapcraft: true,
  snowpack: true,
  'snowpack-light': true,
  snyk: true,
  solidity: true,
  sonarcloud: true,
  spwn: true,
  stackblitz: true,
  stan: true,
  steadybit: true,
  stencil: true,
  stitches: true,
  'stitches-light': true,
  storybook: true,
  stryker: true,
  stylable: true,
  stylelint: true,
  'stylelint-light': true,
  stylus: true,
  sublime: true,
  subtitles: true,
  supabase: true,
  svelte: true,
  svg: true,
  svgo: true,
  svgr: true,
  swagger: true,
  sway: true,
  swc: true,
  swift: true,
  syncpack: true,
  systemd: true,
  'systemd-light': true,
  table: true,
  tailwindcss: true,
  taskfile: true,
  tauri: true,
  taze: true,
  tcl: true,
  teal: true,
  templ: true,
  template: true,
  terraform: true,
  'test-js': true,
  'test-jsx': true,
  'test-ts': true,
  tex: true,
  textlint: true,
  tilt: true,
  tldraw: true,
  'tldraw-light': true,
  tobi: true,
  tobimake: true,
  toc: true,
  todo: true,
  toml: true,
  'toml-light': true,
  toon: true,
  travis: true,
  tree: true,
  trigger: true,
  tsconfig: true,
  tsdoc: true,
  tsdown: true,
  tsil: true,
  tune: true,
  turborepo: true,
  'turborepo-light': true,
  twig: true,
  twine: true,
  typedoc: true,
  typescript: true,
  'typescript-def': true,
  typst: true,
  uiua: true,
  umi: true,
  uml: true,
  'uml-light': true,
  unity: true,
  unlicense: true,
  unocss: true,
  url: true,
  uv: true,
  vagrant: true,
  vala: true,
  'vanilla-extract': true,
  varnish: true,
  vedic: true,
  velite: true,
  velocity: true,
  vercel: true,
  'vercel-light': true,
  verdaccio: true,
  verified: true,
  verilog: true,
  verse: true,
  'verse-light': true,
  vfl: true,
  video: true,
  vim: true,
  virtual: true,
  visualstudio: true,
  vite: true,
  vitest: true,
  vlang: true,
  vscode: true,
  vue: true,
  'vue-config': true,
  'vuex-store': true,
  wakatime: true,
  'wakatime-light': true,
  wallaby: true,
  wally: true,
  warp: true,
  'warp-light': true,
  watchman: true,
  webassembly: true,
  webhint: true,
  webpack: true,
  wepy: true,
  werf: true,
  windicss: true,
  wolframlanguage: true,
  word: true,
  wrangler: true,
  wxt: true,
  xaml: true,
  xmake: true,
  xml: true,
  yaml: true,
  yang: true,
  yarn: true,
  zeabur: true,
  'zeabur-light': true,
  zig: true,
  zip: true,
} as const;

/**
 * Names upstream has renamed or hidden. Still served, still typed, and
 * deliberately not in the object above: a union compiles to nothing, while
 * every entry in that object ships to every application.
 */
type MaterialIconThemeIconAlias =
  | 'folder-admin-open'
  | 'folder-android-open'
  | 'folder-angular-open'
  | 'folder-animation-open'
  | 'folder-ansible-open'
  | 'folder-api-open'
  | 'folder-apollo-open'
  | 'folder-app-open'
  | 'folder-appwrite-open'
  | 'folder-archive-open'
  | 'folder-assembly-open'
  | 'folder-astro-open'
  | 'folder-atom-open'
  | 'folder-attachment-open'
  | 'folder-audio-open'
  | 'folder-aurelia-open'
  | 'folder-aws-open'
  | 'folder-azure-pipelines-open'
  | 'folder-backup-open'
  | 'folder-base-open'
  | 'folder-batch-open'
  | 'folder-benchmark-open'
  | 'folder-bibliography-open'
  | 'folder-bicep-open'
  | 'folder-blender-open'
  | 'folder-bloc-open'
  | 'folder-bower-open'
  | 'folder-buildkite-open'
  | 'folder-cart-open'
  | 'folder-certificate'
  | 'folder-certificate-open'
  | 'folder-changesets-open'
  | 'folder-ci-open'
  | 'folder-circleci-open'
  | 'folder-class-open'
  | 'folder-claude-open'
  | 'folder-client-open'
  | 'folder-cline-open'
  | 'folder-cloud-functions-open'
  | 'folder-cloudflare-open'
  | 'folder-cluster-open'
  | 'folder-cobol-open'
  | 'folder-command-open'
  | 'folder-components-open'
  | 'folder-config-open'
  | 'folder-connection-open'
  | 'folder-console-open'
  | 'folder-constant-open'
  | 'folder-container-open'
  | 'folder-content-open'
  | 'folder-context-open'
  | 'folder-contract-open'
  | 'folder-controller-open'
  | 'folder-core-open'
  | 'folder-coverage-open'
  | 'folder-css-open'
  | 'folder-cue-open'
  | 'folder-cursor-open'
  | 'folder-cursor-open-light'
  | 'folder-custom-open'
  | 'folder-cypress-open'
  | 'folder-dal-open'
  | 'folder-dart-open'
  | 'folder-database-open'
  | 'folder-debug-open'
  | 'folder-decorators-open'
  | 'folder-delta-open'
  | 'folder-desktop-open'
  | 'folder-directive-open'
  | 'folder-dist-open'
  | 'folder-docker-open'
  | 'folder-docs-open'
  | 'folder-download-open'
  | 'folder-drizzle-open'
  | 'folder-dump-open'
  | 'folder-element-open'
  | 'folder-enum-open'
  | 'folder-environment-open'
  | 'folder-error-open'
  | 'folder-eslint-open'
  | 'folder-event-open'
  | 'folder-examples-open'
  | 'folder-expo-open'
  | 'folder-export-open'
  | 'folder-fastlane-open'
  | 'folder-favicon-open'
  | 'folder-features-open'
  | 'folder-filter-open'
  | 'folder-firebase-open'
  | 'folder-firestore-open'
  | 'folder-flow-open'
  | 'folder-flutter-open'
  | 'folder-font-open'
  | 'folder-forgejo-open'
  | 'folder-form-open'
  | 'folder-functions-open'
  | 'folder-gamemaker-open'
  | 'folder-gemini-ai-open'
  | 'folder-generator-open'
  | 'folder-gh-workflows-open'
  | 'folder-git-open'
  | 'folder-gitea-open'
  | 'folder-github-open'
  | 'folder-gitlab-open'
  | 'folder-global-open'
  | 'folder-go-open'
  | 'folder-godot-open'
  | 'folder-gradle-open'
  | 'folder-graphql-open'
  | 'folder-guard-open'
  | 'folder-gulp-open'
  | 'folder-helm-open'
  | 'folder-helper-open'
  | 'folder-home-open'
  | 'folder-hook-open'
  | 'folder-husky-open'
  | 'folder-i18n-open'
  | 'folder-images-open'
  | 'folder-import-open'
  | 'folder-include-open'
  | 'folder-input-open'
  | 'folder-intellij-open'
  | 'folder-intellij-open-light'
  | 'folder-interceptor-open'
  | 'folder-interface-open'
  | 'folder-ios-open'
  | 'folder-java-open'
  | 'folder-javascript-open'
  | 'folder-jinja-open'
  | 'folder-jinja-open-light'
  | 'folder-job-open'
  | 'folder-json-open'
  | 'folder-jupyter-open'
  | 'folder-keys-open'
  | 'folder-kotlin-open'
  | 'folder-kubernetes-open'
  | 'folder-kusto-open'
  | 'folder-layout-open'
  | 'folder-lefthook-open'
  | 'folder-less-open'
  | 'folder-lib-open'
  | 'folder-license-open'
  | 'folder-link-open'
  | 'folder-linux-open'
  | 'folder-liquibase-open'
  | 'folder-log-open'
  | 'folder-lottie-open'
  | 'folder-lua-open'
  | 'folder-luau-open'
  | 'folder-macos-open'
  | 'folder-mail-open'
  | 'folder-mappings-open'
  | 'folder-markdown-open'
  | 'folder-mercurial-open'
  | 'folder-messages-open'
  | 'folder-meta-open'
  | 'folder-metro-open'
  | 'folder-middleware-open'
  | 'folder-migrations-open'
  | 'folder-mjml-open'
  | 'folder-mobile-open'
  | 'folder-mock-open'
  | 'folder-mojo-open'
  | 'folder-molecule-open'
  | 'folder-moon-open'
  | 'folder-netlify-open'
  | 'folder-next-open'
  | 'folder-nginx-open'
  | 'folder-ngrx-store-open'
  | 'folder-node-open'
  | 'folder-nuxt-open'
  | 'folder-obsidian-open'
  | 'folder-organism-open'
  | 'folder-other-open'
  | 'folder-packages-open'
  | 'folder-pdf-open'
  | 'folder-pdm-open'
  | 'folder-php-open'
  | 'folder-phpmailer-open'
  | 'folder-pipe-open'
  | 'folder-plastic-open'
  | 'folder-plugin-open'
  | 'folder-policy-open'
  | 'folder-postman-open'
  | 'folder-powershell-open'
  | 'folder-prisma-open'
  | 'folder-private-open'
  | 'folder-project-open'
  | 'folder-prompts-open'
  | 'folder-proto-open'
  | 'folder-public-open'
  | 'folder-python-open'
  | 'folder-pytorch-open'
  | 'folder-quasar-open'
  | 'folder-queue-open'
  | 'folder-r-open'
  | 'folder-react-components-open'
  | 'folder-redux-reducer-open'
  | 'folder-repository-open'
  | 'folder-resolver-open'
  | 'folder-resource-open'
  | 'folder-review-open'
  | 'folder-robot-open'
  | 'folder-routes-open'
  | 'folder-rules-open'
  | 'folder-rust-open'
  | 'folder-salt-open'
  | 'folder-sandbox-open'
  | 'folder-sass-open'
  | 'folder-scala-open'
  | 'folder-scons-open'
  | 'folder-scripts-open'
  | 'folder-secure-open'
  | 'folder-seeders-open'
  | 'folder-server-open'
  | 'folder-serverless-open'
  | 'folder-shader-open'
  | 'folder-shared-open'
  | 'folder-simulations-open'
  | 'folder-skills-open'
  | 'folder-snapcraft-open'
  | 'folder-snippet-open'
  | 'folder-src-open'
  | 'folder-src-tauri-open'
  | 'folder-stack-open'
  | 'folder-stencil-open'
  | 'folder-store-open'
  | 'folder-storybook-open'
  | 'folder-stylus-open'
  | 'folder-sublime-open'
  | 'folder-supabase-open'
  | 'folder-svelte-open'
  | 'folder-svg-open'
  | 'folder-syntax-open'
  | 'folder-target-open'
  | 'folder-taskfile-open'
  | 'folder-tasks-open'
  | 'folder-television-open'
  | 'folder-temp-open'
  | 'folder-template-open'
  | 'folder-terraform-open'
  | 'folder-test-open'
  | 'folder-theme-open'
  | 'folder-toc-open'
  | 'folder-tools-open'
  | 'folder-trash-open'
  | 'folder-trigger-open'
  | 'folder-turborepo-open'
  | 'folder-typescript-open'
  | 'folder-ui-open'
  | 'folder-unity-open'
  | 'folder-update-open'
  | 'folder-upload-open'
  | 'folder-utils-open'
  | 'folder-vercel-open'
  | 'folder-verdaccio-open'
  | 'folder-video-open'
  | 'folder-views-open'
  | 'folder-vm-open'
  | 'folder-vscode-open'
  | 'folder-vue-directives-open'
  | 'folder-vue-open'
  | 'folder-vuepress-open'
  | 'folder-vuex-store-open'
  | 'folder-wakatime-open'
  | 'folder-webpack-open'
  | 'folder-windows-open'
  | 'folder-wordpress-open'
  | 'folder-yarn-open'
  | 'folder-zeabur-open'
  | 'folder-zed-open'
  | 'oxlint';

export type MaterialIconThemeIconName =
  | keyof typeof material_icon_themeIconNames
  | MaterialIconThemeIconAlias;
export const MaterialIconTheme = createIconSet<MaterialIconThemeIconName>(
  'material-icon-theme',
  material_icon_themeIconNames
);
