/**
 * MedicalIcon Icon Set
 * @see https://icon-sets.iconify.design/medical-icon/
 *
 * Auto-generated - do not edit manually
 */

import { createIconSet } from '../createIconSet';

const medical_iconIconNames = {
  accessibility: true,
  administration: true,
  'alternative-complementary': true,
  ambulance: true,
  anesthesia: true,
  billing: true,
  cardiology: true,
  'care-staff-area': true,
  'cath-lab': true,
  chapel: true,
  'coffee-shop': true,
  dental: true,
  dermatology: true,
  'diabetes-education': true,
  'drinking-fountain': true,
  'ear-nose-throat': true,
  elevators: true,
  emergency: true,
  'family-practice': true,
  'fire-extinguisher': true,
  'first-aid': true,
  genetics: true,
  'gift-shop': true,
  'health-education': true,
  'health-services': true,
  'hearing-assistance': true,
  hospital: true,
  'i-accessibility': true,
  'i-administration': true,
  'i-alternative-complementary': true,
  'i-ambulance': true,
  'i-anesthesia': true,
  'i-billing': true,
  'i-cardiology': true,
  'i-care-staff-area': true,
  'i-cath-lab': true,
  'i-chapel': true,
  'i-coffee-shop': true,
  'i-dental': true,
  'i-dermatology': true,
  'i-diabetes-education': true,
  'i-drinking-fountain': true,
  'i-ear-nose-throat': true,
  'i-elevators': true,
  'i-emergency': true,
  'i-family-practice': true,
  'i-fire-extinguisher': true,
  'i-first-aid': true,
  'i-genetics': true,
  'i-gift-shop': true,
  'i-health-education': true,
  'i-health-services': true,
  'i-hearing-assistance': true,
  'i-hospital': true,
  'i-imaging-alternative-ct': true,
  'i-imaging-alternative-mri': true,
  'i-imaging-alternative-mri-two': true,
  'i-imaging-alternative-pet': true,
  'i-imaging-root-category': true,
  'i-immunizations': true,
  'i-infectious-diseases': true,
  'i-information-us': true,
  'i-inpatient': true,
  'i-intensive-care': true,
  'i-internal-medicine': true,
  'i-interpreter-services': true,
  'i-kidney': true,
  'i-labor-delivery': true,
  'i-laboratory': true,
  'i-mammography': true,
  'i-medical-library': true,
  'i-medical-records': true,
  'i-mental-health': true,
  'i-mri-pet': true,
  'i-neurology': true,
  'i-no-smoking': true,
  'i-nursery': true,
  'i-nutrition': true,
  'i-oncology': true,
  'i-ophthalmology': true,
  'i-outpatient': true,
  'i-pathology': true,
  'i-pediatrics': true,
  'i-pharmacy': true,
  'i-physical-therapy': true,
  'i-radiology': true,
  'i-registration': true,
  'i-respiratory': true,
  'i-restaurant': true,
  'i-restrooms': true,
  'i-smoking': true,
  'i-social-services': true,
  'i-stairs': true,
  'i-surgery': true,
  'i-text-telephone': true,
  'i-ultrasound': true,
  'i-volume-control': true,
  'i-waiting-area': true,
  'i-womens-health': true,
  'imaging-alternative-ct': true,
  'imaging-alternative-mri': true,
  'imaging-alternative-mri-two': true,
  'imaging-alternative-pet': true,
  'imaging-root-category': true,
  immunizations: true,
  'infectious-diseases': true,
  'information-us': true,
  inpatient: true,
  'intensive-care': true,
  'internal-medicine': true,
  'interpreter-services': true,
  kidney: true,
  'labor-delivery': true,
  laboratory: true,
  mammography: true,
  'medical-library': true,
  'medical-records': true,
  'mental-health': true,
  'mri-pet': true,
  neurology: true,
  'no-smoking': true,
  nursery: true,
  nutrition: true,
  oncology: true,
  ophthalmology: true,
  outpatient: true,
  pathology: true,
  pediatrics: true,
  pharmacy: true,
  'physical-therapy': true,
  radiology: true,
  registration: true,
  respiratory: true,
  restaurant: true,
  restrooms: true,
  smoking: true,
  'social-services': true,
  stairs: true,
  surgery: true,
  'text-telephone': true,
  ultrasound: true,
  'volume-control': true,
  'waiting-area': true,
  'womens-health': true,
} as const;

export type MedicalIconIconName = keyof typeof medical_iconIconNames;
export const MedicalIcon = createIconSet<MedicalIconIconName>(
  'medical-icon',
  medical_iconIconNames
);
