/**
 * Nonicons Icon Set
 * @see https://icon-sets.iconify.design/nonicons/
 *
 * Auto-generated - do not edit manually
 */

import { createIconSet } from '../createIconSet';

const noniconsIconNames = {
  'angular-16': true,
  'babel-16': true,
  'biome-16': true,
  'c-16': true,
  'c-plusplus-16': true,
  'c-sharp-16': true,
  'capacitor-16': true,
  'class-16': true,
  'constant-16': true,
  'css-16': true,
  'dart-16': true,
  'docker-16': true,
  'elixir-16': true,
  'elm-16': true,
  'error-16': true,
  'eslint-16': true,
  'field-16': true,
  'go-16': true,
  'graphql-16': true,
  'html-16': true,
  'interface-16': true,
  'ionic-16': true,
  'java-16': true,
  'javascript-16': true,
  'json-16': true,
  'keyword-16': true,
  'kotlin-16': true,
  'kubernetes-16': true,
  'layout-16': true,
  'loading-16': true,
  'lua-16': true,
  'next-16': true,
  'nginx-16': true,
  'node-16': true,
  'not-found-16': true,
  'npm-16': true,
  'perl-16': true,
  'php-16': true,
  'prettier-16': true,
  'prisma-16': true,
  'python-16': true,
  'r-16': true,
  'react-16': true,
  'rust-16': true,
  'scala-16': true,
  'snippet-16': true,
  'struct-16': true,
  'svelte-16': true,
  'swift-16': true,
  'template-16': true,
  'terraform-16': true,
  'tmux-16': true,
  'toml-16': true,
  'turborepo-16': true,
  'type-16': true,
  'typescript-16': true,
  'variable-16': true,
  'vim-16': true,
  'vim-command-mode-16': true,
  'vim-insert-mode-16': true,
  'vim-normal-mode-16': true,
  'vim-replace-mode-16': true,
  'vim-select-mode-16': true,
  'vim-terminal-mode-16': true,
  'vim-visual-mode-16': true,
  'vscode-16': true,
  'vue-16': true,
  'yaml-16': true,
  'yarn-16': true,
} as const;

export type NoniconsIconName = keyof typeof noniconsIconNames;
export const Nonicons = createIconSet<NoniconsIconName>('nonicons', noniconsIconNames);
