/**
 * Topcoat Icon Set
 * @see https://icon-sets.iconify.design/topcoat/
 *
 * Auto-generated - do not edit manually
 */

import { createIconSet } from '../createIconSet';

const topcoatIconNames = {
  alert: true,
  'arrow-down': true,
  'arrow-left': true,
  'arrow-right': true,
  'arrow-up': true,
  attachment: true,
  audio: true,
  audiooff: true,
  back: true,
  'back-light': true,
  behance: true,
  bookmark: true,
  brush: true,
  build: true,
  calendar: true,
  call: true,
  camera: true,
  cancel: true,
  cart: true,
  chat: true,
  checkmark: true,
  circle: true,
  'circle-outline': true,
  cloud: true,
  collapse: true,
  comment: true,
  computer: true,
  delete: true,
  download: true,
  dribble: true,
  email: true,
  error: true,
  expand: true,
  facebook: true,
  favorite: true,
  feedback: true,
  flickr: true,
  folder: true,
  github: true,
  'github-text': true,
  googleplus: true,
  group: true,
  home: true,
  image: true,
  'image-outline': true,
  instagram: true,
  like: true,
  linkedin: true,
  listview: true,
  location: true,
  lock: true,
  minus: true,
  next: true,
  'next-light': true,
  page: true,
  path: true,
  pencil: true,
  phone: true,
  picasa: true,
  pinterest: true,
  plugin: true,
  plus: true,
  preview: true,
  print: true,
  question: true,
  rectangle: true,
  'rectangle-outline': true,
  refresh: true,
  retweet: true,
  roundedrectangle: true,
  'roundedrectangle-outline': true,
  rss: true,
  save: true,
  search: true,
  settings: true,
  share: true,
  tablet: true,
  text: true,
  tileview: true,
  tumblr: true,
  twitter: true,
  unlock: true,
  user: true,
  videocamera: true,
  view: true,
  vimeo: true,
  w3c: true,
  wifi: true,
  wordpress: true,
} as const;

export type TopcoatIconName = keyof typeof topcoatIconNames;
export const Topcoat = createIconSet<TopcoatIconName>('topcoat', topcoatIconNames);
