/**
 * Websymbol Icon Set
 * @see https://icon-sets.iconify.design/websymbol/
 *
 * Auto-generated - do not edit manually
 */

import { createIconSet } from '../createIconSet';

const websymbolIconNames = {
  archive: true,
  'arrows-cw': true,
  attach: true,
  attention: true,
  block: true,
  cancel: true,
  'cancel-circle': true,
  chat: true,
  clock: true,
  cloud: true,
  code: true,
  cog: true,
  comment: true,
  'comment-alt': true,
  'cw-circle': true,
  doc: true,
  'docs-landscape': true,
  'down-circle': true,
  'down-dir': true,
  'down-micro': true,
  'facebook-rect': true,
  folder: true,
  font: true,
  forward: true,
  'googleplus-rect': true,
  heart: true,
  'heart-empty': true,
  'indent-left': true,
  'indent-right': true,
  'left-circle': true,
  'left-open': true,
  link: true,
  'linkedin-rect': true,
  list: true,
  'list-numbered': true,
  location: true,
  lock: true,
  'lock-open': true,
  logout: true,
  mail: true,
  'minus-circle': true,
  'odnoklassniki-rect': true,
  ok: true,
  'ok-circle': true,
  picture: true,
  'plus-circle': true,
  popup: true,
  'progress-0': true,
  'progress-1': true,
  'progress-2': true,
  'progress-3': true,
  'progress-4': true,
  'progress-5': true,
  'progress-6': true,
  'progress-7': true,
  reply: true,
  'reply-all': true,
  'resize-full': true,
  'resize-full-circle': true,
  retweet: true,
  'right-circle': true,
  'right-dir': true,
  'right-open': true,
  rss: true,
  'rss-alt': true,
  search: true,
  signal: true,
  skype: true,
  star: true,
  tag: true,
  target: true,
  terminal: true,
  th: true,
  'th-large': true,
  'th-list': true,
  'tumblr-rect': true,
  'twitter-bird': true,
  'up-circle': true,
  'up-micro': true,
  'updown-circle': true,
  user: true,
  video: true,
  'vimeo-rect': true,
  'vkontakte-rect': true,
  youtube: true,
} as const;

export type WebsymbolIconName = keyof typeof websymbolIconNames;
export const Websymbol = createIconSet<WebsymbolIconName>('websymbol', websymbolIconNames);
