/**
 * Wi Icon Set
 * @see https://icon-sets.iconify.design/wi/
 *
 * Auto-generated - do not edit manually
 */

import { createIconSet } from '../createIconSet';

const wiIconNames = {
  alien: true,
  barometer: true,
  celsius: true,
  cloud: true,
  'cloud-down': true,
  'cloud-refresh': true,
  'cloud-up': true,
  cloudy: true,
  'cloudy-gusts': true,
  'cloudy-windy': true,
  'day-cloudy': true,
  'day-cloudy-gusts': true,
  'day-cloudy-high': true,
  'day-cloudy-windy': true,
  'day-fog': true,
  'day-hail': true,
  'day-haze': true,
  'day-light-wind': true,
  'day-lightning': true,
  'day-rain': true,
  'day-rain-mix': true,
  'day-rain-wind': true,
  'day-showers': true,
  'day-sleet': true,
  'day-sleet-storm': true,
  'day-snow': true,
  'day-snow-thunderstorm': true,
  'day-snow-wind': true,
  'day-sprinkle': true,
  'day-storm-showers': true,
  'day-sunny': true,
  'day-sunny-overcast': true,
  'day-thunderstorm': true,
  'day-windy': true,
  degrees: true,
  'direction-down': true,
  'direction-down-left': true,
  'direction-down-right': true,
  'direction-left': true,
  'direction-right': true,
  'direction-up': true,
  'direction-up-left': true,
  'direction-up-right': true,
  dust: true,
  earthquake: true,
  fahrenheit: true,
  fire: true,
  flood: true,
  fog: true,
  'gale-warning': true,
  hail: true,
  horizon: true,
  'horizon-alt': true,
  hot: true,
  humidity: true,
  hurricane: true,
  'hurricane-warning': true,
  lightning: true,
  'lunar-eclipse': true,
  meteor: true,
  'moon-alt-first-quarter': true,
  'moon-alt-full': true,
  'moon-alt-new': true,
  'moon-alt-third-quarter': true,
  'moon-alt-waning-crescent-1': true,
  'moon-alt-waning-crescent-2': true,
  'moon-alt-waning-crescent-3': true,
  'moon-alt-waning-crescent-4': true,
  'moon-alt-waning-crescent-5': true,
  'moon-alt-waning-crescent-6': true,
  'moon-alt-waning-gibbous-1': true,
  'moon-alt-waning-gibbous-2': true,
  'moon-alt-waning-gibbous-3': true,
  'moon-alt-waning-gibbous-4': true,
  'moon-alt-waning-gibbous-5': true,
  'moon-alt-waning-gibbous-6': true,
  'moon-alt-waxing-crescent-1': true,
  'moon-alt-waxing-crescent-2': true,
  'moon-alt-waxing-crescent-3': true,
  'moon-alt-waxing-crescent-4': true,
  'moon-alt-waxing-crescent-5': true,
  'moon-alt-waxing-crescent-6': true,
  'moon-alt-waxing-gibbous-1': true,
  'moon-alt-waxing-gibbous-2': true,
  'moon-alt-waxing-gibbous-3': true,
  'moon-alt-waxing-gibbous-4': true,
  'moon-alt-waxing-gibbous-5': true,
  'moon-alt-waxing-gibbous-6': true,
  'moon-first-quarter': true,
  'moon-full': true,
  'moon-new': true,
  'moon-third-quarter': true,
  'moon-waning-crescent-1': true,
  'moon-waning-crescent-2': true,
  'moon-waning-crescent-3': true,
  'moon-waning-crescent-4': true,
  'moon-waning-crescent-5': true,
  'moon-waning-crescent-6': true,
  'moon-waning-gibbous-1': true,
  'moon-waning-gibbous-2': true,
  'moon-waning-gibbous-3': true,
  'moon-waning-gibbous-4': true,
  'moon-waning-gibbous-5': true,
  'moon-waning-gibbous-6': true,
  'moon-waxing-6': true,
  'moon-waxing-crescent-1': true,
  'moon-waxing-crescent-2': true,
  'moon-waxing-crescent-3': true,
  'moon-waxing-crescent-4': true,
  'moon-waxing-crescent-5': true,
  'moon-waxing-gibbous-1': true,
  'moon-waxing-gibbous-2': true,
  'moon-waxing-gibbous-3': true,
  'moon-waxing-gibbous-4': true,
  'moon-waxing-gibbous-5': true,
  'moon-waxing-gibbous-6': true,
  moonrise: true,
  moonset: true,
  na: true,
  'night-alt-cloudy': true,
  'night-alt-cloudy-gusts': true,
  'night-alt-cloudy-high': true,
  'night-alt-cloudy-windy': true,
  'night-alt-hail': true,
  'night-alt-lightning': true,
  'night-alt-partly-cloudy': true,
  'night-alt-rain': true,
  'night-alt-rain-mix': true,
  'night-alt-rain-wind': true,
  'night-alt-showers': true,
  'night-alt-sleet': true,
  'night-alt-sleet-storm': true,
  'night-alt-snow': true,
  'night-alt-snow-thunderstorm': true,
  'night-alt-snow-wind': true,
  'night-alt-sprinkle': true,
  'night-alt-storm-showers': true,
  'night-alt-thunderstorm': true,
  'night-clear': true,
  'night-cloudy': true,
  'night-cloudy-gusts': true,
  'night-cloudy-high': true,
  'night-cloudy-windy': true,
  'night-fog': true,
  'night-hail': true,
  'night-lightning': true,
  'night-partly-cloudy': true,
  'night-rain': true,
  'night-rain-mix': true,
  'night-rain-wind': true,
  'night-showers': true,
  'night-sleet': true,
  'night-sleet-storm': true,
  'night-snow': true,
  'night-snow-thunderstorm': true,
  'night-snow-wind': true,
  'night-sprinkle': true,
  'night-storm-showers': true,
  'night-thunderstorm': true,
  rain: true,
  'rain-mix': true,
  'rain-wind': true,
  raindrop: true,
  raindrops: true,
  refresh: true,
  'refresh-alt': true,
  sandstorm: true,
  showers: true,
  sleet: true,
  'small-craft-advisory': true,
  smog: true,
  smoke: true,
  snow: true,
  'snow-wind': true,
  'snowflake-cold': true,
  'solar-eclipse': true,
  sprinkle: true,
  stars: true,
  'storm-showers': true,
  'storm-warning': true,
  'strong-wind': true,
  sunrise: true,
  sunset: true,
  thermometer: true,
  'thermometer-exterior': true,
  'thermometer-internal': true,
  thunderstorm: true,
  'time-1': true,
  'time-10': true,
  'time-11': true,
  'time-12': true,
  'time-2': true,
  'time-3': true,
  'time-4': true,
  'time-5': true,
  'time-6': true,
  'time-7': true,
  'time-8': true,
  'time-9': true,
  tornado: true,
  train: true,
  tsunami: true,
  umbrella: true,
  volcano: true,
  'wind-beaufort-0': true,
  'wind-beaufort-1': true,
  'wind-beaufort-10': true,
  'wind-beaufort-11': true,
  'wind-beaufort-12': true,
  'wind-beaufort-2': true,
  'wind-beaufort-3': true,
  'wind-beaufort-4': true,
  'wind-beaufort-5': true,
  'wind-beaufort-6': true,
  'wind-beaufort-7': true,
  'wind-beaufort-8': true,
  'wind-beaufort-9': true,
  'wind-deg': true,
  windy: true,
} as const;

/**
 * Names upstream has renamed or hidden. Still served, still typed, and
 * deliberately not in the object above: a union compiles to nothing, while
 * every entry in that object ships to every application.
 */
type WiIconAlias =
  | 'aliens'
  | 'forecast-io-clear-day'
  | 'forecast-io-clear-night'
  | 'forecast-io-cloudy'
  | 'forecast-io-fog'
  | 'forecast-io-hail'
  | 'forecast-io-partly-cloudy-day'
  | 'forecast-io-partly-cloudy-night'
  | 'forecast-io-rain'
  | 'forecast-io-sleet'
  | 'forecast-io-snow'
  | 'forecast-io-thunderstorm'
  | 'forecast-io-tornado'
  | 'forecast-io-wind'
  | 'moon-0'
  | 'moon-1'
  | 'moon-10'
  | 'moon-11'
  | 'moon-12'
  | 'moon-13'
  | 'moon-14'
  | 'moon-15'
  | 'moon-16'
  | 'moon-17'
  | 'moon-18'
  | 'moon-19'
  | 'moon-2'
  | 'moon-20'
  | 'moon-21'
  | 'moon-22'
  | 'moon-23'
  | 'moon-24'
  | 'moon-25'
  | 'moon-26'
  | 'moon-27'
  | 'moon-3'
  | 'moon-4'
  | 'moon-5'
  | 'moon-6'
  | 'moon-7'
  | 'moon-8'
  | 'moon-9'
  | 'moon-waxing-crescent-6'
  | 'owm-200'
  | 'owm-201'
  | 'owm-202'
  | 'owm-210'
  | 'owm-211'
  | 'owm-212'
  | 'owm-221'
  | 'owm-230'
  | 'owm-231'
  | 'owm-232'
  | 'owm-300'
  | 'owm-301'
  | 'owm-302'
  | 'owm-310'
  | 'owm-311'
  | 'owm-312'
  | 'owm-313'
  | 'owm-314'
  | 'owm-321'
  | 'owm-500'
  | 'owm-501'
  | 'owm-502'
  | 'owm-503'
  | 'owm-504'
  | 'owm-511'
  | 'owm-520'
  | 'owm-521'
  | 'owm-522'
  | 'owm-531'
  | 'owm-600'
  | 'owm-601'
  | 'owm-602'
  | 'owm-611'
  | 'owm-612'
  | 'owm-615'
  | 'owm-616'
  | 'owm-620'
  | 'owm-621'
  | 'owm-622'
  | 'owm-701'
  | 'owm-711'
  | 'owm-721'
  | 'owm-731'
  | 'owm-741'
  | 'owm-761'
  | 'owm-762'
  | 'owm-771'
  | 'owm-781'
  | 'owm-800'
  | 'owm-801'
  | 'owm-802'
  | 'owm-803'
  | 'owm-804'
  | 'owm-900'
  | 'owm-901'
  | 'owm-902'
  | 'owm-903'
  | 'owm-904'
  | 'owm-905'
  | 'owm-906'
  | 'owm-957'
  | 'owm-day-200'
  | 'owm-day-201'
  | 'owm-day-202'
  | 'owm-day-210'
  | 'owm-day-211'
  | 'owm-day-212'
  | 'owm-day-221'
  | 'owm-day-230'
  | 'owm-day-231'
  | 'owm-day-232'
  | 'owm-day-300'
  | 'owm-day-301'
  | 'owm-day-302'
  | 'owm-day-310'
  | 'owm-day-311'
  | 'owm-day-312'
  | 'owm-day-313'
  | 'owm-day-314'
  | 'owm-day-321'
  | 'owm-day-500'
  | 'owm-day-501'
  | 'owm-day-502'
  | 'owm-day-503'
  | 'owm-day-504'
  | 'owm-day-511'
  | 'owm-day-520'
  | 'owm-day-521'
  | 'owm-day-522'
  | 'owm-day-531'
  | 'owm-day-600'
  | 'owm-day-601'
  | 'owm-day-602'
  | 'owm-day-611'
  | 'owm-day-612'
  | 'owm-day-615'
  | 'owm-day-616'
  | 'owm-day-620'
  | 'owm-day-621'
  | 'owm-day-622'
  | 'owm-day-701'
  | 'owm-day-711'
  | 'owm-day-721'
  | 'owm-day-731'
  | 'owm-day-741'
  | 'owm-day-761'
  | 'owm-day-762'
  | 'owm-day-781'
  | 'owm-day-800'
  | 'owm-day-801'
  | 'owm-day-802'
  | 'owm-day-803'
  | 'owm-day-804'
  | 'owm-day-900'
  | 'owm-day-902'
  | 'owm-day-903'
  | 'owm-day-904'
  | 'owm-day-906'
  | 'owm-day-957'
  | 'owm-night-200'
  | 'owm-night-201'
  | 'owm-night-202'
  | 'owm-night-210'
  | 'owm-night-211'
  | 'owm-night-212'
  | 'owm-night-221'
  | 'owm-night-230'
  | 'owm-night-231'
  | 'owm-night-232'
  | 'owm-night-300'
  | 'owm-night-301'
  | 'owm-night-302'
  | 'owm-night-310'
  | 'owm-night-311'
  | 'owm-night-312'
  | 'owm-night-313'
  | 'owm-night-314'
  | 'owm-night-321'
  | 'owm-night-500'
  | 'owm-night-501'
  | 'owm-night-502'
  | 'owm-night-503'
  | 'owm-night-504'
  | 'owm-night-511'
  | 'owm-night-520'
  | 'owm-night-521'
  | 'owm-night-522'
  | 'owm-night-531'
  | 'owm-night-600'
  | 'owm-night-601'
  | 'owm-night-602'
  | 'owm-night-611'
  | 'owm-night-612'
  | 'owm-night-615'
  | 'owm-night-616'
  | 'owm-night-620'
  | 'owm-night-621'
  | 'owm-night-622'
  | 'owm-night-701'
  | 'owm-night-711'
  | 'owm-night-721'
  | 'owm-night-731'
  | 'owm-night-741'
  | 'owm-night-761'
  | 'owm-night-762'
  | 'owm-night-781'
  | 'owm-night-800'
  | 'owm-night-801'
  | 'owm-night-802'
  | 'owm-night-803'
  | 'owm-night-804'
  | 'owm-night-900'
  | 'owm-night-902'
  | 'owm-night-903'
  | 'owm-night-904'
  | 'owm-night-906'
  | 'owm-night-957'
  | 'wind-direction'
  | 'wind-direction-e'
  | 'wind-direction-n'
  | 'wind-direction-ne'
  | 'wind-direction-nw'
  | 'wind-direction-s'
  | 'wind-direction-se'
  | 'wind-direction-sw'
  | 'wind-direction-w'
  | 'wmo4680-0'
  | 'wmo4680-00'
  | 'wmo4680-01'
  | 'wmo4680-02'
  | 'wmo4680-03'
  | 'wmo4680-04'
  | 'wmo4680-05'
  | 'wmo4680-1'
  | 'wmo4680-10'
  | 'wmo4680-11'
  | 'wmo4680-12'
  | 'wmo4680-18'
  | 'wmo4680-2'
  | 'wmo4680-20'
  | 'wmo4680-21'
  | 'wmo4680-22'
  | 'wmo4680-23'
  | 'wmo4680-24'
  | 'wmo4680-25'
  | 'wmo4680-26'
  | 'wmo4680-27'
  | 'wmo4680-28'
  | 'wmo4680-29'
  | 'wmo4680-3'
  | 'wmo4680-30'
  | 'wmo4680-31'
  | 'wmo4680-32'
  | 'wmo4680-33'
  | 'wmo4680-34'
  | 'wmo4680-35'
  | 'wmo4680-4'
  | 'wmo4680-40'
  | 'wmo4680-41'
  | 'wmo4680-42'
  | 'wmo4680-43'
  | 'wmo4680-44'
  | 'wmo4680-45'
  | 'wmo4680-46'
  | 'wmo4680-47'
  | 'wmo4680-48'
  | 'wmo4680-5'
  | 'wmo4680-50'
  | 'wmo4680-51'
  | 'wmo4680-52'
  | 'wmo4680-53'
  | 'wmo4680-54'
  | 'wmo4680-55'
  | 'wmo4680-56'
  | 'wmo4680-57'
  | 'wmo4680-58'
  | 'wmo4680-60'
  | 'wmo4680-61'
  | 'wmo4680-62'
  | 'wmo4680-63'
  | 'wmo4680-64'
  | 'wmo4680-65'
  | 'wmo4680-66'
  | 'wmo4680-67'
  | 'wmo4680-68'
  | 'wmo4680-70'
  | 'wmo4680-71'
  | 'wmo4680-72'
  | 'wmo4680-73'
  | 'wmo4680-74'
  | 'wmo4680-75'
  | 'wmo4680-76'
  | 'wmo4680-77'
  | 'wmo4680-78'
  | 'wmo4680-80'
  | 'wmo4680-81'
  | 'wmo4680-82'
  | 'wmo4680-83'
  | 'wmo4680-84'
  | 'wmo4680-85'
  | 'wmo4680-86'
  | 'wmo4680-87'
  | 'wmo4680-89'
  | 'wmo4680-90'
  | 'wmo4680-91'
  | 'wmo4680-92'
  | 'wmo4680-93'
  | 'wmo4680-94'
  | 'wmo4680-95'
  | 'wmo4680-96'
  | 'wmo4680-99'
  | 'wu-chanceflurries'
  | 'wu-chancerain'
  | 'wu-chancesleat'
  | 'wu-chancesnow'
  | 'wu-chancetstorms'
  | 'wu-clear'
  | 'wu-cloudy'
  | 'wu-flurries'
  | 'wu-hazy'
  | 'wu-mostlycloudy'
  | 'wu-mostlysunny'
  | 'wu-partlycloudy'
  | 'wu-partlysunny'
  | 'wu-rain'
  | 'wu-sleat'
  | 'wu-snow'
  | 'wu-sunny'
  | 'wu-tstorms'
  | 'wu-unknown'
  | 'yahoo-0'
  | 'yahoo-1'
  | 'yahoo-10'
  | 'yahoo-11'
  | 'yahoo-12'
  | 'yahoo-13'
  | 'yahoo-14'
  | 'yahoo-15'
  | 'yahoo-16'
  | 'yahoo-17'
  | 'yahoo-18'
  | 'yahoo-19'
  | 'yahoo-2'
  | 'yahoo-20'
  | 'yahoo-21'
  | 'yahoo-22'
  | 'yahoo-23'
  | 'yahoo-24'
  | 'yahoo-25'
  | 'yahoo-26'
  | 'yahoo-27'
  | 'yahoo-28'
  | 'yahoo-29'
  | 'yahoo-3'
  | 'yahoo-30'
  | 'yahoo-31'
  | 'yahoo-32'
  | 'yahoo-3200'
  | 'yahoo-33'
  | 'yahoo-34'
  | 'yahoo-35'
  | 'yahoo-36'
  | 'yahoo-37'
  | 'yahoo-38'
  | 'yahoo-39'
  | 'yahoo-4'
  | 'yahoo-40'
  | 'yahoo-41'
  | 'yahoo-42'
  | 'yahoo-43'
  | 'yahoo-44'
  | 'yahoo-45'
  | 'yahoo-46'
  | 'yahoo-47'
  | 'yahoo-5'
  | 'yahoo-6'
  | 'yahoo-7'
  | 'yahoo-8'
  | 'yahoo-9';

export type WiIconName = keyof typeof wiIconNames | WiIconAlias;
export const Wi = createIconSet<WiIconName>('wi', wiIconNames);
